- packages/marshal/test/test-marshal-smallcaps.js
- packages/patterns/test/test-pattern-limits.js
- packages/patterns/test/test-patterns.js
- packages/ses/src/error/stringify-utils.js
- packages/ses/test/error/test-assert-log.js
- packages/ses/test/error/test-stringfy-utils.js
Currently `bestEffortsStringify` uses the default property enumeration order, which is insertion order. As a result, semantically neutral changes that happen to change property insertion order accidentally cause error messages to change, breaking golden tests of error messages.
See example breakage at https://github.com/Agoric/agoric-sdk/actions/runs/5572658660/jobs/10178998419?pr=5422#step:5:212
With expository whitespace:
```js
({
"want": {
"TokenJ": {
"brand": "[Alleged: moola brand]",
"value": "[3n]"
}
},
"give": {
"TokenK": {
"brand": "[Alleged: bucks brand]",
"value": "[5n]"
}
},
"multiples": "[1n]",
"exit": {"onDemand": null}
})
```
vs
```js
({
"exit": {"onDemand": null},
"give": {
"TokenK": {
"brand": "[Alleged: bucks brand]",
"value": "[5n]"
}
},
"multiples": "[1n]",
"want": { …
```
> fix(ses): normalize `bestEffortsStringify` property order

- packages/skel/tsconfig.build.json
- packages/transforms/tsconfig.build.json
This fixes the `yarn pack` behavior for the new packages `skel` and `transforms`. The TypeScript build configuration was misaligned with the TypeScript configuration rename.
> fix: Fix scaffold and transforms yarn pack

- packages/bundle-source/src/index.js
- packages/bundle-source/src/types.js
- packages/bundle-source/test/sanity.js
- packages/bundle-source/test/test-bigint-transform.js
Recently, #1704 was a good step forward to introduce typing for the return value of `@endo/bundle-source`.  However, it came at the cost of requiring all callers to narrow the return type using assertions, knowing the moduleFormat they were using.
This PR discriminates between the different ModuleFormats to return an appropriate type that requires no assertions or narrowing (unless the supplied ModuleFormat cannot be inferred in the calling context).
n/a
n/a
n/a
The types could be tested more thoroughly, but they are at least exercised in `@endo/bundle-source` unit tests.
n/a
> feat(bundle-source): type `bundleSource` more comprehensively

- packages/ses/src/permits.js
https://github.com/endojs/endo/pull/1643
corrected problems with
https://github.com/endojs/endo/pull/1618
but says
>  I remain confused about where group and groupToMap came from. I also noticed groupBy missing. 
Indeed, I was confused.
Endo master is current with those PRs and is not consistent with the current state of https://github.com/tc39/proposal-array-grouping , which is now at stage 3.
This proposal is apparently implemented by
* V8 11.8.28 of latest Chrome Canary, Version 118.0.5944.0 (Official Build) canary (arm64)
I verified that it is not yet implemented by
* V8 11.5.150.22 of latest Chrome, Version 115.0.5790.170 (Official Build) (arm64)
* V8 11.5.150.22 of latest Brave, 1.56.20 Chromium: 115.0.5790.171 (Official Build) (arm64) 
* V8 11.3.244.8-node.10 of latest Node, 20.5.1 …
> fix(ses): prepare for Array Grouping proposal

- packages/exo/src/exo-tools.js
- packages/patterns/index.js
- packages/patterns/src/patterns/internal-types.js
- packages/patterns/src/patterns/patternMatchers.js
- packages/patterns/src/types.js
Subset of https://github.com/endojs/endo/pull/1712 that does not break compat.
Typing and validation for `InterfaceGuard`s, `MethodGuard`s, and `AwaitArgGuard`s.
> fix(patterns): type guards

- packages/assert/index.js
- packages/assert/test/test-index.js
- packages/ses/types.d.ts
refs: #1717
Fewer exports per https://github.com/endojs/endo/pull/1717#discussion_r1295130523
Clearer names per https://github.com/endojs/endo/pull/1717#discussion_r1297908833
These are breaking changes to master, but not to what's been published.
> clean up assert exports

- packages/pass-style/src/error.js
- packages/pass-style/test/test-passStyleOf.js
@mhofman discovered that `passStyleOf` was not validating that an error's `stack` property was a string-valued non-enumerable data property before concluding that it is a passable error. In fact, it was not even validating that the value of the `stack` property is passable. This flaw thus enabled data that was judged passable to carry non-passable data. 
This PR repairs that deficiency.
> fix(pass-style): passable error validation

- packages/exo/src/exo-makers.js
- packages/exo/test/test-revoke-heap-classes.js
Background: Exos already have a level of indirection between the exposed method with the protective method guard vs the raw method. In order to enable prototype-based method sharing of the protective methods, they lookup the context from their `this`, which is the exo object itself. The context is then passed as the `this` to the raw method. Having paid for this level of indirection, we already use it for many benefits, like enforcing that the exposed methods cannot be applied to unrelated instances.
An additional benefit we can obtain from this indirection is revocation. However, creating a revocable exo is the odd case. We don't want the normal case to pay an undue notational cost to accommodate the odd case, even if that raises the notational cost of the odd case a bit. We do so by …
> feat(exo): revocables

- packages/ses/NEWS.md
- packages/ses/README.md
- packages/ses/demos/challenge/README.md
- packages/ses/demos/challenge/index.html
- packages/ses/docs/draft-standalone-spec.md
- packages/ses/docs/guide.md
- packages/ses/src/permits.js
- packages/ses/src/tame-date-constructor.js
- packages/ses/src/tame-math-object.js
- packages/ses/test/test-tame-date-unit.js
- packages/ses/test/test-tame-date.js
- packages/ses/test/test-tame-math-unit.js
- packages/ses/test/test-tame-math.js
- packages/zip/README.md
Fixes #910 
@phoddie, I seem unable to add you as an official reviewer, but please consider yourself one anyway. I'm eager for your comments.
Technically this is a compat break, which I currently mark with a `fix(ses)!:`. Reviewers, please let me know whether you consider this change a compat break, or whether I should demote it to `fix(ses):`. Thanks.
> fix(ses): align with XS property censorship agreement

- packages/exo/README.md
- packages/ses/docs/secure-coding-guide.md
Saw https://github.com/endojs/endo/pull/1740/files?short_path=12f0146#diff-12f0146121857891eaea02008892eb51e98883364bc9ed4dfc544b7676e96c43 and wondered if it was a common mistake. Not too common, but not unique either.
See also https://github.com/Agoric/agoric-sdk/pull/8260
> doc: fix wrong quote in import example code

- packages/exo/README.md
- packages/exo/src/exo-tools.js
- packages/exo/test/test-heap-classes.js
- packages/patterns/src/patterns/patternMatchers.js
- packages/patterns/src/types.js
Fixes #1728
Extend InterfaceGuard with a `symbolMethodGuards` field whose value is a CopyMap\<symbol, MethodGuard> when the interface has symbol-keyed methods such as Symbol.asyncIterator. The current implementation expresses it as completely optional and does not create it when there are no symbol-keyed methods, but we could also set it to an empty CopyMap in that case.
None AFAICT.
None AFAICT, even if we always add the CopyMap.
None.
Just unit tests.
None special; the new functionality should be fully backwards compatible.
> fix(exo): Extend InterfaceGuard to support symbol-keyed methods

- packages/patterns/README.md
We have a convention for interface variable names of an identifier beginning with an upper case letter and ending with an uppercase `I`, such as `FooI`. Whether this convention is great or not, it is pervasive in our code, but with a small number of exceptions, which this PR fixes.
See https://github.com/Agoric/agoric-sdk/pull/8262
> doc(patterns): consistent interface naming

- packages/marshal/index.js
- packages/marshal/src/rankOrder.js
- packages/patterns/NEWS.md
- packages/patterns/index.js
- packages/patterns/src/keys/checkKey.js
- packages/patterns/src/keys/compareKeys.js
- packages/patterns/src/keys/copySet.js
- packages/patterns/src/keys/keycollection-operators.js
- packages/patterns/src/keys/merge-bag-operators.js
- packages/patterns/src/keys/merge-set-operators.js
- packages/patterns/src/patterns/patternMatchers.js
- packages/patterns/src/types.js
- packages/patterns/src/utils.js
- packages/patterns/test/test-copyBag.js
- packages/patterns/test/test-copyMap.js
- packages/patterns/test/test-copySet.js
- packages/patterns/test/test-patterns.js
closes: #1727
Supports CopyMap patterns by building value arrays from consistently-sorted merged entries after verifying key agreement.
Also implements but disables support for CopyMap comparison in alignment with CopySet and in particular CopyBag patterns—CopyMap X < CopyMap Y iff 
1. X and Y are both Keys, and 
2. ∀ x ∈ X (x ∈ Y ∧ X[x] ≤ Y[x]) [_every key in X is also in Y with an equivalent or bigger value_], and 
3. ∃ y ∈ Y (y ∉ X ∨ X[y] < Y[y]) [_at least one key in Y is either not in X or is in X with a smaller value_]. 
Note that this matches a commented-out `successCase(specimen, M.gt(makeCopyMap([])))` assertion in test-patterns.js but **differs** from some comments in compareKeys.js implying that maps with different keys should not be comparable (aligning with CopyRecord). I …
> feat(patterns): Support CopyMap Patterns

- packages/exo/NEWS.md
Ref #1740
Note also that we've got quite a bit of variance in NEWS.md files; should that be corrected?
```sh
$ awk 'FNR==1 && $0!=""' packages/*/NEWS.md | sort
User-visible changes in base64:
User-visible changes in `@endo/captp`:
User-visible changes in `@endo/exo`:
User-visible changes in `@endo/marshal`:
User-visible changes in `@endo/promise-kit`:
User-visible changes in eventual-send:
User-visible changes in SES:
User-visible changes in SES-Ava:
User-visible changes in Static Module Record, née Transform Module:
User-visible changes in Zip:
User-visible changes to netstring:
User-visible changes to the CommonJS module analyzer:
User-visible changes to the compartment mapper:
User-visible changes to the Endo environment initializer:
```
> docs(exo): Update NEWS.md

- packages/exo/README.md
- packages/exo/src/exo-tools.js
- packages/exo/test/test-heap-classes.js
- packages/patterns/index.js
- packages/patterns/src/patterns/internal-types.js
- packages/patterns/src/patterns/patternMatchers.js
- packages/patterns/src/types.js
To prepare for https://github.com/endojs/endo/pull/1712 , first abstract access to the contents of the guards. Once agoric-sdk is updated to a version of endo with this PR, its use of guards can be switched from directly accessing record properties, which would break on transition to #1712 , to calling the getters defined here, which will work before and after.
Once all such access is changed, we can then do a later endo release incorporating #1712 without breaking agoric-sdk.
> fix(patterns,exo): abstract guard getters

- .github/workflows/ci.yml
- packages/bundle-source/cache.js
In the most recent Endo release, I added a required `pid` argument to the bundle source cache maker, which is a breaking change. This change reverses that mistake by making the argument optional and using a large crypto-random number instead. It transpires that this new, default behavior is better than passing the `pid` for a process with more than one cache.
> fix(bundle-source): Backward-compatibility for cache pid argument

- packages/errors/package.json
I accidentally omitted the `@endo/errors` package from the last publish. This makes the package public.
> chore(errors): Prepare for first publish

- packages/patterns/test/test-patterns.js
More test coverage of `M.splitRecord`
> test: additional tests of splitRecord

- packages/patterns/src/patterns/internal-types.js
- packages/patterns/src/patterns/patternMatchers.js
The previous endo release added `getInterfaceGuardPayload` so that agoric-sdk could start to use it, rather than accessing the fields of an interface guard directly. This paves the way for https://github.com/endojs/endo/pull/1712 . However, because the type of `getInterfaceGuardPayload` did not propagate the type parameter from the guard argument to the returned payload, thehttps://github.com/Agoric/agoric-sdk/pull/8339  attempt to switch to it causes type errors due to the loss of this type information.
> fix(patterns): pass type parameter from interface guard to payload

- packages/marshal/src/encodePassable.js
- packages/pass-style/src/typeGuards.js
- packages/pass-style/src/types.js
- packages/patterns/src/patterns/internal-types.js
- packages/patterns/src/patterns/patternMatchers.js
- packages/patterns/src/types.js
- packages/patterns/test/test-copyBag.js
Staged on https://github.com/endojs/endo/pull/1771
Make guards a distinct category of taggeds, on par with matchers.
> fix(patterns)!: tag and retype guards

- packages/exo/src/exo-tools.js
- packages/exo/test/test-heap-classes.js
Alternative to https://github.com/endojs/endo/pull/1764 experiment.
Of the options listed there, this one
> Preserve the tolerant behavior, but not pass the values of the extra args through to the protected raw behavior method. This would preserve the input validation intent of method guards while still accommodating API growth and thus version slippage.
As suggested by @mhofman and @turadg
> fix(exo)!: extra undeclared args dropped

- packages/ses-integration-test/package.json
The private `ses-integration-test` package is not published to npm and nothing depends upon it, and we can’t conceive any reason anyone would try to fetch it from npm. However to eliminate any possible confusion, this change puts `ses-integration-test` in the `@endo/` namespace, ensuring that the `endo` org in `npm` controls the existence of the package.
> chore: Namespace ses integration test

- packages/ses/test/test-import-gauntlet.js
- packages/static-module-record/NEWS.md
- packages/static-module-record/src/transform-analyze.js
- packages/static-module-record/test/test-static-module-record.js
Currently, the `this` value in module scope is `globalThis`. This is a gap in fidelity, since it should be `undefined`, but is not a leak. This change alters the signature of the module functor generated by `StaticModuleRecord` such that `this` is bound to `undefined` with the existing instantiation code in `ses`. This also ensures that the undeniable `arguments` lexical name reveals nothing about the evaluator or module calling convention to the module.
This will break any program that depends on `this` being bound to `globalThis`. Since all such programs were already invalid and would not work in other environments like Node.js, I am choosing to treat this as a non-breaking-change, even though it may require bug-fixes elsewhere to reconcile versions.
This change does not add or remove …
> fix(static-module-record): Bind `this` and `arguments` more correctly

- .github/workflows/ci.yml
This change pushes us to evaluate Node.js 20.7 instead of earlier versions for future LTS in Endo CI. @kumavis found the referenced defect closed prior to this version due to write truncation when experimenting with large bundles over CapTP in the pet daemon.
> chore: Clarify Node.js 20 pre-LTS test version

- packages/marshal/test/test-encode-slot-in-promise.js
- packages/pass-style/src/safe-promise.js
- packages/pass-style/test/test-safe-promise.js
https://github.com/endojs/endo/pull/1781 demonstrates that the current endo (and it just so happens, the already-released endo) enables a passable promise to carry the string that @FUDCo needs to support testing. However, its way of carrying a string was terribly obtuse. 
This PR implements part of the plan explained at https://github.com/endojs/endo/pull/1781#issuecomment-1727080735 . Specifically, to have passable promises follow the precedent of passable far objects and exos, which also allow them to override the inherited @@toStringTag property with an own data property carrying a string value. However, agoric-sdk would not be able to use this more pleasant way of carrying a string until it is upgraded to depend on an endo containing this PR.
> feat(pass-style): Safe promises can override @@toStringTag with a string

- packages/netstring/package.json
- packages/netstring/test/test-netstring.js
- packages/netstring/writer.js
@kumavis identified in review a defect in the chunked mode for netstring writer. This change includes tests for the case where the target writer closes while we attempt to write netstring chunks, and provides the fix. Both tests previously failed.
Previously, writing to a netstring writer could mistakenly indicate that the stream was still open after the target closed, possibly reducing availability.
This should not have a material impact on scale, but might plug a memory leak.
No changes.
The behaviors changed are covered by the unit tests.
This should not create an obstacle for upgrades.
> fix(netstring): Early return during chunked write

- packages/compartment-mapper/src/import-hook.js
I’ve so far been unable to reproduce a problem @kumavis found in compartment-mapper with an obvious solution.
> fix(compartment-mapper): Root alias search

- packages/patterns/src/patterns/patternMatchers.js
By passing `label` here, we missed an intended optimization by `applyLabelingError`, and instead created needless stackframes with a try/catch for every level of a recursive pattern match, even for the `mustMatch` success case. With the `undefined`, when `mustMatch` succeeds, we should avoid all these. When `mustMatch` fails, we'll cut the number of these in half.
I do *NOT* know whether or not this change will make a significant performance difference. I also do not know if the significance will be different on v8 vs XS. I want to use this as my benchmarking + profiling "hello world" exercise, to get to know our performance measurement tooling.
This PR itself only makes the change. It does not measure anything.
> refactor(patterns): Omit needless stackframes

- packages/pass-style/endow.js
- packages/pass-style/package.json
- packages/pass-style/src/passStyleOf.js
Implement @gibson042 's suggestion at https://github.com/endojs/endo/pull/1676/files#r1264339663 as agreed in the thread starting at https://github.com/Agoric/agoric-sdk/pull/8051#issuecomment-1638454456
An advantage of using a symbol-named property on the global instead of a string-named property is that it is not aliased to a global variable name.
> feat(pass-style): Use endowed passStyleOf if at global symbol

- packages/ses/src/global-object.js
- packages/ses/src/lockdown.js
- packages/ses/test/test-compartment-instance.js
- packages/ses/test/test-repair-intrinsics.js
- packages/ses/test/test-tame-symbol-constructor.js
This is a small PR to enhance security by:
1. Freezing some Compartment-endowed capabilities that aren't currently frozen due to them being non-identical instances of their original version from the start Compartment
* Being:
* evaluators: `Compartment`, `eval` and `Function`
2. Hardening some start-Compartment capabilities that aren't currently hardened
*  Being:
* evaluators: `Compartment`, `eval` and `Function`
* `initialGlobalPropertyNames`: `Date`, `Error`, `RegExp`, `Math`, (?`getStackString`)
* Also `Symbol` although not belonging officially to the `initialGlobalPropertyNames` list
Not as far as I can tell
Not as far as I can tell
* Some Intrinsics are now being hardened on the globalThis of the start Compartment, meaning this PR isn't backward compatible with programs that attempt …
> feat(ses): Freeze evaluators, Compartment constructor and Symbol

- packages/marshal/docs/smallcaps-cheatsheet.md
As promised at the last ocapn meeting, here is a compact summary of the Smallcaps encoding of passable JS values into JSON.
> docs(marshal): Smallcaps Cheatsheet

- CONTRIBUTING.md
- packages/eslint-plugin/README.md
- packages/marshal/README.md
- packages/ses/package.json.md
I really like syntax highlighting.
See https://github.com/Agoric/agoric-sdk/pull/8415
> docs: identify language in some markdown blocks

- packages/lockdown/post.js
- packages/ses/src/error/console.js
- packages/ses/src/error/internal-types.js
- packages/ses/src/error/tame-console.js
Fix #1819
Tolerate the absence of non-ECMA-262 web platform APIs.
This follows existing patterns and hardens all introduced new non-primitive values. It will result in calls to a global `print` function that would not have otherwise happened, but only when it exists and `console` is undefined (but I believe any code capable of creating those circumstances could have overridden `console` anyway).
n/a
The non-web-platform environments of `eshost` invocations are sufficiently esoteric that I don't think documentation needs updating.
For similar reasons, I have not introduced new tests (although I suspect that _could_ be done).
None.
> fix: Support absence of TextEncoder/TextDecoder/console

- packages/daemon/src/daemon-node-powers.js
- packages/daemon/src/daemon-node.js
- packages/daemon/src/daemon.js
- packages/daemon/src/guest.js
- packages/daemon/src/host.js
- packages/daemon/src/mail.js
- packages/daemon/src/pet-store.js
- packages/daemon/src/reader-ref.js
- packages/daemon/src/types.d.ts
trying to abstract over
1) persistence mechanism
2) runtime platform
> refactor(daemon): rework power structure for easier persistence + platform abstraction

- packages/daemon/src/daemon-node-powers.js
- packages/daemon/src/mail.js
- packages/daemon/src/pet-name.js
- packages/daemon/src/pubsub.js
- packages/daemon/src/serve-private-path.js
- packages/daemon/src/serve-private-port-http.js
- packages/daemon/src/types.d.ts
- packages/daemon/src/web-page-bundler.js
- packages/daemon/src/web-page.js
- packages/daemon/src/worker-node.js
- packages/stream/index.js
- packages/stream/types.d.ts
Evidently type checks have drifted because `@ts-check` comments are for some reason not redundant with `"checkJs": true` as advertised. This change gets ts-check to pass for all the daemon sources.
> fix(daemon): Strengthen type checks

- packages/daemon/src/daemon-node-powers.js
- packages/daemon/src/daemon.js
- packages/daemon/src/serve-private-path.js
- packages/daemon/src/serve-private-port-http.js
- packages/daemon/src/types.d.ts
These are various bug fixes. There was a problem for services reporting that they started too early, due to a type mismatch for the `started` promise. Also, domain sockets evidently have a path length limit, so certain configurations will fail. The change here makes those errors more transparent to the user.
> fix(daemon): Various bug fixes

- packages/compartment-mapper/src/bundle-cjs.js
- packages/compartment-mapper/test/test-bundle.js
bug fix for bundler for supporting the following commonjs exports patterns 
```js
module.exports.abc = 123
exports.xyz = 456
```
Originally tried to fix it with https://github.com/endojs/endo/commit/7daba15b88752898ab1f9a1895d5cf479ea3575f
but this was insufficient, need to add missing cells and update the `*` cell
not sure if this is the correct change or just a bandaid but it got tests passing
> fix(compartment-mapper): fix for bundling of appended cjs exports

- packages/compartment-mapper/src/parse-cjs-shared-export-wrapper.js
here is the error  before this change
```
➜ (cd trials/bify-simple && PERF_N=100 node ../../endo.js)
(TypeError#1)
TypeError#1: first argument of importNow() must be a string
at nr (packages/perf/trials/bify-simple/node_modules/module-deps/index.js:307:21)
at eval (packages/perf/trials/bify-simple/node_modules/resolve/lib/async.js:93:25)
at eval (packages/perf/trials/bify-simple/node_modules/resolve/lib/async.js:32:18)
at LOOP (node:fs:2624:14)
```
> feat(compartment-mapper): throw error with context when requiring unresolved module

- packages/cli/src/endo.js
- packages/cli/src/kill.js
- packages/daemon/src/daemon.js
- packages/daemon/src/guest.js
- packages/daemon/src/host.js
- packages/daemon/src/mail.js
- packages/daemon/src/pet-store.js
- packages/daemon/src/terminator.js
- packages/daemon/src/types.d.ts
- packages/daemon/src/worker.js
- packages/daemon/test/counter-party.js
- packages/daemon/test/counter.js
- packages/daemon/test/test-endo.js
This stack of changes gives us a `terminate(petName)` method on the Endo Host Powers object. This will cause the daemon to forget the current incarnation of that named value and all named values that depend upon it, including parties that  received the value through `request` or `adopt`. This also terminates workers.
The implications of termination are far-reaching and this is only the beginning. New formulas may self-destruct, like a formula that uses a file watcher to invalidate itself when its on-disk dependencies change. Connections may self-destruct if they disconnect. Weblets might auto-reload if their powers are invalidated.
Also, because the formulas form an acyclic DAG, simple ref-counting should suffice for garbage collecting formulas. Formulas can be retained by pet name paths, …
> feat(daemon): Terminator DAG

- packages/patterns/index.js
- packages/patterns/src/patterns/internal-types.js
- packages/patterns/src/patterns/patternMatchers.js
refs: https://github.com/Agoric/agoric-sdk/pull/8459 , #1794 , https://github.com/Agoric/agoric-sdk/pull/8051
At the @endo/patterns level of abstraction, the `kindOf` function has the same role that `passStyleOf` has at the lower @endo/pass-style level of abstraction. However, the @endo/patterns package omitted `kindOf` from its exports, preventing some natural uses, such as those found in https://github.com/Agoric/agoric-sdk/pull/8459
This PR simply repairs that omission, by exporting `kindOf` so that dependent packages can use it.
Without `kindOf`, client code like https://github.com/Agoric/agoric-sdk/pull/8051 might be tempted to just check `passStyleOf(x) === 'tagged' && getTag(x) === 'someTagOfInterest'`. But this does not verify that `x` obeys the invariants expected of an object …
> feat(patterns): export kindOf

- packages/ses/package.json
- packages/ses/package.json.md
- packages/ses/types.d.ts
Much like #1803, this adds `types` conditional exports where appropriate.
Additionally, I fixed a type in `ThirdPartyStaticModuleInterface` which I was bumping up against.
> fix(ses): fix types export for newer module resolutions

- packages/ses/src/permits.js
closes: #1849
This allows `Promise.withResolves` to the permits list.
> Add `Promise.withResolvers` to permits list

- CONTRIBUTING.md
This change enshrines the role of the `next-release` label in our process for cutting Endo releases, ensuring that the releaser is reminded to check.
> docs: Formalize next-release label in process

- packages/exo/src/exo-tools.js
- packages/exo/test/test-heap-classes.js
closes: #1858
Correct the outdated implementation of `M.callWhen` that didn't account for changes made in #1831.
Needs careful examination, since method guards provide an essential barrier to protect against misuse.
n/a
n/a
A small unit test to demonstrate the problem now passes with the updated code.
n/a
> fix(exo): update `M.callWhen` broken by `M.raw()`

- packages/eventual-send/package.json
- packages/eventual-send/utils.js
- packages/exo/package.json
- packages/exo/src/exo-tools.js
- packages/exo/src/get-interface.js
- packages/exo/test/test-exo-class-js-class.js
- packages/exo/test/test-exo-wobbly-point.js
- packages/exo/test/test-heap-classes.js
- packages/exo/test/test-non-enumerable-methods.js
- packages/marshal/test/test-marshal-testing.js
- packages/pass-style/index.js
- packages/pass-style/package.json
- packages/pass-style/src/make-far.js
- packages/pass-style/test/test-far-class-instances.js
- packages/pass-style/test/test-far-wobbly-point.js
- packages/pass-style/test/test-passStyleOf.js
- packages/patterns/src/patterns/patternMatchers.js
closes: #1817 
refs: #1815 #1808 #1773 #1766 
The intention of the exo-making methods was to be able to use a JS class' `.prototype` as a source of raw methods. This PR
* fixes the bugs reported in #1817 that prevented use of JS classes as a source of raw methods for an exo class.
* additionally accommodates JS class inheritance so that superclasses can also provide raw classes.
* provides tests that show use of JS classes to construct Exo classes.
* these tests also provide hypothetical helper abstractions for better supporting such use of classes. 
* These helpers remain in tests because this PR merely demonstrates that such support is possible, without committing to the particular helpers to actually provide. We need at least to bikeshed from the currently awful names …
> fix(exo): allow richer behaviorMethods

- packages/compartment-mapper/package.json
- packages/daemon/package.json
- packages/lp32/package.json
- packages/ses/package.json
- packages/stream/package.json
- packages/where/package.json
Closes #1802 
TypeScript's `node16` and `nodenext` module resolution algorithms attempt to adhere more closely to the behavior of the `exports` field.  To that end, if an `exports` field is present in a package, the `types` field is ignored; instead, a `types` conditional export is expected.
Without this change, any consumer using one of these newer--_officially recommended_--module resolution algorithms will be unable to load any `types.d.ts` file from any package.  We retain the `types` field because of backwards compatibility with the legacy `node` module resolution algorithm.
[Read more about how I came to this conclusion](https://gist.github.com/boneskull/ae1faac253379a7d6f24749c9ba12c24)
_It depends._  While this file is not _truly_ needed for type support if type declarations are …
> fix: enable compatibility with node16/nodenext module resolution

- packages/pass-style/doc/copyArray-guarantees.md
- packages/pass-style/doc/copyRecord-guarantees.md
- packages/pass-style/doc/enumerating-properties.md
This is a drive-by polish of Mark’s property enumeration tables in the pass-style documentation. I maintain that these are high art worthy of exhibition on T-Shirts.
> docs(pass-style): Polish and conslidate property enumeration tables

- packages/daemon/src/pet-store.js
when overwriting a value in pet-store, we should remove the previous value.
This ensures we run proper cleanup:
- delete petname files
- remove known pet name for formula
- report deletion to subscribers
> fix(daemon): pet-store removes petname when overwriting with write

- packages/pass-style/src/types.js
_Originally posted by @erights in https://github.com/Agoric/documentation/pull/876#discussion_r1411146371_
> > _CopyTaggeds_ representing higher-order types
> 
> Not necessarily higher order in general. Probably the intended point is that these concepts are defined at a higher abstraction layer.
> chore: Improve the explanation of PassStyle "tagged"

- packages/grain/test/test-index.js
@kumavis i'm not sure what the end goal is for the grain package but i thought this fix might be appreciated. 
below is a screenshot of my console from a moment ago. i'm running the test with the `-w` flag so the passing tests show as soon as the update is saved.
*note - you're likely aware of the text below but adding it in for context*
this is something i frequently run into when testing hardened js code. ava needs `prepare-test-env-ava.js` to be the first import. just a guess here but its likely that vscode's prettier extension which automatically rearranges imports so that relative imports follow any dependency import.
> fix: updated test code

- .github/workflows/typedoc-gh-pages.yml
publish the site generated by `yarn docs` to https://endojs.github.io/endo/
This required changing [the setting](https://github.com/endojs/endo/settings/pages) from "classic" to use Actions:
n/a
n/a
More docs!
The workflow will only run in master. I don't know a good way to test it without merging.
n/a
> publish TypeDoc site to GH Pages

- .github/workflows/typedoc-gh-pages.yml
https://github.com/endojs/endo/pull/1883 introduced a new workflow https://github.com/endojs/endo/actions/workflows/typedoc-gh-pages.yml
It hasn't run yet because it was on pushes to `main` and this repo uses `master`.
This PR corrects that and enables manual dispatch too.
Manual dispatch can be called anytime, but only by admins
n/a
--
🤞
n/a
> fix typedoc-gh-pages config

- .github/workflows/typedoc-gh-pages.yml
- package.json
The job is running now but failing because the `typedoc` dep isn't installed: https://github.com/endojs/endo/actions/runs/7107676143/job/19349573778
This solves it with `npx typedoc`, instead of doing the full yarn install.
> npx typedoc

- packages/ses/scripts/bundle.js
closes: #1853
Prepends the `ses` _package.json > version_ as a comment to the bundled lockdown file
Possibly worth mentioning the version number is now included in the SES lockdown shim
Possibly add a unit test to check the version number is present at the head of the file
Manually tested locally:
```bash
git clean -fdx
```
```bash
nvm use 16 # or 18 or 20
```
```bash
npm i --force # https://github.com/endojs/endo/assets/1881059/72a4079c-fe00-4de8-ac2d-fb13406edbad
```
```bash
cd packages/ses
npm run build
```
```bash
head dist/ses.cjs # ensure correct version present as comment on line 1
```
```bash
npm run test
```
on Node
- v14.20.1
- ❌ [CI errors](https://github.com/endojs/endo/pull/1854#discussion_r1387159574)
- now [fixed](https://github.com/endojs/endo/pull/1854#discussion_r13880815 …
> feat(ses): add SES version to lockdown shim

- .github/workflows/typedoc-gh-pages.yml
The latest failure (https://github.com/endojs/endo/actions/runs/7107980418/job/19350413938) is that the imports don't resolve:
```
Run npx typedoc
npm WARN exec The following package was not found and will be installed: typedoc@0.25.4
[info] Converting project at ./packages/base[6](https://github.com/endojs/endo/actions/runs/7107980418/job/19350413938#step:4:7)4
[warning] No entry points were provided, this is likely a misconfiguration.
[info] Converting project at ./packages/bundle-source
[info] Converting project at ./packages/captp
packages/captp/src/atomics.js:1:23 - error TS26[8](https://github.com/endojs/endo/actions/runs/7107980418/job/19350413938#step:4:9)8: Cannot find type definition file for 'ses'.
1 /// <reference types="ses"/>
```
That's because there was no yarn install. So …
> ci: yarn install before typedoc

- packages/exo/src/exo-tools.js
- packages/exo/test/test-heap-classes.js
closes: #1888 
refs: #1889 #1765 #1809  https://github.com/Agoric/agoric-sdk/pull/8514 https://github.com/Agoric/agoric-sdk/pull/8641
Breaking change: Change method guard arguments matching rule to reject extra arguments by default.
Prior to #1765 we (I) had a bad bug that enabled extra args to bypass intended input validation. This was a definite security risk. At the time of this writing, agoric-sdk does indeed depend on an endo prior to #1765 and so does suffer from this risk.
#1765 repairs the security risk per se, in that these extra arguments are silently dropped instead. But experience has shown that this lenient behavior masks bugs that are better caught and fixed. The purpose of this PR is to have the method guard by default reject argument lists with extra args beyond those …
> fix(exo)!: reject extra args by default

- packages/evasive-transform/package.json
- packages/ses/package.json
- packages/static-module-record/package.json
- yarn.lock
closes: #1846
This should put #1846 to bed. The latest patch releases for Babel have addressed the property override mistake observed while bundling under lockdown.
As evidence, integrating this branch into Agoric SDK https://github.com/Agoric/agoric-sdk/pull/8514 obviates the need to run the bundler with overrideTaming: severe.
> Upgrade Babel 7.23

- packages/daemon/src/daemon-node-powers.js
- packages/daemon/src/daemon.js
- packages/daemon/src/types.d.ts
Reduces platform coupling to the implementation of workers by moving the connection protocol into the platform-specific makeWorker power.
> refactor(daemon): Remove worker connection protocol coupling from daemon

- packages/cli/src/cat.js
- packages/daemon/src/daemon-node-powers.js
- packages/daemon/src/daemon.js
- packages/daemon/src/reader-ref.js
- packages/daemon/src/types.d.ts
This change lines up the EndoReadable type for content address store nodes.
This also renames the `stream()` method to `streamBase64()` in hopes that someday we can add a `stream()` method that transits pass-by-copy immutable bytes instead.
> fix: Settle the readable types

- packages/cli/src/endo.js
- packages/cli/src/install.js
- packages/cli/src/open.js
This change factors an `endo install` command out of `endo open`, clarifying that you can install a weblet once and open it by name thereafter.
> feat(cli): Extract install from open command

- yarn.lock
closes: #XXXX
refs: #XXXX
The yarn.lock changes in this PR were purely automatically generated from a clean master by running `yarn`. No other changes.
> fix: commit auto-generated yarn.lock

- packages/env-options/README.md
- packages/env-options/package.json
- packages/env-options/test/prepare-test-env-ava.js
- packages/lockdown/package.json
- packages/ses-ava/package.json
- packages/ses-ava/test/prepare-test-env-ava.js
- packages/ses-ava/test/test-env-options.js
closes: #XXXX
refs: #XXXX
This PR is non-urgent, and so should wait for the current endo-release-agoric_sdk-upgrade dance to settle down.
Currently, before this PR, we get the following cyclic dependency warnings from `yarn build`
```
lerna WARN ECYCLE Dependency cycles detected, you should fix these!
lerna WARN ECYCLE @endo/compartment-mapper -> ses -> @endo/env-options -> @endo/init -> @endo/compartment-mapper
lerna WARN ECYCLE @endo/eventual-send -> (nested cycle: @endo/compartment-mapper -> ses -> @endo/env-options -> @endo/init -> @endo/compartment-mapper) -> @endo/eventual-send
lerna WARN ECYCLE @endo/lockdown -> (nested cycle: @endo/eventual-send -> (nested cycle: @endo/compartment-mapper -> ses -> @endo/env-options -> @endo/init -> @endo/compartment-mapper) -> @endo/eventual-send) …
```
> refactor(env-options): migrate test to reduce cyclic dependencies

- packages/bundle-source/src/is-entrypoint.js
- packages/eslint-plugin/lib/configs/recommended.js
- packages/eslint-plugin/lib/rules/no-nullish-coalescing.js
- packages/eslint-plugin/lib/rules/no-optional-chaining.js
- packages/evasive-transform/src/generate.js
- packages/evasive-transform/src/index.js
Agoric’s load generator test uses `node -r esm` which doesn’t support the `??` nor `?.` operators.
This change introduces a lint rule to help us avoid this trip-fall and then ensures that existing packages pass the new rules.
> Avoid null coalescing and optional chaining

- packages/captp/package.json
- packages/far/package.json
- packages/lockdown/package.json
- packages/marshal/package.json
To limit exposure to Hyrum’s Law, this change introduces an `"exports"` property to the four packages in Endo that currently lack one. Node.js 16+ and Endo’s bundler forbid deep imports to modules not expressly mentioned in `"exports"`.
> fix: Expressly forbid deep imports through captp, far, lockdown, marshal

- packages/evasive-transform/src/generate.js
- packages/evasive-transform/src/transform-ast.js
Agoric still uses an ESM emulation through the pattern `node -r esm` in its testnet load generator, which entrains Endo’s bundler. This change addresses “RESM” compatibility regressions with the recent creation of the `@endo/evasive-transform`, which is not tested under RESM.
> fix(evasive-transform): RESM treatment

- packages/daemon/src/daemon.js
- packages/daemon/test/test-endo.js
closes: #1901
A flaw in the Endo pet daemon prevented the user from creating new user profiles. The flow crept in through the refactor that separated external and internal facets for every entity that endo can create.
> fix(daemon): makeIdentifiedHost wrapped controller bug

- packages/exo/src/exo-makers.js
- packages/exo/test/test-amplify-heap-class-kits.js
- packages/exo/test/test-revoke-heap-classes.js
towards: https://github.com/Agoric/agoric-sdk/issues/8664
refs: #1666 
Adds a `receiveAmplifier` option to `definedExoClassKit` to parallel the existing `receiveRevoker`. The amplifier function you receive is a two argument function of `aFacet` and a `facetName`. If `aFacet` is an unrevoked facet instance of a cohort of that exo class kit, and `facetName` is the name of a facet column of that exo class kit, then the named element of `aFacet`'s cohort is returned.
See https://github.com/Agoric/agoric-sdk/issues/8664 for more explanation.
This PR does not by itself finish https://github.com/Agoric/agoric-sdk/issues/8664 . Rather, we need to wait for an endo release incorporating this PR followed by an agoric-sdk-endo sync before we can get started implementing this same feature for virtual …
> feat(exo): lightweight inter-facet rights amplification

- packages/exo/src/exo-makers.js
- packages/exo/test/test-amplify-heap-class-kits.js
closes: #XXXX
refs: #1902 
At https://github.com/endojs/endo/pull/1902#issuecomment-1874451253 @mhofman rightly points out
> In the kernel meeting a couple weeks ago, we discussed having the shape of this rights amplification function be a simple function that accepts a facet, and returns the cohort. I think I preferred that shape vs taking a facet name, but I do realize I didn't capture that feedback in this pull request.
This PR fixes that oversight.
I flagged this PR with a `fix(exo)!: ...` because this fix is not a compat change from #1902. OTOH, it is unlikely that anyone is using the #1902 API yet, in which case this PR is a compat change from the prior endo state. The last endo release was before #1902, so this PR is also a compat change from the last release.
Should I downgrade to …
> fix(exo): reform exo amplifier API

- packages/env-options/src/env-options.js
- packages/ses/src/error/fatal-assert.js
- packages/ses/src/error/tame-console.js
- packages/ses/src/tame-domains.js
- packages/ses/test/test-lockdown-shimmed-process.js
Fixes #1917
Updates packages/ses/src/error/tame-console.js to check for a `globalThis.process.on` function rather than assuming it when `globalThis.process` is defined.
Also updates general patterns for checking `globalThis` properties for better uniformity.
n/a
n/a
n/a
n/a
n/a
> fix(ses): Support an incomplete shimmed globalThis.process

- package.json
- packages/bundle-source/src/is-entrypoint.js
- packages/bundle-source/typedoc.json
- packages/evasive-transform/src/generate.js
- packages/lockdown/typedoc.json
- packages/marshal/src/encodeToCapData.js
- packages/marshal/src/types.js
- packages/marshal/test/test-marshal-capdata.js
- packages/marshal/test/test-marshal-far-function.js
- packages/marshal/test/test-marshal-far-obj.js
- packages/marshal/test/test-marshal-smallcaps.js
- packages/marshal/test/test-marshal-stringify.js
- packages/marshal/typedoc.json
- packages/ses/typedoc.json
- yarn.lock
Enables typedoc for these packages:
- ses
- @endo/lockdown
- @endo/bundle-source - this required fixing a `realpathSync` argument
- @endo/marshal - this required hard-coding the `any` and `string` types that it was trying to import from `pass-style` but failing
> more typedoc

- packages/patterns/src/utils.js
closes: #1450 
refs: #XXXX
Remove evasive blank line that was needed to work around a TypeScript problem #1450 but is no longer needed.
None
None
Should ease transition to using TS types for generated documentation. But does not yet actually help.
None
None
> refactor(patterns): remove evasive blank line

- scripts/create-package.sh
I renamed `repackage.sh` to `create-package.sh` when it stopped being idempotent. This updates its internal documentation to reflect the change.
> fix(scripts): Update create-package comment doc

- packages/marshal/test/test-marshal-serialization.js
closes: #1537
This PR addresses issues from #1537. It includes the following changes.
* Updated README.md file to reference new API.
* Removed odd line breaks throughout the README.md file.
* Added test code demonstrating correct usage + comparing the result to the old `M.serialize` and M.unserialize` methods.
*Note - This is my first PR attempt in the endo repository. I've read through the Contributing.md file but please let me know of any changes that may be necessary (or any problems at all with what I have drafted) 🙂*
Thanks!
> test(marshal): added test cases for new serialization API

- packages/captp/src/atomics.js
- packages/exo/test/test-exo-wobbly-point.js
- packages/far/test/test-e.js
- packages/lp32/reader.js
- packages/marshal/test/test-marshal-capdata.js
- packages/marshal/test/test-marshal-smallcaps.js
- packages/marshal/test/test-marshal-testing.js
- packages/netstring/reader.js
- packages/pass-style/test/test-far-class-instances.js
- packages/pass-style/test/test-passStyleOf.js
- packages/ses/src/lockdown.js
- packages/ses/test/test-make-hardener.js
- packages/stream/index.js
refs: #1914
While working on #1686, I found out that some shared prototypes are currently hardened as a side effect of an instance being hardened. This PR adds explicit harden for these.
It also contains a small refactor to harden all intrinsics in one shot instead of multiple calls to `harden`, as there are cycles in those, and some intrinsics were effectively hardened in other calls.
More explicit hardening brings more security
None
In Node.js, the `Buffer` and when the console is untamed, the internal `SafeMap` are now explicitly hardened. These would likely get hardened as side-effect of hardening instances before.
Tested in #1914 and https://github.com/Agoric/agoric-sdk/pull/8700 that these are all prototypes found through instances by existing tests. There may be others lurking, but …
> feat: explicitly harden some shared prototypes

- packages/ses/src/error/tame-console.js
- packages/ses/test/error/test-permit-removal-warnings.js
closes: #XXXX
refs: #1345 #1942 
A flaw in tame-console.js made it hard to use throws-and-logs.js to test the console output that happens during lockdown. The flaw is that tame-console.js read the value of the global `console` variable at initialization, rather than when `tameConsole()` is called. This PR moves that initialization code into `tameConsole`, which is highly unlikely to break any working code.
Using that fix, this PR also tests the current behavior that #1345 complains about. A later PR #1942 will fix that problem, building on this PR so that the difference is itself tested.
Prior to this PR, tame-console.js used `console` and `print` as ambient globals without a `/* global ... */` annotation. For `console` this is not surprising, as we generally assume this is ambiently …
> refactor(ses): refactor console init and test cleanup

- packages/ses/src/permits-intrinsics.js
- packages/ses/test/error/test-permit-removal-warnings.js
Staged on #1941 
closes: #1345 
refs: #1941 
Places all intrinsics removal cleanup diagnostics into a collapsed console group.
Attn @Jack-Works 
none
none
We should mention somewhere what this diagnostic means. Even though it is less visible, because it is now in a collapsed group, it is still purposely visible on the console output and people should be able to find out what it means --- and to know when to bring it to our attention.
none
none
> feat(ses): group removal cleanup diagnostics

- packages/compartment-mapper/demo/policy/index.mjs
- packages/compartment-mapper/src/import.js
- packages/compartment-mapper/src/node-modules.js
- packages/compartment-mapper/src/policy-format.js
- packages/compartment-mapper/src/policy.js
- packages/compartment-mapper/src/types.js
- packages/compartment-mapper/types.d.ts
This adds/narrows types for policies and exports them from the `compartment-mapper` entry point. It also updates some usages of existing and new types (e.g., removing "`@typedef` references", squashing some null-reference bugs, etc.).
> [!NOTE]
> This does not change the fact that `@endo/compartment-mapper` does not export types properly to `node16`/`nodenext`-resolution consumers (see #1803).
**Reviewers:** please scrutinize the types added to `src/types.js` closely. The generics allow an attenuator implementation to define the types of custom params which it expects. For example:
```js
// policy-converter.js
/**
* @typedef {'$root'} RootPolicy
* @typedef {'write'} WritePolicy
*/
/**
* Extends Endo's `PolicyItem` with the special {@link RootPolicy} and {@link WritePolicy}
* @typedef …
```
> feat(compartment-mapper): add policy-related types

- packages/ses/src/error/README.md
Closes #887 updating docs to reflect current implementation, which does reveal stacks on uncaught exception in most platforms without additional effort.
> docs(ses): Clarify that SES reveals stacks to console on uncaught exception

- packages/env-options/README.md
- packages/env-options/src/env-options.js
- packages/eventual-send/src/track-turns.js
- packages/exo/src/exo-makers.js
- packages/ses-ava/test/test-env-options.js
- packages/ses/src/lockdown.js
refs: https://github.com/Agoric/agoric-sdk/pull/8136
refs: https://github.com/Agoric/agoric-sdk/issues/8096
refs: https://github.com/Agoric/agoric-sdk/blob/master/docs/env.md#DEBUG
refs: https://github.com/endojs/endo/pull/1922
The indirection of `getEnvironmentCaptor` is only needed to support `getCapturedEnvironmentOptionNames`
`getCapturedEnvironmentOptionNames` is not currently used in either `endo` or `agoric-sdk`. Thus, we have enhanced
`@endo/env/options` to also directly export non-capturing forms of the other functions, like `getEnvironmentOption`, that are made and returned by `getEnvironmentCaptor`.
The value of an option is often supposed to be a list of strings separated by commas (`','`). However
https://github.com/Agoric/agoric-sdk/issues/8096 explains that sometimes our …
> feat(env-options): env-options conveniences for common cases

- packages/ses/test/test-frozen-anon-intrinsics.js
closes: #167
Expressly verifies that lockdown freezes at least one anonymous intrinsic even though it is a special category.
> test(ses): Test freezing of anonymous intrinsics

- packages/bundle-source/cache.js
- packages/bundle-source/src/fs.js
- packages/bundle-source/src/tool.js
Fixes #1955
Windows rename is not atomic and fails if the target exists. Our CI revealed this to us because it cached a bundle.
> fix(bundle-source): Accommodate Windows lack of atomic rename

- packages/eventual-send/src/track-turns.js
refs: https://github.com/Agoric/agoric-sdk/pull/8136
refs: https://github.com/Agoric/agoric-sdk/issues/8096
refs: https://github.com/Agoric/agoric-sdk/blob/master/docs/env.md#DEBUG
As explained at https://github.com/Agoric/agoric-sdk/issues/8096 , prior to this PR, eventual-send's use of the `DEBUG` option mistakenly split it on colons (`':'`). This PR switches that one use to split on commas (`','`) instead. 
Following widespread conventions leads to fewer unpleasant surprises.
none
https://github.com/Agoric/agoric-sdk/blob/master/docs/env.md#DEBUG already speaks in terms of the value of `DEBUG` being a comma separated list. Prior to this PR, the endo implementation does not conform to that document. But the agoric-sdk implementation would still not conform until fixed by …
> fix(eventual-send): switch DEBUG option to be comma separated

- package.json
- packages/skel/test/test-index.js
Makes the placeholder test in the placeholder package (`packages/skel/test/test-index.js`) fail by default.
Closes #1586
> chore(monorepo): Make placeholder tests fail by default

- packages/eventual-send/src/E.js
- packages/eventual-send/src/local.js
- packages/eventual-send/src/message-breakpoints.js
- packages/eventual-send/utils.js
- packages/pass-style/test/prepare-breakpoints.js
- packages/pass-style/test/test-message-breakpoints-demo.js
- packages/pass-style/test/test-message-breakpoints.js
closes: #XXXX
refs: #XXXX
Given an environment variable setting of
```console
$ export ENDO_DELIVERY_BREAKPOINTS="quatloos issuer.getAmountOf=*"
```
then when `E` invokes a `getAmountOf` method on an object with @@toStringTag of `'Alleged: quatloos issuer'`, it should first execute a JavaScript `debugger;` statement. When run normally, i.e., not under a debugger, the `debugger;` statement has no effect. But when run under a debugger, this statement acts as a breakpoint, causing execution to pause there.
If the "*" at the end is replaced by a number, then each time execution matches, the number is decremented by 1. When it reaches zero, it executes `debugger;`.
If the "getAmountOf" is replaced with "*", then it breakpoints on any method of a quatloos issuer.
If the "quatloos issuer" is …
> feat(eventual-send): breakpoint on delivery by env-options

- packages/exo/test/test-amplify-heap-class-kits.js
- packages/exo/test/test-heap-classes.js
- packages/exo/test/test-label-instances.js
- packages/exo/test/test-non-enumerable-methods.js
closes: #XXXX
refs: https://github.com/Agoric/agoric-sdk/pull/8745
At https://github.com/Agoric/agoric-sdk/pull/8745#discussion_r1451052306 @dckc noticed that an optional `x` parameter should have been declared optional but was not. Turns out that I had copy-paste-modify that mistaken declaration to other tests. 
This PR fixes the ones in endo. https://github.com/Agoric/agoric-sdk/pull/8750 the ones in agoric-sdk
none
none
more accurate static types should help us generate more accurate docs
none
none
> fix: "x" parameter in many tests is optional

- packages/ses/test/error/test-permit-removal-warnings.js
closes: #XXXX
refs: #1973 
Just skips the test that would currently trigger bug #1973 , until it is fixed.
none
none
none
Enables our tests to succeed even on platforms with novel properties that would generate init-time warnings, like Node 22.
none
> fix(ses): Suppress bug #1973 until it is fixed

- packages/exo/src/exo-tools.js
closes: #XXXX
refs: #1925 https://github.com/Agoric/agoric-sdk/pull/8752
A ContextProvider is a function from an instance to a Context or `undefined`. But the type did not include the `undefined`.
> fix(exo): ContextProvider typing

- packages/ses/src/permits.js
closes: #XXXX
refs: #1969 https://github.com/tc39/proposal-set-methods
Anticipates https://github.com/tc39/proposal-set-methods .
While doing #1969, I noticed
on the Chrome Canary console, which is SES letting us developers know that it encountered properties that it did not previously know about. No security problem, because they were all successfully removed. But the warning lets us know that we should decide what to do about these properties, including explicitly deciding that they should be deleted.
In this case, the properties are from the set-methods proposal, that we participated in at tc39 and are satisfied is safe. This PR permits them, so that SES no longer removes them.
With this PR on top of #1969, Chrome Canary's console is clean.
If we missed or misunderstood something about …
> feat(ses): Anticipate set-methods proposal

- packages/ses/src/enable-property-overrides.js
closes: #XXXX
refs: #1969 
At https://github.com/endojs/endo/pull/1969#pullrequestreview-1823695473 @mhofman suggests:
> As a matter of process, I would really prefer if independent changes were in separate commits. The change to the property override logic is great, but it seems it could easily stand in its own commit.
Because it is so separate, I made it into a this separate PR.
At https://github.com/endojs/endo/pull/1969#discussion_r1453556803 @mhofman suggests better code for that part of #1969. This PR uses that suggestion.
none
none
none
none
none
> refactor(ses): cleaner enable-property-overrides

- packages/ses/NEWS.md
- packages/ses/src/enable-property-overrides.js
- packages/ses/src/enablements.js
- packages/ses/src/lockdown.js
- packages/ses/src/tame-faux-data-properties.js
- packages/ses/test/test-tame-faux-data-properties.js
Fixes a bug initially reported by @FrederikBolding.
Staged on #1974 
closes: #1971 
refs: #1655 #1968 https://github.com/tc39/proposal-iterator-helpers https://github.com/endojs/endo/issues/1973
The iterators-helpers proposal https://github.com/tc39/proposal-iterator-helpers is now shipping in Chrome Canary. As per spec, it makes two properties into accessors that act like data properties that protect against the override mistake, i.e., that enable the property to be overridden by assignment. However, our permits for these properties were written when we knew them to be data properties, are they currently are on the other engines we've tested on to date. Because of this discrepancy, SES failed to initialize on Chrome Canary.
The purpose of this PR is to provide a mechanism to tolerate …
> fix(ses): handle properties that are already override protected

- packages/ses/NEWS.md
- packages/ses/src/tame-faux-data-properties.js
Fix a few typos and apply some minor tweaks to grammar and code.
n/a
n/a
n/a
n/a
n/a
> chore(ses): Cleanup after gh-1969

- packages/exo/src/exo-makers.js
- packages/exo/test/test-amplify-heap-class-kits.js
- packages/exo/test/test-is-instance-heap-class-kits.js
- packages/exo/test/test-live-instance-heap-class-kits.js
Now staged on #1964 
closes: #XXXX
refs: #1924 #1964 
This PR adds a third meta-level rights amplification power: the power to tell if an object is a live instance of an exo class, or a live facet instance of an exo class kit.
After revoking and amplifying, the remaining obvious meta-level rights amplification power normally associated with classes is unforgeable instance testing. (In some ocap literature, this is sometimes referred to as "brand testing". But given ERTP's conflicting use of the term "brand", this is best avoided.)
Given revocability and our desire that all these meta-level powers be essentially free, these test only that an object is a live instance of the associated class, or a live facet instance of the associated class kit. In neither case do we distinguish between a …
> feat(exo): instance testing

- packages/ses/src/compartment.js
- packages/ses/src/permits.js
- packages/ses/test/error/throws-and-logs.js
- packages/ses/test/test-compartment-instance.js
- packages/ses/test/test-compartment-prototype.js
Replaces the `Compartment` `toString` function with a `@@toStringTag` string property. This necessitated updating the permit for `%CompartmentPrototype%`, and some related tests. Some adjacent cleanup is also performed.
Ref: #676
> refactor(ses): Replace Compartment toString property with @@toStringTag

- packages/marshal/docs/smallcaps-cheatsheet.md
closes: #XXXX
refs: #XXXX
Upgrade the smallcaps cheatsheet's "OCapn name" column to use the latest agreed OCapN names.
Attn @cwebber @tsyesika @jar398
none
none
This PR itself doesn't change the first column "Passable value" of the names we normally use when we're not speaking to OCapN interoperability, so none there.
OCapN connected discussions have largely already moved to the new terminology, so this is mostly catchup.
none
none
> docs(marshal): Update to latest agreed ocapn terminology

- packages/base64/src/decode.js
- packages/base64/src/encode.js
- packages/base64/test/bench-main.js
* Capture results
* Make two passes per scenario
* Clarify full vs. short-input scenarios and run both against the same loop body
* Use performance.now() for benchmarking where available (e.g. Node.js)
n/a
n/a, except for potentially providing data to guide scaling improvements.
n/a
js{Encode,Decode}Base64 are now exported internally within the package so they may be benchmarked.
n/a
> chore(base64): Improve benchmark script

- packages/cli/src/endo.js
- packages/cli/src/prompt.js
Closes: #1987 
Renames the CLI `reset` command to `purge` in order to better distinguish it from `restart`. Also adds a confirmation prompt to the command, which can be overridden with the `-f`/`--force` flag.
N/A
N/A
N/A
Would it be helpful to start adding unit tests for anything where that's straightforward? cc: @kriskowal 
This is breaking for `@endo/cli`, but I'm not sure what we're doing about breaking changes at this stage, if anything.
> refactor(cli): Rename `reset` command to `purge`

- packages/compartment-mapper/src/import-archive.js
This addresses the `@ts-ignore` found in `makeFauxModuleExportsNamespace()`, which was renamed from `makeFeauxModuleExportsNamespace()`, because "féaux" translates to "loyal supporters" and not "fake" or "false" like was presumably intended.
I am not so bold to rename it `makeErsatzModuleExportsNamespace()`, despite "ersatz" being a wholly superior word to either of the above alternatives.
_Anyway_, this adds a proper type signature and fixes the return type; the `importHook` prop of the returned value did not adhere to the [definition of `ImportHook`](https://github.com/endojs/endo/blob/master/packages/ses/types.d.ts#L97). Likewise, `StaticModuleType` demands an `exports` array.
Given this apparently _worked just fine_ before I changed it, one could argue the types ought to be loosened …
> chore(compartment-mapper): fix type of internal function

- packages/daemon/src/daemon.js
- packages/daemon/src/formula-identifier.js
- packages/daemon/src/guest.js
- packages/daemon/src/host.js
- packages/daemon/src/pet-store.js
- packages/daemon/src/types.d.ts
- Adds `parseFormulaIdentifier` utility
- Adds  `{type, number}` formula identifier pair as `value` to petstore `follow()` entries
- Adds `listEntries` to petstore in `Object.fromEntries` with `{type, number}` formula identifier pair as value
- Provides `followEntries` as an alias to `follow`
- Exposes `listEntries` and `followEntries` on host and guest
I'm sending the `{type, number}` formula identifier pair instead of the string formula identifier. Alternatively, we could just the formula identifier.
> feat(daemon): pet store list entries

- .github/ISSUE_TEMPLATE/work_item.md
- .github/PULL_REQUEST_TEMPLATE.md
Adds considerations to pull request and issue templates to remind us about compatibility concerns.
> docs: Reminders for compatibility concerns

- packages/marshal/src/encodePassable.js
Ref #1982
Speeds up by 21% decoding a representation of the following CopyRecord:
```
{
primitives: [undefined, null, true, false, 0, 1, 0n, 1n, "foo", Symbol.for("bar")],
arrays: [[], [{}]],
records: { empty: {}, singular: { array: [] } },
}
```
(and speeds up decoding a CopyArray containing 10 copies thereof by about 100%)
No significant effects in Node.js.
n/a
As stated on the tin.
n/a
n/a
n/a
n/a
> perf(marshal): Replace XS-expensive string operations

- packages/base64/src/decode.js
- packages/base64/test/test-main.js
Fixes #1990
Test invalid encodings, and reject input that is too short.
None known.
n/a
Should this have a CHANGELOG entry?
New and improved!
n/a
> fix(base64): Reject too-short encodings

- packages/marshal/src/encodePassable.js
- packages/marshal/src/encodeToSmallcaps.js
- packages/marshal/src/marshal.js
Most notably, prefer `charAt(0) === ch` over `startsWith(ch)`.
```console
$ esbench --eshost-option '-h *XS' --init '
const c50 = "I am the *very* model of a modern major general.\n\n";
const c500 = Array(10).fill(c50).join("");
const c5k = Array(100).fill(c50).join("");
const c50k = Array(1000).fill(c50).join("");
' '' '{                                     
"c50.startsWith(ch)": `result = c50.startsWith("I");`,
"c500.startsWith(ch)": `result = c500.startsWith("I");`,
"c5k.startsWith(ch)": `result = c5k.startsWith("I");`,
"c50k.startsWith(ch)": `result = c50k.startsWith("I");`,
"c50[0]": `result = c50[0] === "I";`,
"c500[0]": `result = c500[0] === "I";`,
"c5k[0]": `result = c5k[0] === "I";`,
"c50k[0]": `result = c50k[0] === "I";`,
"c50.charAt(0)": `result = c50.charAt(0) === "I";`, …
```
> perf(marshal): Replace more XS-expensive string operations

- packages/eventual-send/README.md
tildot is far from ready-for-prime-time
context: increased priority on reference docs
- [@endo/eventual\-send \- v1\.1\.0 \| Endo API documentation](https://endojs.github.io/endo/modules/_endo_eventual_send.html)
> docs(eventual-send): strike ~. (tildot) fwd ref

- packages/bundle-source/src/zip-base64.js
encountered the incompatibility in either 1kce demo or cat ui in https://github.com/endojs/endo/pull/1877
this applies the evasive eval transform to cjs in addition to mjs as we do currently
replaces https://github.com/endojs/endo/pull/2003
> fix(bundle-source): apply eval evasion for cjs modules too

- packages/cli/src/endo.js
- packages/cli/src/make.js
- packages/cli/src/run.js
- packages/daemon/src/daemon-node-powers.js
- packages/daemon/src/daemon.js
- packages/daemon/src/host.js
- packages/daemon/src/pet-store.js
- packages/daemon/src/types.d.ts
- packages/daemon/src/web-page-bundler.js
- packages/daemon/src/web-page.js
- packages/daemon/src/worker.js
- packages/daemon/test/test-endo.js
Renames the `UNSAFE` flag to `UNCONFINED`, which is more specific. Also renames internals using "unsafe" (like `import-unsafe`) to use "unconfined" instead.
Will require an `endo purge -f`.
> feat(cli)!: Rename --UNSAFE to --UNCONFINED

- packages/common/test/test-from-unique-entries.js
- packages/common/test/test-object-map.js
closes: #XXXX
refs: https://github.com/Agoric/agoric-sdk/pull/8771
https://github.com/Agoric/agoric-sdk/pull/8771 will remove some copies of code in agoric-sdk that have migrated to endo. For two of these, the corresponding tests in agoric-sdk did some minor testing beyond the corresponding tests in endo. This PR merely moves that testing logic so it doesn't get lost in the shuffle.
> test(common): migrate missing tests

- packages/ses/src/permits.js
closes: #XXXX
refs: https://github.com/tc39/proposal-float16array
We should continue to permit all safe API elements that have reached stage 3. This one is safe and had not yet been included.
none
none
none
none
keeping up
none
Neither breaking, not warrants any mention in NEWS.md. As long as they don't see the warning, no one will care.
> feat(ses): permit stage 3 float16 proposal API

- packages/daemon/src/daemon-node-powers.js
- packages/daemon/src/pet-store.js
When splitting a hash into a single byte prefix and suffix, I accidentally trimmed four bits from the head of the suffix. Nothing broke because the mistake was consistent over a consistent hash but it is technically incorrect.
> fix(daemon): Address off-by-nybble formula path error

- packages/cli/demo/README.md
- packages/cli/demo/cat.js
- packages/cli/src/endo.js
- packages/cli/src/install.js
- packages/daemon/src/host.js
Buzz a sharp corner off of the `install` and `open` workflow by allowing them to be combined into a single command.
> feat(cli): Add install --open flag

- packages/ses/test/test-make-hardener.js
Closes #1053
A defect in a version of Node 14 required us to relax a check in the SES tests. With Node.js 14 a distant memory and 18 being LTS, we can reapply the test.
This reenables a test of our invariants.
Not applicable.
None.
Improves tests.
Does not alter compatibility.
Will not impact upgrade.
> chore(ses): Reapply hardened typed array configurable properties test

- packages/syrup/src/encode.js
refs: #1984
`encodeString`:
* Avoid redundant encoding.
* Cache `length` to avoid re-reading.
* Anticipate the likely count of prefix bytes to avoid moving data.
`encodeArray`:
* Account for element minimum size in encodeArray buffer expansion
`encodeAny`:
* Pass diagnostic path data as an array rather than a string 
(In the absence of errors, the associated string concatenation doesn't even take place.)
<details><summary>Effect</summary>
```shell
esbench -n 100 --repetitions 10 --eshost-option '-h V8,*XS' --eshost-option '-m' \
--init-file <(printf '%s\n' '
import { smuggle } from "data:text/javascript,delete globalThis.harden; if(typeof TextEncoder === `undefined`) Object.defineProperties(globalThis, { TextDecoder: { writable: true, enumerable: false, configurable: true, value: class …
```
> perf(syrup): Minimize expensive operations when encoding

- packages/daemon/src/daemon.js
- packages/daemon/src/formula-identifier.js
- packages/daemon/src/host.js
- packages/daemon/src/pet-store.js
- packages/daemon/src/types.d.ts
- packages/daemon/test/test-endo.js
Problem: Commands like `endo make counter.js --name counter` implicitly create a unique worker for the counter. This makes it impossible to address the worker for follow-up commands, like an `eval` co-located with the `counter`.
This change introduces an undeniable `INFO` name to all hosts that allows the host to address the values used to create pet named values. For example, `INFO -> counter -> worker` addresses the worker that was used to create `counter`. Until we have pet name path lookup (#1915), you need multiple invocations of `E()` to perform of depth greater than 1, for example:
```text
> endo make counter.js --name counter
Object [Alleged: Counter] {}
> endo eval 'E(INFO).lookup("counter")' INFO --name inspector
Object [Alleged: Inspector (make-bundle ... )]
> endo eval …
```
> feat(daemon): Undeniable host INFO tool

- packages/daemon/src/mail.js
- packages/daemon/src/types.d.ts
- packages/daemon/test/lookup.js
- packages/daemon/test/test-endo.js
Supersedes: #1915 
Implements mailbox petname path lookup by making the mailbox `lookup()` method variadic. Adds tests to verify how this composes with the inspector and caplets with their own `lookup()` method.
This enables us to later add dot-separated paths for petnames in the CLI.
Did I overlook any places that should accept `string | string[]` where currently only a single `petName` is expected?
> feat(daemon): Add petname path lookup

- packages/ses/src/enablements.js
- packages/ses/test/test-enable-property-overrides-default.js
- packages/ses/test/test-enable-property-overrides-severe-debug.js
- packages/ses/test/test-enable-property-overrides-severe.js
closes: #XXXX
refs: #2029 
This does not close #2029 , but it does close the first hurdle, the 
```
TypeError: Cannot assign to read only property 'concat' of object '[object Object]'
```
problem. I have yet to diagnose or fix the 
```
TypeError#2: Cannot perform 'ownKeys' on a proxy that has been revoked
```
The problem fixed by this PR is interesting. The override mistake is in mobx generated code, where the corresponding mobx source code is a TypeScript class definition. The generated code is not a JS class definition, but rather, seems to target pre-class JS. The surprising mistake is that the generated code is initializing the methods on the "class" .prototype using assignment rather than `defineProperty` in blatant violation of the JS class semantics. Presumably, this is also a …
> feat(ses): enablements needed by (old?) mobx

- packages/marshal/README.md
- packages/marshal/index.js
- packages/marshal/src/encodePassable.js
- packages/marshal/test/test-encodePassable.js
Fixes #1349
Open questions:
```diff
-"~(^^stab snull smetasyntactic!_variables  ^s!* s!! ^sfoo sbar sbaz   "
+"~(^^stab\tsnull\tsmetasyntactic variables\t\t^s\n9\ts\n0\t^sfoo\tsbar\tsbaz\t\t\t"
```
> fix(marshal): Add a smaller and more efficient passable encoding

- packages/exo/test/make-legacy-guards.js
- packages/exo/test/test-legacy-guard-tolerance.js
closes: #XXXX
refs: https://github.com/Agoric/agoric-sdk/issues/8826 #2038 
Tests the compat failure behavior prior to #2038 that we believe is the cause behind our current understanding of https://github.com/Agoric/agoric-sdk/issues/8826 . Sets things up so that #2038 's differences in behavior, to give us the compat https://github.com/Agoric/agoric-sdk/issues/8826 needs, can be demonstrated by the changes it must make to these tests so they will pass again.
Since this PR is only adding tests, none. But see considerations in #2038 
Since this PR is only adding tests, none. But see considerations in #2038 
Since this PR is only adding tests, none. But see considerations in #2038 
The whole point of this PR. See the description. But these are just for unit testing compat problems that we …
> test(patterns,exo): pre-tests of upcoming #2038

- packages/cli/src/commands/eval.js
- packages/cli/src/pet-name.js
- packages/daemon/src/daemon.js
- packages/daemon/src/host.js
- packages/daemon/src/mail.js
- packages/daemon/src/pet-name.js
- packages/daemon/src/pet-store.js
- packages/daemon/src/types.d.ts
- packages/daemon/test/test-endo.js
Ref: #2023 
Adds support for dot-delimited petname paths to the CLI `eval` command. This required modifications to the `evaluate` method of the daemon's `host.js`, and the introduction of a new formula type, `lookup`.
The `lookup` formula type is necessary because the names in a lookup path may have neither petnames nor formula identifiers associated with them. Consider:
```text
> endo eval '10' --name ten
10
> endo eval 'foo' foo:INFO.ten.source
10
```
The only way retrieve the value for `source` is to call `E(HOST).lookup('INFO', 'ten', 'source')`, and since the `eval` formula expects its values to be mediated by formula identifiers, the lookup of `INFO.ten.source` must itself be stored as a formula.
The `lookup` formula is an `-id512` formula with the following interface:
```typescript …
```
> feat(cli,daemon): Support dot-delimited petname paths for CLI `eval` command

- packages/ses/test/error/test-permit-removal-warnings.js
- packages/ses/test/error/throws-and-logs.js
closes: #1973 
refs: #XXXX
Previously, `throwsAndLogs` would only support testing against a literal golden. But for testing the initial-removal-log-messages, this was too fragile, since new engines might have added new properties whose removal would general additional initial-removal-log-messages. This PR enable the caller to provide an alternative compare function. That one test then uses this flexibility to tolerate additional warnings interspersed between the golden warnings it looks for.
none
none
none
The whole point. This enables us to turn an annoying `test.skip` back into the needed `test`.
Enables the test to remain compatible with benign future engine versions.
none.
Nothing breaking.
No news updates warranted.
> test(ses): fix 1973, unskip log test

- packages/cli/src/context.js
- packages/cli/src/endo.js
The CLI `--as` option previously supported paths like this:
```
endo list --as foo --as bar
```
This does away with the ability to specify the option multiple times, and replaces it with dot-delimited path support:
```
endo list --as foo.bar
```
This works for all commands.
> feat(cli): Support dot-delimited paths for `--as` option in all commands

- packages/exo/test/test-non-enumerable-methods.js
- packages/marshal/test/marshal-test-data.js
- packages/marshal/test/test-encodePassable.js
- packages/marshal/test/test-marshal-capdata.js
- packages/marshal/test/test-marshal-justin.js
- packages/marshal/test/test-marshal-smallcaps.js
- packages/marshal/test/test-marshal-stringify.js
- packages/marshal/test/test-rankOrder.js
closes: #XXXX
refs: #XXXX
At https://github.com/endojs/endo/pull/2008#discussion_r1470460271 @dckc explained why `test/test-*.js` files should not export things. Currently, we have a few of those. This PR reforms those, moving shared stuff into separate `test/*.js` files that are not `test-*` files, and exporting from there.
none
none
none
The whole point. By exporting from one `test-*.js` file and importing into another, ava would run sometimes run the exporting test twice, or when it did not need to.
none
none
Nothing breaking.
No news updates warranted.
> test(marshal,exo): stop exporting from test-*.js files

- packages/bundle-source/src/zip-base64.js
- packages/cli/src/commands/bundle.js
- packages/cli/src/endo.js
needed `commonDependencies` option exposed to handle node builtin package shims for browser
> feat: endo bundle command supports specifying commonDeps

- packages/daemon/src/daemon.js
- packages/daemon/src/host.js
- packages/daemon/src/mail.js
- packages/daemon/src/pet-store.js
- packages/daemon/src/types.d.ts
unify naming of methods in `petStore` and `mail` that synchronously return a `formulaIdentifier` for a non-path petname
> fix(daemon): use naming convention "identifyLocal"

- packages/daemon/package.json
Adds a `test:clean` package script to `@endo/daemon`, which we should never, but nevertheless may, need.
> chore(daemon): Add test:clean script

- packages/daemon/src/daemon.js
- packages/daemon/src/host.js
this helps remove an unnecessary dependency on `formulaIdentifierForRef` in host
(we are currently suspicious of the correctness of `formulaIdentifierForRef`)
> Daemon: in host breakout makeHost/makeGuest from provideHost/provideGuest

- packages/daemon/src/daemon.js
- packages/daemon/src/formula-identifier.js
- packages/daemon/src/pet-store.js
Replaces the numberless `pet-inspector` formula with the id512-equivalent. The root inspector has the zero id. This can be replaced with a random number in the future.
> refactor(daemon): Remove numberless inspector formula

- packages/daemon/src/daemon-node-powers.js
- packages/daemon/src/daemon.js
- packages/daemon/src/formula-identifier.js
- packages/daemon/src/pet-store.js
Replaces the numberless `host` formula with the zero `host-id512` formula. Can be replaced with something random in the future.
> refactor(daemon): Remove numberless host formula

- packages/daemon/src/daemon.js
- packages/daemon/src/formula-identifier.js
- packages/daemon/src/host.js
Converts the `least-authority` formula to a numbered, id512 equivalent. The formula number used will always be the zero id512, but this can be changed in the future.
> refactor(daemon): Make least-authority formula numbered

- packages/daemon/src/daemon.js
- packages/daemon/src/formula-identifier.js
- packages/daemon/src/web-page-bundler.js
Converts the `web-page-js` formula to a numbered, id512 equivalent. The formula number used will always be the zero id512, but this can be changed in the future.
> refactor(daemon): Make web-page-js formula numbered

- packages/daemon/src/daemon.js
- packages/daemon/src/formula-identifier.js
- packages/daemon/src/host.js
Converts the `endo` formula to a numbered, id512 equivalent. The formula number used will always be the zero id512, but this can be changed in the future.
> refactor(daemon): Make endo formula numbered

- packages/marshal/NEWS.md
- packages/marshal/package.json
- packages/marshal/src/marshal-justin.js
- packages/marshal/src/marshal.js
- packages/marshal/test/test-marshal-capdata.js
- packages/marshal/test/test-marshal-smallcaps.js
closes: #XXXX
refs: #2042 #550 
To enable future versions of marshal to send extra error properties, like `cause` and `error`, marshal must tolerate receiving them.
Sets the stage for #2024 
by tolerating the reception of extra error props, we no longer inhibit senders from sending them, including misspelled or otherwise mistaken ones. This weaken the degree to which unmarshaling validates. This is the necessary price of accommodating expected future growth.
none
none
tests included also serve as a baseline for #2042, which needs to change them in order to pass again. This provides a record of the difference between this PR and #2042.
The whole point, is to accommodate an expected future in which some extra properties are sent, such as `cause` and `errors`.
This change, to tolerate …
> feat(marshal): tolerate extra error props

- packages/cli/src/commands/list.js
- packages/cli/src/endo.js
- packages/daemon/src/guest.js
- packages/daemon/src/host.js
- packages/daemon/src/mail.js
- packages/daemon/test/test-endo.js
Replaces https://github.com/endojs/endo/pull/1918
dropped shorthand flag for `--all` bc its already pretty short and didnt want to confuse with `--as`
> Daemon: List special names

- packages/daemon/src/daemon-node-powers.js
- packages/daemon/src/types.d.ts
- breaks out `SocketPowers` from `NetworkPowers`
- adds `connectPort` for tcp net layer to be utilized later
Ref: https://github.com/endojs/endo/pull/1993
> feat(daemon): Add TCP net layer

- packages/cli/src/commands/make.js
- packages/daemon/src/daemon-node-powers.js
- packages/daemon/src/daemon.js
- packages/daemon/src/host.js
- packages/daemon/src/types.d.ts
- packages/daemon/src/worker.js
- packages/daemon/test/test-endo.js
if we want to add backwards compat we can attempt to resolve the old path, but the attempt at backwards compat that was in the cherry-picked commit looked broken (didnt re-resolve)
update of https://github.com/endojs/endo/pull/1899
> Daemon: Change unsafe import formula from path to specifier

- packages/ses/src/permits.js
closes: #XXXX
refs: https://github.com/Moddable-OpenSource/moddable/issues/523#issuecomment-1942904505
Initializing SES on XS reports additional non-standard properties to remove, beyond those previously mentioned by https://github.com/Moddable-OpenSource/moddable/issues/523 . Initializing SES on QuickJS reveals a different set of additional non-standard properties to remove. Without this PR, all these extra properties are still safely removed, but with a console warning because they were unexpected. This PR simply adds a `propertyName: false` for each of these to `permits.js` to record that we now expect them and do not need the warning.
The purpose of the warning is so that we, the SES developers, are alerted to surprising additions to the platform in case they raise the possibility of …
> feat(ses): expect more properties to censor

- packages/daemon/src/daemon-node-powers.js
- packages/daemon/src/daemon.js
- packages/daemon/src/host.js
- packages/daemon/src/mail.js
- packages/daemon/src/pet-store.js
- packages/daemon/src/types.d.ts
- packages/daemon/src/web-page-bundler.js
- packages/daemon/test/test-endo.js
Removes the `-id512` and `-sha512` suffixes from all formula type strings. These were redundant since all formula numbers are of that format (except `web-bundle`, which we shall fix in the near future).
> refactor(daemon): Despecify id512/sha512 in formula type

- packages/cli/src/commands/log.js
Doing `endo log` when the daemon is stopped would previously provide unhelpful results. Now, the user is notified that the daemon is not running instead. `endo log -f` will not exit but wait for the daemon to start, then operate normally.
> fix(cli): Improve log behavior when stopped

- packages/cli/package.json
- packages/daemon/package.json
Set `package.json['private']` to `true` to prevent accidentally publishing `@endo/daemon` and `@endo/cli`.
> feat(cli,daemon): Make packages private

- packages/cli/src/endo.js
- packages/daemon/index.js
- packages/daemon/test/test-endo.js
- packages/daemon/types.d.ts
Recently, we renamed `reset` to `purge` in the daemon and CLI. This takes care of some leftover references to "reset".
> refactor(cli,daemon): Rename leftover `reset` references to `purge`

- packages/daemon/src/pet-store.js
- packages/daemon/src/types.d.ts
I'm not sure what the ideal pattern is.
This change is an improvement because it gives us a single source of truth for the types, whereas before we have repeated and unaligned definitions.
Its also worse because now the definitions are not readable above the functions implementations.
Apparently this setup also affects jsdoc generation
im not sure what a better way is, but i think this is worth merging for now
> fix(daemon): enhance types for pet-store

- packages/daemon/src/daemon.js
When formula numbers were made unique, it appears we missed doing so for the guest pet store and worker. This PR ensures that they are derived in a manner similar to that of the host.
> fix(daemon): Ensure guest store and worker formula numbers are unique

- packages/daemon/src/mail.js
> fix(daemon): in mail remove redundant SELF lookup

- packages/daemon/src/daemon-node-powers.js
- packages/daemon/src/mutex.js
use mutex to ensure serial file operations
all updates happen synchronously in memory
all disk operations are queued to ensure that the previous operation completed before continuing
> fix(Daemon): node file powers write lock

- packages/daemon/src/daemon-node-powers.js
- packages/daemon/src/daemon.js
- packages/daemon/src/guest.js
- packages/daemon/src/host.js
- packages/daemon/src/mail.js
- packages/daemon/src/pet-store.js
- packages/daemon/src/types.d.ts
- packages/daemon/test/test-endo.js
- Factors out endo configuration ( eg default host formulaIdentifier ) from newly named `daemonCore`.
- Introduces `incarnateXyz` methods to be used when creating a new thing for the first time.
- Persists all formulas and requires them to be incarnated before they can be reified via `provideValueForFormulaId`
- Adds Handles as a generic pointer to another formula, where the pointer is exposed on the internal facet only. This is currently used to give a guest a reference to the host without exposing host endowments. mail uses `provideControllerForFormulaIdentifierAndResolveHandle` to resolve the handle.
Updates: #1993 
Closes: #2087
> feat(daemon): store endo bootstrap and default host formulas

- packages/patterns/NEWS.md
- packages/patterns/src/patterns/patternMatchers.js
- packages/patterns/src/types.js
- packages/patterns/test/test-patterns.js
closes: #XXXX
refs: https://github.com/Agoric/agoric-sdk/pull/8742 https://github.com/Agoric/agoric-sdk/pull/8958
@dckc encountered the need to express a Vow pattern. The Vow abstraction is currently only defined by agoric-sdk. But it is encoded into a Tagged object, where that Tagged is not a recognized kind at the @endo/patterns level. This caused us to notice the inability to express patterns over Tagged objects. This PR adds that. Using it, a VowShape should be expressible as
```js
const VowShape = M.tagged(
'Vow',
harden({
vowV0: M.remotable('VowV0'),
}),
),
);
```
We include a test case that is similar in all the relevant ways.
none
none
We include doccomments in the PatternMatchers type, that should show up next time we regenerate …
> feat(patterns): New `M.tagged` pattern maker

- packages/pass-style/src/copyRecord.js
- packages/pass-style/src/error.js
- packages/pass-style/src/passStyle-helpers.js
- packages/pass-style/src/remotable.js
- packages/pass-style/src/safe-promise.js
Reduce the nesting depth for input validation by defining `reject`s as tag functions rather than traditional wrappers.
n/a
Constructing details is already in the slow path exercised only with an explicit check function, and introducing rest/spread to the wrapper imposes minor additional cost (the `reject` call itself gets about 6% slower on XS and 20% slower on V8). We could probably do better by passing `reject` functions rather than constructing them at each level, but that would affect the public API so I'm not contemplating that here.
n/a
n/a
n/a
n/a
> style(pass-style): Reduce nesting depth for input validation

- packages/daemon/src/daemon.js
- packages/daemon/src/host.js
- packages/daemon/src/mail.js
- packages/daemon/src/types.d.ts
- packages/daemon/test/test-endo.js
Fixes: #2021
Synchronizes the host's `evaluate()` method by delegating all incarnations to the daemon via `incarnateEval()`. The latter is responsible for incarnating its dependents as necessary, and for the generation of their formula numbers. To facilitate this, the synchronous methods `incarnateLookupSync()` and `incarnateWorkerSync()` have been added. These methods synchronously mutate the formula graph, and return promises that resolve when the formulas have been written to disk. The result is that the formula graph is mutated within a single turn of the event loop.
To achieve this, the implementation introduces new constraints on the daemon and its dependents. https://github.com/endojs/endo/pull/2089 introduced the notion of "incarnating" values. By the current …
> refactor(daemon): Synchronize host `evaluate` method

- packages/daemon/src/daemon-node-powers.js
- packages/daemon/src/daemon.js
- packages/daemon/src/mail.js
- packages/daemon/src/mutex.js
- packages/daemon/src/types.d.ts
- packages/daemon/src/worker.js
- packages/daemon/test/context-consumer.js
- packages/daemon/test/test-endo.js
Updates #2086 
Exposes the `context` object to confined and unconfined caplets by passing it as a second argument to their `make()` function.
> feat(daemon): Expose cancellation context in caplets

- packages/daemon/src/daemon.js
- packages/daemon/src/types.d.ts
- packages/daemon/src/weak-multimap.js
- packages/daemon/test/test-weak-multimap.js
Replaces the `formulaIdentifierForRef` WeakMap with a WeakMap-backed multimap, enabling the maintenance of one-to-many relationships between values and formula identifiers.
> refactor(daemon): Retain multiple formula numbers per value

- packages/daemon/package.json
It looks like Lerna didn’t adjust the devDependencies for the daemon to match the latest release. I’ll keep an eye on that, but for now, this addresses the issue and is the mechanical effect of running `./scripts/sync-version.sh .`.
> fix(daemon): Catch up init dev dependency to adjacent workspace

- packages/cli/src/endo.js
Taking a nod from remarks (not tagged because vaccay), I’m consolidating the common endo `--name` flag description.
> refactor(cli): Consolidate common name flag

- packages/ses/src/tame-regexp-constructor.js
closes: #XXXX
refs: #XXXX
MetaMask is targeting React Native, that run on the Hermes JS engine. Thus, it would be good for the ses-shim to work on Hermes. Once problem we ran into is that Hermes omits `Symbol.species`. (Good riddance!) With this PR, the ses-shim should tolerate this difference from standard JS.
***Assuming*** that the semantics of the JS they implement is adjusted from the standard semantics in any of the obvious ways to cope with the absence of `Symbol.species`, this should have little effect on security.
Those "obvious ways" are
- Just act as if the species is always the base constructor itself. IOW, when asking a subclass of Array to `.map`, return an array rather than an instance of this or a related subclass of array.
- Just use `constructor` for what …
> feat(ses): tolerate omitted species

- packages/bundle-source/cache.js
- packages/bundle-source/src/bundle-source.js
- packages/bundle-source/src/nested-evaluate-and-get-exports.js
- packages/bundle-source/src/zip-base64.js
Using dynamic import in bundleSource made it possible to use `bundleSource` for one format and not entrain all the tooling for other formats, like Rollup for `getExport` and Babel for `endoZipBase64`. But, it broke the flow of type information. This change proposed by @michaelfig rectifies the internal and external types.
None.
None.
None.
This PR does not adequately test the exported type signature.
It would pair well with a change that relies on the exported types.
None.
None.
- ~~[ ] Includes `*BREAKING*:` in the commit message with migration instructions for any breaking change.~~
- ~~[ ] Updates `NEWS.md` for user-facing changes.~~
> fix(bundle-source): Export types properly

- packages/ses/docs/lockdown.md
Add section links to the options summary table (placed at the end to minimize disruption when looking at the Markdown source).
> docs(ses): Add section links

- packages/daemon/src/daemon.js
- packages/daemon/src/directory.js
- packages/daemon/src/guest.js
- packages/daemon/src/host.js
- packages/daemon/src/mail.js
- packages/daemon/src/pet-sitter.js
- packages/daemon/src/pet-store.js
- packages/daemon/src/types.d.ts
- adds pet-sitter utility for dealing with specialNames
- factors non-mail methods out of mail
- introduces directories and nameHub interface
- removes `listEntries` and `followEntries` from petStore, host, guest
- breaks host and guest API slightly
Updates https://github.com/endojs/endo/pull/1993
> Daemon: add directories

- packages/cli/src/commands/spawn.js
- packages/daemon/src/host.js
- packages/daemon/src/types.d.ts
- packages/daemon/test/test-endo.js
Removes the host's `makeWorker()` and replaces its use everywhere with the equivalent `provideWorker()`. The latter is essentially like the former but with more validation.
> refactor!(daemon): Remove host `makeWorker()`

- packages/daemon/src/daemon.js
- packages/daemon/src/host.js
- packages/daemon/src/types.d.ts
- packages/daemon/test/doubler.js
- packages/daemon/test/test-endo.js
Progresses: #2086
Synchronizes the host's `makeUnconfined()` per #2086. Refactoring `daemon.js` in support of this goal fixed one bug while revealing another.
In particular, #2074 is progressed by enabling indirect cancellation of caplets via their workers. The issue is not resolved since indirect cancellation of caplets via their caplet dependencies still does not work as intended. A new, failing regression test has been added for this specific case.
The revealed bug is #2021, which we believed to be fixed by #2092. Rather than fixing the bug, that PR concealed it by always creating a new incarnation of `eval` formula workers, even if they already existed. The regression test for #2021 has been marked as failing, and we will have to find a different solution for it.
> refactor(daemon): Synchronize host `makeUnconfined()`

- packages/cli/src/pet-name.js
- packages/daemon/src/daemon.js
- packages/daemon/src/host.js
- packages/daemon/src/types.d.ts
Synchronizes the host's `makeBundle()` following the pattern established by `makeUnconfined()`. Eliminates the host's
`provideWorkerFormulaIdentifier()`, which is everywhere replaced with the synchronous `prepareWorkerFormulaIdentifier()`. Performs some opportunistic refactors of `makeX` and `incarnateX` where `X === 'Bundle' | 'Unconfined'`.
> refactor(daemon): Synchronize host `makeBundle()`

- packages/nat/package.json
- packages/nat/tsconfig.build.json
- packages/nat/tsconfig.json
The types weren't being built in the NPM package. Downstream would get them sometimes by node modules search, but only if within sufficient search depth.
This removes the need for searching node_modules
none
none
no, more like other packages now
CI
fully back compat
none
> build: .d.ts for nat

- packages/daemon/src/daemon-node-powers.js
- packages/daemon/src/daemon.js
- packages/daemon/src/serial-jobs.js
- packages/daemon/src/types.d.ts
- packages/daemon/test/test-serial-jobs.js
Renames the daemon's `Mutex` to `SerialJobs`, which better reflects its purpose. Also removes `lock()` and `unlock()` from its interface.
> refactor!(daemon): Rename mutex to serial-jobs

- packages/pass-style/NEWS.md
- packages/pass-style/index.js
- packages/pass-style/package.json
- packages/pass-style/src/passStyleOf.js
- packages/pass-style/src/string.js
- packages/pass-style/test/prepare-only-well-formed-strings-passable.js
- packages/pass-style/test/test-passable-string.js
closes: #1739 
refs: https://github.com/ocapn/ocapn/issues/47 https://github.com/tc39/proposal-is-usv-string
At an OCapN meeting, we resolved https://github.com/ocapn/ocapn/issues/47 by deciding that only well-formed Unicode strings may be passed. A well-formed Unicode string does not contain any unpaired surrogates. It consists only of a sequence of Unicode code points. A conforming OCapN implementation MUST only emit well-formed Unicode strings, and MUST validate that incoming strings are well-formed, and reject those that are not.
Within the Agoric implementation, the way to implement these restrictions is by having `passStyleOf(str)` only judge well-formed string to be passable, rejecting all other strings as not passable.
If the underlying engine does not yet implement …
> feat(pass-style): feature flag: only well-formed strings are passable

- .github/workflows/ci.yml
- .github/workflows/depcheck.yml
closes: #1046
This removes the last two vestiges of testing on Node.js 16. Depcheck was on 16 by omission. The remaining CI matrix tests were for preventing regressions in `async_hooks` handling, which are leaving firmly behind us. We may at this point remove the promise-kit accommodations for these earlier versions, but that is not in scope for this change.
none
none
We may need to document somewhere that we no longer test Node.js. We have elected not to use the `engines` field in `package.json` since that would be brittle.
fewer
none
none to my knowledge
> chore: Drop Node.js 16 from CI entirely

- packages/daemon/src/daemon.js
- packages/daemon/src/host.js
- packages/daemon/src/types.d.ts
Fixes: #2121 
Synchronizes `makeHost()` and its dependent functions. Also refactors the same and `makeGuest()` to extract their commonalities and restore the more succinct form they possessed before the synchronization effort began. As part of the refactor, #2121 was fixed.
_Note to reviewers:_ I recommend going commit-by-commit.
> refactor!(daemon): Synchronize `makeHost()`

- packages/daemon/src/daemon.js
- packages/daemon/src/types.d.ts
Replaces the daemon's `incarnateLeastAuthority()` with the synchronous `incarnateNumberedLeastAuthority()`, thereby synchronizing it.
> refactor(daemon): Synchronize incarnateLeastAuthority

- packages/daemon/src/daemon-node-powers.js
- packages/daemon/src/daemon.js
- packages/daemon/src/host.js
- packages/daemon/src/types.d.ts
- packages/daemon/test/test-endo.js
Merges the daemon's `storeReaderRef()` into `incarnateReadableBlob()` and synchronizes the implementation. Also converts `makeReadableBlob()` into `makeControllerForReadableBlob()` to align it with the family of functions that already exist for most other formulas.
Contrary to its predecessor, `incarnateReadableBlob()` returns the value for stored value, namely a `FarEndoReadable`. A unit test is added for the case of immediately using a stored value without naming it.
> refactor(daemon): Synchronize incarnateReadableBlob()

- packages/daemon/src/daemon.js
- packages/daemon/src/host.js
- packages/daemon/src/types.d.ts
- packages/daemon/test/test-endo.js
> coordinate, verb, "to combine in harmonious relation or action."
Synchronizes the host's `provideWorker()`. In addition, coordinates the implementations of the host's `provideX` methods such that they all:
1. Attempt to get the existing formula id for the provided name, if any.
2. If there is no existing formula id, incarnate and return a new value.
All type checks during step 1 have been removed. In other words, if you attempt to provide something under an existing name that resolves to a different value type, you're on your own. We may revisit this decision in the future.
> refactor(daemon): Coordinate host `provideX` implementations

- packages/daemon/src/daemon.js
Closes: #2086
Synchronizes the daemon's `incarnateEndoBootstrap()`, thereby concluding the synchronization effort. It should now be impossible to concurrently mutating the formula graph through the public API.
> refactor(daemon): Synchronize incarnateEndoBootstrap

- packages/daemon/src/daemon-node-powers.js
- packages/daemon/src/daemon.js
- packages/daemon/src/directory.js
- packages/daemon/src/guest.js
- packages/daemon/src/host.js
- packages/daemon/src/mail.js
- packages/daemon/src/networks/loopback.js
- packages/daemon/src/types.d.ts
This change blesses `formulate` and `provide` with short names to convey their significance and reduce noise.
> refactor(daemon): Contract formulate and provide

- packages/daemon/src/context.js
- packages/daemon/src/daemon.js
- packages/daemon/src/directory.js
- packages/daemon/src/formula-identifier.js
- packages/daemon/src/guest.js
- packages/daemon/src/host.js
- packages/daemon/src/mail.js
- packages/daemon/src/pet-sitter.js
- packages/daemon/src/pet-store.js
- packages/daemon/src/types.d.ts
- packages/daemon/src/weak-multimap.js
- packages/daemon/test/test-endo.js
We have decided that there is one meaning of “identifier”, that it is “formula identifier”, that it is what “identify” returns, and that we can consequently consistently abbreviate it as “Id” or “id”.
While we’re here, abbreviate `provideControllerForFormulaIdentifier` to `provideController`.
> refactor(daemon): Id means formula identifier

- packages/daemon/src/daemon.js
- packages/daemon/src/directory.js
- packages/daemon/src/host.js
- packages/daemon/src/types.d.ts
Closes: #2146 
Replaces all references to "incarnate"/"incarnation" with "formulate"/"formulation". Incarnations will live on in the phylacteries of our hearts.
> refactor(daemon): Rename "incarnate" to "formulate"

- packages/daemon/src/host.js
- packages/daemon/test/test-endo.js
Fixes the provision of new (i.e. `NEW`) unnamed workers after #2139 broke it. Adds a regression test for this case.
> fix(daemon): Fix provision of new, unnamed workers

- packages/daemon/src/web-server-node-powers.js
Completes our error handling logic for the daemon's web server following #2148.
> fix(daemon): Handle server response error

- packages/bundle-source/src/bundle-source.js
- packages/bundle-source/src/nested-evaluate-and-get-exports.js
- packages/bundle-source/src/zip-base64.js
- packages/ses-ava/package.json
Two changes are necessary to close the gap with Agoric SDK.
1. We need to use `peerDependencies` between `@endo/ses-ava` and `ava`, in order to allow Agoric SDK to run behind on Ava 5 while Endo is on Ava 6. This is consistent with the usage pattern of `wrapTest`, requiring the dependent package to combine their `ava` with `@endo/ses-ava`, with some liberty to use either version.
1. My proposed changes for the `bundleSource` type signature are not currently reconciled and will have to endure another attempt.
> fix: Restore Agoric SDK compatibility for sync

- packages/daemon/src/daemon.js
- packages/daemon/src/directory.js
- packages/daemon/src/formula-identifier.js
- packages/daemon/src/formula-type.js
- packages/daemon/src/guest.js
- packages/daemon/src/host.js
- packages/daemon/src/locator.js
- packages/daemon/src/pet-store.js
- packages/daemon/src/types.d.ts
- packages/daemon/test/test-endo.js
- packages/daemon/test/test-formula-type.js
- packages/daemon/test/test-locator.js
Adds locator strings and a `locate()` method to the daemon's directory abstraction, and thereby hosts and guests. A locator string is a URL of the following form:
```text
endo://{nodeIdentifier}/?id={formulaNumber}&type={formulaType}
```
Formula identifiers are of the form `{formulaNumber}:{nodeIdentifier}`. Therefore, we can say that a locator is the URL form of the formula identifier, annotated with the `formulaType`. If a value is remote, i.e. belonging to a different peer, we set the `type` query param to `remote` to indicate this. `remote` is not a valid formula type in the general case—i.e. there are no formula objects with that type—but perhaps it should be.
Note that the `id` query param is just the `formulaNumber`, not the formula identifier. We may address this internal …
> feat(daemon): Add `locate()` facility

- packages/daemon/index.js
- packages/daemon/src/formula-type.js
- packages/daemon/test/test-endo.js
Fixes #2125
Refactors `test-endo.js` by introducing utilities to absorb the necessary boilerplate to get from an empty state to a reference to a live endo host. Also addresses #2125 by ensuring that test teardown will always run, even in the case of test failures. There should no longer be any dangling node processes after running `yarn test`, and it may even be possible to forego the use of `test:clean` and its `rm -rf /tmp` prelude in the general case.
> test(daemon): Refactor daemon test suite

- packages/daemon/src/daemon.js
- packages/daemon/src/formula-identifier.js
- packages/daemon/src/formula-type.js
- packages/daemon/src/pet-store.js
- packages/daemon/src/types.d.ts
Closes #2166 
Replace the known peers store adapter with a dedicated `known-peers-store` formula type, instantiated the same way as other "special" formulas such as `least-authority`. The adapter used a `pet-store` formula under the hood. Giving it a different formula entirely is probably less likely to confuse us in the future.
> refactor(daemon): Add known-peers-store formula

- packages/common/typedoc.json
refs: https://github.com/Agoric/documentation/issues/1031
https://endojs.github.io/endo/modules/_endo_common.html says "Each utility is in its own top-level source file" but there are no links to them.
n/a
> docs(common): include utility modules in api-docs

- typedoc.json
refs: https://github.com/Agoric/documentation/issues/1031
In https://github.com/Agoric/documentation/issues/1031 , we aim to define "the developer API product" and to supply corresponding reference docs.
This is a proposal to exclude whole packages from consideration, leaving them as implementation details or some such.
@sufyaankhan 
n/a
This could lower some compatibility burdens.
> docs: demote some packages from developer API product

- packages/pass-style/src/make-far.js
refs:
- https://github.com/Agoric/documentation/issues/1031
The 1st bit of SDK used in the 1st sample app in our docs is `Far`.
https://github.com/Agoric/dapp-offer-up/blob/cbf3836dff05e95220a201f930430a10ce960ce3/contract/src/offer-up.contract.js#L22
likewise the "hello world" contract in [smart contract basics](https://docs.agoric.com/guides/zoe/contract-basics.html).
Far's JSDoc was in terms of Remotable. I don't think folks using `Far` need to know about `Remotable` so much.
There's momentum to skip `Far` and teach exo's from the start (https://github.com/Agoric/documentation/issues/1033) but we're not there yet.
n/a
> docs(pass-style): don't rely on Remotable in Far docs

- packages/pass-style/index.js
- packages/pass-style/src/passStyleOf.js
- packages/pass-style/test/test-errors.js
closes: #2173 
refs: #XXXX
As of the last endo release, @endo/passStyle exports two broken tester functions: `isPassableError` and `assertPassableError`, neither of which correctly do what their names promise. In particular, they will judge some non-frozen errors to be passable even though `passStyleOf(e)` will correctly throw, `isPassable(e)` will correctly say `false`, and `matches(e, M.error())` will correctly throw. (`matches` throws if the specimen is not passable).
Their one use was by `toPassableError` which was therefore incorrect, which is how I noticed the problem. This PR fixes `toPassable`.
Fortunately, these two functions do not appear to be used ***anywhere*** else. They are also unneeded, as the other correct tests suffice. Therefore I would like to withdraw them rather …
> fix(pass-style): toPassableError fixed. (is/assert)PassableError removed.

- packages/marshal/src/marshal.js
- packages/pass-style/src/passStyleOf.js
- packages/pass-style/test/test-errors.js
- packages/ses/src/error/assert.js
- packages/ses/src/error/types.js
- packages/ses/types.d.ts
closes: #2198 
refs: #2156 
The symptoms of #2156 reveal that some hosts add "extraneous" or harmful own properties to errors
- Chrome, Brave (v8) adds an own `stack` accessor property, whose getter and setter functions can be used for mischief.
- Firefox (SpiderMonkey) adds own `fileName` and `lineNumber` properties that are useful for diagnostics but should be redacted from public view.
- Safari (JSC) adds an own `line` property, that likewise is useful for diagnostics, but should be redacted from public view.
Note that the contents of the stack should also be redacted from public view, but SES already deals with that separately.
Prior to this PR, some code assumed that the error that `makeError` returns would be passable once frozen. But these extra own properties, or own accessor …
> fix(ses): makeError defaults to making passable errors

- packages/daemon/src/multimap.js
- packages/daemon/src/pet-store.js
- packages/daemon/src/types.d.ts
- packages/daemon/test/test-multimap.js
Addresses some naming issues in the multimap's interface and adds missing test cases.
> refactor(daemon): Fix naming issues in multimap interface

- packages/cli/demo/README.md
- packages/cli/src/commands/mkguest.js
- packages/cli/src/commands/mkhost.js
- packages/cli/src/endo.js
- packages/daemon/src/daemon.js
- packages/daemon/src/guest.js
- packages/daemon/src/host.js
- packages/daemon/src/pet-name.js
- packages/daemon/src/pet-sitter.js
- packages/daemon/src/types.d.ts
- packages/daemon/test/service.js
- packages/daemon/test/test-endo.js
Toward sending messages between mailboxes in separate nodes, this change gives every agent (both hosts and guests) a powerless handle that can be used to mention the agent without leaking agency.
This is somewhat tricky because this is the first cycle in the formula graph. The agent _contains_ a handle and the handle identifier and formula are just ways of referring to the facet held by the agent. So, writing an agent formula generates a handle formula as a side-effect and populates the agent id for handle table.
This also means that `mkguest` and `mkhost` need to designate the handle (so that messages from the other agent are visible) and might optionally also designate a pet name for the agent.
> feat(daemon,cli): One handle for every agent

- packages/cli/demo/cat.js
- packages/cli/src/commands/inbox.js
- packages/cli/src/commands/show.js
- packages/daemon/src/daemon.js
- packages/daemon/src/guest.js
- packages/daemon/src/host.js
- packages/daemon/src/mail.js
- packages/daemon/src/pet-name.js
- packages/daemon/src/types.d.ts
- packages/daemon/test/test-endo.js
Toward delivering mail over the network, this change introduces a `deliver` method on guest and host agents that accepts arbitrary messages into the agent’s inbox. Any other agent can send mail to any other local agent for whom they have a handle and cannot spoof their sender handle.
This is a net simplification, since it reduces our dependence on the internal facet of agents and requires less machinery because it treats messages as capabilities on the wire, freely exposing and carrying identifiers. We no longer have separate internal and external representations of messages and pet name “dubbing” is deferred to the UI. This in turn enables us to defer to the UI the question of whether to query the name for each identifier once or watch for changes.
Stacked on #2184
> refactor(daemon): Move mail delivery to agent public facets

- packages/daemon/src/daemon.js
- packages/daemon/src/directory.js
- packages/daemon/src/guest.js
- packages/daemon/src/host.js
- packages/daemon/src/types.d.ts
- packages/daemon/test/test-endo.js
This is a simplifying refactor that reduces {internal, external} controller facets to just the (external) value. In preparation, removes the last vestiges of internal facets on worker and agent. Then mops up by collapsing the controller logic and structures.
> refactor(daemon): Factor out internal facets

- packages/daemon/src/daemon.js
- packages/daemon/src/mail.js
- packages/daemon/src/types.d.ts
Converts the maker if/else chain into a lookup table for faster dispatch and better type hints. The new maker table type identified the extraneous WebBundleFormula left over from an earlier refactor.
> refactor(daemon): Maker table

- packages/cli/src/endo.js
- packages/daemon/index.js
- packages/daemon/test/test-endo.js
Ensures that the daemon is not restarted after being purged, even if it was previously running. Any CLI command will simply restart the daemon anyway.
> feat(daemon): Always stop the daemon on purge

- packages/daemon/src/daemon.js
- packages/daemon/src/directory.js
- packages/daemon/src/guest.js
- packages/daemon/src/host.js
- packages/daemon/src/types.d.ts
This change adds a vestigial second argument to `provide` that just hints to TypeScript the expected return type, resulting is much less verbose type narrowing. I’ve also advanced `provide` higher in the flow so it can eat all the forward-reference lint comments.
> refactor(daemon): Parameterize provide type assertion

- packages/bundle-source/demo/comments/types.js
- packages/captp/src/captp.js
- packages/captp/src/loopback.js
- packages/captp/src/trap.js
- packages/captp/src/types.js
- packages/compartment-mapper/src/import-archive.js
- packages/compartment-mapper/src/link.js
- packages/compartment-mapper/src/types.js
- packages/far/src/index.js
- packages/marshal/src/deeplyFulfilled.js
- packages/marshal/src/encodeToSmallcaps.js
- packages/marshal/src/marshal-justin.js
- packages/marshal/src/marshal.js
- packages/pass-style/src/error.js
- packages/pass-style/src/internal-types.js
- packages/pass-style/src/make-far.js
- packages/pass-style/src/typeGuards.js
- packages/patterns/src/keys/checkKey.js
- packages/patterns/src/keys/compareKeys.js
- packages/patterns/src/keys/copyBag.js
- packages/patterns/src/patterns/getGuardPayloads.js
- packages/patterns/src/patterns/patternMatchers.js
- packages/patterns/src/patterns/types.js
- packages/patterns/src/types.js
Follow up https://github.com/endojs/endo/pull/2192
I think this wraps up the transition, save for the TODO.
n/a, typedefs
n/a, typedefs
not necessary
CI
Some reduction in exports, but those were deep imports so ok to break
none
> finish transitioning to @import

- .github/workflows/ci.yml
refs: #2230
This change adds `latest` to the CI [node setup action](https://github.com/actions/setup-node) so we can see upcoming breaking changes to our platform. The corresponding test results will not be required for merge.
Testing canary did not pan out. You can get `22-v8-canary` out of `actions/setup-node`, and you can add `yarn install --ignore-engines`, but `yarn` will still die with error if any dependency specifies `engines` since the canary versions do not match other version ranges, even broad ones like `>= 16`. This may be worth revisiting with newer versions of `yarn` or whatever succeeds it.
This increases our visibility into breaking changes on the Node.js platform.
This may prolong CI runs by a multiplicative factor if CI workers are contended.
None.
Increases visibility …
> test(ci): Node.js 22 in CI

- .github/workflows/ci.yml
- packages/pass-style/test/test-passStyleOf.js
- packages/ses/error-codes/SES_UNEXPECTED_ERROR_OWN_STACK_ACCESSOR.md
- packages/ses/src/commons.js
- packages/ses/src/make-hardener.js
closes: #2198 
refs: #2230 #2200  https://chromium-review.googlesource.com/c/v8/v8/+/4459251 #2229 #2231 
Alternative to #2229 that just hacks `harden` to directly repair a problematic error own stack accessor property, replacing it with a data property.
Both before and after this PR, `passStyleOf` will reject errors with the v8 problematic error own stack accessor property, preventing the unsafety at stake here. However, this would mean that much existing code that used to be correct will break when run on a v8 with this problem.
Avoids any extra overhead on platforms without this problem, including all platforms other than v8.
probably none. This PR essentially avoids the need to document the v8 problem that it masks.
Only needed to repair one test to use `harden` rather than `freeze`, …
> fix(ses): `harden` hacks v8 `stack` own accessor problem

- packages/daemon/src/daemon.js
- packages/daemon/src/host.js
- packages/daemon/src/locator.js
- packages/daemon/src/networks/loopback.js
- packages/daemon/src/networks/tcp-netstring.js
- packages/daemon/src/remote-control.js
- packages/daemon/src/types.d.ts
- packages/daemon/test/test-endo.js
- packages/daemon/test/test-remote-control.js
This feature ensures that any pair of pet dæmons will only be connected by a single CapTP connection to ensure that identical remoteable objects round-trip between them. In this framework it is necessary to _partially_ solve the problem of “crossed hellos”, such that two nodes that simultaneous start up and suddenly wish to be connected to each other will race to create the first connection. One of these daemons must drop an established connection and invalidate incarnations that depend upon it. We settle this question by biasing the behavior based on the relative values of their node identifiers.
This does not fully solve the experience of crossed hellos. If hellos get crossed, the loser of the race will get cancelled and may not gracefully recover. Evidence suggests this can manifest as …
> feat(daemon): Ensure a single connection between peers

- packages/cli/src/commands/accept.js
- packages/cli/src/commands/invite.js
- packages/cli/src/endo.js
- packages/daemon/src/daemon.js
- packages/daemon/src/formula-type.js
- packages/daemon/src/host.js
- packages/daemon/src/types.d.ts
- packages/daemon/test/test-endo.js
This change introduces a user workflow for connecting daemons.
```
alice> endo invite bob > invitation.link
*alice sends bob invitation.link*
bob> endo accept alice < invitation.link
```
The two parties can now exchange mail.
```
alice> endo send bob 'Hi, here is @power'
bob> endo inbox
0. alice sent “Hi, here is @power”
bob> endo adopt 0 power 
```
Here's a transcript for testing this in `packages/cli/demo`:
```
> endo make counter.js --name counter
Object [Alleged: Counter] {}
> endo mkhost other other-agent
Object [Alleged: EndoHost] {}
> endo invite bob > invitation.link
> endo accept alice --as other-agent < invitation.link
> endo send bob 'Hi, here is @counter'
> endo show counter
Object [Alleged: Counter] {}
> endo show counter --as other-agent
CapTP cli exception: …
```
> feat(daemon): Invitations

- packages/cli/demo/cat.js
- packages/daemon/src/daemon.js
- packages/daemon/src/directory.js
- packages/daemon/src/guest.js
- packages/daemon/src/host.js
- packages/daemon/src/interfaces.js
- packages/daemon/src/interfaces/web.js
- packages/daemon/src/mail.js
- packages/daemon/src/reader-ref.js
- packages/daemon/src/types.d.ts
- packages/daemon/src/web-page.js
- packages/daemon/src/worker.js
- packages/daemon/test/context-consumer.js
These individually reviewable commits consolidate some recurring patterns, move interface definitions into a separate module, adds more explanatory comments, and fixes some lingering errors.
> refactor(daemon): Consolidate interface definitions and cleanup

- .github/workflows/ci.yml
We’ve seen a lot of EPIPE on write failures that are more common on Windows than Linux/Mac, though they do occur. For that reason along, it would be good to restore Windows CI when we track that issue down, but for now, the flakes are too hard to bear and also block us from upgrading yarn #2222
> test: Drop Windows CI

- packages/cli/src/commands/bundle.js
- packages/cli/src/commands/install.js
- packages/cli/src/commands/make.js
- packages/cli/src/commands/show.js
- packages/cli/src/commands/store.js
- packages/cli/src/endo.js
- packages/daemon/src/host.js
- packages/daemon/src/types.d.ts
- packages/daemon/test/test-endo.js
In, https://github.com/endojs/endo/pull/2226 we gain the ability to marshal copy data and remotables that are backed by formulas.
This change surfaces these features to the CLI by exposing a variety of flags.
```console
> endo store --json '{"hello": "world"}' --name greeting
> endo show greeting
{ hello: 'world' }
```
```console
> endo store --text 'Hello, World!' --name greeting
> endo show greeting
Hello, World!
```
```console
> endo store --bigint 42 --name meaningful-bigint
> endo show meaningful-bigint
42n
```
```console
> endo store --json-stdin --name greeting < <(jq -n '{hello:"world"}')
> endo show greeting
{ hello: 'world' }
```
```console
> endo store --text-stdin --name greeting < <(echo hi)
> endo show greeting
hi
```
```console
> endo store --stdin --name greeting < <(echo …
```
> feat(cli): Expand options for storing values

- packages/patterns/src/keys/checkKey.js
- packages/patterns/src/keys/compareKeys.js
- packages/patterns/src/keys/copyBag.js
- packages/patterns/src/keys/copySet.js
- packages/patterns/src/keys/keycollection-operators.js
- packages/patterns/src/keys/merge-bag-operators.js
- packages/patterns/src/keys/merge-set-operators.js
- packages/patterns/src/patterns/getGuardPayloads.js
- packages/patterns/src/patterns/patternMatchers.js
- packages/patterns/src/patterns/types.js
- packages/patterns/src/types.js
- packages/patterns/test/test-pattern-limits.js
- packages/ses/src/error/assert.js
closes: #XXXX
refs: #2248 #1584 https://github.com/Agoric/agoric-sdk/pull/6432
Pure refactor. Changes only static info. Mostly more consistent and more readable use of `@import`.
One case made less readable: Remove newlines within a large `@import` directive. The reason is that 
`yarn lerna run build:types` chokes on those newlines. TODO minimal repro + report issue.
Extracted from other PRs #1584 #2248 which are now staged on this one. But this should be a reviewable and mergeable improvement regardless of whether we move forward on the others.
none
none
none
none
none
none
- ~[ ] Includes `*BREAKING*:` in the commit message with migration instructions for any breaking change.~
- ~[ ] Updates `NEWS.md` for user-facing changes.~
> refactor(patterns): improve pattern types. Flatten @imports

- packages/ses/error-codes/SES_UNEXPECTED_ERROR_OWN_STACK_ACCESSOR.md
closes: #XXXX
refs: #XXXX
Just updates the stack error-codes doc with relevant links
> docs(ses): add links to stack error-codes doc

- packages/exo/src/exo-tools.js
- packages/exo/test/test-heap-classes.js
closes: #XXXX
refs: #XXXX
Should be a pure refactor without any[1] observable differences. Shorten the exo-call fastpath for the normal thisful case 
- primarily to make stepping into an exo method more pleasant with fewer clicks and visual context switches
- probably also has a performance advantage for the normal thisful case.
By "thisful", I mean the exo objects defined with the normal exo-making, exo-class-making, and exo-class-kit-making APIs, whether directly or via zones. The non-thisful case is only the deprecated virtual and durable kinds, which are not yet gone and so must still be supported. But have only the non-thisful case pay for the arg shifting, rather than making all calls pay for that.
The previous debug experience involved two layers of wrapping function to get from …
> refactor(exo): shorten exo-call fastpath

- packages/cli/demo/cat.js
This adds a chat and message log auto-scroll support to the demo Chat Familier web UI.
Click the cat.
Click chat.
`AGENT` isn’t a handle. We can’t filter on type yet.
But `SELF` is a handle.
Press Send.
> feat(cli): Add chat to demo web UI

- packages/ses/error-codes/SES_UNEXPECTED_ERROR_OWN_STACK_ACCESSOR.md
closes: #XXXX
refs: https://github.com/Agoric/endojs-vespera/pull/1 https://chromium-review.googlesource.com/c/v8/v8/+/4459251/10..15/src/execution/messages.cc#b1131
Now that https://github.com/Agoric/endojs-vespera is public, just adds links into it, and to a related v8 discussion that it links to.
> docs(ses): more links for stack own accessor problem

- packages/pass-style/src/remotable.js
closes: #XXXX
refs: #1933 
The declaration site had both a correct @type declaration and a redundant vestigial partial @returns declaration. Because the latter also was not properly formed, it caused the warning
```
.../endojs/endo/packages/pass-style/src/remotable.js
175:1  warning  Missing JSDoc @returns type  jsdoc/require-returns-type
✖ 1 problem (0 errors, 1 warning)
```
This PR removes it, and does a bit of trivial polishing of the remainder.
none
none
more accurate type declarations should eventually help documentation
none
none
> fix(pass-style): remove redundant vestigial @returns declaration

- packages/ses/NEWS.md
- packages/ses/package.json
- packages/ses/package.json.md
- packages/ses/scripts/bundle.js
Due to changes in TS v5.5, CJS consumers cannot import types from a `type: module` package unless the declaration file has the `.d.cts` extension. This may or may not work the other way.
See [the v5.5. beta announcement](https://devblogs.microsoft.com/typescript/announcing-typescript-5-5-beta/#respecting-file-extensions-and-packagejson-in-other-module-modes) for further explanation.
> fix(ses): fix broken types for CJS consumers

- .github/workflows/typedoc-gh-pages.yml
- packages/ses/package.json
The typedoc CI job failed because of a package manager mismatch that can be addressed by enabling corepack.
https://github.com/endojs/endo/actions/runs/8975075410/job/24648857762
> fix: Corepack with TypeDoc generation job

- packages/exo/NEWS.md
- packages/exo/src/exo-tools.js
- packages/exo/test/test-exo-only-throwables.js
- packages/pass-style/NEWS.md
- packages/pass-style/index.js
- packages/pass-style/src/passStyleOf.js
- packages/pass-style/test/test-errors.js
closes: #XXXX
refs: https://github.com/endojs/endo/pull/2223 
Modest step towards #2223 , 
- bringing all the intended safety: the exo boundary only throws throwables, and that `callWhen` async exo methods only reject with throwable reasons.
- but with less flexibility: the definition of passable errors and throwables is narrower than it need be.
This is one of three necessary steps towards having the exo boundaries become the new intravat defensive security boundary, rather than treating every object boundary as a potential defensive security boundary. The rationale for this step is that the throw-control-path is too hard for reviewers to pay full attention to, so we wish to prevent caps from leaking over the exo boundary via the throw path. (E prevented caps from escaping via throws in …
> feat(pass-style,exo): exo boundary only throws throwables

- packages/exo/test/test-heap-classes.js
- packages/pass-style/src/remotable.js
closes: #XXXX
refs: https://github.com/Agoric/agoric-sdk/pull/9097
As the changed test case demonstrates, before this PR, testing the `passStyleOf` a normal unmarked function was correctly rejected, but with a terrible error message, such as: 
- `"[Symbol(passStyle)]" property expected: "[Function ...]"`
This change aligns with the error message already used for an unmarked objects-as-closure object. For an unmarked function, the error would be
- `Remotables must be explicitly declared: "[Function ...]"`
none
none
none
There might be tests with golden text based on the old error message. These tests would need to be revised to the new text. During the transition, golden text error tests should use a regexp to be compat with both the before and after of this PR, with a link to the PR …
> refactor(pass-style): better non-remotable function error

- .github/PULL_REQUEST_TEMPLATE.md
The pull request template currently leaves invisible comments which have occasionally survived into commit messages. This changes those comments to block quotes to make their existence more evident to reviewers and to encourage change proposers to delete them as they fill the form.
> fix: Make pull request template guidance more evident if it persists

- packages/patterns/src/keys/checkKey.js
- packages/patterns/src/types.js
- packages/patterns/test/types.test-d.ts
`ScalarKey` is a patterns concept but without a typedef. This defines it.
Necessary for https://github.com/Agoric/agoric-sdk/pull/8774#pullrequestreview-2041695483
no
no
no
new tests
no
no
> feat(types): ScalarKey

- packages/cli/demo/cat.js
- packages/cli/package.json
- yarn.lock
This change adds an eval form to the demo weblet.
Click the cat then Eval or type the accelerator key “.”. Fill in the source and add an endowment.
Press thee Evaluate button and observe there’s a new `cat-id` in the pet store.
> feat(cli): Add eval form to demo weblet

- scripts/get-versions.sh
- scripts/set-versions.sh
Recent upgrades to `yarn` and (older) `jq` require updates to the version management scripts we use to sync Endo with Agoric SDK.
> fix: Update version scripts

- packages/cli/src/commands/move.js
- packages/cli/src/endo.js
- packages/daemon/src/directory.js
- packages/daemon/src/pet-store.js
- packages/daemon/test/failed-hub.js
- packages/daemon/test/move-hub.js
- packages/daemon/test/test-endo.js
Adds a command `move` corresponding to the daemon directory's `move()`, with pet name path support. Replaces the existing `rename` command, which had been broken for some time.
Also ensures that the directory's `move()` method immediately deletes the "from" name mapping. Adds a test for the same. This mapping was already removed from disk and would not persist after restarts.
> feat(cli,daemon): Add `move` CLI command

- packages/daemon/test/endo.test.js
Prefer `storeValue()` over more complicated `evaluate()` incantations in tests when we just need some named value to exist.
> refactor(daemon): Prefer `storeValue()` where possible in tests

- scripts/graph.sh
Closes: #XXXX
Refs: https://github.com/Agoric/agoric-sdk/pull/9359
Use the "tred" executable that seems to already be bundled with graphviz to
```
```
At the time of writing, the current graph of endo dependencies is
and the transitive reduction of those is
Notice how the columns *mostly* align. Unfortunately, the columns don't fully align, and the vertical order of elements within each column is not the same. For viewing them side by side for better understanding, it would be better if both of these annoyances were fixed. But I have no idea how to do that, so this PR does not try.
none
none
potentially helps someone who wants to understand how our system is internally layered, which is the point. Otherwise, none
none
none
none
> feat(graph): also generate the transitive reduction

- packages/cli/src/commands/make.js
- packages/cli/src/endo.js
- packages/daemon/src/directory.js
- packages/daemon/src/host.js
- packages/daemon/src/types.d.ts
Enables caplets to be made and values to be stored at deeper pet name paths.
```
endo make x.js -n dir.x
endo store --json 42 -n dir.forty-two
endo store --text-stdin --name dir.greeting < <(echo hi)
```
> feat(daemon,cli): Make and store at path

- packages/cli/src/commands/mkdir.js
- packages/cli/src/commands/store.js
- packages/cli/src/endo.js
- packages/daemon/src/directory.js
- packages/daemon/src/types.d.ts
Adds `mkdir` command to the CLI. Updates the daemon's directory abstraction to accept pet name paths at `makeDirectory()`.
```
> endo mkdir dir
> endo make counter.js -n dir.counter
> endo eval 'E(counter).incr()' counter:dir.counter
1
```
> feat(cli,daemon): Add `mkdir` command

- packages/pass-style/src/copyArray.js
- packages/pass-style/src/copyRecord.js
- packages/pass-style/src/error.js
- packages/pass-style/src/passStyle-helpers.js
- packages/pass-style/src/remotable.js
- packages/pass-style/src/safe-promise.js
- packages/pass-style/src/tagged.js
* Make a rejector only when needed
* Use the value from an already-fetched property descriptor rather than fetching the property again.
* Minimize the number of all-property loops.
None.
The total effect is an improvement of 10% to 20% on both V8 and XS for `passStyleOf(harden(largeArrayOrPlainObject))` as observed by
```sh
scripts/esbench.mjs -b3 -h'V8,*XS' \
-M @endo/init \
-i 'import { passStyleOf } from "@endo/pass-style"; globalThis.passStyleOf = passStyleOf;' \
--arg len:0,1,10,100 \
--setup 'const arr = Array(+len).fill(""), obj = Object.fromEntries(arr.map((val, i) => [`key${i}`, val]));' \
'passStyleOf(harden(arr.slice()))' \
'passStyleOf(harden({ ...obj }))' \
| grep -v '^Removing '
```
<details>
```
passStyleOf(harden(arr.slice())) ("0",0) 102.95928500496524 ops/ms after 81 …
```
> perf(pass-style): Eliminate redundant work to validate passStyle shapes

- packages/patterns/src/patterns/patternMatchers.js
Until we have a rigorous treatment on the usage of patterns, this adds a bandaid to the code itself so anyone looking for how to make a pattern for a struct-like CopyRecord, tuple-like CopyArray, or fixed-length heterogeneous CopyMap will find their way.
> docs(patterns): Comments for fixed-length heterogeneous collection patterns

- packages/nat/src/index.js
Adds a missing "is" to an error message from `Nat`.
None.
n/a
n/a
None.
n/a
We expect error messages to change over time and require code to be tolerant of this.
> chore(nat): Fix typo in Nat error message

- packages/cli/src/commands/list.js
- packages/cli/src/endo.js
The `endo list` command now accepts a `--verbose` option that will cause it to print out a prettified version of the value that would be shown by `endo show` for each entry.
I kept finding myself wanting this during my explorations, so I just went ahead and implemented it.
> cli: Add a `--verbose` option to the `endo list` command

- packages/bundle-source/cache.js
- packages/bundle-source/package.json
- packages/bundle-source/src/main.js
- packages/bundle-source/src/types.js
- packages/bundle-source/src/zip-base64.js
- packages/bundle-source/test/no-transforms.test.js
- yarn.lock
Closes: #2295 
Refs: #400, #2252
This change adds a mode to the `bundle-source` command with the initial flag `--no-transforms` that generates “endo zip base64” style bundles without applying the module-to-program transform and SES shim censorship evasion transforms, such that the original files on disk appear in the zip file. This is a preparatory step, necessary for building test artifacts, in advance of full support for this bundle style.
`bundle-source` is part of the Endo and Agoric toolkit and it, or its surrogate, participate in the toolchain for generating content that can be confined by Hardened JavaScript, but is not trusted by Hardened JavaScript at runtime. It does however _currently_ run with all the authority of the developer in their development environment and its …
> feat(bundle-source): Zip original sources with --no-transforms

- packages/base64/src/encode.js
The bit about rfc4648 is on a function that isn't exported from the package, so it doesn't show up in the [generated reference docs](https://endojs.github.io/endo/functions/_endo_base64.encodeBase64.html).
yes.
> docs: export spec for encodeBase64

- packages/cli/src/commands/run.js
- packages/compartment-mapper/test/main.test.js
- packages/daemon/src/web-page.js
- packages/daemon/src/worker.js
- packages/eventual-send/src/track-turns.js
- packages/ses/demos/challenge/main.js
- packages/ses/demos/console/main.js
Closes: #XXXX
Refs: https://github.com/Agoric/agoric-sdk/issues/9515 https://github.com/Agoric/agoric-sdk/pull/9514
Addresses https://github.com/Agoric/agoric-sdk/issues/9515 as applied to endo, by doing for endo what https://github.com/Agoric/agoric-sdk/pull/9514 does for agoric-sdk
To address https://github.com/Agoric/agoric-sdk/issues/5672 for endo , we should change all applicable uses of `assert` to obtain `assert` by importing it from the `@endo/errors` package. However, attempts to do so ran into the symptoms reported at https://github.com/Agoric/agoric-sdk/issues/9515 for the reasons reported there -- accidentally using the imported `assert` as the endowment for the global `assert` of new Compartments.
This PR prepares the ground for these fixes to …
> fix: endow with original unstructured `assert`

- packages/promise-kit/README.md
Update Promise Kit README
fixes #2318
> chore: Update Promise Kit README

- packages/cli/src/commands/adopt.js
- packages/cli/src/commands/eval.js
- packages/cli/src/commands/install.js
- packages/cli/src/commands/mkdir.js
- packages/cli/src/commands/remove.js
- packages/cli/src/commands/request.js
- packages/cli/src/commands/spawn.js
- packages/cli/src/endo.js
- packages/daemon/src/daemon.js
- packages/daemon/src/directory.js
- packages/daemon/src/guest.js
- packages/daemon/src/host.js
- packages/daemon/src/mail.js
- packages/daemon/src/pet-name.js
- packages/daemon/src/types.d.ts
- packages/daemon/test/endo.test.js
Adds support for dot-delimited petname paths in the `mkdir`, `remove`, and `spawn` commands, plus everywhere there's a `--name` option (the `install`, `make`, `request`, `adopt`, `store`, `eval`, and `bundle` commands).
Ref: #2023
> Further endo daemon CLI support for dot-delimited paths

- .github/workflows/browser-test.yml
The Selenium Docker image with Chrome nightly builds is no longer sufficient for Playwright CI for lack of some system dependencies. This change mitigates the problem by walking back to the default container image until we can prepare a working Docker image for Chrome nightlies.
> ci: Mitigate Playwright failure in CI

- packages/marshal/src/deeplyFulfilled.js
- packages/marshal/test/deeplyFulfilled.test.js
Closes: #1257 
Refs: https://github.com/Agoric/agoric-sdk/pull/5993 https://github.com/Agoric/agoric-sdk/pull/6816 https://github.com/endojs/endo/pull/1455
Low urgency. This is a minor reduction of tech debt.
https://github.com/Agoric/agoric-sdk/pull/5993 introduced `deeplyFulfilledObject` to work around the deficiencies in the typing of `deeplyFulfilled` explained at #1257 . This PR fixes those deficiencies. This does not necessary make `deeplyFulfilledObject` unneeded, but it should enable many callers of `deeplyFulfilledObject` to call `deeplyFulfilled` instead without loss of type fidelity.
Note: the code in this first commit probably does not use TS typing well, resulting in many internal `@ts-expect-error` directives in the implementation. This is because I still don't really …
> types(marshal): fix #1257 typing of `deeplyFulfilled`

- README.md
Fixes broken references introduced in #2338.
Note that Github and our Github pages generate different section anchors from headings, so I’ve created one manually that collides with neither.
> fix(docs): Reference for Agoric and MetaMask collateral and PoLA section

- packages/ses/README.md
> docs(ses): Cross-reference hardenedjs.org

- packages/ses/src/compartment.js
- packages/ses/src/error/assert.js
- packages/ses/src/module-instance.js
- packages/ses/src/module-link.js
- packages/ses/src/module-load.js
- packages/ses/test/import.test.js
- packages/ses/types.d.ts
Refs: #400 #2251 
Pursuant to arriving at parity with XS, this change internally reörients the SES module loader around the concept of a “module descriptor”. This creates some clarity and removes some existing duplication of work for “alias” module descriptors, and prepares the material for a richer module descriptor schema to match those implemented by XS.
No changes.
No changes.
No changes.
No changes.
No changes.
No changes.
> refactor(ses): Retool for module descriptors

- packages/compartment-mapper/src/link.js
Refs: #400
XS does not support `compartment.module`. Rather than emulate it, I chose bring SES into closer alignment with XS module descriptors and use those instead. The Compartment Mapper is the only place we use this feature at the moment.
None.
None.
None.
The existing Compartment Mapper tests exercise this path rigorously.
The new version of Compartment Mapper will not work with an older version of SES. Lerna will make sure the constraint gets updated when we release.
None.
> refactor(compartment-mapper): Pivot to module descriptors

- packages/bundle-source/NEWS.md
- packages/bundle-source/cache.js
- packages/bundle-source/demo/meaning.js
- packages/bundle-source/demo/meaningful.js
- packages/bundle-source/src/bundle-source.js
- packages/bundle-source/src/endo.js
- packages/bundle-source/src/main.js
- packages/bundle-source/src/script.js
- packages/bundle-source/src/types.js
- packages/bundle-source/src/zip-base64.js
- packages/bundle-source/test/endo-script-format.tests.js
- packages/bundle-source/test/tool-command.test.js
- packages/compartment-mapper/src/bundle.js
- packages/compartment-mapper/src/node-modules.js
- packages/compartment-mapper/src/search.js
Refs: https://github.com/Agoric/agoric-sdk/issues/9686
Endo’s `bundle-source` currently generates bundles with the `endoZipBase64` format, which requires the `importBundle` runtime. We typically bootstrap `importBundle` using the `getExport` or `nestedEvaluate` bundle format, which only need `eval` or `compartment.evaluate` to run. These use Rollup internally.
Elsewhere, for distributing SES and toward bootstrapping XS and Hermes variants of SES, we have our own bundler. In this change, we expose this format as `endoScript`, an alternative to `getExport` and `nestedEvaluate` which do not depend on Rollup.
We introduce a `--format` flag to `bundle-source` so any of the old and the new bundle formats are addressable from the CLI.
For easy hacking, we introduce a no-cache mode to …
> feat(bundle-source): Add format flags, add new endoScript format

- packages/cli/src/commands/eval.js
- packages/cli/src/commands/make.js
- packages/cli/src/commands/request.js
- packages/cli/src/pet-name.js
It was discovered that the CLI's `eval` and `request` commands were broken for unspecified result names. This restores functionality to these commands by introducing a new utility function, `parseOptionalPetNamePath()`, which directly returns `undefined` values, and forwards `string` values to `parsePetNamePath()`. Assertions are added in both functions to ensure that the provided path is of the expected type.
> fix(cli): Handle unspecified result names for multiple commands

- packages/lockdown/NEWS.md
- packages/lockdown/commit-debug.js
*BREAKING*: Importing `@endo/lockdown/commit-debug.js` will now endanger integrity as well, in order to get better line numbers. `@endo/lockdown/commit-debug.js` should normally be used only for development/debugging/testing scenarios, where it is not potentially in contact with any genuinely malicious code. For those cases, there is no BREAKING change here. But we're flagging a potentially breaking change in case anyone is importing `@endo/lockdown/commit-debug.js` in scenarios where potentially malicious code is a concern. Such uses should be revised to avoid setting `errorTaming: 'unsafe-debug'`.
Closes: #XXXX
Refs: https://github.com/endojs/endo/pull/2355 https://github.com/Agoric/agoric-sdk/pull/9711
In #2355 , we introduced a new `errorTaming` setting, `'unsafe-debug'`, to sacrifice …
> fix(lockdown): change commit-debug.js to unsafe-debug

- .github/workflows/ci.yml
Node.js 22.5.0 regressed CI with error:
```
Usage Error: Couldn't find the node_modules state file - running an install might help (findPackageLocation)
```
Pinning to 22.4.1 unblocks CI.
We should revisit reverting this with the next Node.js release.
> ci: Pin Node 22.4.1

- packages/eslint-plugin/lib/rules/harden-exports.js
- packages/eslint-plugin/package.json
- packages/eslint-plugin/test/harden-exports.test.js
- yarn.lock
Refs: https://github.com/Agoric/agoric-sdk/pull/9726
A new lint rule, `harden-exports`, to support https://github.com/Agoric/agoric-sdk/pull/9726
Includes an autofixer
Could enhance security
n/a
We don't yet document provided rules: https://endojs.github.io/endo/modules/_endo_eslint_plugin.html
I think that's okay for now. If that is requested I'd file it as a separate issue, out of scope of this one.
I temporarily enabled this in the **recommended** config and ran `lint-fix` on the repo. All the changes looked correct. However `harden()` isn't always available so I don't think we should enable it in any of Endo's shared configs.
n/a
n/a
> harden-exports rule for eslint plugin

- packages/compartment-mapper/NEWS.md
- packages/compartment-mapper/src/bundle-cjs.js
- packages/compartment-mapper/src/bundle-json.js
- packages/compartment-mapper/src/bundle-mjs.js
- packages/compartment-mapper/src/bundle.js
- packages/compartment-mapper/src/types.js
- packages/compartment-mapper/test/bundle.test.js
- packages/compartment-mapper/test/fixtures-0/node_modules/bundle/json.json
- packages/compartment-mapper/test/fixtures-0/node_modules/bundle/main.js
- packages/ses/types.d.ts
Refs: #400, https://github.com/Agoric/agoric-sdk/issues/9686
Endo’s zip bundle format and Rollup both support importing JSON modules. This change adds JSON module support to Endo’s script bundle format. We need this to have Rollup parity for Agoric Core Eval scripts and also to unblock test262 for XS native compartment parity tests.
Obviates Rollup, increases legibility of script bundles.
None.
None. JSON module support is assumed. No one will notice unless it doesn’t work.
This change adds a JSON module to the existing bundle test fixture. This also verifies parity with the Zip bundle format.
This make Endo more compatible with Rollup, but Endo continues to not support `import / with { type: "json" }`, which would be necessary for parity with Node.js proper and newer bundlers.
None.
> feat(compartment-mapper): JSON module support for makeBundle

- packages/bundle-source/NEWS.md
- packages/bundle-source/cache.js
- packages/bundle-source/demo/node_modules/conditional-exports/a.js
- packages/bundle-source/demo/node_modules/conditional-exports/b.js
- packages/bundle-source/demo/node_modules/conditional-exports/package.json
- packages/bundle-source/demo/node_modules/conditional-reexports/entry.js
- packages/bundle-source/demo/node_modules/conditional-reexports/package.json
- packages/bundle-source/src/main.js
- packages/bundle-source/src/script.js
- packages/bundle-source/src/types.js
- packages/bundle-source/src/zip-base64.js
- packages/bundle-source/test/tags-command.test.js
Refs: #400
We’ve discovered that, to create an Endo script bundle that captures our `ModuleSource` constructor shim, it will need to entrain Babel. With the default build conditions, Babel entrains a `debug` package, which entrains `node:tty`. So, it is necessary to add the `"browser"` condition, which instead entrains a package with a JSON module (#2352). This change threads arbitrary conditions (build tags) through `bundle-source` to conveniently generate Endo script bundles with different tags like `browser` or `xs`.
None.
None.
The new flags are advertised in the command’s usage display.
None.
None.
> feat(bundle-source): Add `tag` command-line flag

- packages/cli/src/commands/copy.js
- packages/cli/src/endo.js
Closes: #2286
Closes #2287 
Adds the daemon's existing copy command to the cli.
Compare with [previous commit adding mkdir](https://github.com/endojs/endo/pull/2288/commits/63a58b179cd8469b7140c3bc138b33de0869e529).
These changes were tested manually with expected behavior shown below.
```
➜  demo git:(feat-cli-expose-daemon-copy) endo make counter.js --name x
Starting Endo daemon...
Object [Alleged: Counter] {}
➜  demo git:(feat-cli-expose-daemon-copy) endo eval 'E(x).incr()' x
1
➜  demo git:(feat-cli-expose-daemon-copy) endo cp x y
➜  demo git:(feat-cli-expose-daemon-copy) endo eval 'E(y).incr()' y
2
➜  demo git:(feat-cli-expose-daemon-copy) endo eval 'E(x).incr()' x
3
➜  demo git:(cli-expose-daemon-copy) ✗ endo mkguest alice alice-agent
Object [Alleged: EndoGuest] {}
➜  demo …
```
> feat(cli): Add copy command

- packages/bundle-source/cache.js
- packages/bundle-source/src/bundle-source.js
- packages/bundle-source/test/cache.test.js
Refs: https://github.com/Agoric/agoric-sdk/pull/9735
Agoric SDK integration revealed a regression in the `bundle-source/cache.js` implementation, where the validator didn’t recognize default metadata.
None.
None.
None.
This change includes a regression test.
Restores backward compatibility.
None.
> fix(bundle-source): Recognize default metadata

- packages/ses/NEWS.md
- packages/ses/src/compartment.js
- packages/ses/test/compartment-transforms.test.js
- packages/ses/test/import-cjs.test.js
- packages/ses/test/import-gauntlet.test.js
- packages/ses/test/import-hook.test.js
- packages/ses/test/import-legacy.test.js
- packages/ses/test/import-non-esm.test.js
- packages/ses/test/module-map-hook.test.js
- packages/ses/test/module-map.test.js
Refs: #400 
To reduce mismatched behavior between SES and XS, this change adds an option (to be removed at the next major version) that changes the compartment import method such that it returns a promise for an exports namespace instead of a promise for a box containing the imports namespace. This opts-in to the same thenable behavior as dynamic import in the language.
With this option, we must be weary of thenable modules, as we must be for thenable modules across the rest of the JavaScript ecosystem.
None.
This option will necessarily appear in all portable code examples on hardenedjs.org once it is available.
Tests have been adjusted to take advantage of the new option, except legacy tests which remain to test the behavior without the option enabled.
This is a backward compatible …
> feat(ses): Opt out of namespace boxes

- packages/compartment-mapper/src/bundle.js
- packages/compartment-mapper/src/node-modules.js
- packages/compartment-mapper/src/search.js
- packages/compartment-mapper/test/search.test.js
Refs: 592a485e22 #2344
#2344 introduced a regression in backward compatibility which has not yet been released. The change improved our ability to differentiate ENOENT and EISDIR from other error classes when searching for package.json. This adjusts that change to tolerate the currently accepted `read` function and allow read powers that included a more precise `maybeRead` function instead.
None.
None.
None.
Coverage test added for `search`.
This restores backward compatibility.
Nnoe.
> chore(compartment-mapper): Restore backward compatibility for search

- packages/eslint-plugin/lib/rules/harden-exports.js
- packages/eslint-plugin/test/harden-exports.test.js
_fixup_
The new `harden-exports` rule should not allow a function defined by the `function` keyword to be exported, because it can't really be hardened. The hoisting allows the value to be mutated by an import before it can be hardened.
improvement
none
none
new tests
bug fix
not released yet
> harden-exports error on 'function' keyword

- packages/ses/src/permits.js
Closes: #XXXX
Refs: https://github.com/tc39/proposal-arraybuffer-base64
https://github.com/tc39/proposal-arraybuffer-base64 is now at stage 3, which means we means many engine implementors will proceed to implement and ship it without hiding it behind a flag. And that we should proceed assuming that it will become an official part of the language.
This proposal adds some methods to `Uint8Array` and `Uint8Array.prototype`. While the proposal proceeded through tc39 we did not see any security problems, so we should simply permit this in `permits.js`. The absence of any mention of these currently in `permits.js` cause ses initialization to warn on platforms which implements this proposal -- like Moddable XS. (In fact, these warnings are what alerted us to the need to repair this absence. The …
> feat(ses): permit toHex etc

- browser-test/playwright.config.js
Fixes the web server start command in `browser-test/playwright.config.js`. Previously it was set to `npm run start`, but there is no script in the corresponding `package.json` named `start`. Instead we execute the server script directly using `node server.js`.
> fix(browser-test): Fix web server start script in browser-test

- README.md
_incidental_
Prompted by @ivan's discovery in https://github.com/Agoric/agoric-sdk/pull/9751#discussion_r1686807354
This README was still pointing to SES-shim CI. I updated it to use the Github Action badge. 
This also adds the badge for the Mutable.ai auto wiki.
none
none
here
reviewer please look at the rendered output
none
none
> docs: fix CI status badge

- packages/import-bundle/src/compartment-wrapper.js
- packages/import-bundle/test/export-inescapable-global.js
- packages/import-bundle/test/import-bundle.test.js
- packages/ses/src/error/assert.js
- packages/ses/src/module-load.js
Recent changes to align the Compartment constructor in SES with its XS counterpart changed the argument pattern and this broke the interface of all extant wrappers around the Compartment constructor, of which we only know of one. This change fixes that wrapper and restores continuity of compatibility.
None.
None.
None.
Inescapable global properties should cover this failure. It’s not yet clear why it did not reveal the failure earlier.
Restores compatibility. Reveals that the Compartment change broke more than we anticipated, but not enough to roll back.
None.
> fix(import-bundle): Adapt inescapable compartment mapper constructor

- packages/ses/scripts/bundle.js
Call lockdown before bundling the SES shim
Discussion: https://youtu.be/qGGeACz4cyM
- bundle now fails (TypeError) to build if non-standard JS called after `lockdown()`
- `yarn build` now also logs to console (e.g. `Removing unpermitted intrinsics`) if non-standard JS called before `lockdown()`
> Does this change require or encourage significant increase in consumption of CPU cycles, RAM, on-chain storage, message exchanges, or other scarce resources? If so, can that be prevented or mitigated?
> Give our docs folks …
> feat(ses): call lockdown before bundling SES shim

- packages/cli/package.json
- packages/cli/test/daemon-context.js
- packages/cli/test/demo/confined-script.js
- packages/cli/test/demo/counter-example.js
- packages/cli/test/demo/doubler-agent.js
- packages/cli/test/demo/index.test.js
- packages/cli/test/demo/mailboxes-are-symmetric.js
- packages/cli/test/demo/names-in-transit.js
- packages/cli/test/demo/sending-messages.js
- packages/cli/test/section.js
- packages/cli/test/types.d.ts
- packages/cli/test/with-context.js
- yarn.lock
Closes: #2368
Refs: #2372
A test suite which asserts that the cli demo produces its documented outputs.
Current weaknesses in the implementation include concurrency and independence. They are related and both should be resolved by a change to the daemon initialization in the test setups.
Note that despite these weaknesses, this setup is useful enough to reveal that certain cli commands do not behave as the demo supposes. Notably:
- `endo list --as alice-agent` is rejected because `--as` is not a supported option for `endo list`. This could have been caught with unit tests on the cli endpoints.
- `endo inbox` does not display messages as expected. In some cases the template string for the message has simply been altered, but the discrepancy in the mailboxes-are-symmetric section is …
> test(cli): Add demo doc alignment test, serial implementation

- packages/ses/NEWS.md
- packages/ses/error-codes/SES_ALREADY_LOCKED_DOWN.md
- packages/ses/error-codes/SES_UNCAUGHT_EXCEPTION.md
- packages/ses/error-codes/SES_UNHANDLED_REJECTION.md
- packages/ses/src/error/tame-console.js
- packages/ses/test/console-error-trap.test.js
- packages/ses/test/console-rejection-trap.test.js
Closes: #XXXX
Refs: #XXXX
Use `"SES_UNCAUGHT_EXCEPTION: ...` report output for parity with `SES_UNHANDLED_REJECTION: ...` report output.  Without this feature, `ses` would write the naked exception to stderr, which could lead to confusion when trying to understand _why_ the output was written.  This was doubly confusing if the exception was not an `Error`, rather just some other thrown value.
Improves security by giving more context for error output.
n/a
n/a
Just unit tests.
Since stderr is not generally parsed by programs, I am not concerned with breaking compatibility of the rendering of the uncaught exceptions.  This change should improve the user experience.
If the stderr of your SES program is processed by another program, this change will be visible.  You may need to change your …
> feat(ses): `errorTrapping` reports prepend `"SES_UNCAUGHT_EXCEPTION:"`

- .gitignore
- packages/eventual-send/src/E.js
- packages/eventual-send/src/exports.test-d.ts
- packages/eventual-send/src/handled-promise.js
- packages/eventual-send/src/types.d.ts
- packages/eventual-send/tsconfig.json
- packages/exo/test/types.test-d.ts
- packages/pass-style/src/types.d.ts
- packages/pass-style/src/types.test-d.ts
- packages/promise-kit/index.js
- packages/promise-kit/src/memo-race.js
- packages/promise-kit/tsconfig.json
- packages/ses/src/commons.js
- packages/ses/src/lockdown-shim.js
- packages/ses/src/lockdown.js
- packages/ses/src/tame-harden.js
- packages/ses/tsconfig.json
_incidental_
I was exploring why `tsc` is so slow in agoric-sdk and read that `"strictFunctionTypes": true` might offer a significant speed bump. With that I ran into some problems with `EProxy` that its methods were `never`. That was because the `Callable` type expect `...args: unknown[]` and real values aren't. `unknown` shouldn't be used as a test for extension. The fix was to make it `...args: any[]`.
This does that, and a bunch of other changes that came up while exploring.
The change for Aider is completely unrelated but didn't seem worth its own PR.
none
none
none
CI
Fixes types bugs
Will be noted in conventional commits changelog
> types misc, Passable, fix EProxy

- packages/bundle-source/NEWS.md
- packages/bundle-source/README.md
- packages/bundle-source/cache.js
- packages/bundle-source/demo/meaningful.js
- packages/bundle-source/src/endo.js
- packages/bundle-source/src/main.js
- packages/bundle-source/src/script.js
- packages/bundle-source/src/types.js
- packages/bundle-source/src/zip-base64.js
- packages/bundle-source/test/endo-script-format.tests.js
- packages/evasive-transform/NEWS.md
- packages/evasive-transform/src/index.js
- packages/evasive-transform/src/transform-ast.js
- packages/evasive-transform/src/transform-comment.js
- packages/evasive-transform/test/elide-comment.test.js
- packages/evasive-transform/test/transform-comment.test.js
Closes: #2413 
Adds an option to the bundler to blank the interior of comments, reducing bundle sizes.
This change does not attempt to apply the elideComments behavior if the user selects noTransforms, since it is piggybacking on the censorship evasion transform. These features could be decoupled, elideComments works with endoZipBase64 and a narrower interpretation of noTransforms (no precompiled module transforms).
Some care has been taken to ensure that the resulting comments produce programs with the same behavior in the event the comment must be interpreted as a newline for automatic semicolon insertion (ASI).
None.
- NEWS
- README
- evasive transform unit tests
- bundle source unit tests
- covering endoScript and endoZipBase64
- composition errors with noTransforms
Uncovered:
- cache …
> feat: Elide comments in bundles

- packages/ses/test/enable-default-overrides-default.test.js
- packages/ses/test/enable-property-overrides-default-unsafeError.test.js
- packages/ses/test/enable-property-overrides-default.test.js
Closes: #XXXX
Refs: #2383 
Of the various property override tests, the ones testing the default `'moderate'` setting were calling `lockdown` without an `overrideTaming` option, counting on it to default to `'moderate'`. However, if run locally in an environment where the environment variable `LOCKDOWN_OVERRIDE_TAMING` was set to something else, the test would pointlessly misbehave.
This PR merely sets the option explicitly for those cases, so the tests for the `'moderate'` case are as insensitive to environment variables as the tests for the other cases.
none
none
none
The point. The code before this PR would always work correctly under CI. But the test may pointless fail locally depending on the developers environment variable settings.
none
none
> fix(ses): make test insensitive to an irrelevant env var

- packages/captp/NEWS.md
- packages/captp/src/captp.js
Closes: #2412
Have CapTP abort the connection if `send` returns a promise rejection.  The existing implementation only aborted if `send` threw a synchronous exception.
Crisper handling of async transport-layer failures.
n/a
Allows effective use of `async` CapTP send functions.
Usual CI.
Will abort the connection if an `async` `send` rejects.  Before, the rejection was ignored.
n/a
> feat(captp): handle `send` rejections

- packages/bundle-source/src/endo.js
- packages/bundle-source/src/zip-base64.js
This removes dead code. The bundler uses the `dev` flag only for discovery of `devDependencies` in `mapNodeModules`, and makes no further use of it in the bundling kit.
> refactor(bundle-source): Remove vestigial internal dev option

- .github/workflows/ci.yml
- packages/ses/package.json
Closes: #2418 
Refs: #2417 #1308 
Adapted from https://github.com/endojs/endo/pull/2419#pullrequestreview-2252979514 below
The platform compatibility test specifically validates that SES works on Node.js 12 and can be deleted since it has vanished into history. Node.js 12 required special consideration because of its experimental ESM support. Delete the `test:platform-compatibility` script in the ses `package.json`, as well as the `test/package` fixture in ci.yml
Immediate motivation explained in #2418 , #2417 broken the platform-compatibility-test tests because it depends on the platform providing either `Array.prototype.transfer` or `structuredClone`. Node supports `transfer` starting with Node 22, but supports `structuredClone` starting in Node 18. That should be fine, since that is …
> fix: Delete obsolete platform-compatibility-test

- packages/import-bundle/NEWS.md
- packages/import-bundle/README.md
- packages/import-bundle/src/index.js
- packages/import-bundle/test/import-bundle.test.js
Adds support for `endoScript` to the `importBundle` runtime.
None.
None.
This change makes safe the assumption that all bundles produced by `bundleSource` can be consumed by `importBundle`.
- NEWS
- README
Unit tests included.
None.
None.
> feat(import-bundle): Support endoScript

- packages/module-source/DESIGN.md
- packages/module-source/TESTS.md
- packages/module-source/src/hidden.js
- packages/module-source/test/module-source.test.js
This PR changes the `HIDDEN_PREFIX` of `ModuleSource` from the non-conforming `$h\u200D_` zero-width joiner (`ZWJ`) notation to the conforming `$h\u034F_` combining grapheme joiner (`CGJ`) notation.
A future PR may address further changes to a `$\u034F`-prefixed and `\u034F$`-suffixed format as was suggested by @michaelfig in discussions.
This change is motivated after encountering a parsing error when using `rollup` which was traced back to the `$h\u200D_`-prefixed identifier in an `endoScript` bundle. More importantly, this is also motivated by the subsequent discovery that `rollup`'s implementation was actually conforming to the ECMAScript Specification when it was throwing this error.
To elaborate, while runtimes today will accept the special identifier notation that is currently …
> fix(module-source): Sub non-conforming `ZWJ` prefixes with `CGJ`

- packages/ses/NEWS.md
- packages/ses/src/commons.js
- packages/ses/src/lockdown.js
- packages/ses/src/shim-arraybuffer-transfer.js
- packages/ses/test/shim-arraybuffer-transfer.test.js
Staged on #2419 
Closes: #XXXX
Refs: https://github.com/endojs/endo/pull/2414 #2418 #2419 
#2414  by itself does not work on Node 18 and Node 20 because
- those platforms do not have `Array.prototype.transfer`, so #2414 must use `structuredClone` instead
- `structuredClone` does exist on Node >= 18, so it should be on supported platforms (though see #2418 ). However, `structuredClone` itself is dangerous and so must not be added to the shared intrinsics. As a result, in #2414 , when `@endo/pass-style` is initialized in a created compartment, it fails to find either `Array.prototype.transfer` and `structuredClone
To solve this, @kriskowal suggested that we also shim `Array.prototype.transfer` if needed during `lockdown`, along with other repairs. We are avoiding similarly shimming …
> feat(ses): shim ArrayBuffer.prototype.transfer

- packages/ses/NEWS.md
- packages/ses/console-shim.js
SES exposes `ses/console-shim.js` in `package.json`, but lacked the “thunk” module needed to entrain the actual implementation. Being able to compose all the layers of `ses` *except* `ses/assert-shim.js` proves to be necessary to make progress on parity testing with XS #2252
> fix(ses): Expose ses/console-shim

- packages/ses/package.json
- packages/ses/src/compartment.js
SES restricts access to globals in the lexical scope of SES itself, except for their initial capture in `commons.js`, in order to avoid subsequent modifications to the global environment from damaging the integrity of SES itself. This has the side-effect of making SES itself non-reliant on the side-effects of its own shimming behavior, especially when the application applies the shim layers selectively. This is about to become important because we must omit the `ses/assert-shim.js` layer when running SES under test262, since that conflicts with test262’s own `harness/assert.js`. Capturing `assert` lexically allows SES to rely on its own `assert` API without interfering with the different global.
I’ve added all the Hardened JavaScript API, but did not add `console`. We might add `console` …
> fix(ses): Restrict global assert

- packages/ses/NEWS.md
- packages/ses/package.json
Stemming from a confusion in #2460, I find that we never exported ses/console-shim.js and that this change was buried in a subsequent change in my stack of coming changes.
> feat(ses): Expose ses/console-shim.js for real this time

- .github/workflows/ci.yml
this is automatically already printed by the runner as mentioned [earlier](https://github.com/endojs/endo/pull/2334#discussion_r1761817039) cc @boneskull
> chore: remove redundant node version CI steps

- packages/cli/demo/README.md
- packages/cli/test/demo/index.test.js
- packages/cli/test/demo/mailboxes-are-symmetric.js
- packages/cli/test/demo/names-in-transit.js
- packages/cli/test/demo/sending-messages.js
Closes: https://github.com/endojs/endo/issues/2409
Refs: https://github.com/endojs/endo/pull/2384
This PR updates the readme to properly document the `list` cli command and fixes the failing tests
none
none
none
none
none
none
> test(cli): Fix failing cli tests

- packages/module-source/NEWS.md
- packages/module-source/package.json
- packages/module-source/shim.js
- packages/module-source/src/module-source.js
- packages/ses/NEWS.md
- packages/ses/src/get-anonymous-intrinsics.js
- packages/ses/src/permits-intrinsics.js
- packages/ses/src/permits.js
- packages/ses/test/module-source.test.js
Refs: #2252
To test feature the degree of compatibility between a version of XS, XS with Endo shims, and Node.js with Endo shims, we need a shim for ModuleSource proper. This lets us create an environment with a global `ModuleSource`, where `ModuleSource` is a shared intrinsic of all Compartments.
This change both introduces the shim and the necessary accommodations for the existence of a global ModuleSource shared intrinsic in SES.
The new ModuleSource is subject to hardening of shared intrinsics during SES lockdown. A failure to harden the shared intrinsic would lead to a potential for interference or communication between isolated compartments.
None.
None.
This includes a test for SES that verifies that ModuleSource is properly propagated and hardened.
None.
None.
> feat(ses,module-source): Add ModuleSource shim

- packages/ses/NEWS.md
- packages/ses/src/get-anonymous-intrinsics.js
- packages/ses/src/permits.js
- packages/ses/test/module-source.test.js
This reverts commit 0d210a33c7730e59f722fa2c9e5441eb6065e1b3.
This change caused a failure for Lockdown on XS in Agoric SDK, indicating that it is a breaking change.
Reverting this change is a temporary mitigation.
We will first address the gap in XS CI coverage and then persue a fix.
We will pursue a follow-up change that addresses XS coverage in CI #2463 and then consider repairing the native `ModuleSource` intrinsic under `repairIntrinsics` in SES.
> chore(ses): Revert ModuleSource shared intrinsic

- .github/workflows/ci.yml
- packages/ses/package.json
Refs: #2254
Rigs CI to run tests with `xst`. We can elaborate on this with a broader XS version vector and add XS tests to packages. This is in anticipation of a new harness262 package that will need `xst` in CI.
> test: Introduce XS CI workflow

- packages/ses/NEWS.md
- packages/ses/src/error/console.js
- packages/ses/src/lockdown.js
- packages/ses/src/permits.js
- packages/ses/src/tame-module-source.js
- packages/ses/test/module-source.test.js
Refs: #2463, #2252
In #2463 we introduced ModuleSource to the SES permits, but this interacted catastrophically with the native XS ModuleSource. We reverted this change #2468 to unbreak Agoric SDK integration. This change reintroduces the ModuleSource permits, such that they are compatible with both XS and the `@endo/module-source/shim.js`, which anticipates the introduction of an AbstractModuleSource base class. Because SES can more gracefully tolerate the absence of an permitted [[Proto]] than the presence of a non-permitted [[Proto]], this adjusts the shim to ensure that the AbstractModuleSource shape exists as a side-effect of repairs/taming, before permits are applied.
None.
None.
This change reintroduces a note in NEWS.md for the next release.
The prior regression went unnoticed …
> feat(ses): Tame ModuleSource

- packages/cli/src/commands/adopt.js
- packages/cli/src/commands/reject.js
- packages/cli/src/commands/resolve.js
- packages/cli/src/number-parse.js
- packages/cli/test/number-parse.test.js
This PR introduces a new `parseNumber` function that safely parses input as a number on cli commands.
Additional tests have been added to ensure this new functionality works correctly.
none
none
none
none
none
none
> fix(cli): Improve number parsing

- .github/workflows/ci.yml
Fixes #2283
In order to avoid unnecessary duplication of effort in CI and to keep the required Lint job name consistent as we upgrade the underlying Node.js version, this change drops the test matrix and hard-codes the platform and node version.
> chore(ci): Drop matrix for lint job

- .github/dependabot.yml
_incidental_
https://github.com/endojs/endo/pull/2559 updated major versions, because there was no limit on `update-types`.
Now following this example: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#example-3
n/a
n/a
n/a
I wish we could test before master but it appears not
n/a
n/a
> chore(dependabot): fix all-minor-patch update-types

- packages/compartment-mapper/src/compartment-map.js
The parameter name did not match.
> fix(compartment-mapper): bad type in assertCompartmentMap

- packages/captp/src/captp.js
- packages/captp/test/export-hook.test.js
- packages/captp/test/external-import-export.test.js
alternate implementation of https://github.com/endojs/endo/pull/2562
ExtRef migration notes:
- passing in import/export tables
- replaces `opts.gcHook` (export table)
- replaces `opts.missingExportHook` (export table)
- replaces `captp.exportValue` (export table)
- replaces `captp.importSlot` (import table)
- providing a slot provider
- replaces `opts.onBeforeExportHook` (retrieving slot)
- providing a presence creator
- replaces `opts.onBeforeExportHook` (creating a presence)
- still need `captp.makeRemoteKit`
> feat(captp): allow external import/export tables

- packages/bundle-source/src/bundle-source.js
- packages/captp/src/atomics.js
- packages/captp/src/captp.js
- packages/captp/test/traplib.js
- packages/captp/test/worker.js
- packages/compartment-mapper/src/compartment-map.js
- packages/daemon/src/daemon.js
- packages/daemon/src/worker.js
- packages/errors/index.js
- packages/evasive-transform/src/generate.js
- packages/evasive-transform/src/index.js
- packages/evasive-transform/src/transform-ast.js
- packages/eventual-send/src/E.js
- packages/eventual-send/src/postponed.js
- packages/exo/src/exo-makers.js
- packages/lp32/reader.js
- packages/lp32/writer.js
- packages/pass-style/src/types.test-d.ts
- packages/promise-kit/index.js
- packages/ses/src/compartment-shim.js
- packages/ses/src/error/assert.js
- packages/ses/src/error/console.js
- packages/ses/src/error/internal-types.js
- packages/ses/src/error/note-log-args.js
- packages/ses/src/error/tame-console.js
- packages/ses/types.test-d.ts
- tsconfig.eslint-base.json
_incidental_
In an a3p test I tried disabling `skipLibCheck` and many errors were from Endo packages's omission of module filename extensions.
That's because Endo was using the default [moduleResolution](https://www.typescriptlang.org/tsconfig/#moduleResolution), `node10`. This changes it to `NodeNext` and also the `module` option for compatibility.
That resulted in new errors which I address mostly by switching to explicit `@import`.
none
none
none
- https://github.com/Agoric/agoric-sdk/pull/9385
This might affect consuming packages that depend on ambient types. That's almost certainly only agoric-sdk which we can solve with https://github.com/Agoric/agoric-sdk/pull/9385
If https://github.com/Agoric/agoric-sdk/pull/9385 needs changes then `NEWS.md` should indicate it. I don't think type …
> tsconfig moduleResolution: NodeNext

- packages/module-source/test/module-source.test.js
Refs: #2094
Elaborates failing tests for a known defect of ModuleSource, encountered in the development of #400
> test(module-source): Should export const object with default values

- packages/pass-style/CHANGELOG.md
- packages/pass-style/package.json
- packages/patterns/CHANGELOG.md
- packages/patterns/package.json
In https://github.com/endojs/endo/pull/2602, we inadvertently bumped the major versions for patterns and pass-style (while manually intervening in Lerna’s release process to avoid a major version bump for marshal)
In this change, we retroactively resume the 1.x train for these two packages. These two packages will be manually published to npm and assigned git tags.
> chore(patterns,pass-style): Recouple accidental 2.0.0 releases under 1.x train

- packages/captp/CHANGELOG.md
- packages/captp/package.json
- packages/cli/CHANGELOG.md
- packages/cli/package.json
- packages/daemon/CHANGELOG.md
- packages/daemon/package.json
- packages/exo/CHANGELOG.md
- packages/exo/package.json
- packages/far/CHANGELOG.md
- packages/far/package.json
- packages/marshal/CHANGELOG.md
- packages/marshal/package.json
- packages/pass-style/CHANGELOG.md
- packages/pass-style/package.json
- packages/patterns/CHANGELOG.md
- packages/patterns/package.json
In https://github.com/endojs/endo/pull/2602, we erroneously published 2.0 versions of pass-style and patterns. This release recouples these to their 1.x trains, and propagates that version selector to the dependent packages.
We are losing continuity of a published patch version number, but the computers and I are beyond caring.
> chore: Release 2024-10-22 Supplemental

- packages/ses/README.md
This addresses a speed bump in our documentation of how to use SES, as seen at https://github.com/endojs/endo/issues/1281#issuecomment-2418717060
> docs(ses): Missing lockdown in Compartment doc

- packages/compartment-mapper/src/capture-lite.js
- packages/compartment-mapper/src/types.js
This just allows `captureFromMap()` to receive a `Compartment` option which is passed thru to `link()`.
> feat(compartment-mapper): add Compartment option to captureFromMap

- packages/ses/NEWS.md
- packages/ses/src/permits.js
Closes: #2607 
> "There is no do. There is only try."
> —Noda
See also https://github.com/tc39/proposal-promise-try
none
none
one less divergence to document.
none
better
nothing breaking.
> feat(ses): permit Promise.prototype.try

- packages/compartment-mapper/NEWS.md
- packages/compartment-mapper/src/archive-lite.js
- packages/compartment-mapper/src/compartment-map.js
- packages/compartment-mapper/src/import-hook.js
- packages/compartment-mapper/src/link.js
- packages/compartment-mapper/src/types.js
- packages/compartment-mapper/test/fixtures-retained/node_modules/mk1/package.json
- packages/compartment-mapper/test/retained.test.js
Closes: #2313
This change adds instrumentation to the compartment mapper that allows it to omit module descriptors from archive compartment maps if they’re not needed to link the archived application.
None.
Should reduce bundle sizes.
Does not merit attention and one less surprise for bundle size investigators. Noted in NEWS.
This change augments the existing test for compartment retention to cover module descriptor collection.
The change does not add the "retained" property to archived `compartment-map.json`, so new bundles should remain compatible with older versions of `checkBundle`. However, I relaxed the schema validator to get an unrelated test for `captureCompartmentMap` passing, so future deployments of `checkBundle` will be more lenient.
Should not affect upgrades.
> feat(compartment-mapper): Collect unused module descriptors

- packages/ses/NEWS.md
- packages/ses/docs/lockdown.md
- packages/ses/src/enable-property-overrides.js
- packages/ses/src/lockdown.js
- packages/ses/src/permits-intrinsics.js
- packages/ses/src/reporting-types.d.ts
- packages/ses/src/reporting.js
- packages/ses/test/error/_lockdown-with-extra-intrinsics.js
- packages/ses/test/error/_prepare-with-extra-intrinsics.js
- packages/ses/test/error/permit-removal-warnings-node.test.js
- packages/ses/test/error/permit-removal-warnings.test.js
- packages/ses/types.d.ts
Closes: #2608
This change introduces a `"reporting"` option to `lockdown` and `repairIntrinsics` that determines the means by which SES will send warnings to diagnostic tools like the web or node `console`, `print`, or nowhere at all.
None
None
Relevant documentation added to lockdown options and NEWS.
This adjusts the existing test to use the `"reporting": "console"` option, since it already verifies that behavior and consequently is suitable for verifying the web behavior while standing on Node.js.
This adds a new test that verifies that reporting with the `"platform"` default behavior on node generates no output on stderr and confirms the presence of expected indented and non-indented messages, while being resilient to additional intrinsics being added to the platform.
None.
None.
> feat(ses): Lockdown reporting option

- packages/ses/src/module-link.js
- packages/ses/src/module-load.js
- packages/ses/test/module-map.test.js
This change increases coverage and consistency of error messages for invalid module sources.
None.
None.
None.
It’s tests all the way down.
There is a possibility that this will break tests that are over-constrained on error messages.
None.
> test(ses): Coverage for module source validation

- packages/bundle-source/NEWS.md
- packages/bundle-source/README.md
- packages/bundle-source/demo/fortune.ts
- packages/bundle-source/demo/import-ts-as-js.ts
- packages/bundle-source/demo/reexport-fortune-ts.js
- packages/bundle-source/demo/reexport-fortune-ts.ts
- packages/bundle-source/demo/reexport-meaning-js.js
- packages/bundle-source/demo/reexport-meaning-js.ts
- packages/bundle-source/package.json
- packages/bundle-source/src/endo.js
- packages/bundle-source/src/script.js
- packages/bundle-source/src/zip-base64.js
- packages/bundle-source/test/endo-script-format.test.js
- packages/bundle-source/test/typescript.test.js
- yarn.lock
Closes: #2415 
This change introduces support for TypeScript through type-erasure, using ts-blank-space, which converts type annotations to equivalent blank space. As is consistent with `node --experimental-strip-types`, this only applies to modules with the `.ts`, `.mts`, or `.cts` extensions in packages that are not under `node_modules`, to discourage publishing TypeScript as a source language to npm.
The choice of `ts-blank-space` is intended to minimize runtime behavior difference between TypeScript and JavaScript, such that a reviewer or a debugger of the generated JavaScript aligns with the expected behavior and original text, to the extent that is possible. This should compose well with #2444.
None.
Contains README and NEWS.
Contains spot check tests for TypeScript in the …
> feat(bundle-source): Support TypeScript type erasure

- packages/ses/src/cauterize-property.js
- packages/ses/src/compartment-shim.js
- packages/ses/src/intrinsics.js
- packages/ses/src/lockdown.js
- packages/ses/src/permits-intrinsics.js
- packages/ses/test/tolerate-empty-prototype-toplevel.test.js
- packages/ses/test/tolerate-empty-prototype.test.js
Closes: #2598 
Refs: https://github.com/endojs/endo/pull/2563 https://github.com/endojs/endo/pull/2334 https://github.com/endojs/endo/pull/1221
#1221 was supposed to make ses tolerate undeletable `func.prototype` properties that should be absent, so long as they could be set to `undefined` instead, making them harmless. This tolerance came with a warning to flag the remaining non-conformance.
However #2598 explains why #1221 sometimes fails to do this. #1221 did come with a test, but it fell into the case where #1221 works, which is a non-toplevel function.
#2563 (and #2334 ?) fell into the trap explained by #2598 and untested by #1221, which is an undeletable `func.prototype` on a top-level instrinsic. As a result, #2563 currently contains a workaround for #2598 which this PR would make …
> fix(ses): fix #2598 with cauterizeProperty reuse

- packages/ses/NEWS.md
- packages/ses/src/lockdown.js
- packages/ses/src/tame-date-constructor.js
- packages/ses/src/tame-math-object.js
- packages/ses/test/_lockdown-unsafe.js
- packages/ses/test/lockdown-options.test.js
- packages/ses/types.d.ts
- packages/ses/types.test-d.ts
support for lockdown options `mathTaming` and `dateTaming` were [removed in July 2020](https://github.com/endojs/endo/pull/372). Since these options don't do anything, lockdown should **warn** when these options are specified.
For LavaMoat, we were surprised to find they were being provided to lockdown, but had no effect. Any other unrecognized lockdown options are rejected.
Here is a PR for a breaking change that fully removes the options https://github.com/endojs/endo/pull/2583
> fix(ses): warn on unsupported lockdownOptions mathTaming + dateTaming

- packages/compartment-mapper/src/node-modules.js
I discovered this bug while reviewing Compartment Mapper: I’ve deprecated the `dev` option of `mapNodeModules` in favor of `development` in the `conditions` set option, since generally one should want both behaviors for development mode, so one should imply the other. However, the way this is implemented causes `devDependencies` to be linked for every package in the presence of the `development` condition, and should only be in the entry package.
> fix(compartment-mapper): Dev implied by development condition only for entry package

- packages/ses/types.d.ts
`globalThis` can contain `Symbol` keys, so it is more correctly typed as `Record<PropertyKey, any>`.
This also widens the type of the `globals` parameter in the `Compartment` constructor.
> fix(ses): widen type of globalThis in Compartment

- packages/marshal/package.json
- yarn.lock
They were apparently missing from the beginning: https://github.com/endojs/endo/blame/bc6f30a1191ac65ec69569379e063296e122ea86/packages/marshal/package.json
> chore(marshal): Add eslint devDependencies

- packages/compartment-mapper/test/optional.test.js
- packages/compartment-mapper/test/scaffold.js
- packages/module-source/NEWS.md
- packages/module-source/src/babelPlugin.js
- packages/module-source/src/module-source.js
- packages/module-source/src/transform-analyze.js
- packages/ses/NEWS.md
- packages/ses/src/compartment.js
- packages/ses/src/module-instance.js
- packages/ses/test/import.test.js
Closes: #291
This change adds support for dynamic `import` to `ses` and `@endo/module-source`, such that `import(x)` in the scope of a module loaded from source (using `ModuleSource` in a `Compartment` module loading hook).
This change builds on prior work to ensure that dynamic import is facilitated by a hidden lexical name injected by `ses`. The dynamic import mechanism is isolated to the surrounding compartment and specifiers are resolved on the surrounding module.
This change introduces a static analysis for the presence of a dynamic `import` in the module source, which it communicates on the module source, even if marshaled through JSON, to `ses` that it should create an `import` closure bound to the calling module’s base specifier. This avoids an allocation for most modules.
Only …
> feat(ses,module-source): Dynamic import

- packages/marshal/test/encodePassable.test.js
- packages/marshal/test/rankOrder.test.js
- packages/pass-style/package.json
- packages/pass-style/tools.js
- packages/pass-style/tools/arb-passable.js
- packages/patterns/test/copySet.test.js
Fixes #1741
> [!CAUTION]
> While technically a breaking change, it is pragmatically not marked as such because we are not aware of anything outside of Endo that imports a fast-check arbitrary.
Rather than importing `fc` directly to export arbitraries, @endo/pass-style/tools.js now returns them from an exported `makeArbitraries` function that requires `fc` as an argument.
Best reviewed [with whitespace ignored](https://github.com/endojs/endo/pull/2645/files?w=1).
n/a
n/a
n/a
n/a
This is a breaking change, but only to @endo/pass-style/tools.js. All imports in this repository have been updated, and I didn't see any in [agoric-sdk](https://github.com/Agoric/agoric-sdk) or [agoric-3-proposals](https://github.com/Agoric/agoric-3-proposals), but if there are any then they will need similar …
> refactor(pass-style): Make @fast-check/ava a devDependency

- packages/ses/src/error/console.js
Ref #2643
Ref 5e8fd33e7c9bf23b12640022a5ca4b11c29d0136
Unify the inconsistent approaches to creating [virtual] console functions with appropriate "name" properties.
None.
n/a
n/a
I don't think these details are covered by testing, but it seems like an acceptable gap for now.
None.
None.
> fix(ses): Consistently name console methods

- packages/compartment-mapper/src/map-parser.js
- packages/daemon/test/endo.test.js
- packages/eventual-send/src/E.js
- packages/eventual-send/src/exports.d.ts
- packages/eventual-send/src/exports.test-d.ts
- packages/far/src/exports.d.ts
- packages/far/src/exports.js
- packages/far/src/index.js
incidental
Migrated from https://github.com/Agoric/agoric-sdk/pull/9011
Define an `EReturn` type for the `Awaited<ReturnType<` pattern.
none
none
This will appear in TSdoc
has tests
none
none
> EReturn type

- packages/ses/src/permits.js
Follow-up to
- https://github.com/endojs/endo/pull/2624
Progresses
- https://github.com/endojs/endo/issues/1891
---
Fix `removeUnpermittedIntrinsics` (previously `whitelistIntrinsics`) on Hermes
```console
SES Removing unpermitted intrinsics
Removing intrinsics.Promise.caller
failed to delete intrinsics.Promise.caller TypeError: Property is not configurable
Uncaught TypeError: Property is not configurable
```
after starting again on the problem (now with https://github.com/endojs/endo/pull/2624 addressing `completePrototypes`), it boils down to tolerating two more undeletable non-standard properties (`.caller` and `.arguments`) on the remaining Hermes functions after attempting to remove them
edit: and `.prototype` on some properties
so we can simply extend `cauterizeProperty` after …
> fix(ses): `removeUnpermittedIntrinsics` on Hermes

- packages/eslint-plugin/lib/configs/internal.js
- packages/pass-style/src/types.d.ts
closes: #XXXX
https://github.com/Agoric/agoric-sdk/pull/10751
We generally use names of the form `^([A-Z]\w*)I$`, i.e., identifiers beginning with a capital letter and ending with a lone capital "I", for interface guards. However there were some uses of the same form of name for typescript interfaces. Because interfaces and interface guards are adjacent concepts, this could be confusing. This PR fixes this for endo. The companion https://github.com/Agoric/agoric-sdk/pull/10751 fixes it for agoric-sdk. Because the endo names in question were not exported, there is clearly no dependency between these two PRs. 
Consistent naming conventions makes code more reviewable, which is good for security.
none
Consistent naming conventions helps documentation and its readers.
none
Because these names …
> refactor(pass-style): Avoid name convention conflict

- .github/workflows/browser-test.yml
Refs: https://github.com/Agoric/agoric-private/issues/229
Bumps upload-artifact version from v3 to v4
None
None
None
Updates a deprecated action used in CI but that's about it. **Browser Tests** check was in a failing state before this PR and the action version bump is harmless (already done in other repos)
None
None
> ci: bump upload-artifact action

- packages/patterns/README.md
This commit addresses a broken link to the Endo API Documentation from within the  README. Instead of https://endojs.github.io/, users should be sent to https://endojs.github.io/endo/, which is what this commit addresses.
Ref: #2442 
N/A
> docs(patterns): fixed broken link in README

- packages/marshal/docs/smallcaps-cheatsheet.md
Closes: #XXXX
Refs: 
- https://github.com/ocapn/ocapn/pull/125 
- https://github.com/ocapn/ocapn/blob/28af626441da888c4a520309222e18266dd2f1f2/draft-specifications/Model.md 
- https://github.com/endojs/endo/pull/2452 
- https://github.com/Agoric/agoric-sdk/pull/10084 
- https://github.com/tc39/proposal-immutable-arraybuffer 
- https://github.com/endojs/endo/pull/2414
Revise Smallcaps cheatsheet to track OCapn as of https://github.com/ocapn/ocapn/pull/125
none
none
the point. The cheatsheet was becoming too stale.
none
none
none
> docs(marshal): revise cheatsheet to match ocapn

- packages/ses/src/error/console.js
Closes: #XXXX
Refs: #XXXX
Was getting the irritating warning
This PR simply does what that warning suggests.
Verified that with this change
- `yarn lint` runs clean without any warnings.
- `lint` under CI below passes
- No "Unchanged files with check annotations" warnings appear in this PR's code review page.
none
none
none
none
none
none
> refactor: cleanup type warning

- packages/immutable-arraybuffer/index.js
- packages/immutable-arraybuffer/shim.js
- packages/immutable-arraybuffer/test/index.test.js
- packages/immutable-arraybuffer/test/shim.test.js
Closes: https://github.com/tc39/proposal-immutable-arraybuffer/issues/26
Refs: https://github.com/tc39/proposal-immutable-arraybuffer https://github.com/tc39/proposal-immutable-arraybuffer/issues/15 https://github.com/tc39/proposal-immutable-arraybuffer/issues/9 https://github.com/tc39/proposal-immutable-arraybuffer/issues/16
Since the last work on this immutable-arraybuffer shim, at the tc39 plenary we decided that 
- `transferToImmutable` should take an optional `newLength` parameter, to stay parallel to the other `transfer*` methods.
- The `sliceToImmutable` method should be added.
The spec at https://github.com/tc39/proposal-immutable-arraybuffer and the Moddable XS implementation both already reflect these changes. This PR brings this shim up to date with those changes, closing …
> fix(immutable-arraybuffer): update to recent spec

- packages/captp/src/trap.js
- packages/eventual-send/src/E.js
- packages/eventual-send/src/handled-promise.js
- packages/far/test/marshal-far-function.test.js
- packages/marshal/src/marshal-stringify.js
- packages/marshal/test/marshal-far-function.test.js
- packages/pass-style/test/passStyleOf.test.js
- packages/ses/docs/preparing-for-stabilize.md
- packages/ses/src/commons.js
- packages/ses/src/sloppy-globals-scope-terminator.js
- packages/ses/src/strict-scope-terminator.js
Closes: #XXXX
Refs: https://github.com/Agoric/agoric-sdk/pull/10795
Prepare for anticipated introduction and use of the non-trapping integrity trait as explained at https://github.com/endojs/endo/blob/b12eb434b6672f0ceae41be55aac7f24c4562b7b/packages/ses/docs/preparing-for-stabilize.md
These preparations must work now, before these traits are introduced, and should continue to work after these traits are introduced and used.
Some things that had been deeply frozen automatically by `harden` are now manually frozen by explicit calls to `freeze`. We need to review these carefully to ensure that nothing has inadvertently be left unfrozen as a result of the changes in this PR.
Some proxies will become unhardenable, but they will still be hardenable as of now, so mistaken hardenings will not be …
> refactor: prepare for non-trapping integrity trait

- packages/ses/docs/lockdown.md
> docs(ses): Fix typos in lockdown.md

- packages/ses/src/permits.js
Closes: #XXXX
Refs: https://github.com/tc39/proposals
The `permits.js` file should stay reasonably up to date with https://github.com/tc39/proposals stage 4, 3, and 2.7 proposals. Those it is not yet ready to list, it should at least include in a TODO comment. For non-ancient proposals, each such entry should cite the proposal url.
The entire reason for the permits mechanism is so that elements added to the primordials are not enabled for Hardened JS until the Hardened JS stewards have vetted them. This is mostly by having vetted the specs during the proposal process, ***assuming*** that the implementations follow the spec correctly enough for security purposes. When we later find that an implementation has not, this is a separate security concern to be dealt with then, probably by …
> fix(ses): update permits for stage 2.7.4 proposals

- packages/cli/test/_section.js
Closes: #2702 
Refs: #XXXX
As shown by #2702:
When tests are run under the vscode JavaScript Debug Terminal, every time that test spawns a subshell, extra noise appears on the stderr of that subshell, such as
```
Debugger attached.␊
- Waiting for the debugger to disconnect...
```
This seems symptomatic of a widespread assumption that other tools on the toolchain can inject extra output into the stderr of subshells without typically causing problems.
The test framework code changed by this PR had defaulted both an absent stdout expectation and an absent stderr expectation to expecting the empty string. This PR changes the stderr default expectation to an regexp that accepts anything. This can still be overridden by an explicitly provided stderr expectation, including one explicitly …
> fix(cli): tolerate #2702 stderr noise

- packages/eventual-send/src/E.js
- packages/eventual-send/src/no-shim.js
Closes: #2706
Add some documentation on *E*, in hopes that it will appear as hovertext in IDEs.  Also added an example and a link to the API Documentation.
No impact
No consequences.
No change to any interface. The goal is to add jsDoc to E.
I don't know how to test this before it's deployed. In WebStorm, I was able to see the comment when hovering on *E* in `no-shim.js`, but not anywhere else.
No effects
None
> docs: add some javadoc on E in hopes that it'll be visible in IDEs

- packages/compartment-mapper/NEWS.md
- packages/compartment-mapper/src/node-modules.js
- packages/compartment-mapper/src/policy.js
- packages/compartment-mapper/src/search.js
- packages/compartment-mapper/src/types/external.ts
- packages/compartment-mapper/src/types/internal.ts
- packages/compartment-mapper/src/types/node-modules.ts
I'd like `@endo/compartment-mapper` to a) emit more information about what it's doing and b) allow me to control how it emits that information.
In lieu of a ~~larger~~ ~~complicated~~ reporting/diagnostics system (potentially invoking the spectre of `EventEmitter`), I've allowed a custom logger to be passed in to a handful of functions in `@endo/compartment-mapper` (including both private and public APIs). Generally speaking, `@endo/compartment-mapper` currently _doesn't log anything_ (except the one place that it _does_); I intend to add more `log()` calls in future PRs to aid debugging.
This change:
- adds a `LogFn` type which can be accepted in an options bucket (`LogOptions`)
- `mapNodeModules` and its internal functions now support this option
- `search`, `captureFromMap`, …
> feat(compartment-mapper): add option for custom logger to varied functions

- packages/pass-style/src/copyArray.js
- packages/pass-style/src/copyRecord.js
- packages/pass-style/src/error.js
- packages/pass-style/src/internal-types.js
- packages/pass-style/src/passStyleOf.js
- packages/pass-style/src/remotable.js
- packages/pass-style/src/tagged.js
- packages/ses/src/make-hardener.js
Closes: #XXXX
Refs: https://github.com/Agoric/agoric-sdk/pull/10975 https://github.com/Agoric/agoric-sdk/pull/10982 
Using the benchmark tool from #10975 by @muhammadahmadasifbhatti as modified by #10982 to produce flamegraphs (interactive in vscode) I iterated on that benchmark test which already had very specific simple examples exercising  `passStyleOf`. Together with the snippet at https://github.com/Agoric/agoric-sdk/blob/acbb5da3c5a52bab8db319fd696aed70146f9a89/.github/actions/restore-node/action.yml#L156 (which @gibson042 brought to my attention)
```sh
$ scripts/get-packed-versions.sh ~/endo | scripts/resolve-versions.sh
$ yarn install && yarn build
$ cd packages/benchmark-test
$ yarn bench
```
and then clicking on the latest *.cpuprofile file, assuming you've already installed the …
> refactor(pass-style): faster `passStyleOf`

- packages/compartment-mapper/src/bundle-lite.js
Ref https://github.com/endojs/endo/pull/2707#discussion_r1953346697
Don't rely upon a primordial `Array.prototype[Symbol.iterator]`.
> fix(compartment-mapper): Make bundled code more robust against primordial replacement/manipulation

- packages/bundle-source/tsconfig.json
- packages/common/tsconfig.json
- packages/marshal/tsconfig.json
- packages/pass-style/tsconfig.json
Refs: #2712
Remove `maxNodeModuleJsDepth` which is no longer necessary.
One small step towards
- https://github.com/endojs/endo/issues/2712
None.
None.
None.
None.
None.
None.
> remove maxNodeModuleJsDepth

- packages/marshal/test/marshal-capdata.test.js
- packages/marshal/test/marshal-smallcaps.test.js
- packages/ses/test/error/aggregate-error-console-demo.test.js
- packages/ses/test/error/aggregate-error-console.test.js
- packages/ses/test/error/aggregate-error.test.js
Ref #2042
Ref #550
Some missed improvements related to https://github.com/endojs/endo/pull/2042#pullrequestreview-1894338425 .
> test(marshal,ses): Prefer test.skip over conditional early return

- packages/ses/NEWS.md
- packages/ses/docs/lockdown.md
- packages/ses/error-codes/SES_NO_EVAL.md
- packages/ses/src/commons.js
- packages/ses/src/eval-scope.js
- packages/ses/src/lockdown.js
- packages/ses/test/evalTaming-no-eval.test.js
- packages/ses/test/evalTaming-safe-eval.test.js
- packages/ses/test/evalTaming-unsafe-eval.test.js
- packages/ses/test/evalTaming-unsafeEval.test.js
- packages/ses/types.d.ts
Closes: #XXXX
Refs: #961 #2690 #2723
#961 deviated from our general convention that lockdown option values be kebob-case, instead adding `evalTaming:` option values `safeEval`, `unsafeEval`, `noEval`. (I approved #961 at the time, apparently without noticing this discrepancy.) This PR fixes those to be `safe-eval`, `unsafe-eval`, and `no-eval`. But to avoid breaking any old usage, this PR ensure the only names continue to work for now, but always commented in the code as "deprecated".
This PR does only that. Other changes to the relevant lockdown option or relevant lockdown options machinery are left to #2723 or #2690 respectively. I request that this PR go first, with those others adjusting to this one.
none
non
This PR simply changes the documentation to use the new names without ever …
> fix(ses): lockdown options should be kebob-case

- packages/nat/src/index.js
- packages/pass-style/src/makeTagged.js
- packages/patterns/NEWS.md
- packages/patterns/index.js
- packages/patterns/package.json
- packages/patterns/src/keys/merge-bag-operators.js
- packages/patterns/src/patterns/patternMatchers.js
- packages/patterns/src/types.js
- packages/patterns/test/patterns.test.js
Closes: #XXXX
Refs: #2002 #2008 #2113 #1739 https://github.com/Agoric/agoric-sdk/pull/10952
This PR adds a new `M.containerHas(elementPatt, positiveBigint)` matcher, and exported `containerHasSplit` function. This is motivated to support https://github.com/Agoric/agoric-sdk/pull/10952 , which introduces a minimal form of want pattern in terms of `M.containerHas`.
none
Might help due to early termination of the split operations, which https://github.com/Agoric/agoric-sdk/pull/10952 uses for `AmountMath.isGTE`.
Already doc-documents `M.containerHas` in the types.js file for `M`. That's probably good enough for this PR. The interesting documentation will be explaining want patterns in https://github.com/Agoric/agoric-sdk/pull/10952
Added tests for `M.containerHas`
The reason to postpone …
> feat(patterns): M.containerHas(el,n) to support want patterns

- packages/bundle-source/NEWS.md
- packages/bundle-source/demo/external-fs-transitive.js
- packages/bundle-source/demo/external-fs.js
- packages/bundle-source/src/zip-base64.js
- packages/bundle-source/test/external-fs.test.js
- packages/import-bundle/NEWS.md
- packages/import-bundle/src/index.js
- packages/import-bundle/test/bundle3.js
- packages/import-bundle/test/import-bundle.test.js
This PR allows `bundleSource` and `importBundle` to bundle files and import bundled files respectively in the case that
1. the source file depends on external dependencies (such as 'fs' and 'path') and
2. the bundle is created using the endoZipBase64 moduleFormat option
This functionality already existed in `@endo/compartment-mapper`, and this PR simply plumbs the importHook option to the bundleSource and importBundle APIs.
Any designs which depend upon code bundled with the endoZipBase64 moduleFormat to have no external dependencies will be broken. To my knowledge none exist.
None
The bundleSource documentation does not have a use case showing the importHook option.
See included tests.
None
Bundling with endoZipBase64 is now more permissive, so existing importBundle calls may fail in a …
> feat(bundle-source,import-bundle): Thread importHook option to endoZipBase64 moduleFormat.

- packages/patterns/src/patterns/patternMatchers.js
Rather than limiting the special behavior to `M.or(M.undefined(), other)`, also apply it to `M.or(undefined, other)` and to reversed-order analogs (i.e., `other`-first).
None known.
None known.
n/a
n/a
n/a
n/a
> feat(patterns): Expand special-casing of "optionality" patterns

- packages/ses/NEWS.md
Follow-up to: https://github.com/endojs/endo/pull/2723
Add news for [evalTaming](https://github.com/endojs/endo/blob/master/packages/ses/docs/lockdown.md#evaltaming-options)
> docs(ses): update news for evalTaming

- packages/compartment-mapper/src/node-modules.js
- packages/compartment-mapper/test/fixtures-shortest-path/README.md
- packages/compartment-mapper/test/fixtures-shortest-path/node_modules/app/index.js
- packages/compartment-mapper/test/fixtures-shortest-path/node_modules/app/package.json
- packages/compartment-mapper/test/fixtures-shortest-path/node_modules/gambadilegno/index.js
- packages/compartment-mapper/test/fixtures-shortest-path/node_modules/gambadilegno/package.json
- packages/compartment-mapper/test/fixtures-shortest-path/node_modules/goofy/index.js
- packages/compartment-mapper/test/fixtures-shortest-path/node_modules/goofy/package.json
- packages/compartment-mapper/test/fixtures-shortest-path/node_modules/paperino/index.js
- packages/compartment-mapper/test/fixtures-shortest-path/node_modules/paperino/package.json
- packages/compartment-mapper/test/fixtures-shortest-path/node_modules/pippo/index.js
- packages/compartment-mapper/test/fixtures-shortest-path/node_modules/pippo/package.json
- packages/compartment-mapper/test/fixtures-shortest-path/node_modules/topolino/index.js
- packages/compartment-mapper/test/fixtures-shortest-path/node_modules/topolino/package.json
- packages/compartment-mapper/test/map-node-modules.test.js
- scripts/mermaid-deptree.cjs
The `node_modules`-crawler in `@endo/compartment-mapper` is currently unstable. When there are multiple paths to a module, the "shortest path" to that module remains the first path that was found.
The first path that is found is non-deterministic.  As a result, a `CompartmentDescriptor.path` value can differ from run to run.
This fixes the problem: when a package location in the graph is encountered for the _second_ time (and every time thereafter), we recursively (and its dependency tree, if that too needs updating) check if it still has the shortest path, and update paths as appropriate within the graph.
A fixture in `packages/compartment-mapper/test/fixtures-shortest-path` shows an example of the structure necessary to trigger the original problem.  Previous to the change, this test …
> fix(compartment-mapper): fix crawling

- packages/compartment-mapper/src/node-modules.js
- packages/compartment-mapper/test/fixtures-shortest-path-cycle/README.md
- packages/compartment-mapper/test/fixtures-shortest-path-cycle/node_modules/app/index.js
- packages/compartment-mapper/test/fixtures-shortest-path-cycle/node_modules/app/package.json
- packages/compartment-mapper/test/fixtures-shortest-path-cycle/node_modules/gambadilegno/index.js
- packages/compartment-mapper/test/fixtures-shortest-path-cycle/node_modules/gambadilegno/package.json
- packages/compartment-mapper/test/fixtures-shortest-path-cycle/node_modules/goofy/index.js
- packages/compartment-mapper/test/fixtures-shortest-path-cycle/node_modules/goofy/package.json
- packages/compartment-mapper/test/fixtures-shortest-path-cycle/node_modules/paperino/index.js
- packages/compartment-mapper/test/fixtures-shortest-path-cycle/node_modules/paperino/package.json
- packages/compartment-mapper/test/fixtures-shortest-path-cycle/node_modules/pippo/index.js
- packages/compartment-mapper/test/fixtures-shortest-path-cycle/node_modules/pippo/package.json
- packages/compartment-mapper/test/fixtures-shortest-path-cycle/node_modules/topolino/index.js
- packages/compartment-mapper/test/fixtures-shortest-path-cycle/node_modules/topolino/package.json
- packages/compartment-mapper/test/map-node-modules.test.js
- scripts/mermaid-deptree.cjs
This fixes a bug introduced in #2769 which can lead to a "max call stack exceeded" exception.
And another that will potentially overwrite the entry node with a path if a cycle is encountered.
> fix(compartment-mapper): add missing arg to recursive call

- packages/compartment-mapper/NEWS.md
- packages/compartment-mapper/src/types/external.ts
This un-deprecates (de-deprecates?) the `dev` option to `mapNodeModules`. This flag was deprecated in `@endo/compartment-mapper` v1.2.0 in lieu of using the `conditions` option, but it was not removed. These two options were conflated with each other in an unintended way.
`dev` instructs `mapNodeModules` to consider `devDependencies` when mapping. `conditions` is for satisfying conditional exports.
Added a note to both options clarifying the situation.
n/a
n/a
Updated `NEWS.md`.
n/a
This change is documentation-only.
This change is documentation-only.
> fix(compartment-mapper): un-deprecate the dev flag

- packages/exo/test/heap-classes.test.js
- packages/exo/test/non-enumerable-methods.test.js
- packages/marshal/package.json
- packages/marshal/src/marshal-stringify.js
- packages/marshal/test/marshal-capdata.test.js
- packages/marshal/test/marshal-far-obj.test.js
- packages/marshal/test/marshal-smallcaps.test.js
- packages/marshal/test/marshal-stringify.test.js
- packages/marshal/test/rankOrder.test.js
- packages/marshal/tools/ava-full-order-eq.js
- packages/pass-style/src/iter-helpers.js
- packages/pass-style/src/passStyle-helpers.js
- packages/pass-style/src/remotable.js
- packages/pass-style/src/symbol.js
- packages/patterns/src/keys/checkKey.js
- packages/patterns/test/copyMap.test.js
Staged on https://github.com/endojs/endo/pull/2777
Closes: #XXXX
Refs: #XXXX
No more symbol named methods in remotable. Needed for #2777 to make sense. But a separate PR for now because it causes more errors to investigate.
> Does this change require or encourage significant increase in consumption of CPU cycles, RAM, on-chain storage, message exchanges, or other scarce resources? If so, can that be prevented or mitigated?
> Give our docs folks some hints about what needs to be described to downstream users. …
> fix(pass-style): no symbol named methods in remotables

- packages/marshal/index.js
- packages/marshal/src/rankOrder.js
- packages/patterns/src/keys/compareKeys.js
- packages/patterns/src/keys/keycollection-operators.js
Ref #2113
We want to discourage comparison of strings by UTF-16 code unit as implemented by relational operators.
None.
Includes a trivial (and separable) improvement to `sortByRank`.
None beyond `@deprecated`.
Covered by existing tests.
n/a
I don't think a NEWS.md update is warranted, but could be persuaded otherwise.
> refactor: Deprecate trivialComparator in favor of type-specific `compareNumerics`

- packages/ses/NEWS.md
- packages/ses/package.json
- packages/ses/scripts/hermes-transforms.js
- packages/ses/src/get-anonymous-intrinsics.js
- packages/ses/src/lockdown.js
- packages/ses/src/permits.js
- packages/ses/test/immutable-array-buffer.test.js
- yarn.lock
Closes: #XXXX
Refs: #XXXX
Now that the Immutable ArrayBuffer proposal is at 2.7 and looks likely to proceed to 3, and then on to 4 and the official language, we are now allowing ourselves to build on the shim to emulate it already being in the language. In this PR ses imports the shim (not just the ponyfill) and then permits it's additions as harmless for ses users.
We carefully designed the proposal to maintain our high security standards. Likewise, in our shim, an Immutable ArrayBuffer encapsulates a normal mutable ArrayBuffer. But it is careful not to mutate it or to let it escape. The shim is low fidelity in terms of what it must practically omit --- TypedArrays and DavaView backed by Immutable ArrayBuffers. But these omissions do not raise security hazards, only compat hazards. …
> feat(ses): ArrayBuffer.prototype.transferToImmutable

- packages/marshal/index.js
- packages/marshal/src/encodePassable.js
- packages/marshal/src/encodeToCapData.js
- packages/marshal/src/encodeToSmallcaps.js
- packages/marshal/src/rankOrder.js
- packages/marshal/test/encodePassable.test.js
- packages/marshal/test/marshal-stringify.test.js
- packages/pass-style/src/byteArray.js
- packages/pass-style/src/deeplyFulfilled.js
- packages/pass-style/src/passStyleOf.js
- packages/pass-style/src/typeGuards.js
- packages/pass-style/src/types.d.ts
- packages/pass-style/tools/arb-passable.js
- packages/patterns/src/keys/checkKey.js
- packages/patterns/src/keys/compareKeys.js
- packages/patterns/src/patterns/patternMatchers.js
- packages/patterns/src/types.js
Closes: #1331 
Refs: https://github.com/ocapn/ocapn/issues/5#issuecomment-1492778252 #2414 
Recognize Immutable ArrayBuffers, when also frozen, as the new pass-style `byteArray`. Add a branch for each of the dispatches on pass-style that must now understand byte-arrays as well. As of this PR, many of those additional branches are stubbed out with "not yet implemented" errors as placeholders.
The underlying shim implementation, if we're still using that, uses a normal mutable ArrayBuffer internally, but safely encapsulates it so nothing outside the shim can mutate it.
The underlying shim implementation helps us handle bulk binary data in a largely no-copy or minimal-copy manner.
Will add a new pass-style, so everywhere we enumerate all the pass-styles, we'll need to add byte-array.
Old …
> feat(pass-style,marshal): ByteArray, a new binary Passable type

- packages/marshal/src/types.test-d.ts
- packages/pass-style/index.js
- packages/pass-style/package.json
- packages/pass-style/src/deeplyFulfilled.js
- packages/pass-style/src/typeGuards.js
- packages/pass-style/src/types.d.ts
- packages/patterns/docs/marshal-vs-patterns-level.md
- packages/patterns/src/keys/checkKey.js
- packages/patterns/src/types.js
- yarn.lock
Closes: #XXXX
Refs: #XXXX
For describing Passables that correspond to OCapN Atoms, the terms around "primitive" because increasingly awkward because not all of these are (byteArray) or will be (symbol) represented by JS language-level primitives. Instead, they are/will be represented by JS objects. Thus, we adopt the OCapN name `Atom` instead. We still export the "Primitive*" type names, but deprecate them to remove them once we're past this transition.
We also fixed a few remaining bugs where we were using the JS-level `isObject` to partition Passable types between Atom and non-Atom. We now use `isAtom` instead.
Aside from the naming clarity and the bug fixes, none.
none
It will now be more natural to delegate much of the `@endo/pass-style` documentation to OCapN
We might need to …
> fix(pass-style): rename passable "Primitive" to ocapn "Atom"

- packages/compartment-mapper/src/import-hook.js
- packages/compartment-mapper/src/types/internal.ts
- packages/compartment-mapper/test/dynamic-require.test.js
- packages/compartment-mapper/test/fixtures-dynamic/node_modules/dynamic/index.js
- packages/compartment-mapper/test/fixtures-dynamic/node_modules/invalid-app/README.md
- packages/compartment-mapper/test/fixtures-dynamic/node_modules/invalid-app/good.js
- packages/compartment-mapper/test/fixtures-dynamic/node_modules/invalid-app/index.js
- packages/compartment-mapper/test/fixtures-dynamic/node_modules/invalid-app/package.json
- packages/compartment-mapper/test/fixtures-dynamic/node_modules/is-not-ok/README.md
- packages/compartment-mapper/test/fixtures-dynamic/node_modules/is-not-ok/index.js
- packages/compartment-mapper/test/fixtures-dynamic/node_modules/is-not-ok/package.json
- packages/compartment-mapper/test/fixtures-dynamic/node_modules/is-ok/README.md
- packages/compartment-mapper/test/fixtures-dynamic/node_modules/is-ok/index.js
`findRedirect`, which is part of `importNowHook`, is called when we encounter a dynamic require where the specifier is an absolute path.
Previous to this change, the `RedirectStaticModuleInterface` (a `ModuleDescriptor`) could contain an absolute path. Absolute paths are not generally assumed by `ses` or `@endo/compartment-mapper`. In the situation where the module referenced in the `RedirectStaticModuleInterface` itself imports _another_ package (via mutual recursion & trampolining), these assumptions were violated and we made an attempt to call `resolve()` (from the `node-module-specifier` module) using its absolute path as the referrer, which is explicitly disallowed by `resolve()`; it throws an exception.
To that end, we need to ensure that whatever `ModuleDescriptor` we return from …
> fix(compartment-mapper): specifier of module descriptor returned from findRedirect fixed

- packages/env-options/src/env-options.js
- packages/eventual-send/src/track-turns.js
- packages/ses/src/error/tame-console.js
- packages/ses/src/error/tame-error-constructor.js
- packages/ses/src/lockdown.js
- packages/ses/src/module-load.js
- packages/ses/src/reporting.js
- packages/ses/src/tame-domains.js
- packages/ses/src/tame-harden.js
- packages/ses/src/tame-locale-methods.js
- packages/ses/src/tame-regexp-constructor.js
Closes: #XXXX
Refs: https://github.com/endojs/endo/pull/1710
https://github.com/endojs/endo/pull/1710 enhanced `getEnvironmentOption` with an optional third argument listing all the other allowed choices aside from the default choice. Previously, we had only manual code to detect and complain of unrecognized environment option values. #1710 provides a more declarative form, and reuses the checking-and-complaining logic. However, following #1710 we did not retire much of the previous ad-hoc manual code, nor did we make enough use of this declarative alternative. This PR fixes that.
An advantage to the old ad-hoc manual style is that the enumeration of all possible alternatives was textually close to the dispatch on the alternative. This makes it easy to keep the two in sync. Thus, a …
> refactor(ses): getenv detects more errors

- packages/immutable-arraybuffer/index.js
- packages/immutable-arraybuffer/package.json
- packages/immutable-arraybuffer/shim-hermes.js
- packages/immutable-arraybuffer/src/limited-pony-for-hermes.js
- packages/immutable-arraybuffer/test/limited-pony-for-hermes.test.js
- packages/immutable-arraybuffer/test/shim-hermes.test.js
- packages/ses/scripts/hermes-transforms.js
- packages/ses/src/get-anonymous-intrinsics.js
- packages/ses/test/immutable-array-buffer.test.js
Refs: (https://github.com/endojs/endo/pull/2399) https://github.com/endojs/endo/pull/2400 https://github.com/endojs/endo/pull/2798
Rather than [excluding](https://github.com/endojs/endo/pull/2400/commits/75ea396de858d54b57c87999cca3c4ec3bedb98c) the `'@endo/immutable-arraybuffer/shim.js'` import in the Hermes SES shim
(since Hermes lacks `structuredClone`, `transfer`, private fields and `class` syntax),
here we introduce `'@endo/immutable-arraybuffer/shim-hermes.js'` - a limited version achieved without those.
TODO …
> feat(immutable-arraybuffer): sliceToImmutable Hermes ponyfill and shim

- packages/marshal/NEWS.md
- packages/marshal/index.js
- packages/marshal/src/marshal-justin.js
- packages/marshal/test/marshal-justin.test.js
- packages/patterns/test/qp-on-pattern.test.js
Closes: #XXXX
Refs: https://github.com/Agoric/agoric-sdk/pull/5401
We often need to see the deep contents of a Passable. Indeed, this was kicked off by a slack thread about wanting to quote
```js
M.splitRecord(
harden({
assetKind: M.or('nat', 'set', 'copySet', 'copyBag'),
decimalPlaces: M.and(M.gte(-100), M.lte(100)),
}),
)
```
This PR provides a `qp` function meaning "quote passable". You can use it where you'd use `q`. It produces a quasi-quoted Justin expression of the form in which the passable would be passed. For example, the `qp` of the above pattern is
```js
`makeTagged("match:splitRecord",  [
{
assetKind: makeTagged("match:or", [
"nat",
"set",
"copySet",
"copyBag",
]),
decimalPlaces: makeTagged("match:and", [
makeTagged("match:gte", -100),
makeTagged("match:lte", 100),
]),
},
])` …
```
> feat(marshal): passable to quasi-quoted Justin expr

- packages/marshal/src/marshal-justin.js
Closes: #XXXX
Refs: https://github.com/endojs/endo/pull/2799#discussion_r2085652080
At https://github.com/endojs/endo/pull/2799#discussion_r2085652080 @dckc suggested
>  I suggest including it in the comment.
I intended to. But somehow I resolved it before actually doing this, causing me to miss it when evaluating if I should just merge-and-squash #2799. This PR corrects that omission.
Minor internal comment only. It should not have any other implications.
> doc(marshal): adds missing comment from #2799 review

- packages/module-source/src/babel-plugin.js
- packages/module-source/test/module-source.test.js
Closes: #2094
Modifies `babel-plugin.js` to allow for defaults when destructuring.
The problem noted in #2094 was affecting _all_ such assignments, not just those which are exported.
I'm _extremely suspicious_ of this change because it was so easy that it _must_ be wrong.
If there is a security-related reason for not implementing this, I don't know what it is.
no
n/a
Could throw this in a test fixture, I suppose.
Well, it allows for parsing code containing destructuring assignments with defaults, so take that as you will.
May want a `NEWS.md` entry? I'm honestly surprised somebody isn't complaining about this already.
> fix(module-source): allow defaults in destructuring assignments

- packages/lockdown/commit-debug.js
- packages/lockdown/pre.js
- packages/ses-ava/test/raw-ava-reject.test.js
- packages/ses-ava/test/raw-ava-throw.test.js
- packages/ses-ava/test/ses-ava-reject.test.js
- packages/ses-ava/test/ses-ava-throw.test.js
- packages/ses/NEWS.md
- packages/ses/docs/lockdown.md
- packages/ses/docs/reference.md
- packages/ses/src/error/tame-v8-error-constructor.js
- packages/ses/src/lockdown.js
- packages/ses/types.d.ts
Refs: #2359 
Added two new `stackFiltering:` options
- `'omit-frames'` -- Only omit likely uninteresting frames. Keep original paths.
- `'shorten-paths'` -- Only shorten paths to text likely clickable in an IDE
This fills out the matrix of what should have been orthogonal options.
The existing `'concise'` setting both omits likely uninteresting frames and
shortens their paths. The existing `'verbose'` setting does neither.
The path shortening caused by either `'concise'` or `'shorten-paths'` is also enhanced with two new transformations, in order to make these paths easily and usefully clickable in an IDE like vscode.
- We would already shorten, for example
```
'Object.bar (/vat-v1/.../eventual-send/test/deep-send.test.js:13:21)'
```
to
```
'Object.bar …
```
> fix(ses,lockdown): make filenames in stacktraces clickable

- packages/compartment-mapper/src/node-modules.js
- packages/compartment-mapper/test/fixtures-missing-optional-peer-dependencies/README.md
- packages/compartment-mapper/test/fixtures-missing-optional-peer-dependencies/node_modules/app/index.js
- packages/compartment-mapper/test/fixtures-missing-optional-peer-dependencies/node_modules/app/package.json
- packages/compartment-mapper/test/fixtures-optional-peer-dependencies/README.md
- packages/compartment-mapper/test/fixtures-optional-peer-dependencies/node_modules/app/index.js
- packages/compartment-mapper/test/fixtures-optional-peer-dependencies/node_modules/app/package.json
- packages/compartment-mapper/test/fixtures-optional-peer-dependencies/node_modules/paperina/index.js
- packages/compartment-mapper/test/fixtures-optional-peer-dependencies/node_modules/paperina/package.json
- packages/compartment-mapper/test/map-node-modules.test.js
_May be controversial!_
This adds dependency names found in `peerDependenciesMeta` which are otherwise unspecified in other dependency fields to the list of all dependencies so that a `CompartmentDescriptor` will be created if the package exists.
~~We will prefer any spec already provided in a dependency field instead of the default (which is `*` for lack of a better value).~~
~~A variation on this PR would be to use the version from `devDependencies` if present (regardless of the `dev` flag) and then fall back to `*`. _Most_ packages tend to include `peerDependencies` in `devDependencies`.~~
> [!IMPORTANT]
>
> I noticed that `graphPackage()` was storing the specification for each dependency but this data was unused. I changed the data structures to avoid doing this.
n/a
no
I don't think …
> fix(compartment-mapper): handle invalid peer dependencies

- CONTRIBUTING.md
- packages/benchmark/package.json
- packages/skel/NEWS.md
- packages/skel/README.md
- packages/test262-runner/package.json
- scripts/create-package.sh
Document package creation in CONTRIBUTING.md and update files in package "skel" so scripts/create-package.sh creates a directory that requires minimal boilerplate editing.
n/a
n/a
This could be extended to cover new-package _publishing_ as well, but I'll have to lean on @kriskowal for those details.
Verified manually to create a new package for an upcoming PR.
n/a
n/a
> chore(skel): Improve the state of nascent packages

- packages/ses/src/module-load.js
Much less types but better ROI than https://github.com/endojs/endo/pull/2808
Internals of job queues are not typed precisely, but what this gives us and previous didn't is TS complaining when 
`enqueueJob(memoizedLoadWithErrorAnnotation, [ wrong, argz, go, here ]`
> chore(ses): add typings to job queues to ensure arguments match

- packages/ses/src/error/tame-v8-error-constructor.js
```diff
ℹ t.log (Error#1)
ℹ Error#1: outer t.log containing (Error#2)
ℹ   at makeError (file:///tmp/censor-ses-ava/ses-ava-log.test.js:6:17)
at file:///tmp/censor-ses-ava/ses-ava-log.test.js:10:18
-        at logErrorFirst (file:///tmp/endo/packages/ses-ava/src/ses-ava-test.js:97:14)
-        at wrappedFunc (file:///tmp/endo/packages/ses-ava/src/ses-ava-test.js:217:16)
at async Promise.all (index 0)
ℹ Nested error under Error#1
ℹ   Error#2: inner t.log REDACTED
ℹ      at makeError (file:///tmp/censor-ses-ava/ses-ava-log.test.js:5:27) 
at file:///tmp/censor-ses-ava/ses-ava-log.test.js:10:18 
-           at logErrorFirst (file:///tmp/endo/packages/ses-ava/src/ses-ava-test.js:97:14) 
-           at wrappedFunc (file:///tmp/endo/packages/ses-ava/src/ses-ava-test.js:217:16) 
at async …
```
> feat(ses): Include ses-ava in stack frame filtering

- .github/workflows/ci.yml
- ~~Pinned all actions to avoid certain classes of vulnerabilities.~~
- Pinned deps are best maintained automatically by something like Renovate, but given `actions/setup-node` was still at v3, I don't pinning will necessarily incur more maintenance burden if we choose to maintain it manually.
- See https://www.wiz.io/blog/github-action-tj-actions-changed-files-supply-chain-attack-cve-2025-30066
- Attempt to run against Node.js v22.x in various places (I'll revert this if stuff is still broken)
- Remove invalid syntax
- `fail-fast` cannot be used if there is no matrix
- `path` is an invalid input to `actions/setup-node`
I did not implement the following changes, but I would recommend doing so:
- The `cover` and `viable-release` jobs probably don't need to be run more than once:
- `cover` …
> chore(ci): workflow hygiene

- CONTRIBUTING.md
- packages/panic/CHANGELOG.md
- packages/panic/package.json
- packages/skel/package.json
- scripts/create-package.sh
- yarn.lock
Fixes #2816
Updates create-package.sh to better detect BSD `sed` (the old method was disrupted by bash option "pipefail" and a script was not sufficiently portable). Also mentions package.json field "private" in CONTRIBUTING.md as requested, and better aligns the skel package.json with the output of create-package.sh.
> fix(scripts): Better detect and accommodate BSD sed in create-package.sh

- packages/compartment-mapper/src/import-hook.js
- packages/compartment-mapper/src/link.js
- packages/compartment-mapper/src/types/internal.ts
- packages/compartment-mapper/test/dynamic-require.test.js
- packages/compartment-mapper/test/fixtures-dynamic/node_modules/missing-app/README.md
- packages/compartment-mapper/test/fixtures-dynamic/node_modules/missing-app/index.js
- packages/compartment-mapper/test/fixtures-dynamic/node_modules/missing-app/package.json
- packages/compartment-mapper/test/fixtures-dynamic/node_modules/missing-optional/README.md
- packages/compartment-mapper/test/fixtures-dynamic/node_modules/missing-optional/main.js
- packages/compartment-mapper/test/fixtures-dynamic/node_modules/missing-optional/package.json
Closes: #2819
This adds support for deferred errors to the `importNowHook` implementation. In practice, that means _dynamically-required packages may now attempt to load missing optional dependencies_ without blowing up at load time.
To avoid algorithm divergence, I created a factory function `makeDeferError()` which returns a `deferError()` function that both `makeImportHook()` and `makeImportNowHook()` use. `makeImportNowHook` now requires a `shouldDeferError` option, like `makeImportHook`.
n/a
n/a
n/a
I added a test
I don't believe `makeImportNowHook` is a public API, so there should be no compatibility issues.
This is just a bugfix.
> fix(compartment-mapper): handle missing optional packages in dynamically-required modules

- packages/benchmark/package.json
- packages/bundle-source/package.json
- packages/captp/package.json
- packages/cli/package.json
- packages/common/package.json
- packages/daemon/package.json
- packages/errors/package.json
- packages/eslint-plugin/package.json
- packages/evasive-transform/package.json
- packages/eventual-send/package.json
- packages/far/package.json
- packages/immutable-arraybuffer/package.json
- packages/init/package.json
- packages/lockdown/package.json
- packages/marshal/package.json
- packages/ocapn/package.json
- packages/panic/package.json
- packages/promise-kit/package.json
Refs: #2821
* Add *.tsbuildinfo to `"postpack": "git clean -f ..."` scripts (cf. https://github.com/endojs/endo/pull/2821#discussion_r2103392181 )
* Remove lint-check package.json scripts (they are redundant aliases for `lint`)
None known.
n/a
I could not find any existing references to the `lint-check` scripts.
n/a
n/a
n/a
> chore: Improve package.json uniformity

- .github/workflows/typedoc-gh-pages.yml
This seems to be failing on `master`. Upgrading to `actions/deploy-pages@v4` means we [also have to upgrade](https://github.com/actions/deploy-pages/releases/tag/v4.0.0) to `actions/upload-pages-artifact@v3` and add a new permission.
> chore(ci): attempt to fix bust deploy-pages workflow

- packages/daemon/src/daemon.js
- packages/daemon/src/host.js
- packages/daemon/src/types.d.ts
- packages/daemon/test/endo.test.js
The pet dæmon will revive all of the objects in the PINS special directory whenever it restarts. This is a more general case of NETS, which must also be revived on restart so that they can establish listener sockets, but are more deeply integrated in peer names. The test included illustrates the usage through API.
> feat(daemon): PINS restored on startup

- packages/immutable-arraybuffer/index.js
Closes: #XXXX
Refs: https://github.com/endojs/endo/pull/2785
The Immutable ArrayBuffer shim, on non-Hermes, relies on the existence of *either* a global `structuredClone` or `Array.prototype.transfer`. However, I forgot to capture early the global `structuredClone` into a module-local one, and to then use that repeatedly. MetaMask scuttling deleted the global `structuredClone`, running headlong into my mistake on platforms (Node 18 and Node 20) that do not also have `Array.prototype.transfer`.
This PR fixes that mistake, capturing `structuredClone` early, and then using the resulting module-local one.
The bug this PR fixes was a security hazard.
none
none
In theory, we should add scuttling as an orthogonal dimension of our platform testing matrix. However that is rather expensive for …
> fix(immutable-arraybuffer): capture structuredClone early

- packages/path-compare/CHANGELOG.md
- packages/path-compare/LICENSE
- packages/path-compare/README.md
- packages/path-compare/SECURITY.md
- packages/path-compare/index.js
- packages/path-compare/package.json
- packages/path-compare/src/index.js
- packages/path-compare/test/index.test.js
- packages/path-compare/tsconfig.build.json
- packages/path-compare/tsconfig.json
- yarn.lock
This extracts the `pathCompare` (~~and `stringCompare`~~ `stringCompare` is present, but not exposed as a public API) functions from `@endo/compartment-mapper` so that they may be used directly by the ecosystem.
Ref: #2789 for use of this package
none
n/a
n/a
"We" wrote new tests and added them.
n/a
n/a
> feat(path-compare): create @endo/path-compare

- packages/compartment-mapper/package.json
- packages/compartment-mapper/src/compartment-map.js
- packages/compartment-mapper/src/digest.js
- packages/compartment-mapper/src/node-modules.js
- yarn.lock
This removes the code copied from `@endo/compartment-mapper` to create `@endo/path-compare` and uses `@endo/path-compare` instead.
Ref: #2787
> chore(compartment-mapper): use @endo/path-compare

- packages/pass-style/src/byteArray.js
- packages/ses/test/error/assert-log.test.js
- packages/ses/test/error/tame-console-unfilteredError.test.js
- packages/ses/test/error/tame-console-unsafe-unfilteredError.test.js
- packages/ses/test/error/tame-console-unsafe-unsafeError-unfilteredError.test.js
- packages/ses/test/error/tame-console-unsafe-unsafeError.test.js
- packages/ses/test/error/tame-console-unsafe.test.js
- packages/ses/test/error/tame-console-unsafeError.test.js
- packages/ses/test/error/tame-console.test.js
- packages/ses/types.test-d.ts
Closes: #XXXX
Refs: https://github.com/Agoric/agoric-sdk/pull/11458
Whenever we say, for example, 
```js
assert.fail(X`...`)
```
we should instead say
```js
Fail`...`
```
This PR is a refactor doing exactly this.
none
none
none
Most of the uses were in tests.
none
none
> refactor: shorten used failure idiom

- packages/immutable-arraybuffer/README.md
- packages/immutable-arraybuffer/index.js
- packages/marshal/src/encodePassable.js
- packages/pass-style/src/deeplyFulfilled.js
- packages/patterns/src/patterns/patternMatchers.js
- packages/patterns/src/types.js
- packages/patterns/test/pattern-limits.test.js
- packages/ses/src/permits.js
Closes: #XXXX
Refs: #2248 
While working on #2248, I ran into previously undetected bugs due to confusion between `'bytes'` and `'byteArray'` as the name for passable Immutable ArrayBuffers. This PR is extracted from the portions of #2248 in which I fix this and test the fix.
The bug manifested in trying to test the pattern-based limits enforcement for byteArrays. The inability to enforce those limits create both security and scaling hazards. This PR fixes those hazards.
`M.bytes()` should no longer appear in any docs. Use `M.byteArray()` instead.
Had previous PRs tested the limits enforcement, this bug would have been found and fixed earlier. Mea culpa. This PR does add those tests.
If there was previous code using `M.bytes()`, or storing the matcher object it produces, then we'd have a …
> fix(pass-style): better byteArray support

- packages/path-compare/README.md
- packages/path-compare/src/index.js
Refs: #2787
Applies suggestions from https://github.com/endojs/endo/pull/2787#pullrequestreview-2812907861 .
> refactor(path-compare): Improve documentation and reduce implementation code size

- packages/pass-style/src/byteArray.js
The most recent releases of ses and pass-style introduce support for immutable ArrayBuffer with a pass-style of “byteArray” in anticipation of the upcoming JavaScript standard. Although versions of pass-style and ses that were published together work together, pass-style on older versions of ses on platforms that predate immutable ArrayBuffer (virtually all), pass-style does not tolerate the non-existence of immutable `ArrayBuffer.prototype.transferToImmutable` whether shim or native. This change makes pass-style suitable on all previously supported platforms.
https://github.com/endojs/endo/releases/tag/ses%401.13.0
> fix(pass-style): Tolerate non-existence of immutable ArrayBuffer

- packages/ses/NEWS.md
- packages/ses/README.md
- packages/ses/src/compartment.js
- packages/ses/src/module-load.js
- packages/ses/test/import-now-hook.test.js
- packages/ses/test/import.test.js
- packages/ses/types.d.ts
Refs: #2820
This adds the `noAggregateLoadErrors` flag to the `Compartment` constructor in its `CompartmentOptions`. The default value of this flag is `false`, which retains the current behavior.
If `true`, this will cause the first error encountered during load (`load` or `loadNow`) to be thrown or rejected.
> ~~A second PR (or subsequent commit in this PR) will thread this flag through `@endo/compartment-mapper` where it can more easily be provided (e.g., to `importLocation()`, `loadFromMap()`, etc.).~~
> This won't be strictly necessary for `@lavamoat/node`'s use-case, so I'd rather just kick the can down the road until it's needed.
none that I'm aware of
n/a
The `aggregateLoadErrors` flag should be documented w/ the rest of `CompartmentOptions`.
This has tests which cover both `load` …
> feat(ses): add noAggregateLoadErrors flag

- packages/patterns/NEWS.md
- packages/patterns/src/patterns/patternMatchers.js
- packages/patterns/test/patterns.test.js
Closes: #XXXX
Refs: #2799 
#2799 added a new `q`-like quoter named `qp`, for "quote passable", that renders any value into Justin source text. This was specifically motivated for displaying patterns within error messages in a readable and informative manner.
The `@endo/patterns` package itself formulates many error messages to explain why a specimen did not match a pattern. Some of these message include quoted forms of nested patterns. But those were still quotes with `q`, leading @dckc to report still seeing error messages like
```
Error {
message: '... - Must match one of ["[match:splitRecord]","[match:splitRecord]"]',
}
```
This PR changes the quoting of nested errors to use `qp` instead, so a `[match:splitRecord]` might instead render as
```js
`makeTagged("match:splitRecord", [
{ …
```
> fix(patterns): use `qp` for nested pattern error messages

- packages/base64/src/common.js
- packages/base64/test/main.test.js
Closes: #XXXX
Refs: #2844 
https://github.com/endojs/endo/pull/2844 currently depends on `@endo/base64` for base64 encoding and decoding. @kriskowal asked that it be changed to use a hex encoding instead, for which changes to `@endo/base64` would be irrelevant. So I'm capturing in this PR the minor improvement I made to that package while working on #2844 .
exporting mutable data (`monodu64`) from a module is a security hazard. It is not exported from the package, so this is only a hazard, not a vulnerability. In this case there was zero reason not to freeze `monodu64`, so this PR does, leaving us one less security hazard to worry about.
none
none
Aside from `monodu64`, the other changes to this PR is to expand the test in ways I noticed while working on #2844 .
none
none
> refactor(base64): minor improvements

- packages/marshal/src/marshal-justin.js
- packages/marshal/test/marshal-justin.test.js
- packages/marshal/tools/marshal-test-data.js
* Improve JSDoc comments for `roundTripPairs` and `jsonJustinPairs`
* Improve test coverage for indented Justin by removing non-semantic whitespace
* Improve the readability of `decodeToJustion` slot rendering
n/a
n/a
See above.
See above.
n/a
n/a
> refactor(marshal): Cleanup some Justin code

- packages/marshal/NEWS.md
- packages/marshal/test/string-rank-both-order.test.js
- packages/marshal/test/string-rank-unicode-order.test.js
- packages/marshal/test/string-rank-utf16-order.test.js
- packages/marshal/tools/marshal-test-data.js
- packages/patterns/NEWS.md
- packages/patterns/test/string-key-unicode-order.test.js
Refs: #2873
* Differentiate string rank order tests by name
* DRY out data and functions for string rank order tests
* Accommodate implementation-defined order of `sort(comparator)` comparisons
* Clarify in NEWS.md that ENDO_RANK_STRINGS is not limited to on/off
n/a
n/a
n/a
See above
n/a
n/a
> chore: Clean up after #2873

- packages/exo/src/exo-tools.js
- packages/marshal/src/encodeToCapData.js
- packages/marshal/src/encodeToSmallcaps.js
- packages/marshal/src/marshal.js
- packages/pass-style/src/passStyle-helpers.js
- packages/pass-style/src/remotable.js
- packages/pass-style/src/safe-promise.js
- packages/patterns/src/patterns/patternMatchers.js
- packages/ses/src/cauterize-property.js
- packages/ses/src/commons.js
- packages/ses/src/enable-property-overrides.js
- packages/ses/src/error/assert.js
- packages/ses/src/global-object.js
- packages/ses/src/intrinsics.js
- packages/ses/src/make-hardener.js
- packages/ses/src/permits-intrinsics.js
- packages/ses/src/scope-constants.js
- packages/ses/src/tame-regenerator-runtime.js
Closes: #XXXX
Refs: #1627 
Replaces #1627 
Starting with Node 16.9, `Object.hasOwn` is supported and does what our hand rolled `hasOwnPropertyOf` or `objectHasOwnProperty` did. This PR changes all uses to use `hasOwn` instead. However, for the sake of compat, it only deprecates the old exports. It does not delete them.
Reviewers, `objectHasOwnProperty` is not exported from ses. Should I delete it instead of deprecating it?
none
none
one less thing to document
none
none, as long as all platforms we still support already provide `Object.hasOwn`.
none
> refactor: `hasOwn` rather than `hasOwnPropertyOf` or `objectHasOwnProperty`

- CONTRIBUTING.md
This change documents some minor changes that have accumulated to our release process since we began posting release notes and a step was obviated by the last Lerna upgrade.
> chore: Update release instructions for release notes and such

- packages/compartment-mapper/test/fixtures-implicit-reexport/direct.js
- packages/compartment-mapper/test/fixtures-implicit-reexport/index.js
- packages/compartment-mapper/test/fixtures-implicit-reexport/indirect.js
- packages/compartment-mapper/test/fixtures-implicit-reexport/package.json
- packages/compartment-mapper/test/implicit-reexport.test.js
This is an additional test that verifies that we have already taken into due consideration the case of importing and exporting a mutable binding.
> test(compartment-mapper): Verify implicit reexport propagation

- packages/compartment-mapper/src/parse-cjs-shared-export-wrapper.js
- packages/compartment-mapper/test/cjs-compat.test.js
- packages/compartment-mapper/test/fixtures-cjs-compat/node_modules/app/index.js
- packages/compartment-mapper/test/fixtures-cjs-compat/node_modules/exports-shenanigans/default-exports.js
- packages/compartment-mapper/test/scaffold.js
- packages/compartment-mapper/test/test.types.d.ts
This fixes a situation where a module which uses `Object.defineProperty` to define its own `default` property. Previously, the CJS parser wrapper erroneously overwrote the property with the value of `default.default` (which, practically, is often `undefined`).
Example:
```js
const a = (exports.a = {});
Object.defineProperty(exports, 'default', {
get: () => a,
enumerable: true,
});
```
In the above, `a` would be exported, but `default` would be lost.
This more accurately mimics Node.js' behavior.
The problem was originally detected in `@babel/core` which uses this pattern in its CJS distfiles.
* * *
- Also adds types for the scaffolding harness. 
n/a
n/a
n/a
Test added.
Improves ecosystem compat.
n/a
> fix(compartment-mapper): do not blast named default exports in CJS

- packages/ses/src/commons.js
- packages/ses/test/_delete_hasOwn.js
- packages/ses/test/hasOwn-shim.test.js
Closes: https://github.com/endojs/endo/issues/2930
Refs: #XXXX
`Object.hasOwn` is supported on all JS engine versions that Endo officially supports, such as Node 18. Thus, technically, Endo should not need to cope with the absence of `Object.hasOwn`. However, as https://github.com/endojs/endo/issues/2930 reports, this absence seems to be the only impediment to running on the version of Safari/JSC shipping on iOS 15.3 or earlier. Fortunately, `Object.hasOwn` is trivial to shim, so this PR trivially shims it when it is absent.
Supporting such ancient engines makes it more likely for people to run ses on such ancient engines, which is indeed the point of this PR. However, ancient engines are also more likely to violate conformance with modern JS in other ways that may violate the ses …
> feat(ses): repair missing "hasOwn"

- packages/ses/scripts/bundle.js
Previously, running `yarn build:vanilla` would print something like:
```
❯ yarn build
-- Building 'undefined' version of SES --
Bundle size: 476660 bytes
Minified bundle size: 217577 bytes
Copied ./types.d.ts to ./dist/types.d.cts
-- Building 'hermes' version of SES --
Bundle size: 476693 bytes
Copied ./types.d.ts to ./dist/types.d.cts
```
Now it reads `vanilla` instead of `undefined`.
> chore(ses): fix vanilla build script output

- packages/ses/docs/lockdown.md
- packages/ses/src/reporting.js
- packages/ses/test/error/_throws-and-logs.js
Closes: #2908
Refs: #636 #944 #945 https://github.com/nodejs/node/pull/59456
Due to timing, reporter.js runs before lockdown replaces the system console with our causal console. Thus, when `makeReporter` makes a reporter that uses some global console, it uses the platform's original global console rather than the causal console. I don't know if this was purposeful or good enough at the time, so I don't know whether this PR is a workaround or a proper fix. In any case, it fixes the case of immediate interest by using the current global console to report rather than the original one.
@gibson042 checked below and found that the `console` property of the global of the start compartments remains mutable after lockdown. This is a security hazard, but is consistent with our stance on the …
> fix(ses): to workaround #2908 use current console

- packages/exo/src/exo-makers.js
Fixes: #2937
agoric-sdk integration PR: https://github.com/Agoric/agoric-sdk/pull/11756
Use `ExoClassMethods` for `makeExo`, in alignment with the implementation internally leveraging `defineExoClass`.
None known.
n/a
Nothing specific.
Should be covered by existing tests, but I'm open to ideas for more coverage.
I suspect that internal method calls for non-class exos are probably rare, which is why this went undetected. But if anything is affected, it will probably invalidate undesirable `@ts-expect-error` comments.
> fix(exo): Correct the typing for `makeExo` methods

- .github/workflows/ci.yml
This adds `macos-15` (macOS Sequoia) to the CI matrix for the `test` job in the `ci.yml` workflow.
I have reason to suspect something is amiss in `@endo/module-source`, but this may be a bug in the VM image.
> chore(ci): run tests on macOS Sequoia

- packages/exo/src/exo-tools.js
- packages/exo/test/exo-wobbly-point.test.js
- packages/patterns/NEWS.md
- packages/patterns/index.js
- packages/patterns/src/patterns/getGuardPayloads.js
Closes: #XXXX
Refs: https://hackmd.io/@rekmarks/H1X6VtP5eg#
https://hackmd.io/@rekmarks/H1X6VtP5eg# @rekmarks explains the need to express that one interface guard effectively extends another. In a slack thread, @michaelfig explains how all we need is a helper that can extract the method guards from an super/base interface guard which can then be used with `...` when defining a sub/derived interface guard. Revising the name to fit this PR, @michaelfig 's pattern is
```js
const I2 = M.interface('I2', {
...getNamedMethodGuards(I1),
doMore: M.call().returns(M.any()),
});
```
By putting the `...` first, the sub/derived interface guard can override "inherited" interface guards as well as adding new ones.
Note that this ignores symbol-named method guards. This feature is deprecated anyway, and …
> feat(patterns): helper for interface guard inheritance

- packages/errors/NEWS.md
- packages/errors/index.js
- packages/marshal/src/marshal-justin.js
- packages/ses/NEWS.md
- packages/ses/src/error/assert.js
- packages/ses/src/error/stringify-utils.js
- packages/ses/src/error/types.js
- packages/ses/test/error/assert-log.test.js
- packages/ses/types.d.ts
...as the culmination of general cleanup.
* Make `assert` an arrow function, resolving a TODO
* Rename StringablePayload to Stringable
* Rename HiddenDetails to DetailsParts
* Improve parameter/variable names
* Improve type documentation and examples
* Add `assert.makeError` and deprecate `assert.error` as an alias
* Add an `@endo/errors` export of `assert.details` with its own name
None known.
n/a
If accepted, [agoric-sdk use of `assert.error`](https://github.com/search?q=repo%3AAgoric%2Fagoric-sdk+%22assert.error%22&type=code) should be replaced with `assert.makeError`.
Existing coverage is sufficient.
`assert.error` is deprecated, but retained as an alias of `assert.makeError` to support existing code.
NEWS.md was updated to document the change.
> feat(ses): Add assert.makeError and deprecate assert.error as an alias

- packages/ocapn/src/captp/captp-engine.js
- packages/ocapn/src/client/index.js
- packages/ocapn/src/client/ocapn.js
- packages/ocapn/src/client/types.js
- packages/ocapn/src/client/util.js
- packages/ocapn/src/codecs/descriptors.js
- packages/ocapn/src/codecs/operations.js
- packages/ocapn/src/codecs/passable.js
- packages/ocapn/src/codecs/subtypes.js
- packages/ocapn/src/codecs/util.js
- packages/ocapn/src/cryptography.js
- packages/ocapn/src/netlayers/tcp-test-only.js
- packages/ocapn/src/syrup/codec.js
- packages/ocapn/src/syrup/js-representation.js
- packages/ocapn/test/client.test.js
- packages/ocapn/test/codecs/_codecs_util.js
- packages/ocapn/test/codecs/components.test.js
- packages/ocapn/test/codecs/descriptors.test.js
- packages/ocapn/test/codecs/operations.test.js
- packages/ocapn/test/codecs/passable.test.js
- packages/ocapn/test/cryptography.test.js
- packages/ocapn/test/handoffs.test.js
- packages/ocapn/test/syrup/codec.test.js
A minor refactor to streamline types.
> refactor(ocapn): Use new tsdoc imports instead

- .yarnrc
- .yarnrc.yml
- package.json
- yarn.lock
In order to generally reduce vulnerability to npm install script attacks, this change adopts various best practices and tools for managing scripts including yarn configuration that prevents these scripts from running in general, a canary to detect misconfiguration and fail fast, and the `allow-scripts` utility from LavaMoat in the event we need to run postinstall.
> chore: Disallow install scripts by default
