packages/compartment-shim/src/globalObject.js
packages/compartment-shim/test/integration/globalObject-properties.test.js
packages/compartment-shim/test/unit/globalObject.test.js

Added tests to guard behavior.
https://github.com/Agoric/SES-beta/issues/33

Fix globalThis tests

---

packages/harden/README.md
packages/harden/src/anonIntrinsics.js
packages/harden/src/buildTable.js
packages/harden/src/whitelist.js
packages/lockdown-shim/src/main.js
packages/ses/demos/challenge/README.md
packages/ses/docs/secure-coding-guide.md
packages/ses/docs/source/api.md
packages/ses/docs/source/api.rst
packages/ses/docs/source/draft-standalone-spec.md
packages/ses/docs/source/draft-standalone-spec.rst

As discussed in:
https://github.com/Agoric/SES-shim/issues/127

Replace "primordial" terminology with adjective-"intrinsic"

---

packages/compartment-shim/src/make-functionConstructor.js

According to:
https://github.com/Agoric/SES-shim/issues/200

Assert Function.__proto__ identity across all compartments

---

packages/ses/NEWS.md
packages/ses/docs/SES-shim-2.0.md
packages/ses/package.json

Update the news and release in development.

SES back to development with v0.7.1+1-dev

---

packages/ses/src/tame-global-reg-exp-object.js
packages/ses/test/tame-global-reg-exp-object.test.js

239 fix regexp species

---

packages/ses/src/intrinsic-names.js
packages/ses/src/tame-function-constructors.js
packages/ses/src/whitelist-intrinsics.js

just whitespace, typos, and such

fix(ses): comments

---

packages/ses/test/compartment.test.js

Fixes #248
Or rather, demonstrates that #248 was a misunderstanding and this is
working as expected.

fix(ses): transform is an object with a rewrite method

---

packages/harden/index.d.ts
packages/harden/package.json

Hi @kriskowal, can you please land this and publish the new @agoric/harden 0.0.5 to NPM?
It's necessary to begin adding Typescript support to Zoe.

Add index.d.ts to published harden package

---

packages/harden-integration-test/package.json
packages/harden/package.json
packages/make-hardener-integration-test/package.json
packages/make-hardener/package.json
packages/ses/package.json

This change affects only packages that have a build step at this time.

fix: Add pre-publish build step

---

packages/ses/src/make-eval-function.js
packages/ses/src/make-function-constructor.js
packages/ses/test/lockdown.test.js

This is a preliminary change to decouple Compartment and lockdown. #259

Allow privileged Compartments before lockdown

---

CONTRIBUTING.md

A couple minor adjustments to line up with conventional commits and patterns established by @warner.

fix: Release process details

---

packages/make-importer/README.md
packages/make-importer/src/importer.js
packages/ses/NEWS.md
packages/ses/README.md
packages/ses/src/compartment-shim.js
packages/ses/src/intrinsic-names.js
packages/ses/src/intrinsics-global.js
packages/ses/src/main.js
packages/ses/src/module-link.js
packages/ses/src/module-load.js
packages/ses/src/whitelist.js
packages/ses/test/import-commons.js
packages/ses/test/module-static-record.test.js
packages/transform-module/README.md

To make the name consistent with the current Compartment proposal.
Fixes #299

fix(ses, transform-module)!: Fix StaticModuleRecord name

---

packages/ses/src/lockdown-shim.js

Fixes #326 
Removes support for old noTame options, which we can't merge until after https://github.com/Agoric/agoric-sdk/pull/1128 is merged.
As described in #326, subsequent calls to `lockdown` don't need to agree exactly. Only the options provided need to agree exactly. Absence implies agreement with the status quo, whatever that is.

fix: remove deprecated noTame options

---

package.json
packages/endo/LICENSE
packages/endo/REMOVEME.js
packages/endo/package.json
yarn.lock

This change includes the mechanical changes needed to scaffold Endo.

feat(endo): Project scaffold

---

packages/ses/src/enablements.js

fix(ses): Aliasing true to t did not improve readability

---

packages/ses/src/enablements.js
packages/ses/src/whitelist-intrinsics.js

fix(ses): Spelling errors

---

packages/ses/docs/source/getting-started.md

See https://github.com/Agoric/SES-shim/issues/23

Remove obsolete text about Web Workers and Realms

---

packages/ses/NEWS.md
packages/ses/package.json

Adds index.d.ts to the list of files that are archived for the next releasee.

feat(ses): Prepare to publish with TypeScript definitions

---

packages/ses/src/compartment-shim.js
packages/ses/src/global-object.js
packages/ses/src/lockdown-shim.js
packages/ses/src/lockdown.js
packages/ses/test/global-object.test.js

This is a small change in preparation of layering SES. #403

fix(ses): Unravel compartment/lockdown import cycle

---

packages/ses/src/compartment-shim.js
packages/ses/src/module-load.js

Prior to this change, the Compartment constructor translated the module map into aliases.  After this change, the compartment loader addresses the module map on demand.  Some validation remains in the constructor for early errors when possible.  This change prepares the Compartment for a dynamic module map hook, necessary to emulate wildcard linkage for Node.js packages, and also sufficient to enable cyclic dependencies among modules in separate compartments.

ses(chore): Address moduleMap on-demand

---

packages/endo/package.json

Just manually fixed a dependency version number to something plausible that seems to work

fix: working version number

---

packages/compartment-mapper/package.json
packages/endo/package.json
packages/ses/NEWS.md
packages/ses/package.json

This change must not be squashed.

Publish SES v0.10.4

---

.github/workflows/ci.yml
packages/ses/package.json
packages/ses/src/get-anonymous-intrinsics.js
packages/ses/test/package/test.cjs

includes
- fix for node 10 support (in `get-anonymous-intrinsics.js`)
- test for node 10 support

Node 10 support for SES dist

---

packages/compartment-mapper/src/zip/buffer-reader.js
packages/compartment-mapper/src/zip/buffer-writer.js

Evidently, not all of our tools know about them yet.

refactor(compartment-mapper): Private fields were premature

---

packages/ses/README.md

docs(ses): Clarify default powers of Compartments

---

packages/ses/src/error/assert.js

Just a trivial comment, so I'm just gonna merge it without a review cycle.

fix: comment about breakpoint

---

packages/ses/src/error/tame-v8-error-constructor.js

Implements @michaelfig 's suggestion at https://github.com/Agoric/SES-shim/issues/570#issuecomment-772727175
Fixes #570 
My smallest PR ever!

Fix RegExp so hyphen comes last

---

package.json
patches/acorn+7.4.1.patch
yarn.lock

untested, but I _think_ this is what we need.

patch-package post-install script to patch acorn

---

packages/ses/src/enablements.js

I forgot to ask that this comment be added to #595 . Attn @AidenRourke

fix: comment who needs push enabled

---

packages/ses/package.json
packages/ses/rollup.config.js

these transforms are useful, but are not exposed in the published package

feat(ses): Export SES Transforms

---

packages/compartment-mapper/package.json
packages/endo/package.json
packages/ses-ava/package.json
packages/ses-integration-test/package.json
packages/ses/NEWS.md
packages/ses/package.json

The release I just pushed to https://www.npmjs.com/package/ses is 07edd868c1a0 . This PR has that plus the "back to dev" commit.

Release 0.12.6

---

packages/ses/src/make-function-constructor.js

It seems that XS may still be vulnerable to the attack explained at https://github.com/tc39/ecma262/pull/2374#issuecomment-813769710 where `new Function('/*', '*/ ) {')` would incorrectly validate.
With this PR, SES builds a correct safe `Function` constructor by composing two calls to an original unsafe `Function` constructor that may suffer from this bug but is otherwise correctly validating. This assumption seems to be true of all major JavaScript engines including XS.
Mysteriously, at
https://github.com/endojs/endo/blob/e9199f41c511b5df10593d931febdd90693b011a/packages/ses/test/test-break-function-eval.js#L69
we already test that this case is properly rejected. If XS has this bug, then prior to this PR this test should have failed on XS. It would be good to resolve this mystery before …

fix: workaround remaining validation bug

---

packages/ses-integration-test/puppeteer-test/utility/test-bundler.js

The SES integration tests have begun to flap: about one in four CI runs fail because the integration test failed for one Node.js version or the other. This appears to be because the test runs until the page title renders, which is sometimes before the tests produce any results. This changes the test to run until a page error is emitted or the TAP footer gets written.
Refs #688

test(ses-integration-test): Lower flaps

---

package.json
packages/netstring/LICENSE
packages/netstring/README.md
packages/netstring/index.d.ts
packages/netstring/index.js
packages/netstring/jsconfig.json
packages/netstring/package.json
packages/netstring/reader.js
packages/netstring/rollup.config.js
packages/netstring/src/reader.js
packages/netstring/src/types.js
packages/netstring/src/writer.js
packages/netstring/test/defer.js
packages/netstring/test/stream.js
packages/netstring/test/test-netstring.js
packages/netstring/writer.js
scripts/repackage.sh
skel/rollup.config.js

This brings `netstring` into the Endo repository as a stand-alone package. This provides a foundation for framing asynchronous binary messages, like streaming JSON, but also non-text messages.

feat(netstring): Port netstring from agoric-sdk/xsnap internals

---

packages/ses/src/whitelist-intrinsics.js

A minor confusion of homophones.

fix(ses): Fix intentional typo

---

packages/compartment-mapper/NEWS.md
packages/compartment-mapper/package.json

Quick fix for a publishing mistake.

fix(compartment-mapper): Missing node-powers from published files

---

packages/ses/NEWS.md
packages/ses/src/module-link.js

This is a minor improvement to the expressiveness of module system linkage errors, discovered in debugging.

feat(ses): Improve link errors

---

.github/workflows/ci.yml
package.json
packages/base64/package.json
packages/cjs-module-analyzer/package.json
packages/compartment-mapper/package.json
packages/endo/package.json
packages/netstring/package.json
packages/ses-ava/package.json
packages/ses/package.json
packages/static-module-record/package.json
packages/syrup/package.json
packages/zip/package.json
yarn.lock

Baseline coverage automation #694

---

packages/ses/index.js
packages/ses/src/commons.js
packages/ses/src/compartment-shim.js
packages/ses/src/global-object.js
packages/ses/src/lockdown-shim.js
packages/ses/src/tame-function-tostring.js
packages/ses/src/whitelist-intrinsics.js
packages/ses/test/test-global-object.js

Verbs the function name and communicates its purpose outward to context of use.

refactor(ses): Clarify markVirtualizedNativeFunction

---

packages/ses/src/whitelist.js

docs(ses): Add an up reference to --proto-- in SES permits

---

packages/ses/src/whitelist-intrinsics.js

At the Agoric/MetaMask Red Team security review, we found in particular that `visit` might be a better verb than `whitelist` for the internal functions of `whitelistIntrinsics`. In this change, I went on to clarify the verb “whitelisted” with “allowed” and factored away a `continue` that eslint forbad for clarity.
I remain a little dissatisfied with the side-effective `isAllowed*` functions, but don't have a better idea since they both co-visit the property and permit and influence control-flow with both throwing an error and returning a boolean.

refactor(ses): Clarify internal terms for culling disallowed intrinsics

---

packages/netstring/index.d.ts

Wherein, the protagonist dies a little inside.

fix(netstring): Fix TypeScript definition typo

---

packages/base64/CHANGELOG.md
packages/base64/package.json
packages/cjs-module-analyzer/CHANGELOG.md
packages/cjs-module-analyzer/package.json
packages/compartment-mapper/CHANGELOG.md
packages/compartment-mapper/package.json
packages/endo/CHANGELOG.md
packages/endo/package.json
packages/eslint-config/CHANGELOG.md
packages/eslint-config/package.json
packages/eslint-plugin/CHANGELOG.md
packages/eslint-plugin/package.json
packages/netstring/CHANGELOG.md
packages/netstring/package.json
packages/ses-ava/CHANGELOG.md
packages/ses-ava/package.json
packages/ses-integration-test/CHANGELOG.md
packages/ses-integration-test/package.json
packages/ses-types-test/CHANGELOG.md
packages/ses-types-test/package.json
packages/ses/CHANGELOG.md
packages/ses/package.json
packages/static-module-record/CHANGELOG.md
packages/static-module-record/package.json
packages/syrup/CHANGELOG.md
packages/syrup/package.json
packages/test262-runner/CHANGELOG.md
packages/test262-runner/package.json
packages/zip/CHANGELOG.md
packages/zip/package.json

This release propagates a minor bugfix for netstring.

chore: release

---

packages/ses/src/scope-handler.js

We discovered in review that we’d prefer to use `create` instead of `__proto__` and to freeze proxy handlers, just in case.

refactor(ses): Freeze proxy handlers for scopes

---

packages/ses/test/test-backslash-u-identifier.js

Add tests for backslash behavior

---

README.md

fix: Fix amateur etymology error in README

---

packages/ses/test/test-console-error-trap.js

test(ses): Fix console error trap exit code test

---

package.json
packages/lp32/LICENSE
packages/lp32/README.md
packages/lp32/index.d.ts
packages/lp32/index.js
packages/lp32/jsconfig.json
packages/lp32/package.json
packages/lp32/reader.js
packages/lp32/src/host-endian.js
packages/lp32/test/lockdown.js
packages/lp32/test/test-lp32.js
packages/lp32/writer.js

This adds a stream library for communicating over Chrome’s native message host protocol.
https://developer.chrome.com/docs/apps/nativeMessaging/

feat(lp32): Implement Chrome native message host streams

---

packages/ses/src/commons.js
packages/ses/src/tame-locale-methods.js
packages/ses/test/test-tame-locale-methods.js

fix(ses): Number.prototype.toLocaleString radix confusion

---

packages/ses/src/whitelist.js

The cause property on errors is now a stage 4 proposal and in evidence in the wild.

fix(ses): Error cause permits

---

packages/ses-types-test/validation.ts
packages/ses/NEWS.md
packages/ses/index.d.ts

fix(ses): Add assert.error options bag to type definition

---

package.json
packages/far/CHANGELOG.md
packages/far/README.md
packages/far/jsconfig.json
packages/far/package.json
packages/far/src/index.js
packages/far/test/prepare-test-env-ava.js
packages/far/test/test-e.js
packages/far/test/test-marshal-far-function.js
packages/far/test/test-marshal-far-obj.js

chore: Migrate far from Agoric SDK

---

package.json
packages/import-bundle/CHANGELOG.md
packages/import-bundle/LICENSE
packages/import-bundle/NEWS.md
packages/import-bundle/README.md
packages/import-bundle/package.json
packages/import-bundle/src/compartment-wrapper.js
packages/import-bundle/src/compartment-wrapper.md
packages/import-bundle/src/index.js
packages/import-bundle/test/bundle1.js
packages/import-bundle/test/bundle2.js
packages/import-bundle/test/prepare-test-env-ava.js
packages/import-bundle/test/test-compartment-wrapper.js
packages/import-bundle/test/test-import-bundle.js
yarn.lock

chore(import-bundle): Migrate from Agoric SDK'

---

packages/daemon/index.d.ts
packages/eslint-config/eslint-config.json
packages/eventual-send/src/index.d.ts
packages/netstring/index.d.ts
packages/ses-types-test/validation.ts
packages/ses/index.d.ts
packages/ses/src/lockdown-shim.js
packages/static-module-record/index.d.ts
packages/static-module-record/package.json
packages/stream-types-test/validation.ts
packages/stream/index.d.ts
packages/stream/package.json
packages/stream/types.d.ts
packages/where/types.d.ts

- style: Lint TypeScript
- style(eslint-config)!: Check all files, especially TypeScript
This includes breaking changes to `@endo/eslint-config` that are marked as breaking for the next release.

style: Lint TypeScript

---

packages/marshal/src/marshal.js

Fixes https://github.com/Agoric/agoric-sdk/issues/4337.
Fixes https://github.com/Agoric/agoric-sdk/issues/4302 since thenables are not passable.

Assert that unserialize makes only passables

---

packages/marshal/src/marshal.js

Fixes https://github.com/Agoric/agoric-sdk/issues/4313

marshal's Hilbert processing should only freeze rest, not harden it.

---

packages/eventual-send/src/E.js
packages/marshal/src/deeplyFulfilled.js
packages/marshal/src/dot-membrane.js
packages/marshal/src/helpers/copyArray.js
packages/marshal/src/helpers/copyRecord.js
packages/marshal/src/helpers/error.js
packages/marshal/src/helpers/internal-types.js
packages/marshal/src/helpers/passStyle-helpers.js
packages/marshal/src/helpers/remotable.js
packages/marshal/src/helpers/tagged.js
packages/marshal/src/make-far.js
packages/marshal/src/makeTagged.js
packages/marshal/src/marshal-justin.js
packages/marshal/src/marshal.js
packages/marshal/src/passStyleOf.js
packages/marshal/src/types.js
packages/promise-kit/index.js

See https://github.com/Agoric/agoric-sdk/pull/4323 .
@turadg , I tried to add you as a reviewer, but couldn't. What needs to be fixed?

Remove more extraneous spaced-comment comments

---

packages/base64/package.json
packages/bundle-source/package.json
packages/captp/package.json
packages/cjs-module-analyzer/package.json
packages/cli/package.json
packages/compartment-mapper/package.json
packages/daemon/package.json
packages/eventual-send/package.json
packages/far/package.json
packages/import-bundle/package.json
packages/init/package.json
packages/lockdown/package.json
packages/lp32/package.json
packages/marshal/NEWS.md
packages/marshal/package.json
packages/nat/package.json
packages/netstring/package.json
packages/promise-kit/package.json
packages/ses-ava/package.json
packages/static-module-record/package.json
packages/stream-node/package.json
packages/stream/package.json
packages/syrup/package.json
packages/where/package.json
packages/zip/package.json
scripts/repackage.sh

fix: Publish all materials consistently

---

packages/static-module-record/package.json
packages/static-module-record/src/babelPlugin.js
packages/static-module-record/src/transform-analyze.js
yarn.lock

- Revert "Revert "fix(static-module-record): minimise source changes with `recast`""
- Revert "Revert "build(deps): add a patched version of `recast`""
- fully patch agoric-labs/ast-types#Agoric-built

feat: Restore recast-based whitespace preservation

---

packages/ses/test/test-make-hardener.js

fix(ses): Relax hardened typed array test to be insensitive to bugfix between Node.js 14 and 16

---

.github/workflows/ci.yml
packages/stream/test/test-pump.js

chore: Drop Node.js 12 in CI

---

packages/bundle-source/src/index.js
packages/import-bundle/test/test-import-bundle.js

See
https://github.com/Agoric/agoric-sdk/blob/5e9c02a24cb3fadb8c67279f8183cac8d7cd03b1/packages/run-protocol/src/collect.js#L57-L67
Just fixes the ones I encountered. I did no systemic search of any kind to detect more such violations.

Adds some missing hardens

---

packages/ses/test/test-import-non-esm.js

This lost test should have been enabled. The role it serves is to demonstrate the low-level API of a third-party static module record, without the additional complications specific to CommonJS.

test(ses): Reenable and update third-party static module record test

---

package.json
packages/base64/package.json
packages/check-bundle/package.json
packages/cjs-module-analyzer/package.json
packages/cli/package.json
packages/compartment-mapper/package.json
packages/daemon/package.json
packages/eslint-config/package.json
packages/lp32/package.json
packages/netstring/package.json
packages/promise-kit/package.json
packages/ses-ava/package.json
packages/ses-types-test/package.json
packages/ses/package.json
packages/static-module-record/package.json
packages/stream-node/package.json
packages/stream-types-test/package.json
packages/stream/package.json
packages/syrup/package.json
packages/where/package.json
packages/zip/package.json
scripts/repackage.sh
yarn.lock

Upgrade TypeScript from 4.5 to 4.6

chore: upgrade TypeScript to 4.6

---

packages/ses/src/compartment-shim.js
packages/ses/test/test-compartment-constructor.js

- test(ses): Test object with toString as compartment name
- fix(ses): Fix compartment with name from object with toString
Fixes: #1195

fix(ses): Compartment name from object with toString

---

packages/eventual-send/src/track-turns.js

This allows eventual-send to be used in -r esm style Agoric deploy scripts.

fix(eventual-send): Remove ?. and ?? operators for RESM

---

packages/eventual-send/NEWS.md
packages/eventual-send/src/track-turns.js

fix(eventual-send): Remove lingering ?. operator

---

packages/marshal/src/encodeToCapData.js
packages/marshal/src/helpers/copyArray.js
packages/marshal/src/helpers/copyRecord.js
packages/marshal/src/helpers/error.js
packages/marshal/src/helpers/internal-types.js
packages/marshal/src/helpers/passStyle-helpers.js
packages/marshal/src/helpers/remotable.js
packages/marshal/src/helpers/safe-promise.js
packages/marshal/src/helpers/tagged.js
packages/marshal/src/passStyleOf.js

Like https://github.com/Agoric/agoric-sdk/pull/6076 , but for endo.

refactor(marshal)!: fix bad check defaults

---

packages/marshal/src/encodeToSmallcaps.js
packages/marshal/src/marshal.js
packages/marshal/test/test-marshal-smallcaps.js

Based on a suggestion by @mhofman at https://github.com/endojs/endo/pull/1282#discussion_r968921875

fix: suggested smallcaps improvement

---

packages/ses/test/test-scope.js

tests extracted from https://github.com/endojs/endo/pull/1293 and fixed for current implementation

Add general scope tests

---

packages/marshal/src/helpers/passStyle-helpers.js
packages/marshal/src/passStyleOf.js
packages/marshal/test/test-marshal-stringify.js
packages/ses/src/make-hardener.js

fix(marshal): Return a special error message from passStyleOf(typedArray)

---

packages/ses/src/enablements.js

@FUDCo , I'm asking you to review because https://github.com/Agoric/agoric-sdk/pull/6451 made me look ;)

fix: minor improvements to some override comments

---

packages/marshal/src/passStyleOf.js
packages/marshal/test/test-passStyleOf.js

Split from #1313 for expediency.
Fixes #1318

fix(marshal): Check if input is an error before checking if it is remotable

---

packages/marshal/NEWS.md

Ref https://github.com/endojs/endo/pull/1328

chore(marshal): Update NEWS.md

---

packages/marshal/src/helpers/remotable.js

Without this, marshaling a remotable incurs a redundant verification in `getInterfaceOf`.
<details><summary>ad hoc analysis</summary>
```sh
node --input-type=module -e '
import Benchmark from "benchmark";
import "../init/index.js";
import { makeMarshal } from "./src/marshal.js";
const { serialize } = makeMarshal(x => x, x => x, { errorTagging: "off", serializeBodyFormat: "smallcaps" });
let result;
(new Benchmark.Suite())
.add("shallow remotable", {
setup: () => {
const rProto = Object.defineProperties({}, { [Symbol.for("passStyle")]: { value: "remotable" }, [Symbol.toStringTag]: { value: "Remotable" } });
shallow = Object.create(rProto);
Array(20).fill().forEach((_, i) => { shallow[`method${i}`] = () => {}; });
},
fn: () => { result = serialize(harden(shallow)); },
})
.add("deep …
```

perf(marshal): Memoize checkRemotable

---

packages/compartment-mapper/src/node-modules.js
packages/compartment-mapper/test/fixtures-0/node_modules/brooke/brooke.js
packages/compartment-mapper/test/fixtures-0/node_modules/brooke/package.json
packages/compartment-mapper/test/fixtures-optional/node_modules/alpha/index.js
packages/compartment-mapper/test/fixtures-optional/node_modules/alpha/package.json
packages/compartment-mapper/test/fixtures-optional/node_modules/beta/index.js
packages/compartment-mapper/test/fixtures-optional/node_modules/beta/package.json
packages/compartment-mapper/test/fixtures-optional/node_modules/optional-cjs/index.js
packages/compartment-mapper/test/fixtures-optional/node_modules/optional-cjs/package.json
packages/compartment-mapper/test/fixtures-optional/node_modules/optional-esm/index.js
packages/compartment-mapper/test/fixtures-optional/node_modules/optional-esm/package.json
packages/compartment-mapper/test/scaffold.js
packages/compartment-mapper/test/test-optional.js

Fixes #1177 and related compatibility issues

compartment-mapper: add support for package.json exotic dependency fields

---

packages/eventual-send/src/handled-promise.js
packages/eventual-send/src/local.js
packages/eventual-send/test/test-eventual-send.js
packages/far/test/test-e.js

Fixes https://github.com/Agoric/agoric-sdk/issues/6570

fix: include inherited methods in missing method error

---

packages/ses/src/tame-function-constructors.js

close https://github.com/endojs/endo/issues/1281

fix: crash under csp

---

package.json
packages/base64/package.json
packages/check-bundle/package.json
packages/cjs-module-analyzer/package.json
packages/cli/package.json
packages/compartment-mapper/package.json
packages/daemon/package.json
packages/lp32/package.json
packages/marshal/src/make-far.js
packages/netstring/package.json
packages/promise-kit/package.json
packages/ses-ava/package.json
packages/ses-integration-test/package.json
packages/ses/package.json
packages/static-module-record/package.json
packages/stream-node/package.json
packages/stream-types-test/package.json
packages/stream/package.json
packages/syrup/package.json
packages/where/package.json
packages/zip/package.json
patches/events+3.3.0.patch
yarn.lock

Release notes:
https://devblogs.microsoft.com/typescript/announcing-typescript-4-9/
Most motivating feature: [the new `satisfies` operator](https://devblogs.microsoft.com/typescript/announcing-typescript-4-9/#satisfies)
Updates the dep and others that were necessary to get back to green.

update TypeScript to 4.9

---

packages/marshal/src/marshal-justin.js
packages/marshal/test/test-marshal-justin.js

Allow an optional `slots` argument to `decodeToJustin` that allows printing of `slotToVal(slot, "iface")`.

feat(marshal): display slot values if supplied

---

packages/ses/src/error/types.js

Correction of some minor issues noticed in passing during documentation review.
Analog of https://github.com/Agoric/agoric-sdk/pull/6751

docs: Miscellaneous commentary cleanup

---

packages/ses/docs/guide.md

Fix guide.md Compartment link

---

packages/ses/package.json
packages/ses/package.json.md
packages/ses/src/sloppy-globals-scope-terminator.js
packages/ses/src/transforms.js
packages/ses/tools.js

makes ses utils available which is useful when working with ses

feat(ses): publish utils bundle

---

packages/exo/src/interface-tools.js
packages/patterns/index.js
packages/patterns/src/patterns/patternMatchers.js
packages/patterns/src/types.js
packages/patterns/test/test-pattern-limits.js
packages/patterns/test/test-patterns.js

Per https://github.com/Agoric/agoric-sdk/issues/6844

Rename 'fit' to 'mustMatch'

---

packages/eventual-send/src/handled-promise.js
packages/eventual-send/test/test-hp.js

Prompted by conversation at https://github.com/endojs/endo/pull/1465#discussion_r1086887864 .

feat(eventual-send): Harden HandledPromise modulo intrinsic exit points

---

packages/exo/docs/exo-taxonomy.md

* Clean up some phrasing
* Explicitly identify the functions in each category.

docs(exo): Improve documentation

---

packages/marshal/src/marshal.js
packages/marshal/src/types.js

clearer marshal method names

---

packages/ses-ava/src/ses-ava-test.js

```diff
-{THROWN,REJECTED} from ava test: (Error#1)
+{THROWN,REJECTED} from ava test("…title…"): (Error#1)
```

feat(ses-ava): Include test title in special console error logging

---

packages/base64/package.json
packages/cli/package.json
packages/daemon/package.json
packages/exo/README.md
packages/exo/package.json
packages/lp32/package.json
packages/netstring/package.json
packages/pass-style/README.md
packages/patterns/README.md
packages/patterns/package.json
packages/stream/package.json
packages/syrup/package.json
packages/where/package.json
packages/zip/package.json

See https://github.com/endojs/endo/pull/1451#pullrequestreview-1263981440
@kriskowal does this reflect a problem in repackage.sh ?

docs: fix readme urls

---

packages/compartment-mapper/src/link.js
packages/compartment-mapper/src/node-modules.js
packages/compartment-mapper/src/policy.js
packages/eslint-config/eslint-config.json
packages/pass-style/src/typeGuards.js
packages/patterns/src/types.js

chore: Handle warnings from new eslint-plugin-jsdoc recommended rules

---

.github/workflows/ci.yml
packages/captp/src/captp.js
packages/compartment-mapper/src/link.js
packages/compartment-mapper/src/policy.js
packages/eslint-config/NEWS.md
packages/eslint-config/README.md
packages/eslint-config/eslint-config.cjs

...but limit enhanced linting to "src" files (for now).
Ref #1497

ci: Update to use type-aware linting

---

packages/patterns/index.js
packages/patterns/src/keys/checkKey.js
packages/patterns/src/keys/copyBag.js
packages/patterns/src/keys/copySet.js
packages/patterns/src/keys/merge-bag-operators.js
packages/patterns/src/patterns/patternMatchers.js
packages/patterns/src/types.js
packages/patterns/test/test-copyBag.js

Tracking with https://github.com/Agoric/agoric-sdk/pull/7081

refactor: track agoric-sdk changes

---

packages/patterns/src/keys/checkKey.js

Mirrors https://github.com/Agoric/agoric-sdk/pull/7140

chore(patterns): Refine types

---

packages/ses/docs/lockdown.md

`__allowUnsafeMonkeyPatching__` was removed a long time ago, except it was still mentioned in a markdown file.

docs: remove vestiges of __allowUnsafeMonkeyPatching__

---

packages/ses/test/test-frozen-primordials.js

arguments objects don't have a special prototype
Ref 5c41bdc0628d69a83a1c9378e986573444f2bb1d

test: Replace misleading test

---

packages/exo/src/exo-makers.js
packages/exo/src/exo-tools.js

Mirrors https://github.com/Agoric/agoric-sdk/pull/7360

chore(exo): Define narrow Exo-related context types

---

packages/ses/docs/lockdown.md

One correction and some minor improvements.
Note to reviewers: Low urgency.

doc(ses): improve doc of `__hardenTaming__` option

---

packages/pass-style/doc/copyArray-guarantees.md
packages/pass-style/doc/copyRecord-guarantees.md

Adapt @warner's table from https://github.com/Agoric/agoric-sdk/issues/7446 as replacement for nested list.
Eventually, see also http://arejsobjectscursed.com/
Note to reviewers: Low urgency

doc(pass-style): property name cases table

---

packages/compartment-mapper/src/archive.js

lil refactor
breaks out the `compartmentMap` transforming function that prepares it for an archive

CompartmentMapper: break out creation of archiveCompartmentMap

---

packages/compartment-mapper/src/bundle.js

The Compartment Map contains a bundler that is entirely sufficient for bundling SES proper. Since its original design, @naugtur expanded it to handle CommonJS. So, the missing feature that would make it suitable for bundling a larger bootstrapping system, say, one that could bootstrap eventual-send and import-bundle, was module aliases.
This change introduces an alias map, which fast-forwards every import resolution thru aliases to the concrete implementation of the imported module.

feat(compartment-mapper): Bundler support for aliases

---

packages/ses/src/strict-scope-terminator.js
packages/ses/test/test-sloppy-globals-scope-terminator.js
packages/ses/test/test-strict-scope-terminator.js

Fixes https://github.com/endojs/endo/issues/1490
See that issue for explanation.
@argp1 I cannot add you as an official reviewer, but please review anyway. Thanks.

fix(ses): better safari debugging

---

packages/marshal/README.md

ibid is gone since #2898 f865a2a

docs(marshal): prune ibid

---

patches/@lerna+version+5.6.2.patch

backport of https://github.com/lerna/lerna/pull/3766/

chore(deps): patch Lerna for Prettier v3 compat

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/security.md
.github/ISSUE_TEMPLATE/support_request.md
.github/ISSUE_TEMPLATE/work_item.md
.github/PULL_REQUEST_TEMPLATE.md
SECURITY.md

Add issue and pull request templates

---

README.md

Since we last revised the Endo README, everything we previously stated as aspirational has come to pass, with very few qualifications.

docs: Revise README to reflect accomplishments

---

packages/daemon/src/worker.js

Was this left out on purpose?
cc @michaelfig

chore(daemon): endow worker with console

---

.github/workflows/ci.yml
packages/bundle-source/cache.js
packages/bundle-source/package.json

refs: #1732
The "Bundle refactoring" in #1732 broke the release process:
```
$ (cd packages/bundle-source && yarn pack)
yarn pack v1.22.19
$ tsc --build jsconfig.build.json
cache.js:90:7 - error TS2322: Type '{ bundleFileName: any; bundleTime: any; bundleSize: any; moduleSource: { relative: any; absolute: any; }; contents: { relativePath: any; mtime: any; size: any; }[]; }' is not assignable to type 'BundleMeta'.
Object literal may only specify known properties, but 'bundleSize' does not exist in type 'BundleMeta'. Did you mean to write 'bundleTime'?
90       bundleSize,
~~~~~~~~~~
cache.js:178:17 - error TS2339: Property 'bundleTime' does not exist on type 'BundleMeta | undefined'.
178         const { bundleTime, bundleSize, contents } = meta;
~~~~~~~~~~
cache.js:178:29 - error TS2339: …
```

ci(viable-release): simple check that the packages are releasable

---

jsconfig.eslint-full.json
packages/bundle-source/cache.js
packages/bundle-source/src/bundle-source.js
packages/bundle-source/src/transform.js
packages/bundle-source/src/types.js
packages/captp/src/finalize.js
packages/compartment-mapper/src/bundle.js
packages/exo/src/exo-makers.js
packages/exo/src/exo-tools.js
packages/pass-style/src/passStyleOf.js
packages/patterns/src/patterns/internal-types.js
packages/patterns/src/patterns/patternMatchers.js
packages/patterns/src/types.js
packages/ses/src/error/note-log-args.js

This fixes some of Endo's drifting away from Agoric SDK's requirements.  Other changes can be made in the Agoric SDK directly, so they are being done there.
Notably:
1. `@endo/bundle-source` typing and cache semantics (partly because `cache.js` was omitted from typechecking)
2. `?.` and `??` causing problems when attempting to bundle-source modules that use them.
3. Improve typing of `@endo/exo` to align with Agoric SDK's `packages/zone` and `packages/base-zone`.
n/a
n/a
n/a
We really need CI somehow to trigger an integration test on Agoric SDK (#1761), to prevent landing Endo PRs that break things unless we know what we're doing, but that's for a later date.
n/a

fix: restore compatibility with Agoric SDK master

---

packages/lockdown/commit-debug.js
packages/ses/src/enablements.js
packages/ses/src/lockdown.js

Unbreak old links to lockdown-options.md

doc(ses,lockdown): unbreak old links to lockdown-options.md

---

packages/cli/demo/README.md
packages/cli/demo/cat.js
packages/cli/package.json
packages/cli/src/endo.js
packages/cli/src/locator.js
packages/cli/src/message-format.js
packages/cli/src/mkguest.js
packages/cli/test/test-message-format.js
packages/daemon/src/daemon-node-powers.js
packages/daemon/src/daemon.js
packages/daemon/src/types.d.ts

This change consists of various fixes I’ve found while continuing to work in connection invitations. Commits are individually reviewable. This is targeted to merge in the `endo` branch.

Endo Pet Daemon Catch-up

---

packages/ses/src/permits.js

Follow-up from https://github.com/endojs/endo/pull/1850. I was hasty.

docs(ses): Annotate Promise.withResolvers permit

---

packages/daemon/src/guest.js
packages/daemon/src/host.js
packages/daemon/src/pet-store.js
packages/daemon/src/types.d.ts

allows querying for pet name existence
extracted from https://github.com/endojs/endo/pull/1862

feat(daemon): Add and expose petstore "has"

---

.github/workflows/typedoc-gh-pages.yml

_If only there were a way to test the workflow before master._
(I verified in my local checkout last time, but this time I copy-pasted the string)

fix typedoc command name

---

packages/ses/docs/README.md

fix(ses): Remove link to stale Read the Docs

---

packages/ses/README.md

docs(ses): Fix Compartment typo in README.md

---

packages/daemon/src/daemon.js
packages/daemon/src/worker.js

Removes some unused params from `@endo/daemon`.

chore(daemon): Remove unused params

---

.github/ISSUE_TEMPLATE/work_item.md
.github/PULL_REQUEST_TEMPLATE.md
packages/base64/src/decode.js
packages/base64/test/test-main.js
packages/bundle-source/src/zip-base64.js
packages/eventual-send/README.md
packages/marshal/src/encodePassable.js
packages/marshal/src/encodeToSmallcaps.js
packages/marshal/src/marshal.js

This brings @kumavis CJS evasive transform fix into the daemon.

Merge master into endo (2024-01-25)

---

packages/daemon/src/mail.js
packages/daemon/src/types.d.ts
packages/daemon/test/test-endo.js

this powers the chat feature in https://github.com/endojs/endo/pull/1877
including the package message formula type-aware context menu

feat(daemon): mail is delivered to both inboxes + includes formula identifiers

---

packages/cli/src/commands/make.js
packages/daemon/package.json
packages/daemon/test/test-endo.js

Closes: #2024 
Tests confined bundles using `makeBundle`. Adds a utility to make using `makeBundle` significantly easier in tests for the daemon.

test(daemon): Add `makeBundle` test

---

packages/eslint-plugin/lib/configs/internal.js
packages/eslint-plugin/lib/configs/recommended.js

Neglected in https://github.com/endojs/endo/pull/1929/

lint: nullish-coalescing only for 'internal' config

---

packages/cli/src/commands/mkguest.js
packages/cli/src/commands/mkhost.js
packages/cli/src/endo.js
packages/daemon/src/daemon.js
packages/daemon/src/guest.js
packages/daemon/src/host.js
packages/daemon/src/types.d.ts

Allows host or guest to be created with petnames populated by creator

feat: daemon can specify introducedNames when making guests or hosts

---

packages/cli/src/commands/dismiss.js
packages/cli/src/commands/inbox.js
packages/cli/src/commands/log.js
packages/cli/src/commands/mkhost.js
packages/cli/src/commands/ping.js
packages/cli/src/commands/reject.js
packages/cli/src/commands/remove.js
packages/cli/src/commands/request.js
packages/cli/src/commands/show.js
packages/cli/src/commands/spawn.js

Removes unused arguments to CLI command handlers.

fix(cli): Remove unused arguments to command handlers

---

packages/daemon/src/daemon.js
packages/daemon/src/mail.js
packages/daemon/src/types.d.ts

types for the type gods :moyai:

daemon: enhance types for mail

---

packages/cli/src/commands/list.js
packages/cli/src/endo.js

This allows a client to watch for changes to their pet store inventory.

feat(cli): Follow list changes

---

packages/daemon/test/test-mutex.js

Adds tests for `daemon/src/mutex.js`.

test(daemon): Add mutex unit tests

---

packages/daemon/src/daemon-node-powers.js
packages/daemon/src/daemon.js
packages/daemon/src/formula-identifier.js
packages/daemon/src/host.js
packages/daemon/src/pet-sitter.js
packages/daemon/src/pet-store.js
packages/daemon/src/types.d.ts
packages/daemon/test/test-endo.js

This is a sequence of refactors that get us closer to indexing controllers by formula numbers (without type).

refactor(daemon): Index formulas by number

---

packages/ses/src/make-eval-function.js

refactor(ses): Update make-eval-function.js

---

packages/daemon/src/daemon.js

Closes #2165
Once a formula has been written and until it’s provably unreachable, we need not consult storage.

refactor(daemon): Memoize formulas

---

packages/daemon/src/daemon-node-powers.js
packages/daemon/src/worker-node.js
packages/daemon/src/worker.js

Removes extraneous arguments to worker processes.

refactor(daemon): Remove extraneous worker process args

---

packages/daemon/src/connection.js
packages/daemon/src/context.js
packages/daemon/src/daemon-node-powers.js
packages/daemon/src/daemon-node.js
packages/daemon/src/daemon.js
packages/daemon/src/deferred-tasks.js
packages/daemon/src/directory.js
packages/daemon/src/formula-identifier.js
packages/daemon/src/guest.js
packages/daemon/src/host.js
packages/daemon/src/mail.js
packages/daemon/src/multimap.js
packages/daemon/src/pet-sitter.js
packages/daemon/src/pet-store.js
packages/daemon/src/pubsub.js
packages/daemon/src/reader-ref.js
packages/daemon/src/remote-control.js
packages/daemon/src/serial-jobs.js
packages/daemon/src/types.d.ts
packages/daemon/src/web-server-node-powers.js
packages/daemon/src/web-server-node.js
packages/daemon/src/worker-node-powers.js
packages/daemon/src/worker-node.js
packages/daemon/src/worker.js

Largely mechanical change to use `@import` instead of `@type {import(...`.

refactor(daemon): Use @import

---

packages/ses/src/make-hardener.js

closes: #XXXX
refs: #XXXX
All this `path` maintenance within `harden` was there in case we encountered failures to harden that were hard to diagnose. They accumulate the path accumulated from the harden root to the thing that failed to be hardened. But it was never used to produce a better error message. Rather, they could have been useful from a debugger's eye view. But in all the years we've paid the price for this diagnostic, we have not made use of it. The operations used to accumulate the path are expensive string operations and WeakSet operations.
Because the diagnostic information was never actually shown in any diagnostic, this change should be completely without any observable effect. Hence, this PR is a pure refactor.
Mostly none. By making `harden` cheaper, perhaps it'll be …

refactor(ses): remove unused expensive diagnostic from harden

---

packages/cli/src/commands/make.js

Clean up temp bundle when make() throws

---

packages/base64/typedoc.json
packages/captp/typedoc.json
packages/check-bundle/typedoc.json
packages/errors/typedoc.json
packages/eventual-send/typedoc.json
packages/exo/typedoc.json
packages/far/typedoc.json
packages/init/typedoc.json
packages/pass-style/typedoc.json
packages/patterns/typedoc.json
packages/promise-kit/typedoc.json
packages/ses-ava/typedoc.json
packages/zip/typedoc.json

- Generate typedoc for more packages.
- Disable the validation suppressions.
n/a
n/a
docs per se
CI and manually looked over build output
n/a
n/a

typedoc for more packages

---

packages/bundle-source/NEWS.md
packages/bundle-source/src/main.js

Fills in the usage and NEWS for #2294.

docs(bundle-source): Document no transforms mode

---

packages/pass-style/src/string.js

Closes: #XXXX
Refs: https://github.com/Agoric/agoric-sdk/pull/9233
Only removes TODO comment that was done in https://github.com/Agoric/agoric-sdk/pull/9233

comment(pass-style): remove TODO done at agoric #9233

---

packages/cli/src/endo.js

Adds common aliases to a handful of CLI commands.

feat: Add common aliases to CLI commands

---

packages/ses/NEWS.md
packages/ses/docs/lockdown.md

Add documentation for `legacyRegeneratorRuntimeTaming`.
Closes: #2423
Refs: #2383

docs(ses): add doc for legacyRegeneratorRuntimeTaming

---

packages/ses/test/package.test.js

test assertion failure outside of the test function leads to uncaught exception

fix(ses): package test correctly rejects instead of uncaught exception

---

README.md

Minor documentation improvement.

docs: Links for Agoric and MetaMask

---

packages/compartment-mapper/src/types/external.ts

Small improvements to typedocs for some common options.

docs(compartment-mapper): Improve docs for options

---

packages/pass-style/src/typeGuards.js

As seen at e.g. https://github.com/endojs/endo/pull/2645/files?w=1#files:~:text=Unchanged%20files%20with%20check%20annotations

chore(pass-style): Resolve eslint warnings

---

package.json
yarn.lock

chore: upgrade Jessie

---

packages/compartment-mapper/README.md

Some explanatory tweaks as I come up to speed on this package.

chore(compartment-mapper): Improve README text and formatting

---

packages/immutable-arraybuffer/README.md

Trivial update to the README of the immutable-arraybuffer shim.

docs(immutable-arraybuffer): update README

---

packages/ses/src/module-load.js
packages/ses/test/import-cjs.test.js

It took a while, but we've encountered  case that would first go into a dynamic require (therefore trigger compartment-mapper using importNow) and proceed to import a codebase with a cycle in cjs modules.
The minimal implementation of enqueueJob that we used in importNow was causing the synchronous case for `memoizedLoadWithErrorAnnotation` to become depth-first and getting into cycles before anything got successfully memoized.
The new `syncJobQueue` guarantees a breadth-first order. 
none
`current` and `next` in `syncJobQueue` get swapped and each layer of the module dependency tree gets processed as a separate step, which should be reasonably memory efficient. I could eliminate recursion from `drainQueue` altogether, but that seems a premature optimization.
It's a fix
The testcase is …

fix(ses): avoid depth-first loading sequence in loadNow to prevent getting stuck in cycles

---

packages/promise-kit/test/promise-kit.test.js

Refs: https://github.com/endojs/endo/actions/runs/15353141616/job/43207173454?pr=2822
Node 22 seems to have a v8 version that has a different gc behavior. This changes the test to better account for different generational gc and scheduling behaviors.
None
None
None
Tested locally across Node versions
```
for i in {1..10}; do yarn test > /dev/null || { echo failed attempt $i; break; }; done
```
The test is a little brittle, haven't looked if there's a better way.
None

test(promise-kit): accommodate more sensitive gc

---

packages/marshal/src/rankOrder.js

> Most PRs should close a specific Issue. All PRs should at least reference one or more Issues. Edit and/or delete the following lines as appropriate (note: you don't need both `refs` and `closes` for the same one):
Closes: #XXXX
Refs: #XXXX
> Add a description of the changes that this PR introduces and the files that are the most critical to review.
> Does this change require or encourage significant increase in consumption of CPU cycles, RAM, on-chain storage, message exchanges, or other scarce resources? If so, …

refactor(marshal): some drive bys from 2871

---

packages/pass-style/src/passStyle-helpers.js
packages/pass-style/src/remotable.js
packages/pass-style/src/tagged.js

> Most PRs should close a specific Issue. All PRs should at least reference one or more Issues. Edit and/or delete the following lines as appropriate (note: you don't need both `refs` and `closes` for the same one):
Closes: #XXXX
Refs: #XXXX
> Add a description of the changes that this PR introduces and the files that are the most critical to review.
> Does this change require or encourage significant increase in consumption of CPU cycles, RAM, on-chain storage, message exchanges, or other scarce resources? If so, …

bug(pass-style,patterns): somehow breaks in copySet test

---

.github/workflows/ci.yml
packages/benchmark/install-engines.sh
packages/benchmark/package.json

fix(endo): Run benchmark only in presence of CI bin/xst
