- package.json
- packages/harden/package.json
- packages/harden/rollup.config.js
- packages/make-hardener/package.json
- packages/make-hardener/rollup.config.js
- yarn.lock
This fixes the errors I was seeing in `yarn build`, caused by the rollup config looking for a file (`index.js`) that got renamed recently (to `main.js`). It also updates `yarn.lock` as a side-effect.
refs #6
> fix rollup

- packages/lockdown-shim/src/main.js
- packages/lockdown-shim/test/lockdown-allow.test.js
- packages/lockdown-shim/test/lockdown-options.test.js
- packages/lockdown-shim/test/lockdown.test.js
Resolves:
*Can/should lockdown() be called twice*
https://github.com/Agoric/SES-shim/issues/40
*Reject unrecognized options*
https://github.com/Agoric/SES-shim/issues/32
> Allow re-invocation of lockdown() & reject unrecognized options

- .gitignore
- scripts/graph.sh
This change introduces a script for generating the shallow interdependency graph among packages in the SES monorepo.
This is a preview at time of writing:
> Add script to generate dependency graph

- package.json
- packages/error-stack-shim/package.json
- packages/ses-integration-test/package.json
This change marks a couple test repositories as private, fixes the
capitalization of one package name, and updates the release process to
reflect the pivot to Yarn workspaces and Lerna.
> Fix private package metadata (and similar)

- packages/harden/package.json
- packages/make-hardener-integration-test/package.json
- packages/make-hardener/NEWS.md
- packages/make-hardener/package.json
- packages/ses/package.json
This release is the first to be published from the ses-shim monorepo and
includes changes necessary for compatibility with SES 0.7.
> release make-hardener v0.0.7

- package.json
- packages/ses-integration-test/scaffolding/rollup/ses.js
- packages/ses/package.json
- packages/ses/rollup.config.js
- packages/ses/test/package.test.js
- packages/ses/test/package/package.json
- packages/ses/test/package/test.cjs
- packages/ses/test/package/test.js
- packages/ses/test/package/test.mjs
This aligns ses/package.json such that SES can be imported with a CommonJS
loader, with the `esm` package using `node -r esm`, as well as Node.js ESM
support, all using the same "ses" name.
node main.js
const { lockdown } = require('ses');
node main.mjs and node -r esm main.js
import { lockdown } from 'ses';
This change includes a regression test that verifies each of these cases.
Fixes #214
> Fix importing CJS, RESM, and ESM

- packages/ses/NEWS.md
- packages/ses/package.json
Bug fixes.
This release addresses an exception observed where locking down fails because
SES cannot delete the prototype of the harden function.
This is addressed by upgrading @agoric/make-harden to version 0.0.7.
This release also restores fulls upport for importing SES as CommonJS, Node.js
ESM, and Node.js emulated ESM with the `esm` package.
> SES v0.7.2

- packages/harden/src/main.js
- packages/make-hardener-integration-test/pre-release-browser-tests/rollup/make-hardener.js
- packages/make-hardener/package.json
- packages/make-hardener/rollup.config.js
- packages/ses/src/lockdown-shim.js
- packages/ses/test/enable-property-overrides.test.js
This change rearranges make-hardener so that it supports the full hybrid of ESM, RESM, and CJS module systems.
> make-hardener: Fix direct Node.js ESM support

- packages/harden/package.json
- packages/make-hardener-integration-test/package.json
- packages/make-hardener/NEWS.md
- packages/make-hardener/package.json
- packages/ses/package.json
This release addresses #217 so that SES 0.7 will work when imported by an
ECMAScript module in Node.js among other environments.
> make-hardener v0.0.8

- packages/ses/src/enablements.js
- packages/ses/test/enable-property-overrides.test.js
Fixes #226 
I didn't include these two. Looks like there were also tests validating that they are override-able, wouldn't want to lose them either 
https://github.com/Agoric/SES/commit/d695dfbcf3b37a31d4ae0ab3f9ae7a754f02fd26
```
AsyncFunction: {
prototype: {
constructor: t,
name: t,
toString: t,
},
},
AsyncGeneratorFunction: {
prototype: {
constructor: t,
name: t,
toString: t,
},
},
```
> ses/enablements: add some missing enablements

- packages/ses/NEWS.md
- packages/ses/package.json
This release adds Node.js ESM support by upgrading @agoric/make-hardener to a
hybrid version for most modern module systems.
* Newless calls to the RegExp constructor now work after lockdown.
* upgrade @agoric/make-hardener v0.0.8
> SES v0.7.4

- packages/make-simple-evaluate/yarn.lock
- yarn.lock
This updates `yarn.lock` to include newer versions of `acorn` and `minimist`, in an attempt to address the security alerts that github is flagging. I'm not confident that it will address all of them, but I want to see if it makes a dent at all.
Github is currently warning about three things:
* acorn in the top-level yarn.lock
* minimist in the top-level yarn.lock
* minimist in packages/make-simple-evaluate/yarn.lock
Github/dependabot filed a PR for `acorn`, however 1: the PR was landed already, 2: there are three distinct versions of `acorn` cited in our yarn.lock. 3: two of those versions were in the advisory as insecure, and 4: the PR only modified one of them. This PR modifies the other insecure one, in the hopes that dependabot will be satisfied
There were three distinct versions of …
> Update deps to address security alerts

- packages/harden/package.json
@kriskowal would you be able to publish a new version of `@agoric/harden` based on this?  The current 0.0.6 is broken.
Without this PR, we get:
```
Error: Cannot find module '@agoric/harden'. Please verify that the package.json has a valid "main" entry] {
code: 'MODULE_NOT_FOUND',
path: '/Users/michael/agoric/agoric-sdk/node_modules/@agoric/harden/package.json',
requestPath: '@agoric/harden'
}
```
> We need to publish the harden src directory for NPM to work

- packages/harden/src/main.js
The `SecurityWarning` should be able to be explicitly silenced.  One way to do this is:
`my-test.js`:
```js
import './initialize-ses.js';
import harden from '@agoric/harden';
... test code
```
`initialize-ses.js`:
```js
// Tell that we don't have harden yet, but don't want to warn.
globalThis.harden = false;
```
</details>
Also, update the text of the `SecurityWarning` to describe what the issue is.
> Allow silencing SecurityWarning

- packages/ses/src/compartment-shim.js
- packages/ses/src/lockdown-shim.js
- packages/ses/src/main.js
- packages/ses/test/break-function-eval.test.js
- packages/ses/test/compartment-constructor.test.js
- packages/ses/test/compartment-instance.test.js
- packages/ses/test/compartment-prototype.test.js
- packages/ses/test/confinement.test.js
- packages/ses/test/global-object-mutability.test.js
- packages/ses/test/global-object-properties.test.js
- packages/ses/test/identity-continuity.test.js
- packages/ses/test/leak-endowments.test.js
- packages/ses/test/leak-unsafe-eval.test.js
- packages/ses/test/lockdown.test.js
- packages/ses/test/reject-direct-eval.test.js
- packages/ses/test/reject-html-comment.test.js
- packages/ses/test/reject-import-expression.test.js
- packages/ses/test/typeof.test.js
- packages/ses/test262/compartment-shim.js
With this change, Compartment becomes a public export.  This puts lockdown and Compartment on even footing, since it will no longer be necessary to lockdown to realize the Compartment global. In a planned change, Compartment will likely become a separate package.
> Export Compartment as Compartment instead of default

- packages/ses/test/node.js
- packages/ses/test/node.test.js
Toward introducing Compartment.import, we will need a resolveHook to pass to the Compartment constructor.  This resolve function implements Node.js style module specifier resolution.  A Node.js package compartment distinguishes internal and external specifier based on whether they resemble relative paths.  The referrer in a Compartment will always have an internal path.  The specifier may be relative or non-relative to address internal or external modules respectively.  Although Node.js affords absolute paths as module specififers, the Compartment API will not accommodate these specifiers at least upon the first draft.
This module is neither yet used nor public.  Its behavior may be a suitable default for all Compartment but that remains undecided.  Consequently, this module is likely to …
> chore(ses): Introduce Node-style module specifier resolver

- packages/transform-module/NEWS.md
- packages/transform-module/README.md
- packages/transform-module/package.json
- packages/transform-module/src/main.js
- packages/transform-module/test/export-default.test.js
- packages/transform-module/test/export-named.test.js
- packages/transform-module/test/import.test.js
- packages/transform-module/test/sanity.test.js
Rolling up @babel/core and @babel/standalone in SES both proved problematic. The former because of a bad interaction with Rollup. The latter because it entrains the package `private` which shims intrinsics and interferes with SES lockdown. To that end @michaelfig has published a version of @babel/standalone as @agoric/babel-standalone with the packages that interfere with SES omitted.
This is a preamble to introducing @agoric/transform-module as a dependency of SES and supporting module loaders in compartments.
> fix(transform-module)!: Use @agoric/babel-standalone over @babel/core

- packages/transform-module/NEWS.md
- packages/transform-module/src/main.js
This change freezes the surface of module static records provided by transform-module.
While this is not necessary for any security property of SES, it is one more assurance to ease them through review.
Notably, this “inner” module static record still carries the transformed source and SES will create a thin ModuleStaticRecord that hides this “analysis” result entirely, not for any security property, but to avoid unnecessarily exposing implementation details that should remain free to evolve.
> fix(transform-module)!: Freeze module static records

- packages/ses-integration-test/scaffolding/rollup/rollup.config.test.js
- packages/ses/package.json
- packages/ses/src/compartment-shim.js
- packages/ses/src/intrinsics-global.js
- packages/ses/src/main.js
- packages/ses/src/whitelist.js
- packages/ses/test/module-static-record.test.js
- yarn.lock
Compartment import hooks will be obliged to eventually return ModuleStaticRecords. These are reusable references to a parsed module. The ModuleStaticRecord constructor produces an opaque token from module text.
> feat(ses): Add ModuleStaticRecord

- packages/ses/src/module-load.js
The loader is responsible for loading ModuleStaticRecords and from them deriving corresponding ModuleLinkageRecords (no explicit constructor) with references to the records of the modules they import. The loader must be able to transit links to other compartments.
> Add a module loader

- packages/ses/src/module-instance.js
This function implements the instantiation convention for a ModuleStaticRecord.  The module static record is a function and metadata about what a module imports and exports, and how it presents those exports based on whether they are mutable and whether they is a temporal-dead-zone between when the module is instantiated and when an exported field becomes accessible.  The module instance type connects the module to namespace of imported and exported modules and provides the mechanism for eventually executing that module.
This is a slightly altered copy of the module instance constructor from the `@agoric/make-importer` package. The changes facilitate coupling with compartments. We may elect to project these changes back out and take a dependency.
The facilities for threading additional …
> Add private module instance type

- packages/ses/src/module-link.js
Provided that a graph of module compartment records has been fully loaded asynchronously, we can then synchronously instantiate and cross-link the import and export namespaces of all those module instances. After linking, we are ready to synchronously execute any subgraph from any entry point.
> Add module linker

- packages/ses/src/module-instance.js
- packages/ses/src/module-link.js
- packages/ses/src/module-load.js
- packages/ses/src/module-proxy.js
- packages/ses/test/module-proxy.test.js
For a module in one compartment to import a module in another compartment, the Compartments must pre-arrange for a module specifier to alias the other compartment. The mechanism @erights and I discussed to make this possible is the introduction of a compartment.module method that would return the module exports namespace object for a module, possibly before that module has even been loaded. Behind the scenes, a weak map tracks the corresponding compartment and specifier for each module exports namespace object, so the Compartment constructor can infer the alias for any module exports namespace object received through its module map.
To facilitate this, the presentation of a module exports namespace needs to be a proxy for the eventual internal representation, so that any property access …
> Add module exports namespace proxy

- packages/ses/README.md
- packages/ses/src/compartment-shim.js
- packages/ses/src/module-link.js
- packages/ses/test/compartment-instance.test.js
- packages/ses/test/compartment-prototype.test.js
- packages/ses/test/import-commons.js
- packages/ses/test/import-gauntlet.test.js
- packages/ses/test/import.test.js
- packages/ses/test/node.js
- packages/ses/test/node.test.js
This change introduces support for `import` and `importNow` on Compartments.
This is largely a refactor of `@agoric/make-importer` and subsumes the needed components into `ses` proper to avoid creating an interface with potential for shearing versions.
This is an early draft.
- Add support for module maps.
Follow up changes that need to be moved into separate tracking tickets:
> Support Compartment.import

- packages/ses/README.md
- packages/ses/src/compartment-shim.js
- packages/ses/test/import-commons.js
- packages/ses/test/import-stack-traces.test.js
- packages/transform-module/src/main.js
This change adds the `//# sourceURL=` directive through the SES module transformer from the public `ModuleStaticRecord` constructor, as a second optional argument. This allows the original file name to surface in stack traces, instead of the eval machinery that led to it.
> Thread module locations through stack traces

- packages/harden/package.json
Evidently the package check script isn’t failing builds. This is a correction inspired by the package.json linter `scripts/check-packages.sh`.
> chore(harden): Fix dev version nit

- packages/ses/NEWS.md
- packages/ses/src/enablements.js
- packages/ses/test/enable-property-overrides.test.js
This adds `FunctionPrototype.apply`, as well as `.message` for all the
various Error prototypes, to the enablements list.
This allows tape-4.x to be imported after lockdown, as well as fixing tape's
t.throws() method.
refs #293, but does not close it because tape-5.x is still broken
Note: this currently fails local tests, I think because we have assertions that these items are *not* on the list. I'd appreciate some pointers as to how to fix these.
> add enablements to fix tape-4.x

- packages/ses/NEWS.md
- packages/ses/src/compartment-shim.js
- packages/ses/src/whitelist.js
- packages/ses/test/break-function-eval.test.js
- packages/ses/test/compartment-instance.test.js
- packages/ses/test/compartment-prototype.test.js
- packages/ses/test/compartment.test.js
- packages/ses/test/confinement.test.js
- packages/ses/test/global-object-properties.test.js
- packages/ses/test/identity-continuity.test.js
- packages/ses/test/leak-endowments.test.js
- packages/ses/test/leak-unsafe-eval.test.js
- packages/ses/test/ses.test.js
- packages/ses/test/typeof.test.js
- packages/ses/test/whitelist.test.js
This change brings the shim in compliance with the current proposed specification.
> Rename compartment.global to globalThis

- packages/ses/test/import-gauntlet.test.js
- packages/ses/test/import-stack-traces.test.js
- packages/ses/test/import.test.js
This brings the compartment tests in conformance with the style @Chris-Hibbert and I discussed to best signal test completion and ensure that all planned assertions have an opportunity to fail the test. Using async tests precludes the need for calling `end` explicitly (it is implied by the resolution of the returned promise), but `plan` is necessary to ensure a test that goes off the rails fails.
> Use test plan for compartment tests

- packages/ses/NEWS.md
- packages/ses/src/evaluate.js
- packages/ses/src/transforms.js
- packages/ses/test/compartment.test.js
- packages/ses/test/evaluate.test.js
This change simplifies the compartment transforms for evaluated programs to just an array of functions that accept and return program strings.  The previous version of this API enabled transforms to add endowments and left room for future transformable properties.  We have elected to use the compartment `evaluate` function to introduce lexical endowments and `globalThis` to introduce enumerable and computable endowments.
Fixes #321
> fix(ses)!: Simplify transforms

- packages/ses/NEWS.md
- packages/ses/demos/challenge/main.js
- packages/ses/src/lockdown-shim.js
- packages/ses/src/tame-global-date-object.js
- packages/ses/src/tame-global-error-object.js
- packages/ses/src/tame-global-math-object.js
- packages/ses/src/tame-global-reg-exp-object.js
- packages/ses/test/lockdown-allow.test.js
- packages/ses/test/lockdown-options.test.js
- packages/ses/test/lockdown.test.js
- packages/ses/test/tame-date-allow.test.js
- packages/ses/test/tame-error-allow.test.js
- packages/ses/test/tame-global-date-object-allow.test.js
- packages/ses/test/tame-global-error-object-allow.test.js
- packages/ses/test/tame-global-math-object-allow.test.js
- packages/ses/test/tame-global-reg-exp-object-allow.test.js
- packages/ses/test/tame-math-allow.test.js
- packages/ses/test/tame-rexexp-allow.test.js
First step towards fixing #326 , suitable for a transitional release where we accept both old and new style taming options.
For each old `noTameFoo` option, replace with a `fooTaming` option. Where the old style was boolean defaulting to false, the new style starts with `'safe'` and `'unsafe'` choices, defaulting to `'safe'`. This allows some options to grow further choices in the future.
> fix(326): accept old and new taming options during transition

- packages/endo/DESIGN.md
- packages/endo/README.md
This change submitted for design review, ahead of subsequent implementation.
The primary objective for `endo` is to relieve `agoric-sdk` of the need to use `rollup` for an application with modules to be executable under SES. This in turn will allow us to limit the endowments that are passed to modules in each package individually, instead of the blanketing the application as a whole.
The scope of the following implementation includes only support for ESM modules in Node.js packages that explicitly mark their exported modules with the `main` or `exports` properties, where all compartments are in a shared frozen realm and third-party packages receive no powerful modules or endowments. Further work is needed for CommonJS, packages with implicitly public modules, source-to-source module …
> feat(endo): Add Endo README and DESIGN

- .eslintrc.json
- packages/endo/REMOVEME.js
- packages/endo/package.json
- packages/endo/src/node-module-specifier.js
- packages/endo/src/url.js
- packages/endo/test/join.test.js
- packages/endo/test/relative.test.js
- packages/endo/test/relativize.test.js
- packages/endo/test/resolve.test.js
The `url.js` module implements `relative(referrer, specifier)` to reconstruct a relative path between two URLs. This is useful for creating references in a `compartmap.json` that are normalized relative to the root of an archive.
The remaining `module-specifier.js` provides three functions for manipulating Node.js packaged module specifiers.
The Node.js package.json allows relative or absolute module specifiers
like `"main": "./index.js"` or `"main": "index.js"`.
The `relativize` function normalizes all such paths to their relative
form since Endo compartments use absolute specifiers for external
linkage and relative specifiers for internal linkage.
It is not possible for `package.json` to express a module specifier
that refers to a module in another package.
The join function joins an …
> feat(endo): Module specifier and URL math

- packages/ses/src/lockdown-shim.js
- packages/ses/src/tame-global-date-object.js
- packages/ses/src/tame-global-error-object.js
- packages/ses/src/tame-global-math-object.js
- packages/ses/src/tame-global-reg-exp-object.js
- packages/ses/src/whitelist.js
- packages/ses/test/tame-date-allow.test.js
- packages/ses/test/tame-date.test.js
- packages/ses/test/tame-global-date-object-allow.test.js
- packages/ses/test/tame-global-date-object.test.js
- packages/ses/test/tame-global-error-object-allow.test.js
- packages/ses/test/tame-global-error-object.test.js
- packages/ses/test/tame-global-math-object-allow.test.js
- packages/ses/test/tame-global-math-object.test.js
- packages/ses/test/tame-global-reg-exp-object-allow.test.js
- packages/ses/test/tame-global-reg-exp-object.test.js
- packages/ses/test/whitelist-intrinsics.test.js
- packages/ses/test262/tame-global-date-object.js
- packages/ses/test262/tame-global-error-object.js
- packages/ses/test262/tame-global-math-object.js
- packages/ses/test262/tame-global-regexp-object.js
Minimal subset of intrinsic reform, preparing to improve the error taming in a subsequent PR.
Each of the `tameGlobalFooObject` repair functions no longer modifies `globalThis` itself. Rather, it returns a record of the binding[s] to be added to the start compartment global, and the binding[s] to be added to the shared globals for all other compartments by default. It is up to the caller to figure out what to so with the contents of this record. This also makes unit tests more straightforward.
While fixing the repairs, there was ad-hoc partial suppression of some of the locale methods. Instead, we simply suppress all of these in the whitelist.
> fix: partial intrinsic reform

- packages/ses/src/check-anon-intrinsics.js
- packages/ses/src/commons.js
- packages/ses/src/compartment-shim.js
- packages/ses/src/enable-property-overrides.js
- packages/ses/src/get-anonymous-intrinsics.js
- packages/ses/src/get-named-intrinsic.js
- packages/ses/src/intrinsics-global.js
- packages/ses/src/lockdown-shim.js
- packages/ses/src/module-instance.js
- packages/ses/src/module-link.js
- packages/ses/src/module-load.js
- packages/ses/src/module-proxy.js
- packages/ses/src/realm-rec.js
- packages/ses/src/repair-legacy-accessors.js
- packages/ses/src/tame-function-constructors.js
- packages/ses/src/tame-global-date-object.js
- packages/ses/src/tame-global-error-object.js
- packages/ses/src/tame-global-math-object.js
- packages/ses/src/tame-global-reg-exp-object.js
- packages/ses/src/whitelist-intrinsics.js
The first commit downsizes the use of defineProperties to defineProperty in enablements because this is more clearly appropriate.
The second commit ensures that all modules use commons.js as the source of Object functions, ensuring that we always use the patched defineProperty as a matter of style and for other possible knock-on benefits.
> ses(fix): Repair defineProperty internally

- packages/endo/src/infer-exports.js
Packages may export any number of modules.
In package.json, a library developer can specifically call out a "main"
module to represent the package as a whole.
For example, "./src/main.js" for the package named "ses" exports a
module simply named "ses" that refers to "./src/main.js" in the "ses"
package.
What modules a package exports may depend on the "tags" of the host
environment, like "import" for environments that support ECMAScript
modules, "require" for environments that only support CommonJS modules,
or "browser" for web front-ends.
The "browser" property in "package.json" overrides "main" when the
"browser" build tag is present.
The "browser" property has broad adoption, starting with first
packages to lean on Browserify.
Most packages technically export every one of their modules …
> feat(endo): Infer the module map a package exports

- packages/ses/src/tame-global-error-object.js
- packages/ses/src/whitelist.js
- packages/ses/test/error-manipulation.test.js
- packages/ses/test/tame-error-allow.test.js
- packages/ses/test/tame-error.test.js
- packages/ses/test/tame-global-error-object.test.js
An initial taming of the Error constructor that should both be safe enough and compat enough for cases we've seen.
Build on the partial-intrinsic-reform branch, which set the stage.
Current a Draft PR because none of this is tested yet.
> fix: tame Error constructor

- packages/ses/src/tame-global-error-object.js
- packages/ses/test/callsite-properties.test.js
- packages/ses/test/install-ses-safe.js
- packages/ses/test/install-ses-unsafe.js
- packages/ses/test/tap-after-safe-lockdown.test.js
- packages/ses/test/tap-after-unsafe-lockdown.test.js
As explored in #367, the `source-map-support` library (used by the same `tap` test framework we use here in SES-shim) relies upon some `callSite` behavior that we were not providing when in `errorTaming: 'unsafe'` mode.
This PR exposes more properties in the `callSite` objects that we give to the user's `Error.prepareStackTrace` replacement function. `isToplevel`, `isNative`, `getPosition`, and `getScriptNameOrSourceURL` are now revealed. I believe these only violate confidentiality (just like the previous `getFileName`, etc), and will not violate integrity.
It also puts all these properties on the callSite's prototype, not on the callSite object itself. `source-map-support` enumerates the prototype's properties to see what it should copy in the wrapper that *it* makes, and it wasn't able …
> expose more callSite properties, put them on the prototype

- packages/ses/index.d.ts
- packages/ses/package.json
Simple little hack to get `harden` well-typed in source files that contain:
```js
/// <reference types="ses"/>
```
> docs: add typings for SES's global harden()

- packages/ses/NEWS.md
> chore: update ses/NEWS with properties removed in 0.9.0

- packages/ses/NEWS.md
- packages/ses/src/lockdown-shim.js
- packages/ses/src/tame-locale-methods.js
- packages/ses/src/whitelist.js
- packages/ses/test/tame-locale-methods-allow.test.js
- packages/ses/test/tame-locale-methods.test.js
Rather than removing the `*Locale*` methods, replace them with their non-locale equivalents.
`String.prototype.localeCompare` doesn't seem to have a builtin non-locale equivalent, so we provide one.
Fixes #335 
Fixes #378 
See #379 
See https://github.com/Agoric/agoric-sdk/issues/1290
> fix: restore locale methods safely

- packages/endo/src/compartmap.js
The compartmentMapForNodeModules function gathers a graph of all the
package.json files for the transitive dependencies of one package,
then translates this into a "compartment map".
A "compartment map" describes a DAG of compartments, linked by arbitrary
names.
Every entry in the compartment map provides all the information Endo
needs to construct a SES Compartment, assuming that the compartment will
use a Node.js-compatible resolveHook and an importHook that knows where
to find the corresponding package's files, based on their root path.
The compartment map shape will be used by the compartment assembler
for executing applications directly from the file system, for building
archives, and for running applications in archives.
> feat(endo): Add compartmap

- packages/endo/src/search.js
A Node.js application is a module and its transitive dependencies.
To provide as close an approximation of Node.js, running an Endo
application is also the importing of an entry module.
To construct the compartment graph for the module, the search
function starts with a path to the module and searches for
the first parent directory that contains a "package.json".
Node.js does not require there to be a "package.json".
Neither do web applications using ESM or Deno applications.
This is a constraint that we might relax in a future version by creating
a special compartment for entry modules.
> feat(endo): Add search

- packages/endo/src/assemble.js
- packages/endo/src/compartmap.js
The compartment assembler takes a compartment map and builds the
corresponding compartment instances, feeding the modules exported by
each dependency into the dependee compartment's module map.
> feat(endo): Add assemble

- packages/endo/src/assemble.js
- packages/endo/src/import.js
The import function most directly models the Node.js command line:
pass the path to the entry module and the capability to read files on
the corresponding file system.
Importing a module creates a compartment graph and executes the entry
module of the root compartment.
> feat(endo): Add import

- packages/endo/src/zip.js
Our current archive format of choice is Zip.  Our current implementation of choice is stuk/jszip.  Endo's functions that interact with archives assume an Archive interface with read, write, data, and a from-data constructor.  To decouple Endo's internals from the specifics of JSZip, this thin adapter presents the JSZip API as this Archive interface.
> feat(endo): Add zip

- packages/ses/src/commons.js
- packages/ses/src/tame-error-constructor.js
- packages/ses/test/v8-callsite-properties.test.js
Fixes #370 
When we make an error by calling `new` on either of our replacement `Error` constructors, it calls the original `Error` constructor to make the error. Thus, the replacement `Error` constructor is on the stack above the creation of the new error object. This is exactly the problem that v8 designed `Error.captureStackTrace` to solve, and we solve it using their suggested pattern. The price of this pattern is that the stack trace is reified into a structured-stack-trace (sst) immediately rather than on demand. However, rendering the sst as a string is still on demand as intended.
> fix: remove extra stackframe

- packages/ses/NEWS.md
- packages/ses/src/compartment-shim.js
- packages/ses/src/whitelist.js
- packages/ses/test/compartment-instance.test.js
- packages/ses/test/compartment-prototype.test.js
This change surfaces the `load` function so compartments can be used to create archives without executing any of the assembled modules.
> feat(ses): Add Compartment load function

- packages/ses/src/compartment-shim.js
- packages/ses/src/global-object.js
- packages/ses/src/lockdown-shim.js
- packages/ses/src/make-eval-function.js
- packages/ses/src/make-function-constructor.js
- packages/ses/src/tame-function-constructors.js
- packages/ses/src/tame-function-tostring.js
- packages/ses/src/whitelist-intrinsics.js
- packages/ses/src/whitelist.js
- packages/ses/test/compartment-constructor.test.js
- packages/ses/test/compartment-instance.test.js
- packages/ses/test/global-object.test.js
- packages/ses/test/module-static-record.test.js
Rather than add a bunch of add hoc `toString` methods to try to make shimmed methods appear native, instead tame `Function.prototype.toString` to do a brand check on whether a function is an honorary native function. Have the whitelisting machinery apply this brand to every surviving function encountered during whitelisting.
> fix: consolidate honorary native function printing

- packages/ses-integration-test/package.json
- packages/ses-integration-test/scaffolding/rollup/rollup.config.test.js
- packages/ses-integration-test/transform-tests/config/rollup.config.cjs.js
- packages/ses-integration-test/transform-tests/config/rollup.config.esm.js
- packages/ses-integration-test/transform-tests/config/rollup.config.no-lib.js
- packages/ses/package.json
- packages/ses/rollup.config.js
- packages/ses/src/compartment-shim.js
This plugin eliminates the problem I previously encountered with importing standalone Babel idiomatically. It sadly does not redress our fork of standalone Babel, because we still need to cull  dependencies that do not play well with lockdown.
> fix(ses): Use CommonJS Rollup plugin

- packages/endo/src/archive.js
The archive module is a variation on the import module.
After loading a compartment graph off disk, instead of executing the
entry module, it creates a Zip archive of the working set of modules
and a compartment map.
The bulk of the work in archiving is rewriting the compartment map
to match the archive layout.
Instead of having packages scattered hierarchically on the file system,
the archive has a single directory for each compartment.
The compartment names are arbitrary, but must be unique and ideally
human-readable, so the format is name@version#unique.
> feat(endo): Add archive

- packages/endo/src/import-archive.js
Running an application mostly uses the same parts needed to run the
original application from disk.
Instead of building a compartment map, we just deserialize the
ready-made compartmap.json from the archive.
We use the same compartment assembler, but with importHooks backed by
the archive instead of the file system.
> feat(endo): Add import-archive

- packages/harden/package.json
- packages/make-hardener/package.json
- packages/make-importer/package.json
- packages/ses/package.json
- packages/transform-module/package.json
This is needed by tooling like Rollup, when used in conjunction
with the latest Node 12.x and 14.x branches.
Without this PR, we get failures of the following form:
```
$ rollup -c
src/main.js → public/build/bundle.js...
[!] (plugin svelte) Error: Package subpath './package.json' is not defined by "exports" in /Users/michael/agoric/agoric-sdk/packages/simple-wallet/node_modules/@agoric/harden/package.json
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /Users/michael/agoric/agoric-sdk/packages/simple-wallet/node_modules/@agoric/harden/package.json
at applyExports (internal/modules/cjs/loader.js:490:9)
at resolveExports (internal/modules/cjs/loader.js:506:23)
at Function.Module._findPath (internal/modules/cjs/loader.js:634:31)
at …
```
> chore: update package.jsons to allow import of themselves

- packages/ses/NEWS.md
- packages/ses/README.md
- packages/ses/src/compartment-shim.js
- packages/ses/src/module-instance.js
- packages/ses/src/module-link.js
- packages/ses/src/module-load.js
- packages/ses/test/import-cjs.test.js
- packages/ses/test/import-non-esm.js
This change includes a sequence of refactoring commits that fully decouple the `load` and `execute` phases of importing modules. The `load` phase only considers the superficial `imports` field of a static module record, which is the same for both first-party ESM and third-party static module records. The `execute` phase then treats these types of static module record according to their type.
In validating a static module record, we take care to provide the most informative error message, particularly to distinguish the case where a `StaticModuleRecord` may have crossed realms and the SES-shim could not see its “internal” fields. This is distinguishable because such records have `imports` and no `execute` method, implying that there *should* be internal fields associated with the record. …
> feat(ses): Add support for third-party modules

- packages/error-stack-shim/package.json
This addresses an error introduced in the release of harden@0.1.0 where
the version was concurrently bumped for error-stack-shim, to a version
that no longer works.
> fix(error-stack-shim): Address version limit for harden

- packages/ses/NEWS.md
- packages/ses/package.json
- packages/ses/rollup.config.js
- packages/ses/src/compartment-shim.js
- packages/ses/src/get-anonymous-intrinsics.js
- packages/ses/src/inert.js
- packages/ses/src/lockdown-main.js
- packages/ses/src/lockdown-shim.js
- packages/ses/src/main.js
- packages/ses/test/lockdown-options.test.js
This change creates a `ses/lockdown` entry module that serves as a thin layer that provides only `lockdown` and `harden`, is significantly lighter in bytes, and is sufficient for some uses of SES.
A future version may introduce a thin layer of `Compartment` with `evaluate` (but lacking a module system) since this is a sufficient runtime target for any application and doesn’t entrain a JavaScript module parser.
Toward removing `lockdown` dependency on `Compartment`, the inert constructors for `Compartment` and `StaticModuleRecord` shift into a stand-alone module that both can depend upon.
> feat(ses): Create a thin lockdown layer

- packages/ses/src/whitelist-intrinsics.js
Actual author @kriskowal , repairing a bug reported by @michaelfig .
I (@erights) am surprised this fix is needed. I thought the whitelist already did this.
> Make the whitelist tolerant of the absence of expected things

- packages/ses/src/intrinsics.js
Follow up to #407
Because `StaticModuleRecord` was listed in the whitelist's `universalPropertyNames` but was absence from the global, the old
```js
newIntrinsics[intrinsicName] = globalObject[globalName];
```
was creating a property on `newIntrinsics` named `StaticModuleRecord` with value `undefined`. This PR adds a check so that absent properties on `globalObject` skip the above assignment.
> fix: tolerate whitelist absence better

- packages/ses/lockdown.js
- packages/ses/package.json
- packages/ses/rollup.config.js
- packages/ses/ses.js
- packages/ses/src/lockdown-main.js
- packages/ses/test/compartment-constructor.test.js
- packages/ses/test/compartment.test.js
- packages/ses/test/global-lexicals-evaluate.test.js
- packages/ses/test/global-lexicals-modules.test.js
- packages/ses/test/harden.test.js
- packages/ses/test/import-cjs.test.js
- packages/ses/test/import-non-esm.js
- packages/ses/test/install-ses-safe.js
- packages/ses/test/install-ses-unsafe.js
- packages/ses/test/lockdown-allow.test.js
- packages/ses/test/lockdown.test.js
- packages/ses/test/module-static-record.test.js
- packages/ses/test/nesting.test.js
- packages/ses/test/property-override.test.js
- packages/ses/test/ses.test.js
- packages/ses/test/tame-date.test.js
- packages/ses/test/tame-locale-methods-unsafe.test.js
- packages/ses/test/tame-locale-methods.test.js
- packages/ses/test/tame-math.test.js
- packages/ses/test/tame-rexexp.test.js
- packages/ses/test/tame-v8-error-unsafe.test.js
- packages/ses/test/tame-v8-error.test.js
- packages/ses/test/v8-callsite-properties.test.js
- packages/ses/test/whitelist-intrinsics.test.js
- packages/ses/test/whitelist.test.js
This change moves the entry points for `ses` to the top-level such that systems that do not recognize the `exports` property in `package.json` will still be able to `import "ses/lockdown"` as if they did.  This makes our guidance for importing the lockdown layer more universal.
> fix(ses): Generally import "ses/lockdown"

- packages/ses/src/enable-property-overrides.js
The override mistake is supposed to emulate the way assignment should have worked in the absence of the override mistake. Before this PR, when an assignment would have created a new property, the emulated assignment creates a property that inherits the enumerability and configurability of the property being overridden. But new properties actually created by assignment don't do that. They start with `writable`, `enumerable`, and `configurable` all true.
This PR still needs tests.
> fix: correct fix for override mistake

- packages/ses/NEWS.md
- packages/ses/src/whitelist.js
This is a temporary fix until lockdown gets a more disciplined way of updating the whitelist with vetted shims.  In any event, it is a step toward `Promise.delegate`, but that standard hasn't yet been implemented in `@agoric/eventual-send/shim`.
@kriskowal Please update and release a new patch version of `ses`, so that we can use this in agoric-sdk.
> fix(ses): Add HandledPromise to the whitelist

- packages/ses/NEWS.md
- packages/ses/src/compartment-shim.js
- packages/ses/src/module-load.js
- packages/ses/test/import.test.js
Adds a `moduleMapHook` option to the `Compartment` constructor options.  The module map hook can return values for the `moduleMap` for any given module specifier, or return `undefined` to fall back to the `importHook`.  This allows for wildcard linkage to other compartments.
> feat(ses): Add moduleMapHook

- packages/ses/src/scope-handler.js
@FUDCo  has seen the `getOwnPropertyDescriptor` trap happen on the scopeHandler under the v8/Chrome debugger, but not otherwise. This PR adds the same kind of workaround we did for the `getPrototypeOf` trap for a Safari bug --- immediately above the code for this new one.
Until we know how to reproduce, we cannot test if this PR helps. @FUDCo , if you could give feedback as part of review? Thanks.
> Workaround v8 debugger bug

- packages/endo/README.md
- packages/endo/src/archive.js
- packages/endo/src/lockdown.js
When a module imports `./alice`, this implies either `./alice.js` or `./alice/index.js`. This change scans for a matching module.
Ideally we would not need to do this, but it is required for Node.js parity. In a subsequent change, it may be possible to rewrite the “compartment map” into a more detailed “module map”, with details for every module in an archives working set, so this probing only occurs when running an application outside of an archive or constructing an archive, not running an archived application.
> feat(endo): Search for .js or /.index.js

- packages/endo/README.md
- packages/endo/src/archive.js
- packages/endo/src/assemble.js
- packages/endo/src/compartmap.js
- packages/endo/src/import-archive.js
- packages/endo/src/import.js
- packages/endo/src/infer-exports.js
- packages/endo/src/parse-requires.js
- packages/endo/src/parse.js
- packages/endo/test/main.test.js
- packages/endo/test/node_modules/danny/main.js
- packages/endo/test/node_modules/danny/package.json
- packages/endo/test/node_modules/typehybrid/README.md
- packages/endo/test/node_modules/typehybrid/main.js
- packages/endo/test/node_modules/typehybrid/meaning.js
- packages/endo/test/node_modules/typehybrid/package.json
If a package is not of "type": "module", but does provide a "module": e.g., "./main.js, the ".js" extension implies CommonJS but the property implies that "./main.js" is a ECMAScript module.  This change allows the module field to override the package type.
> feat(endo): Infer module type from package.json "module"

- packages/endo/DESIGN.md
- packages/endo/src/archive.js
- packages/endo/src/assemble.js
- packages/endo/src/compartmap.js
- packages/endo/src/import-archive.js
- packages/endo/src/import.js
- packages/endo/src/module-map-hook.js
- packages/endo/src/parse.js
- packages/endo/src/zip.js
- packages/endo/test/main.test.js
- packages/endo/test/node_modules/clarke/TODO
- packages/endo/test/node_modules/danny/main.js
- packages/endo/test/node_modules/danny/package.json
When asked for a module named "x", Node.js will search for "x.js" then "x/index.js".
For packages that do not supply an "exports" property in their "package.json", any module contained by that package is a valid exported module.
To achieve parity with these two features, Endo uses different techniques when loading from the file system and loading from an archive.
When reading from the file system, Endo will search for a satsifactory candidate in each compartment's asynchronous importHook.  Endo also uses the compartment's new moduleMapHook to search for dependency compartments in the "scope" of a module identifier prefix.  These allow Endo to operate from an incomplete compartment map for the initial load.
The Endo archiver instead creates a more complete compartment map, with every …
> feat(endo): Search for index.js and implied package exports

- packages/endo/src/archive.js
- packages/endo/src/compartmap.js
- packages/endo/src/import-archive.js
- packages/endo/src/import.js
- packages/endo/src/json.js
- packages/endo/src/parse.js
- packages/endo/src/search.js
This change annotates JSON syntax errors with the location of the originating file throughout Endo.
> feat(endo): Improve JSON file parse error messages

- packages/ses/NEWS.md
- packages/ses/README.md
- packages/ses/src/module-load.js
- packages/ses/test/import.test.js
This change enables importHook to return a record for a module that has a different specifier than the requested module specifier.  This enables the Node.js pattern of redirecting `name` to `name/index.js` and respecting the latter name as the referrer for its own imports.
> feat(ses): Support importHook alias returns

- packages/endo/src/archive.js
- packages/endo/src/import-hook.js
- packages/endo/src/import.js
This change observes considerable duplication between the import hook for loading off the file system and recording a load off the file system for archives. This was conscionable when they were small, but searching for `index.js` complicates these. The side-effect of recording some metadata on the fly is okay for now. The records are immediately eligible for GC when running off the filesystem. This could be transformed to a system of hooks within hooks if it becomes problematic.
> refactor(endo): Consolidate archive and import hooks

- packages/endo/src/archive.js
This broke the correspondence between locations in compartmap.json and what actually existed in a zip file. The cost of this change is the possibility of ambiguity for some special symbols in path components.
> fix(endo): Do not URL encode compartment and path within archives

- packages/endo/src/assemble.js
- packages/ses/NEWS.md
- packages/ses/README.md
- packages/ses/src/compartment-shim.js
- packages/ses/src/module-load.js
- packages/ses/src/whitelist.js
- packages/ses/test/compartment-instance.test.js
- packages/ses/test/compartment-prototype.test.js
This is a follow-on from #431 which was accidentally reported as merged by Github, on the perception that it had merged into its feature branch, not onto the main branch. Review feedback captured in the second commit.
> feat(ses): Carry compartment names in error messages

- packages/ses/src/tame-error-constructor.js
- packages/ses/src/whitelist.js
A more natural home for this list, especially if anything else reuses it. 
For example
https://github.com/Agoric/agoric-sdk/blob/c43a08fb1733596172a7dc5ca89353d837033e23/packages/marshal/marshal.js#L136-L144
duplicates this list. Once we move marshal.js into the SES-shim monorepo we should have it import NativeErrors to build this map.
> fix: Move NativeErrors list to whitelist.js

- .eslintrc.json
- packages/ses/src/compartment-shim.js
- packages/ses/src/enable-property-overrides.js
- packages/ses/src/tame-math-object.js
- packages/ses/test/property-override.test.js
Added to SES-shim all lint rules it was missing from agoric-sdk.
Did not yet remove any lint rules that are only in SES-shim. We might want to propagate some of these back to agoric-sdk.
> fix: towards reconciling lint rules with agoric-sdk

- packages/ses/lockdown.js
- packages/ses/ses.js
- packages/ses/src/compartment-shim.js
- packages/ses/src/module-shim.js
- packages/ses/test/break-function-eval.test.js
- packages/ses/test/compartment-instance.test.js
- packages/ses/test/compartment-prototype.test.js
- packages/ses/test/confinement.test.js
- packages/ses/test/global-object-mutability.test.js
- packages/ses/test/global-object-properties.test.js
- packages/ses/test/identity-continuity.test.js
- packages/ses/test/import-gauntlet.test.js
- packages/ses/test/import-stack-traces.test.js
- packages/ses/test/import.test.js
- packages/ses/test/module-compartment-instance.test.js
- packages/ses/test/module-compartment-prototype.test.js
- packages/ses/test/reject-direct-eval.test.js
- packages/ses/test/reject-html-comment.test.js
- packages/ses/test/reject-import-expression.test.js
- packages/ses/test/typeof.test.js
- packages/ses/test262/compartment-shim.js
Following on the SES-lite change, this is a smaller change that moves code that modifies the environment out of `src` and into the two shim entry-points, to make the separation between these layers more clear.
> refactor(ses): Detangle shims from modules

- packages/transform-module/README.md
- packages/transform-module/src/main.js
This change makes transform-module's `moduleAnalysis` consistent with the term used in the SES module shim, which creates a `staticModuleRecord` from this internal representation.
> refactor(transform-module): Rename module analysis

- package.json
- packages/assert/exported.js
- packages/assert/jsconfig.json
- packages/assert/package.json
- packages/assert/rollup.config.js
- packages/assert/src/assert.js
- packages/assert/src/main.js
- packages/assert/src/types.js
- packages/console/jsconfig.json
- packages/console/package.json
- packages/console/src/console.js
- packages/console/src/types.js
- yarn.lock
This contains several fixes to avoid `@ts-ignore`s.
Merging with #447.
> refactor: improve types for assert/console

- .github/workflows/ci.yml
- package.json
- yarn.lock
@kriskowal is there a reason why the `"engine"` field was set to `">13.0.0"`?
We should not be gratuitously incompatible.
> chore: test with same Node.js as agoric-sdk (supported for AVA)

- packages/compartment-mapper/README.md
- packages/compartment-mapper/package.json
- packages/compartment-mapper/src/archive.js
- packages/compartment-mapper/src/assemble.js
- packages/compartment-mapper/src/import-archive.js
- packages/compartment-mapper/src/node-modules.js
This is a minor adjustment to the schema of a compartment map that replaces the “main” compartment and “entry” module properties with a single “entry” object that rhymes with the `CompartmentModule` type used in compartment module maps.
> refactor(compartment-mapper): Compartment map has "entry"

- packages/compartment-mapper/README.md
- packages/compartment-mapper/package.json
- packages/compartment-mapper/src/archive.js
- packages/compartment-mapper/src/assemble.js
- packages/compartment-mapper/src/import-archive.js
- packages/compartment-mapper/src/import.js
- packages/compartment-mapper/src/node-modules.js
- packages/compartment-mapper/test/main.test.js
This change better aligns "applications" (compartments comprised of a
graph of linked peer compartments) with the Compartment type itself.
> refactor(compartment-mapper): Rename application execute to import

- packages/compartment-mapper/package.json
- packages/compartment-mapper/rollup.config.js
- yarn.lock
We have no coherent story for threading UMD dependencies on Node.js built-in modules.
We also have a mystery as to why Rollup feels that it needs to link any Node.js built-in modules.  The dependencies may be coming from using Babel parser and translate.
> fix(compartment-mapper): Withdraw UMD Rollup

- packages/ses/NEWS.md
- packages/ses/lockdown.js
- packages/ses/ses.js
- packages/ses/src/get-anonymous-intrinsics.js
- packages/ses/src/lockdown-shim.js
- packages/ses/test/compartment-prototype.test.js
- packages/ses/test/lockdown-options.test.js
- packages/ses/test/whitelist-intrinsics.test.js
This change divides the anonymous intrinsics into the lockdown+compartment and compartment+module layers.
Fixes #467
> fix(ses): Fix lockdown layer pollution from module layer

- packages/ses/src/enable-property-overrides.js
- packages/ses/src/lockdown-shim.js
- packages/ses/test/frozen-primordials.test.js
Addresses https://github.com/ljharb/object.assign/issues/79 . Attn @ljharb . Please feel free to leave review comments. Question for you at the bottom of this note.
This reverts the enable-property-override mechanism to stop using the detached-properties mechanism and instead go back to the original strategy --- putting the original value on an own property of the getter function of the new accessor. However, rather than name this extra property `.value` as Caja did, we name it with the registered symbol `Symbol.for('originalValue')`. We export this symbol, but we also make it a registered symbol so it can be used by reconstructing it rather than importing it. By exposing the original value on any own property, `harden` still finds it and its transitive walk proceeds.
We give the property …
> fix: no more detached properties

- packages/ses/src/enablements.js
- packages/ses/test/enable-property-overrides.test.js
Fixes #474 
Removes `Function.prototype.apply` from the enablements whitelist, of properties that need the override mistake fixed. This particular entry said it was because `tape` broke. But @ljharb , the maintainer of tape, said that it should not have a problem with `apply`. After removing it, our existing tests work just fine. But (question for reviewers) do any of them use tape in a way that would detect a remaining problem if there is one?
> fix: remove "apply" from enablements whitelist

- packages/ses/NEWS.md
- packages/ses/README.md
- packages/ses/src/enable-property-overrides.js
- packages/ses/test/frozen-primordials.test.js
Rename `originalDataPropertyValue` to `originalValue`.
Explain in README and NEWS.
> Suppress override mistake with `originalValue` on getter

- packages/compartment-mapper/NEWS.md
- packages/compartment-mapper/README.md
- packages/compartment-mapper/src/assemble.js
- packages/compartment-mapper/src/import-archive.js
- packages/compartment-mapper/src/import.js
- packages/compartment-mapper/test/main.test.js
- packages/compartment-mapper/test/node_modules/app/main.js
- packages/compartment-mapper/test/node_modules/evaluator/evaluator.js
- packages/compartment-mapper/test/node_modules/evaluator/package.json
- packages/compartment-mapper/test/transform.test.js
Previously, the `import` methods provided by the compartment mapper accepted `endowments` and `modules` as positional arguments. With this sequence of changes, they ultimately accept an options bag instead, consisting of options named `globals` (instead of `endowments`), `globalLexicals`, `modules`, `transforms`, and a `Compartment` constructor override.
Commits are individually reviewable and may be rebase-merged instead of squash-merged.
*Aside:* This leaves open the design question of threading module transforms and/or module censors. Module transforms potentially alter the import graph, so would need to be applied before archival. These would be running on behalf of the publisher, not the executor, making them an inadequate foundation for censoring. We could also support module …
> compartment-mapper: Thread transforms through import options bag

- packages/ses/lockdown.js
- packages/ses/ses.js
- packages/ses/src/tame-function-tostring.js
Previously, the multiple calls to `tameFunctionToString` were adding redundant layers of indirection. This was correctness preserving but unnecessary. Add a bit of logic so secondary calls reuse the results of the first call.
> fix: flatten tameFunctionToString

- .eslintrc.json
- packages/ses/test262/compartment-shim.js
- packages/ses/test262/repair-legacy-accessors.js
- packages/ses/test262/tame-global-date-object.js
- packages/ses/test262/tame-global-error-object.js
- packages/ses/test262/tame-global-math-object.js
- packages/ses/test262/tame-global-regexp-object.js
In keybase @katelynsills said:
Btw, the way to turn off the annoying red squigglies in tests when they tell you something you import should be a real dependency is this ESLint setting:
```js
"import/no-extraneous-dependencies": [
"error",
{
"devDependencies": true
}
]
```
This PR does that.
> fix: eslint rule to suppress bogus dependency warning

- packages/compartment-mapper/README.md
Per a conversation at the SES Strategy meeting, this fixes a few points of confusion in the Compartment Mapper workflow diagram. The subtle distinction of `+` was too confusing, so removed. `loadLocation` stops before assembling a compartment graph, so the application artifact _can_ be reused. `parseArchive` does not read modules from the file system.
On the bright side, the audience to the presentation of this graph *was* able to follow the meaning diagram closely enough to illuminate its mistakes!
> docs(compartment-mapper): Fix diagram nits

- packages/ses/NEWS.md
- packages/ses/README.md
- packages/ses/src/compartment-shim.js
- packages/ses/src/module-instance.js
- packages/ses/src/module-shim.js
- packages/ses/test/compartment-transforms.test.js
This is a non-standardizable short-cut that allows a compartment to be constructed with a single chain of Program construction to Program construction transforms that apply both to evaluated expressions within the compartment and imported modules **after** they have been converted from Module to Program constructions. This reveals an implementation detail of SES-shim but does not compromise security, since the evaluator provides the foundation for our security guarantees.
> feat(ses): Add __shimTransforms__ Compartment option

- packages/compartment-mapper/NEWS.md
- packages/compartment-mapper/src/assemble.js
- packages/compartment-mapper/src/import-archive.js
- packages/compartment-mapper/src/import.js
- packages/ses/src/compartment-shim.js
- packages/ses/test/compartment-transforms.test.js
This addresses a bug fix in SES, the corresponding fix for the test that revealed the bug, and also threads this new option through the Compartment Mapper machinery.
> fix: Fully thread __shimTransforms__ through Compartment Mapper and SES

- packages/compartment-mapper/NEWS.md
- packages/compartment-mapper/src/import-archive.js
- packages/compartment-mapper/src/import.js
- packages/compartment-mapper/src/zip/format-reader.js
- packages/compartment-mapper/src/zip/format-writer.js
This change puts a ring of parentheses on calls to `import`, and inlines type definitions for buffered reader and writer to avoid using `import` at all in TypeScript JSDoc type annotations.
> fix(compartment-mapper): Work around dynamic import censoring

- packages/compartment-mapper/NEWS.md
- packages/compartment-mapper/src/import-archive.js
- packages/compartment-mapper/src/import.js
The prior tack was simplified away when round-tripped through certain Babel transforms. I don’t believe we’ve arrived at a principled stance to how to press this code through the Agoric SDK consistently, but this one gets us farther for now.
> fix(compartment-mapper): Different tack to evade SES import censor

- packages/ses/ERRORS.md
- packages/ses/NEWS.md
- packages/ses/src/compartment-shim.js
- packages/ses/src/evaluate.js
- packages/ses/src/module-instance.js
- packages/ses/src/transforms.js
- packages/ses/test/reject-direct-eval.test.js
- packages/ses/test/reject-html-comment.test.js
- packages/ses/test/reject-import-expression.test.js
This should permit a more graceful debugging experience for censorship errors.
> feat(ses): Censorship error messages may now contain the source name

- packages/ses/NEWS.md
- packages/ses/src/compartment-shim.js
- packages/ses/src/evaluate.js
- packages/ses/src/get-source-url.js
- packages/ses/src/module-instance.js
- packages/ses/src/transforms.js
- packages/ses/test/get-source-url.test.js
- packages/ses/test/reject-direct-eval.test.js
- packages/ses/test/reject-html-comment.test.js
- packages/ses/test/reject-import-expression.test.js
This change allows SES to surface the alleged file name for a censorship error.
A future change might use the same internals to surface syntax errors from the StaticModuleRecord constructor instead of receiving a second location argument.
> feat(ses): Retract evaluate name option, use sourceURL

- .github/workflows/depcheck.yml
- package.json
- packages/compartment-mapper/package.json
- packages/endo/package.json
- packages/make-hardener/package.json
- packages/make-importer/package.json
- packages/make-simple-evaluate/package.json
- packages/ses-integration-test/package.json
- packages/ses/package.json
- packages/test262-runner/package.json
- packages/transform-module/package.json
- scripts/check-mismatched-dependencies.js
- scripts/check-packages.sh
- scripts/repackage.sh
This ports the dependency checker from agoric-sdk to ensure we don’t break the invariant again that dependencies in the project depend on version predicates satisfied by the versions checked into the repository.
> chore: Add dependency consistency checker

- packages/ses/src/enable-property-overrides.js
If the value of `prop` is a symbol `${prop}` throws whereas `${String(prop)}` produces a pleasing diagnostic. Should only be used to generate diagnostic text since the stringified from of a symbol is a valid string name for a property.
See https://github.com/Agoric/agoric-sdk/pull/2094
> fix: tolerate symbols as property names

- packages/ses/src/whitelist.js
Add to whitelist expectations of seeing most of what we report at https://github.com/Moddable-OpenSource/moddable/issues/523 , but with value `false` so they're still deleted anyway, but silently. Link these to https://github.com/Moddable-OpenSource/moddable/issues/523 to say why these are already expected.
Add new safe elements introduced in ES2021.
In the process I noticed that the section numbers are already stale. They were too fragile anyway, so are now removed. Removed also any comments that said nothing beyond what the code says.
> fix: adapt whitelist to XS. clean it up too

- packages/ses/src/error/assert.js
- packages/ses/src/error/types.js
- packages/ses/test/error/assert-log.test.js
`assert.error` is an obviously missing method. Exactly like `assert.fail` for making an error with associated details. But unlike `assert.fail` it just returns the error rather than throwing it.
Currently the only way to get this effect from outside the assert module is
```js
let err;
try {
assert.fail(d`...`);
} catch (e) {
err = e;
}
```
which would be just horrible.
Motivation:
While debugging a change to https://github.com/Agoric/agoric-sdk/pull/1905 I'm seeing places where we're not logging info we should be due to the lack of this method.
> Add missing assert.error method

- packages/ses/src/error/console.js
- packages/ses/test/error/assert-log.test.js
- packages/ses/test/error/tame-console.test.js
To reduce verbosity in interactive console logs, like the browser's, we had been using `groupCollapsed` for nesting output. This was in addition to logging using `console.debug` which requires verbose output to be turned on. We left the nested output at `console.debug` level, which is adequate to make the normal experience concise. Given that, this PR changes from `groupCollapsed` to `group` so that nested output starts expanded by default but can still be collapsed.
In addition, the label for a group was not terribly informative, and sometimes empty, making it mysterious what to click on. This PR also improves the labels.
> Friendlier nested console output for browsers

- packages/ses/src/error/assert.js
Just found out that a `debugger;` statement in source causes node (or v8 in general?) to deoptimize. Setting a breakpoint on line 170 as already suggested by the comment accomplishes much the same thing. Do removed the `debugger;` statement.
> fix: remove "debugger;" statement

- packages/ses/src/error/assert.js
- packages/ses/src/error/internal-types.js
- packages/ses/src/error/types.js
`packages/ses/src/error/types.js` was missing an `// @ts-check` and so we didn't catch that it also had bad TypeScript types. 
In particular, it no longer had a `DetailsTag` type. The reason that was missing is because I (MarkM) couldn't figure out how to get a `...` rest argument type to work in an `@param` or a `@callback` type. The answer that I found that worked for me is to use a `@typedef` type rather than a `@callback` type.
I'm not sure what the intended scope of #161 is, but it at least reduces the remaining problem some.
> Add missing ts-checks. Fix resulting type errors

- packages/ses/src/error/tame-v8-error-constructor.js
- packages/ses/test/error/test-v8-concise-stack-filtering-unit-tests.js
Fixes https://github.com/Agoric/agoric-sdk/issues/2326#issuecomment-773020389 by recognizing ellipses as suggested there, so
```
Object.bootstrap (v1/.../SwingSet/test/vat-admin/terminate/bootstrap-speak-to-dead.js:40:59)
```
gets shortened to
```
Object.bootstrap (SwingSet/test/vat-admin/terminate/bootstrap-speak-to-dead.js:40:59)
```
Refactor the filtering and shortening of concise stack traces to be more data driven, so that it can eventually be made user configurable, and so the testing and filtering rules can be unit tested.
Unit test them.
> Better concise stack traces

- packages/ses/test/error/test-tame-console-unsafe-unsafeError-unfilteredError.js
Just the same test cases as the similarly named test files, but with a different set of `lockdown` options.
> Add missing testcase

- packages/ses/NEWS.md
- packages/ses/src/error/assert.js
- packages/ses/src/error/types.js
Needed by https://github.com/Agoric/agoric-sdk/pull/2515
The local `assert` module exports a `makeAssert` function precisely in order to enable uses like https://github.com/Agoric/agoric-sdk/pull/2515 . However, due to an oversight, it is not reexported by the `@agoric/assert` module. It is not clear what the right way is to enable `@agoric/assert` to reexport it. So this PR is just a temporary kludge that works with the kludge in https://github.com/Agoric/agoric-sdk/pull/2515 when `yarn link`ed together.
> Effectively export makeAssert by putting it on assert

- packages/ses/NEWS.md
- packages/ses/src/error/assert.js
- packages/ses/src/error/stringify-utils.js
- packages/ses/src/error/types.js
- packages/ses/test/error/test-assert-log.js
- packages/ses/test/error/throws-and-logs.js
From the text added to `NEWS.md`
* The `assert.quote` function re-exported by `@agoric/assert` as `q`
has always done only a best effort stringify, intended only to
be interpreted by a human under benign conditions. Within that constraint
its best effort is now better, providing informative though ambiguous
renderings of values problematic for `JSON.stringify`, still including
cycles, but now also functions, promises, `undefined`, `NaN`, `Infinity`,
bigints, and symbols.
> assert's q function is a better best efforts stringify

- packages/ses/index.d.ts
- packages/ses/jsconfig.json
- packages/ses/src/compartment-shim.js
- packages/ses/src/error/assert.js
- packages/ses/src/error/console.js
- packages/ses/src/error/internal-types.js
- packages/ses/src/error/types.js
- packages/ses/src/lockdown-shim.js
This change includes Compartment and lockdown in the SES shim’s exported types and generally extends the reach of TypeScript verification into SES sources. This change uses the expedient of reexporting the return types of functions that are checked by `yarn tsc:lint` which may not be sufficient. In a subsequent change, it will likely be necessary to convert the Compartment and lockdown types into interface definitions that are imported by the sources and also exported by `index.d.ts`.
> feat(ses): Expand TypeScript coverage for Compartment and lockdown

- packages/compartment-mapper/jsconfig.json
- packages/endo/jsconfig.json
- packages/make-hardener/jsconfig.json
- packages/make-hardener/src/main.js
- packages/ses/index.d.ts
- packages/ses/jsconfig.json
- packages/ses/src/compartment-shim.js
- packages/ses/src/error/console.js
- packages/ses/src/error/types.js
- packages/ses/src/lockdown-shim.js
- packages/transform-module/jsconfig.json
These fixes are needed to correctly export global types to consumers of ses.
We also standardize on `"target": "esnext"` in anticipation of future Javascript.
> Fix typing

- package.json
- patches/acorn+7.1.1.patch
- patches/acorn+7.4.1.patch
- yarn.lock
There's a bug in acorn7 that's interfering with SES and is fixed in acorn8. However, there's no good way to force all acorn linkage to link with at least acorn8, so in the meantime we're patching as in https://github.com/Agoric/agoric-sdk/pull/2549 
However, SES-shim has no such patches or `patches` directory,  I don't know what configuration magic enables patch files like this to work. So I'm starting by just cargo culting https://github.com/Agoric/agoric-sdk/pull/2549 and hoping for the best.
> Cargo cult agoric-sdk #2549

- packages/ses/src/enablements.js
- packages/ses/test/test-enable-property-overrides.js
- yarn.lock
Fixes https://github.com/Agoric/agoric-sdk/issues/2324
Fixes https://github.com/Agoric/SES-shim/issues/477
To enable `Object.prototype.constructor` to be overridden by assignment, we needed to make it into an accessor property. However, this confused the Node console as explained at https://github.com/Agoric/agoric-sdk/issues/2324 . But not doing so had been blocked by our dependency on acorn 7 which performs such an assignment. That dependency has now been fixed by 
https://github.com/Agoric/SES-shim/pull/588
and
https://github.com/Agoric/agoric-sdk/pull/2549
so we can proceed.
> Stop enabling O.p.constructor to be overridden by assignment.

- packages/ses/NEWS.md
- packages/ses/demos/challenge/main.js
- packages/ses/demos/console/main.js
- packages/ses/src/error/console.js
- packages/ses/src/error/tame-error-constructor.js
- packages/ses/src/error/tame-v8-error-constructor.js
- packages/ses/src/whitelist-intrinsics.js
- packages/ses/src/whitelist.js
- packages/ses/test/error/test-assert-log.js
Fixes #525 
Using #590 to iterate within several browsers, I repaired several issues.
* #525 was that assigning `Error.stackTraceLimit` was failing in non-v8-based browsers because `Error` had no such property and is frozen. Although the property is indeed non-standard and absent in non-v8 systems, Google's documentation encourages assignments to it anyway. This is a noop elsewhere, but is harmless when `Error` is unfrozen. To accommodate this practice, this PR installs a noop `Error.stackTraceLimit` accessor property on every platform. It is a noop everywhere except in the start compartment of a v8-based platform.
* On the Safari browser (and presumably on any host using the JSC engine) `DataView` has a non-standard but non-deletable `BYTES_PER_ELEMENT` property whose value is a number. …
> Lenient stackTraceLimit works across browsers

- packages/ses/src/enablements.js
- packages/ses/test/test-enable-property-overrides.js
- packages/ses/test/test-property-override.js
I have been trying to use SES to sandbox third party scripts for services like Twitter Widgets and Google Analytics. My goal is to be able to fetch these scripts from their servers, and run them in a SES compartment with limited capabilities. 
The issue that I ran into is that these scripts frequently overwrite an array's push function like in the example below.
```
const list = []
list.push = function newPush {}
```
This becomes impossible after `lockdown()` has been called due to [The Override Mistake](https://web.archive.org/web/20141230041441/http://wiki.ecmascript.org/doku.php?id=strawman:fixing_override_mistake). This PR aims to fix the problem by allowing an Array's `push` method to be overwritten.
Fixes (https://github.com/Agoric/SES-shim/issues/593)
- New feature (non-breaking …
> Repair Array Push

- packages/ses/src/enablements.js
- packages/ses/src/error/types.js
Record that d3-color also overrides `O.p.constructor` by assignment.
Fix typo.
> fix: comments only

- package.json
- packages/ses-ava/.prettierrc.json
- packages/ses-ava/LICENSE
- packages/ses-ava/exported.js
- packages/ses-ava/jsconfig.json
- packages/ses-ava/package.json
- packages/ses-ava/rollup.config.js
- packages/ses-ava/src/main.js
- packages/ses-ava/src/ses-ava-test.js
- packages/ses-ava/src/types.js
- packages/ses-ava/test/test-raw-ava-reject.js
- packages/ses-ava/test/test-raw-ava-throw.js
- packages/ses-ava/test/test-ses-ava-reject.js
- packages/ses-ava/test/test-ses-ava-throw.js
When a test case `test(title, func)` fails because `func` threw an error or returned a promise that eventually rejects, ava prints the stack in what looks like console output but is not. This bypasses all of our fancy error support --- the error details and all the deep stack support -- which made it extremely unpleasant to debug failing tests.
This PR provides a `testWrapper` function that acts like ava's `test` function, except that when a test fails, the failure is also reported to the actual console. When used under SES, this is the fancy console that SES installs.
Since this only does something when the ava test fails, there's no easy way to include an automated test. However I have monkey tested it (in https://github.com/Agoric/agoric-sdk/pull/2159 ) and it seems to work.
fixes #577
> Wrap ava test function to log failures to actual console

- packages/compartment-mapper/README.md
- packages/compartment-mapper/src/archive.js
- packages/compartment-mapper/src/assemble.js
- packages/compartment-mapper/src/extension.js
- packages/compartment-mapper/src/import-archive.js
- packages/compartment-mapper/src/import-hook.js
- packages/compartment-mapper/src/import.js
- packages/compartment-mapper/src/infer-exports.js
- packages/compartment-mapper/src/json.js
- packages/compartment-mapper/src/main.js
- packages/compartment-mapper/src/node-module-specifier.js
- packages/compartment-mapper/src/node-modules.js
- packages/compartment-mapper/src/parse.js
- packages/compartment-mapper/src/search.js
- packages/compartment-mapper/src/types.js
- packages/compartment-mapper/src/url.js
- packages/compartment-mapper/src/zip.js
- packages/compartment-mapper/src/zip/compression.js
- packages/compartment-mapper/src/zip/format-writer.js
- packages/compartment-mapper/src/zip/signature.js
- packages/compartment-mapper/src/zip/writer.js
- packages/ses/NEWS.md
- packages/ses/index.d.ts
This change introduces SES TypeScript definitions sufficient for the Compartment Mapper to be fully checked by TypeScript.
Fixes #161
> Expand SES and Compartment Mapper TypeScript coverage

- packages/ses/src/error/types.js
This refinement makes the assertion meaningful (before it was just asserting the equivalent of `any`).
> fix: assert.typeof(xxx, 'object') should assert record or null

- packages/ses/NEWS.md
- packages/ses/src/enablements.js
- packages/ses/test/test-enable-property-overrides.js
The vega package is the only one we are aware of that causes this problem.
In light of the patch fixing vega in agoric-sdk , the issue filed at https://github.com/vega/vega/issues/3075 and the PR https://github.com/vega/vega/pull/3109 , this PR removes `hasOwnProperty` from the enablements.js list. See new NEWS text for more explanation.
> Don't enable hasOwnProperty to be overridden by assignment

- packages/ses/src/error/stringify-utils.js
- packages/ses/test/error/test-assert-log.js
Previously, if an object had a property named by the `Symbol.toStringTag` symbol *and it was empty*, then the human readable "quoted" printing by `q` would be `"[<value of that property>]"`.
This PR removes the "and it was empty" part of that condition. This PR should wait until https://github.com/Agoric/agoric-sdk/issues/2018 is closed, because until then data objects, whether empty or not, will pass this test, preventing `q` from providing a pleasant display of their properties.
Until then, however, we have a painful difference in how `q` renders a remotable vs a remote presence of that remotable. Currently, for our objects-as-closures style of remotable, `q` will show the method names. This difference means that `t.throws` tests will see different quoted text in error messages …
> Symbol.toStringTag dominates default q stringify

- packages/ses/demos/challenge/index.html
- packages/ses/demos/challenge/main.js
The existing challenge UI explanatory text is somewhat misleading.
We don't do confinement of the defender.  While that would be
interesting, the status quo usefully demonstrates that you don't have to jump
through hoops to use SES in normal JS programs.
> docs: update description of the SES challenge to match reality

- packages/ses/src/whitelist.js
Entering these properties into whitelist.js with a `false` setting, like omitting them, causes them to be removed. But listing them explicitly records that we're not surprised by seeing them, so `lockdown` removes them silently. If we see a property that does not appear on the whitelist at all, `lockdown` logs a record of that so we can react to the surprise. https://github.com/endojs/endo/issues/612 nicely demonstrates how useful that feedback is.
This PR is a result of testing https://ses-demo.netlify.app/demos/console/ on a variety of browsers, plus recording what we already know about XS. Because I am on a Mac, I have not tested Edge. If someone could and post the console output, that would be appreciated.
> Blacklist properties we expect to remove

- packages/ses/package.json
- packages/ses/rollup.config.js
SES is constrained to use a regular expression for evasive transforms.
SES exposes the evasive transforms as options to `evaluate`.
For cases where a bundler is involved, this problem is better solved
with a parser transform that can distinguish comments from names in
scope and can discern whether the transformation it proposes is likely
to cause semantic breakage.
This reverts commit 5ec8858648254e7cd2a1bf9c054a1d5d2749c31b.
Fixes #609
> feat(ses): Revert "Export SES Transforms (#608)"

- packages/ses/src/enablements.js
- packages/ses/test/test-enable-default-overrides-default.js
- packages/ses/test/test-enable-property-overrides.js
Fixes #616 
The culprit here is https://github.com/feross/buffer which we've also encountered in https://github.com/Agoric/agoric-sdk/issues/2663 . From the investigation there, the `feross/buffer` package overrides a lot more of TypedArray than `toLocaleString`, which is why I went all the way back to '*'.
@kumavis your second test is overriding `Object.prototype.toLocaleString` which surprised me. First, could you try this PR out against your failure of `feross/buffer` to see if it really is adequate to fix the problems you're encountering? Second, if so, could you comment out the enabling of `Object.prototype.toLocaleString` and see if it still works? Because it is on `Object.prototype`, I'd like to avoid adding it unless we really need to. Thanks.
> Enablements needed by Buffer

- packages/compartment-mapper/NEWS.md
- packages/compartment-mapper/src/archive.js
- packages/compartment-mapper/src/assemble.js
- packages/compartment-mapper/src/import-archive.js
- packages/compartment-mapper/src/import-hook.js
- packages/compartment-mapper/src/import.js
- packages/compartment-mapper/src/parse.js
- packages/compartment-mapper/src/types.js
- packages/compartment-mapper/test/test-transform.js
This change introduces module transforms as an option for running applications and building archives.  The motivating use case is the application of parser-based evasive transforms.  These transforms can change the source slightly such that they do not trip SES censorship of dynamic imports and possibly other patterns, without changing the meaning of the program.
https://github.com/Agoric/agoric-sdk/issues/2684
> feat(compartment-mapper): Add module transforms

- packages/ses/NEWS.md
- packages/ses/lockdown-options.md
- packages/ses/src/error/README.md
- packages/ses/src/error/assert.js
- packages/ses/src/error/types.js
- packages/ses/src/lockdown-shim.js
Under the default `{errorTaming: 'safe'}` setting, the SES shim already redacts stack traces from error instances when it can (currently: v8, spiderMonkey, XS). The setting `{errorTaming: 'unsafe'}` suppresses that redaction, instead blabbing these stack traces on error instances via the expected `errorInstance.stack`.
The purpose of the `details` template literal tag (often spelled `X` or `d`) together with the `quote` function (often spelled `q`) is to redact data from the error messages carried by error instances. With this PR, the same `{errorTaming: 'unsafe'}` would suppress that redaction as well, so that all substitution values would act like they've been quoted. IOW, with this setting
```js
assert(false, X`literal part ${secretData} with ${q(publicData)}.`);
```
would act like …
> Setting `{errorTaming: 'unsafe'}` does not redact secrets

- packages/compartment-mapper/NEWS.md
- packages/compartment-mapper/src/assemble.js
- packages/compartment-mapper/test/node_modules/app/main.js
- packages/compartment-mapper/test/node_modules/brooke/brooke.js
- packages/compartment-mapper/test/node_modules/builtin/builtin.js
- packages/compartment-mapper/test/node_modules/clarke/index.js
- packages/compartment-mapper/test/node_modules/danny/src/danny.js
- packages/compartment-mapper/test/node_modules/danny/src/index.js
By default, freeze the global object in every compartment after endowments. We may in a future version allow some compartments to remain thawn through explicit configuration from the application (possibly recommended on a per library basis). We may in a future version provide a hook for alternate global post processing like `harden`.  We do not take a dependency on `harden` because that would limit the use of compartment mapper as a demonstration of how Node.js could use compartments as a standard module loader API, orthogonal to SES.
> feat(endo): Freeze all global objects

- README.md
The README contains statements of intent in an implied subjunctive mood. This change makes that clearer, but review feedback of the form “Integrate the aspirational sense in the whole document instead” is welcome.
> doc: Clarify that Endo is aspirational

- packages/ses-ava/test/test-raw-ava-reject.js
- packages/ses-ava/test/test-raw-ava-throw.js
- packages/ses/lockdown-options.md
- packages/ses/test/error/test-tame-console-unfilteredError.js
- packages/ses/test/error/test-tame-console-unsafe-unfilteredError.js
- packages/ses/test/error/test-tame-console-unsafe-unsafeError-unfilteredError.js
- packages/ses/test/error/test-tame-console-unsafe-unsafeError.js
- packages/ses/test/error/test-tame-console-unsafe.js
- packages/ses/test/error/test-tame-console-unsafeError.js
- packages/ses/test/error/test-tame-console.js
Using `consoleTaming: 'unsafe'` will preserve the original platform console. However, due to #636 the Node console is confused by `constructor` properties that have been turned into accessors. Note that we do *not* recommend this setting. But if you need to use it, it is best used with `overrideTaming: 'min'` which avoids turning any `constructor` properties into accessors.
The `errorTaming: 'unsafe'` option will avoid redacting the information normally hidden from error instances: the call stack and the detailed error message created by the `assert.details` template literal tag. `lockdown` suppresses the redaction of the details by replacing the global `assert` object with one whose `assert.details` does not redact. Thus, if you use `errorTaming: 'unsafe'` be sure to sample the `assert` …
> Unsafe errorTaming and consoleTaming needs other adjustments

- packages/ses/src/error/assert.js
- packages/ses/test/error/test-tame-console-unfilteredError.js
- packages/ses/test/error/test-tame-console-unsafe-unfilteredError.js
- packages/ses/test/error/test-tame-console-unsafe-unsafeError-unfilteredError.js
- packages/ses/test/error/test-tame-console-unsafe-unsafeError.js
- packages/ses/test/error/test-tame-console-unsafe.js
- packages/ses/test/error/test-tame-console-unsafeError.js
- packages/ses/test/error/test-tame-console.js
The setting `{errorTaming: unsafe}` suppresses the redaction of unmarked substitution values in detailed error messages, as it should.
The `assert.quote` function is for marking a particular substitution as immune from redaction, which it does under normal circumstances. 
When both are used together (hence "double disclosure bug") the `q` marked substitution no longer disclose the quoted payload. Due to me using the wrong map, it was instead disclosing the declassifier object itself.
> Fix double disclosure bug, where `assert.quote` can render badly

- packages/ses/NEWS.md
- packages/ses/lockdown-options.md
- packages/ses/src/lockdown-shim.js
- packages/ses/test/test-unsafe-kludge-for-react.js
We temporarily introduce a new `__unsafeKludgeForReact__` option whose
`'unsafe'` setting that unsafely allows React to work under SES in the browser
even before React is fixed. Once React is fixed, this option will disappear.
Enables https://github.com/Agoric/dapp-token-economy/issues/159 to be fixed by injecting SES on the page first, as shown at https://github.com/Agoric/dapp-token-economy/pull/155
@dckc @kriskowal This is now ready for review. @dckc Because you created this PR I cannot add you as an official reviewer but please look anyway.
> feat: non-security mode for create-react-scripts compat. (KLUDGE)

- packages/ses/src/lockdown-shim.js
This PR does not yet test this change because it is not clear how. Thus Draft until we hear the results of downstream testing.
> Tolerate double initialization and lockdown

- packages/ses/NEWS.md
- packages/ses/src/error/assert.js
- packages/ses/src/error/console.js
- packages/ses/src/error/internal-types.js
- packages/ses/src/error/types.js
- packages/ses/test/error/test-assert-log.js
- packages/ses/test/error/throws-and-logs.js
The externally visible change is that `assert.error` takes an options bag with an `errorName` option that will be used to form the error tag shown in the privileged console view. It does not affect what's visible to unprivileged code.
This is in preparation for `marshal` using it when unserializing errors, so that the error tag indicates that this is a remote error. See https://github.com/Agoric/agoric-sdk/pull/2769
> Prepare for marshal error tagging

- packages/compartment-mapper/src/import-archive.js
- packages/compartment-mapper/src/import.js
- packages/ses/NEWS.md
- packages/ses/error-codes/SES_IMPORT_REJECTED.md
- packages/ses/src/commons.js
- packages/ses/src/transforms.js
- packages/ses/test/test-reject-direct-eval.js
- packages/ses/test/test-reject-import-expression.js
Relaxes the censorship of `import` and `eval` in programs evaluated under SES to specifically allow the use of `import.import()` or `evaluator.eval()` methods.
Fixes #664
> feat(ses): Allow import and eval methods

- package.json
- packages/compartment-mapper/package.json
- yarn.lock
This adds a purported peer dependency on octokit and a misaligned version of rollup.
Hereafter, `yarn install` should offer no warnings.
Fixes #597
> Fix dependency warnings

- packages/ses/NEWS.md
- packages/ses/src/module-instance.js
- packages/ses/src/module-link.js
- packages/ses/test/test-import-cjs.js
- packages/ses/test/test-import-gauntlet.js
*BREAKING CHANGE* Third-party static module interface implementations *must* now explicitly list their exported names. For CommonJS, this implies using a heuristic static analysis of `exports` changes. Consequently, third-party modules can now participate in linkage with ESM including support for `export * from './spec.cjs'` and also named imports like `import * from './spec.cjs'`.
Part 1 of #666
> feat(ses)!: Third-party module exports

- packages/ses/NEWS.md
- packages/ses/README.md
- packages/ses/src/module-instance.js
- packages/ses/src/module-link.js
- packages/ses/src/module-shim.js
This change refactors SES most of the way back to a simpler form, where the module system is provided by the lightweight `ses/lockdown` and the `ses` layer only adds the `StaticModuleRecord` constructor. The `StaticModuleRecord` constructor is the only part that entrains Babel.
The piece of coupling that made this impossible before was the `moduleAnalyses` `WeakMap` that allowed the `StaticModuleRecord` constructor to produce an opaque object, such that the contract between `StaticModuleRecord` and the `Compartment` `importHook` was private and could be changed without advice on the SES-shim public API or impact on the SES-shim version number. This is a nice property, but it’s not as nice as performance.
So, instead, this change introduces a `__PrecompiledStaticModuleRecord__` which …
> refactor(ses): Decouple StaticModuleRecord

- packages/cjs-module-analyzer/index.d.ts
- packages/cjs-module-analyzer/package.json
- packages/compartment-mapper/package.json
- packages/compartment-mapper/src/parse.js
This is a build fix that I will land without review. This raises concern for me because every PR was tested atop HEAD and this issue didn’t show up until after the conflicting branches both landed.
> fix: Realign TS, JS, and package names

- packages/compartment-mapper/NEWS.md
- packages/compartment-mapper/package.json
- packages/compartment-mapper/src/parse.js
- packages/compartment-mapper/src/types.js
This anti-climactic change brings together Syrup and the StaticModuleRecord refactor such that ESM gets precompiled on the way into an archive, and executed directly on the way out.
It will likely be necessary to break the compartment mapper into separate packages for creating archives and executing them, perhaps with some shared logic, to relieve the dependency on `@endo/static-module-record` when executing from an archive. Stay tuned.
> feat(compartment-mapper): Precompile ESM

- packages/compartment-mapper/NEWS.md
- packages/compartment-mapper/package.json
- packages/compartment-mapper/src/parse.js
- packages/compartment-mapper/src/types.js
This anti-climactic change pre-compiles ESM and executes the compiled
static module records from an archive.
Refs #673
This is a repost of #687 which I mistakenly landed into a branch that has since been overwritten.
> feat(compartment-mapper): Precompiled ESM

- packages/compartment-mapper/NEWS.md
- packages/compartment-mapper/src/assemble.js
- packages/compartment-mapper/src/bundle.js
- packages/compartment-mapper/src/import-hook.js
- packages/compartment-mapper/src/main.js
- packages/compartment-mapper/src/parse-archive-mjs.js
- packages/compartment-mapper/src/types.js
- packages/compartment-mapper/test/node_modules/bundle/import-all-from-me.js
- packages/compartment-mapper/test/node_modules/bundle/import-and-export-all.js
- packages/compartment-mapper/test/node_modules/bundle/import-and-reexport-name-from-me.js
- packages/compartment-mapper/test/node_modules/bundle/import-default-export-from-me.js
- packages/compartment-mapper/test/node_modules/bundle/import-named-export-and-rename.js
- packages/compartment-mapper/test/node_modules/bundle/import-named-exports-from-me.js
- packages/compartment-mapper/test/node_modules/bundle/main.js
- packages/compartment-mapper/test/node_modules/bundle/package.json
- packages/compartment-mapper/test/node_modules/bundle/reexport-all.js
- packages/compartment-mapper/test/node_modules/bundle/reexport-name.js
- packages/compartment-mapper/test/test-bundle.js
- packages/static-module-record/DESIGN.md
- packages/static-module-record/src/static-module-record.js
- packages/static-module-record/src/transform-analyze.js
This change introduces a bundler (module concatenator) that is suitable for applications that consist entirely of ESM/mjs, do not require live bindings, and do not require compartmentalization of packages. This is the first iteration on a bundler and is suitable in its current form to generate a SES bundle on par with the current `dist/ses.umd.js`.
The next iteration will be able to receive built-in modules and be suitable for bootstrapping Endo on Endo’s own modules, providing a clearer migration path from `-r esm` and relaxing the constraint that Endo be able to bootstrap on Node.js.
This change includes a relatively comprehensive test of MJS to MJS linkage and verifies that the behavior is equivalent to importing the same program as an archive.
Refs #175
> feat(compartment-mapper): Introduce rudimentary bundler

- packages/static-module-record/test/test-static-module-record.js
This change reenables five hitherto-failing tests of StaticModuleRecord.
Refs #709
> test(static-module-record): Restore scope proxy live update tests

- packages/compartment-mapper/test/node_modules/app/main.js
- packages/compartment-mapper/test/node_modules/typehybrid/main.js
- packages/static-module-record/src/babelPlugin.js
- packages/static-module-record/test/test-static-module-record.js
In adding tests for bundles, I discovered a problem with `export { name as othername } from 'module'`, where the `othername` was ignored.
*needs rebase and merge target change after #710 lands*
> fix(static-module-record): Fix export name as

- packages/compartment-mapper/src/infer-exports.js
- packages/ses/src/error/tame-v8-error-constructor.js
- packages/ses/src/evaluate.js
- packages/ses/src/get-anonymous-intrinsics.js
- packages/ses/src/get-source-url.js
- packages/ses/src/global-object.js
- packages/ses/src/intrinsics.js
- packages/ses/src/lockdown-shim.js
- packages/ses/src/make-evaluate-factory.js
- packages/ses/src/make-function-constructor.js
- packages/ses/src/module-instance.js
- packages/ses/src/scope-constants.js
- packages/ses/src/scope-handler.js
- packages/ses/src/tame-function-tostring.js
- packages/ses/src/transforms.js
- packages/ses/src/whitelist.js
Toward #175, an upcoming change introduces a JavaScript module bundler based on our own `StaticModuleRecord`’s internal module-to-program transform and linkage calling conventions. This would allow our module system to host itself.
However, beneath SES, we would not have a scope proxy, and the scope proxy is necessary to facilitate live bindings, such as exported function declarations. We do not need live bindings, so it’s a sensible compromise to use `export const` functions instead. This change prepares SES and the Endo internals for such a bundler.
Ref #175
> Const exports

- packages/ses/NEWS.md
- packages/ses/error-codes/SES_DEFINE_PROPERTY_FAILED_SILENTLY.md
- packages/ses/error-codes/SES_EVAL_REJECTED.md
- packages/ses/src/commons.js
See https://bugs.webkit.org/show_bug.cgi?id=222538#c17
By no longer defining `defineProperty` in terms of `defineProperties`, we should avoid this infinite recursion bug. Because this should have no observable effect other than on a buggy Safari, there's nothing to test.
> Workaround Safari bug 222538#c17

- packages/static-module-record/src/babelPlugin.js
- packages/static-module-record/src/transform-analyze.js
- packages/static-module-record/test/test-static-module-record.js
I was able to fix a few of these tests, and improve the clarity of the Babel transform.
Stacked on 709-export-name-as-default.
> Some fixes for StaticModuleRecord tests

- packages/zip/src/compression.js
- packages/zip/src/format-reader.js
- packages/zip/src/format-writer.js
- packages/zip/src/types.js
We encounter problems when attempting to decode the Uint8Array `[0, 0]` into a `"\x00\x00"` string under XS due to a limitation of our `TextDecoder` shim that is based on the XS `String.fromArrayBuffer` function on that engine https://github.com/Moddable-OpenSource/moddable/issues/644. This work-around maintains the easy values for values comparison of compression method magic numbers/strings by switching the internal representation from string to number.
> fix(zip): Tolerate XS null terminated string limitation

- packages/compartment-mapper/NEWS.md
- packages/compartment-mapper/src/archive.js
- packages/compartment-mapper/src/node-modules.js
This change addresses a non-determinism bug in the production of compartment maps and is necessary for consistent production of archives.
> fix(compartment-mapper): Deterministic archives

- packages/base64/NEWS.md
- packages/base64/package.json
- packages/ses-ava/NEWS.md
- packages/ses-ava/package.json
Svelte tooling needs access to each package’s metadata. Node.js ESM now requires public access to modules in a package to be expressed in an `exports` property (if present). This change lines up `ses-ava` and `base64`, which lagged behind the current package skeleton.
> feat: Expose package.jsons

- packages/zip/src/buffer-reader.js
- packages/zip/src/buffer-writer.js
- packages/zip/src/format-reader.js
- packages/zip/src/format-writer.js
The Zip implementation contains a couple general-use tools for reading and writing bytes: BufferReader and BufferWriter. To minimize scope, I’d only implemented little-endian read and write methods, since we only need little-endian. It’s possible to support both and erase some unnecessary code by using the web platform `DataView` instead.
This provides no change in behavior and makes the buffer utilities closer to ready to factor into a general-purpose package, for reuse elsewhere, like `netstring` and `syrup`.
> refactor(zip): Use DataView

- packages/ses/NEWS.md
- packages/ses/lockdown-options.md
- packages/ses/src/enable-property-overrides.js
- packages/ses/src/lockdown-shim.js
- packages/ses/test/test-enable-property-overrides-severe-debug.js
This allows SES callers to help diagnose which override enablements
are being used, with a backtrace.
The idiom for `@agoric/install-ses` when tracking down the override
mistake with the `constructor` property is to set the following
environment variable:
```sh
export LOCKDOWN_OPTIONS='{"overrideDebug":["constructor"],"overrideTaming":"severe","errorTaming":"unsafe","stackFiltering":"verbose"}'
```
Then, when some script deep in the require stack does:
```js
function MyConstructor() { }
MyConstructor.prototype.constructor = XXX; // Would throw if Object.prototype.constructor is not repaired.
```
the caller backtrace will be logged to the console.  Then, the workaround is to change the second line to:
```js
Object.defineProperty(MyConstructor.prototype, 'constructor', { value: XXX }); // …
```
> feat: create `overrideDebug: [...props]` option

- packages/compartment-mapper/src/bundle.js
- packages/ses/error-codes/SES_NO_SLOPPY.md
- packages/ses/index.js
Integration with Agoric SDK revealed that the SES bundle, now generated by the compartment-map bundler instead of rollup, by virtue of running under CommonJS rules, was not running in strict mode as is default for ESM. This invalidated SES lockdown which complained vigorously about `arguments` and `caller` properties on some of its own repaired functions. This addresses the issue by generating strict mode bundles.
The bundle as written is sufficient for our purpose but does not compose concatenatively, which is sometimes consider a good practice for UMD style bundles. I’m open to the option of wrapping the entire bundle in yet-another-IFFE if folks feel strongly about that invariant.
> fix(compartment-mapper): Generate strict bundle

- packages/static-module-record/test/test-static-module-record.js
- packages/syrup/test/test-fuzz.js
These debug logs were intended to be useful in case tests fail, but sometimes generate data that causes a console beep or is simply too verbose to be useful from the top-level `yarn test`.
> test: Mute certain test logs

- packages/ses/package.json.md
These are my notes on why we’ve arrived at certain implementation choices for the SES `package.json`, for review should they need to change: a sign to hang on Chesterton’s fence.
> doc(ses): Add explainer for package.json

- packages/base64/NEWS.md
- packages/cjs-module-analyzer/NEWS.md
- packages/compartment-mapper/NEWS.md
- packages/netstring/NEWS.md
- packages/ses-ava/NEWS.md
- packages/ses/NEWS.md
- packages/static-module-record/NEWS.md
- packages/zip/NEWS.md
This mechanical change regularizes the format of NEWS.md across all Endo packages, including the heading level, date format, and bullet kind. The latter are consistent with the new Lerna CHANGELOG format, so it’s easier to update.
> fix: Regularize format of NEWS.md

- lerna.json
- package.json
- yarn.lock
This change parallels https://github.com/Agoric/agoric-sdk/pull/3230 and configures Lerna to behave consistently with the npm semantics of `^0` dependencies, both for recommending versions and building a change log based on conventional commits.
> chore: Update Lerna configuration

- package.json
These packages are no longer in the repository and need to be garbage collected for tooling.
> fix: Remove defunct workspace packages

- packages/base64/package.json
- packages/ses-integration-test/package.json
These are a couple discrepancies I’ve discovered in the packaging of base64 and ses-integration-test, the former revealed through integration testing with Agoric SDK.
> fix: Fix some stray packaging mistakes

- packages/ses/NEWS.md
- packages/ses/index.d.ts
In the removal of the consolidation of the `@agoric/make-hardener` package into SES, the SES type definition needed this update.
> fix(ses): Export hardener types properly

- packages/base64/CHANGELOG.md
- packages/base64/NEWS.md
- packages/base64/package.json
- packages/cjs-module-analyzer/CHANGELOG.md
- packages/cjs-module-analyzer/package.json
- packages/compartment-mapper/CHANGELOG.md
- packages/compartment-mapper/package.json
- packages/endo/CHANGELOG.md
- packages/endo/package.json
- packages/eslint-config/CHANGELOG.md
- packages/eslint-config/package.json
- packages/eslint-plugin/CHANGELOG.md
- packages/eslint-plugin/package.json
- packages/netstring/CHANGELOG.md
- packages/netstring/package.json
- packages/ses-ava/CHANGELOG.md
- packages/ses-ava/package.json
- packages/ses-integration-test/CHANGELOG.md
- packages/ses-integration-test/package.json
- packages/ses/CHANGELOG.md
- packages/ses/NEWS.md
- packages/ses/package.json
- packages/static-module-record/CHANGELOG.md
- packages/static-module-record/package.json
- packages/syrup/CHANGELOG.md
- packages/syrup/package.json
- packages/test262-runner/CHANGELOG.md
- packages/test262-runner/package.json
- packages/zip/CHANGELOG.md
- packages/zip/package.json
```diff
--- a/packages/base64/CHANGELOG.md
+++ b/packages/base64/CHANGELOG.md
@@ -3,6 +3,15 @@
All notable changes to this project will be documented in this file.
See [Conventional Commits](https://conventionalcommits.org) for commit guidelines.
+### [0.2.1](https://github.com/endojs/endo/compare/@endo/base64@0.2.0...@endo/base64@0.2.1) (2021-06-06)
+
+
+### Bug Fixes
+
+* Fix some stray packaging mistakes ([0eb9297](https://github.com/endojs/endo/commit/0eb9297b1fc9753c235c53d746aa7d7994781216))
+
+
+
--- a/packages/ses-integration-test/CHANGELOG.md
+++ b/packages/ses-integration-test/CHANGELOG.md
@@ -3,6 +3,15 @@
All notable changes to this project will be documented in this file.
See [Conventional Commits](https://conventionalcommits.org) for commit guidelines.
+### …
```
> chore(release): publish

- packages/ses-ava/README.md
A minor typo missed in renaming `@agoric` to `@endo`.
> fix(ses-ava): Doc nit

- packages/ses/src/error/assert.js
- packages/ses/src/error/stringify-utils.js
- packages/ses/test/error/test-assert-log.js
Fixes #729 
@dckc I should still take your suggestion to give detailsTokens their own `toString` method. However, that solves less of the problem. For example, the test case added in this PR would still fail. Instead, where the `assert` module itself stringifies something directly, not through `details`, it would now stringify the `quote` of it. IOW, it would use `bestEffortStringify`.
Since I don't yet know how to reproduce #729, I'll start with this PR, and take your suggestion later after we see if this PR solves your problem.
> Best effort assert printing

- packages/compartment-mapper/NEWS.md
- packages/compartment-mapper/src/archive.js
- packages/compartment-mapper/src/assemble.js
- packages/compartment-mapper/src/import-hook.js
- packages/compartment-mapper/src/types.js
- packages/compartment-mapper/test/test-main.js
Upon creating a new archive, the user will now be required to provide a
modules record (with meaningless values) to denote what dependencies are
expected to be provided by the importer.
> feat(compartment-mapper)!: Required exits on archives

- packages/compartment-mapper/NEWS.md
- packages/compartment-mapper/src/archive.js
- packages/compartment-mapper/src/import.js
- packages/compartment-mapper/src/node-modules.js
- packages/compartment-mapper/src/types.js
- packages/compartment-mapper/test/fixtures-0/node_modules/app/package.json
- packages/compartment-mapper/test/fixtures-no-trans-dev-deps/node_modules/app/index.js
- packages/compartment-mapper/test/fixtures-no-trans-dev-deps/node_modules/app/package.json
- packages/compartment-mapper/test/fixtures-no-trans-dev-deps/node_modules/direct/index.js
- packages/compartment-mapper/test/fixtures-no-trans-dev-deps/node_modules/direct/package.json
- packages/compartment-mapper/test/fixtures-no-trans-dev-deps/node_modules/indirect/index.js
- packages/compartment-mapper/test/fixtures-no-trans-dev-deps/node_modules/indirect/package.json
- packages/compartment-mapper/test/test-main.js
The import and archive functions now accepta `dev` flag that indicates that the `devDependencies` of the entry module's package should be included in the compartment graph.  This must be passed explicitly and is off by default since that will be the norm for applications.
This is the bug of the day blocking https://github.com/Agoric/agoric-sdk/pull/3273
In furtherance of https://github.com/Agoric/agoric-sdk/issues/2684
> feat(compartment-mapper): Developer dependencies

- packages/compartment-mapper/NEWS.md
- packages/compartment-mapper/jsconfig.json
- packages/compartment-mapper/src/node-powers.js
Although this lint check locally works fine, it fails two dependency edges up from here.
Refs: https://github.com/Agoric/agoric-sdk/pull/3346
> fix(compartment-mapper): Export types properly

- packages/ses/package.json
- packages/ses/package.json.md
Node.js with ESM support uses the `exports` property to guide an import or require call to the relevant content, trusting that mechanism and ignoring the extension of the file. However, `@web/dev-server` depends on the extension to be consistent. It’s therefore necessary to use the `import` and `require` predicates, even though the referenced files have identical content. This change also makes the packaging more consistent, always using the built SES bundle, not trusting the module system (which may attempt to produce an equivalent module) if that can be avoided.
> fix(ses): Fix packaging for `@web/dev-server`

- packages/ses/src/tame-date-constructor.js
Fixes #520 
I first added a missing `// @ts-check` at the top and was gratified to see a red underline at the typo, and no where else.
> fix: typo vs type checker

- packages/ses/NEWS.md
- packages/ses/index.js
- packages/ses/src/lockdown-shim.js
- packages/ses/test/test-harden-before-lockdown.js
Reveals `harden` only after `lockdown`. Harden was never usable before lockdown because it would render the environment ireparable.  Calling `harden` before `lockdown` previously threw an exception.  Now it is possible to write libraries that are usable both in JS and SES, which can know whether to harden their API by the presence of harden in global scope.
Fixes #787
> feat(ses): Reveal harden only after lockdown

- packages/ses/NEWS.md
- packages/ses/index.d.ts
- packages/ses/lockdown-options.md
- packages/ses/src/error/tame-console.js
- packages/ses/src/lockdown-shim.js
- packages/ses/test/console-error-trap/abort-lockdown.js
- packages/ses/test/console-error-trap/abort.js
- packages/ses/test/console-error-trap/default-lockdown.js
- packages/ses/test/console-error-trap/default.js
- packages/ses/test/console-error-trap/exit-code-lockdown.js
- packages/ses/test/console-error-trap/exit-code.js
- packages/ses/test/console-error-trap/exit-lockdown.js
- packages/ses/test/console-error-trap/exit.js
- packages/ses/test/console-error-trap/hazard.js
- packages/ses/test/console-error-trap/index.html
- packages/ses/test/console-error-trap/index.js
- packages/ses/test/console-error-trap/platform-lockdown.js
- packages/ses/test/console-error-trap/platform.js
- packages/ses/test/console-error-trap/report-lockdown.js
- packages/ses/test/console-error-trap/report.js
- packages/ses/test/test-console-error-trap.js
Errors are reported as `{}` when they are caught by Node.js or the web runtime because their stacks are censored. They must be caught with a platform hook and passed to the tamed console to reveal their stack. 
- test(ses): Test error output on Node.js (a failing test)
- fix(ses): Trap and report errors (fixes failing test)
Must be merged to keep the left traversal on git bisectable with passing tests.
Fixes #769
> fix(ses): Fix {} error reports

- .github/workflows/ci.yml
- packages/base64/package.json
- packages/cjs-module-analyzer/package.json
- packages/compartment-mapper/package.json
- packages/endo/package.json
- packages/netstring/package.json
- packages/ses-ava/package.json
- packages/ses/package.json
- packages/static-module-record/package.json
- packages/syrup/package.json
- packages/zip/package.json
Enforcing coverage, as predicted, is too bold at this stage. The only practical mitigation at this point is to adjust the coverage numbers, since the reports produce vast lists of lines that are all opportunities to improve coverage, many of which would have to be reevaluated at every juncture where coverage was not sufficient. Coverage enforcement is only really practical when the thresholds are 100% and checks apply only to code we have not expressly opted out of coverage. 
It’s also moderately infuriating that the coverage is not as high on Node.js 12 as it is on 14, so debugging coverage failures involves checking on all supported Node.js versions. That could perhaps be mitigated by reducing the CI version matrix to just the youngest supported version.
> test: Coverage enforcement ETOOBOLD

- packages/ses/_redirects
- packages/ses/demos/challenge/README.md
- packages/ses/demos/challenge/index.html
Needed so that https://ses-demo.agoric.app is not embarrassing.
Also, update more of the docs to point there correctly.
> ci: deploy netlify site to redirect to the demos page

- packages/ses/src/commons.js
- packages/ses/src/whitelist-intrinsics.js
Some functions that appear as though they should be exported from `commons.js` were declared in `whitelist-intrinsics.js`. `objectHasOwnProperty` and `ownKeys` (from `Reflect`) are now imported from `commons.js` instead of declared in `whitelist-intrinsics.js`. As a consequence, `uncurryThis` is no longer used in `whitelist-intrinsics.js`, and that function is completely removed from that file. `ownKeys` is added as an export of `commons.js` along with the other properties of `Reflect` exported from that file.
> refactor(ses): Consolidate declarations of uncurryThis and related functionality into commons.js

- packages/ses/src/compartment-shim.js
- packages/ses/src/tame-function-constructors.js
- packages/ses/src/whitelist.js
- packages/ses/test/test-whitelist.js
Updates the error messages of errors thrown by inert function constructors and add tests to ensure that they do in fact throw those errors after lockdown.
> refactor(ses): Update inert constructor error messages and add tests

- packages/ses/src/evaluate.js
- packages/ses/src/make-evaluate-factory.js
- packages/ses/src/scope-handler.js
- packages/ses/test/test-scope-handler.js
As discussed at Sestival 2021, an week-long Agoric/MetaMask Red Team event, the audit-ability of the scope proxy would be improved if there were no incidental state on the scope proxy handler which might collide with the namespace of handlers as used by Proxy and no suspicious use of `this`. This change replaces this boolean flag on the handler object with a controller object with named methods for the intended behaviors.
This includes on incidental behavior change that is a precaution redundant with the revocation of the proxy—checking whether the flag to allow one unsafe eval to pass through the proxy itself resets the flag.
> refactor(ses): Avoid use of receiver object `this` in scope handler

- packages/ses/src/scope-handler.js
- packages/ses/test/test-scope-handler-pollution.js
SES shim subsumes Compartment shim, which is orthogonal to Lockdown shim: Compartments can be used to demonstrate module loading before lockdown. Lockdown tames Compartment just like anything else.
But, Compartment captures the machinery of containment and is vulnerable to prototype pollution before lockdown. So, the scope proxy cannot rely on invariants provided by lockdown, like the absence of a `value` property on the `Object.prototype`. This is a small change to protect against that case.
> fix(ses): Scope proxy defense against property descriptor prototype

- packages/ses/src/module-link.js
- packages/ses/test/test-get-source-url.js
- packages/ses/test/test-property-override.js
Drive-by notation simplification
> fix(ses): Use eslint-disable notation consistently

- packages/ses/docs/secure-coding-guide.md
We are moving in general toward not explaining the origin of the SES acronym.
*Requires squash*
> docs: One less SES acronym explainer

- packages/ses/src/module-load.js
Just some minor improvements I stumbled into in debugging for #794
> fix(ses): Improve error messages for invalid module records

- packages/ses/NEWS.md
- packages/ses/src/whitelist.js
Array and String prototype `at` methods are a Stage 3 proposal for
ECMA 262 and are appearing in implementations.
Fixes #854
> feat(ses): Add permits for at methods

- packages/netstring/index.d.ts
- packages/netstring/reader.js
- packages/netstring/stream.js
- packages/netstring/test/test-netstring.js
- packages/netstring/writer.js
The type definitions for netstring must be explicit for lint to pass in
dependees.
Blocks https://github.com/Agoric/agoric-sdk/pull/2978 (which landed prematurely and will need to be reconstructed with the next published version of netstring)
> fix(netstring): Explicitly export types

- packages/compartment-mapper/NEWS.md
- packages/compartment-mapper/src/node-modules.js
- packages/compartment-mapper/test/fixtures-0/node_modules/app/main.js
In Node.js ESM, a package may import its own name. This is particularly
useful for creating tests and testing examples of usage from a
third-party perspective, and is necessary for feature parity.
Blocks https://github.com/Agoric/agoric-sdk/pull/3273
> feat(compartment-mapper): Support reflexive imports

- packages/ses/NEWS.md
- packages/ses/error-codes/SES_NO_DOMAINS.md
- packages/ses/index.d.ts
- packages/ses/index.js
- packages/ses/lockdown-options.md
- packages/ses/src/lockdown-shim.js
- packages/ses/src/tame-domains.js
- packages/ses/test/test-tame-domains-after-lockdown.js
- packages/ses/test/test-tame-domains-before-lockdown.js
> fix(ses): Add Node.js domain hazard mitigation

- packages/compartment-mapper/test/fixtures-cycle-cjs/node_modules/app/index.js
- packages/compartment-mapper/test/fixtures-cycle-cjs/node_modules/app/package.json
- packages/compartment-mapper/test/fixtures-cycle-mjs/node_modules/app/index.js
- packages/compartment-mapper/test/fixtures-cycle-mjs/node_modules/app/package.json
- packages/compartment-mapper/test/test-cycle-cjs.js
- packages/compartment-mapper/test/test-cycle-mjs.js
- packages/ses/NEWS.md
- packages/ses/src/module-link.js
- packages/ses/src/module-load.js
- packages/ses/test/test-import.js
Previously, SES would stall when attempting to load a module that imported itself through an alias.
- test(ses): Test module reflexive import
- test(compartment-mapper): Add reflexive import tests
- fix(ses): Fix reflexive imports
> fix(ses): Fix reflexive imports

- packages/base64/NEWS.md
- packages/base64/src/decode.js
- packages/base64/src/encode.js
Refs: https://github.com/agoric-labs/xsnap-pub/pull/4 https://github.com/Agoric/agoric-sdk/pull/3817 https://github.com/Moddable-OpenSource/moddable/pull/700
> feat(base64): Ponyfill on XSnap

- packages/ses/README.md
This documents where a vetted-shim might be imported, but the documentation fails to explain its presence and since SES does not support vetted shims at time of writing there is no suitable explanation to add.
> doc(ses): Remove confusing reference to vetted-shim module

- packages/compartment-mapper/src/parse-pre-cjs.js
Precompiled CommonJS should work under XSnap but XSnap does not provide a URL global. The URL global is prohibitively expensive to shim or verily even provide as a native binding. Instead, we relax the coupling on that platform with a very weak version of its behavior that should be sufficient for the purposes of computing `__dirname`.
> fix(compartment-mapper): Reduce pre-cjs dependence on URL

- MAINTAINERS.md
Discovered a step in the release instructions that was not necessary.
> fix: Remove superfluous release instruction

- packages/ses/NEWS.md
- packages/ses/src/lockdown-shim.js
- packages/ses/test/test-package.js
*BREAKING CHANGE*: The lockdown option `domainTaming` is now `safe` by default, which will break any application that depends transtively on the Node.js `domain` module.  This protects against the unhardened `domain` property appearing on shared objects like callbacks and promises.
This change may need to wait until no more Agoric dapps depend on `-r esm`, since landing this would cut Agoric off from receiving new patches or features from new releases of SES off of `master`. That could force us into the much more labor intensive situation of making back-ports, which would not benefit from the lerna monorepo tooling. cc @michaelfig
> fix(ses)!: Domain taming safe by default

- packages/compartment-mapper/NEWS.md
- packages/compartment-mapper/src/archive.js
- packages/compartment-mapper/src/import-archive.js
- packages/compartment-mapper/src/import-hook.js
- packages/compartment-mapper/src/link.js
- packages/compartment-mapper/src/parse-archive-cjs.js
- packages/compartment-mapper/src/parse-archive-mjs.js
- packages/compartment-mapper/src/parse-pre-cjs.js
- packages/compartment-mapper/src/parse-pre-mjs.js
- packages/compartment-mapper/src/types.js
- packages/compartment-mapper/test/test-source-url-rewrite.js
- packages/compartment-mapper/test/test-stack.js
Adds hooks to archive production and consumption for reading and writing source locations, such that other tools yet to be written can use these hooks to provide fully qualified local debug source URLs.  Archive creation functions now accept a `captureSourceLocation(compartmentName, moduleSpecifier, sourceLocation)` hook and archive parsing functions accept `computeSourceLocation(compartmentName, moduleSpecifier)`.
> feat(compartment-mapper): Add hooks for sourceURL

- packages/ses/index.d.ts
as used here https://github.com/endojs/endo/blob/3a3afddf8828c21dcc58b9c98243b31e2cc99d47/packages/ses/src/error/tame-console.js#L74
> errorTrapping type - missing "none" option

- packages/ses/src/error/tame-console.js
- packages/ses/test/test-console-error-trap.js
Errors caught by the `errorTrapping` feature were being logged with only their stack traces. The error message was omitted.
Now the log for trapped errors includes the error message along with the stack trace.
> fix(ses): Include error in trapped error log

- packages/compartment-mapper/src/bundle.js
- packages/ses/scripts/bundle.js
- packages/static-module-record/package.json
- packages/static-module-record/src/babelPlugin.js
- packages/static-module-record/src/transform-analyze.js
- yarn.lock
- Use `@agoric/recast` to minimise the changes made to `static-module-record`-transformed code
- Clean up `@endo/compartment-mapper/bundle.js` output to have proper indentation
- Output `functor` sources first, so that the uninteresting linkage machinery appears at the end of the bundle
> Much prettier module-transformed code and bundles

- packages/ses/src/whitelist.js
All of those added by this PR are powerless and purely computational, and so should be enabled by the whitelist (rather than using `false` to acknowledge that they are expected but remove them).
> fix: update whitelist with stage 3 and 4 proposals

- packages/static-module-record/NEWS.md
- packages/static-module-record/package.json
- packages/static-module-record/src/babelPlugin.js
- packages/static-module-record/src/transform-analyze.js
- yarn.lock
This change reverts two changes that turned out to not be backward compatible as advertised.  My intent is to publish a patch to unbreak the upgrade path for existing installations and then later restore these changes either in a subsequent patch or a major bump.
These are surgical reverts for a portion of the changes that were released, not a full roll-back.
- Revert "fix(static-module-record): minimise source changes with `recast`"
- Revert "build(deps): add a patched version of `recast`"
- fix(static-module-record): Account for unlocated nodes in displayAsExport
Please review closely the novel code in the final commit that got the tests passing but was evidently unnecessary when composed with recast.
> fix(static-module-record): Revert recast

- package.json
- packages/stream/LICENSE
- packages/stream/README.md
- packages/stream/index.d.ts
- packages/stream/index.js
- packages/stream/jsconfig.json
- packages/stream/package.json
- packages/stream/test/lockdown.js
- packages/stream/test/test-stream.js
Adds a small stream library that provides a foundation for streaming with async iterators. The types are a bit more rigid than AsyncIterator in order to mesh better in TypeScript.
The library includes a reductive makePromiseKit since the AsyncQueue requires a “soft” object and doesn’t require much else that `@agoric/promise-kit` might provide, but nevertheless, I took a cue from attempting to use `@agoric/promise-kit` and implemented the library atop hardened JavaScript.
> feat(stream): Add stream library

- package.json
- packages/stream-json/LICENSE
- packages/stream-json/README.md
- packages/stream-json/index.d.ts
- packages/stream-json/index.js
- packages/stream-json/jsconfig.json
- packages/stream-json/package.json
- packages/stream-json/reader.js
- packages/stream-json/test/lockdown.js
- packages/stream-json/test/test-stream-json.js
- packages/stream-json/writer.js
This builds on #964, providing adapters for Uint8Array message streams to JSON streams, capturing the concerns of transcoding and marshaling. These are also hardened.
> feat(stream-json): Add JSON stream adapters

- package.json
- packages/stream-node/LICENSE
- packages/stream-node/README.md
- packages/stream-node/index.d.ts
- packages/stream-node/index.js
- packages/stream-node/jsconfig.json
- packages/stream-node/package.json
- packages/stream-node/reader.js
- packages/stream-node/test/cat.js
- packages/stream-node/test/lockdown.js
- packages/stream-node/test/test-stream-node.js
- packages/stream-node/writer.js
This builds on #964 and provides adapters for Node.js Reader and Writer in terms of hardened JS streams (based on the async iterator protocol.)
> feat(stream-node): Node.js stream adapters

- package.json
- packages/stream-types-test/package.json
- packages/stream-types-test/tsconfig.json
- packages/stream-types-test/validation.ts
- packages/stream/index.d.ts
- packages/stream/index.js
- packages/stream/jsconfig.json
- packages/stream/package.json
- packages/stream/test/test-stream.js
- packages/stream/types.d.ts
This change ejects certain type definitions from the stream library as they are not fully expressible as JSDoc. Particularly, this allows the reader and writer generic types to have default templates.
> refactor(stream): Give types unto TypeScript

- package.json
- packages/lockdown/CHANGELOG.md
- packages/lockdown/commit-debug.js
- packages/lockdown/commit.js
- packages/lockdown/package.json
- packages/lockdown/post.js
- packages/lockdown/pre.js
This uses git subtree to migrate Lockdown from the Agoric SDK repository as part of the greater plan to move Endo dependencies to the Endo repository. Uses the git subtree instructions from #560.
Refs #506
> chore: Migrate lockdown from Agoric SDK

- README.md
- packages/ses/README.md
- fix: Broken link to security at top level
- docs(ses): Security claims and caveats
> docs: Security claims and caveats

- packages/ses/README.md
The example in question claims that the per-compartment `Function` constructor arranges for `this` to be bound to its particular `globalThis`. However, because compartments only reveal strict mode functions, `this` is `undefined`. So, to support the claim documented above the example, we amend the example to grab `globalThis` from the scope of the function body.
> fix(ses): Fix mistaken this binding example

- packages/init/package.json
- packages/promise-kit/package.json
- packages/stream-node/package.json
- packages/stream-types-test/package.json
- packages/stream/package.json
- scripts/all-versions.sh
- scripts/get-versions.sh
- scripts/set-versions.sh
- scripts/sync-versions.sh
This change adds some scripts we can use to keep dependency versions in sync
across packages, then applies them to our current setup.
The get, set, and sync scripts are borrowed from Agoric SDK.
The all script is new.
- chore: Add version synchronization scripts
- chore: Synchronize versions
- chore: Update yarn.lock
> chore: Synchronize internal versions

- packages/ses/NEWS.md
- packages/ses/error-codes/SES_DIRECT_EVAL.md
- packages/ses/src/lockdown-shim.js
- packages/ses/test/test-evalability.js
- packages/ses/test/unevalability.js
- test(ses): Test dynamic eval detection
- feat(ses): Check early for dynamic evalability
Fixes #343
> feat(ses): Detect corrupted feral eval early

- packages/ses/src/lockdown-shim.js
- packages/ses/test/no-direct-eval.js
- packages/ses/test/no-eval.js
- packages/ses/test/test-no-direct-eval.js
- packages/ses/test/test-no-eval.js
This change adds nuance to the code that checks for whether eval is
direct-eval. We do want to screen environments where eval is indirect.
But, if eval throws an exception instead, that would indicate a
content-security-policy that excludes unsafe-eval, and SES should be
usable for this case in a future version.
Currently, this case fails for other reasons.
So this change adds a known-failing test.
> fix(ses): Direct eval check should not preclude no-eval under CSP

- packages/lp32/package.json
- packages/lp32/test/lockdown.js
- packages/lp32/test/test-lp32.js
- packages/netstring/NEWS.md
- packages/netstring/package.json
- packages/netstring/test/lockdown.js
- packages/netstring/test/test-netstring.js
- packages/stream-node/package.json
- packages/stream-node/test/lockdown.js
- packages/stream-node/test/test-stream-node.js
- packages/stream-types-test/validation.ts
- packages/stream/README.md
- packages/stream/index.d.ts
- packages/stream/index.js
- packages/stream/package.json
- packages/stream/test/lockdown.js
- packages/stream/test/test-map.js
- packages/stream/test/test-prime.js
- packages/stream/test/test-pump.js
- packages/stream/test/test-stream.js
- packages/stream/types.d.ts
This change introduces pump and prime functions to the stream package.
Pump moves iterations from a reader to a writer and returns a promise for when either the reader or writer closes. The implementation of pump was more concise before satisfying TypeScript because the `tick` and `tock` internal phases were possible to express with a single `push` function that alternated direction. I found the duplication and mutual recursion tolerable.
Prime is an adapter for a generator function when it is used as a writer, which “primes” the generator, causing it to advance to the first yield expression immediately. Some nuance follows to handle the cases that the generator returns or throws before reaching a yield.
> feat(stream): Add pump and prime

- packages/eventual-send/src/E.js
- packages/eventual-send/src/handled-promise.js
- packages/eventual-send/test/test-e.js
refs: Agoric/agoric-sdk#4362
closes: Agoric/agoric-sdk#4363
Move hardening around HandledPromises to the shim so that it can't be bypassed with a malicious user-level `E`.
The motivation in Agoric/agoric-sdk#4362 still applies; when we're under SES, we should harden on the boundaries of the system.  HandledPromise's eventual send and eventual get support is such a thing.
> feat: HandledPromise hardening

- packages/marshal/src/helpers/error.js
- packages/marshal/src/marshal.js
Restore edits from https://github.com/Agoric/agoric-sdk/pull/4304 to the marshal package.
Fixes https://github.com/Agoric/agoric-sdk/issues/4312 again ;)
Have recognition of passable Error obtain name from prototype, skipping any own name property on the error instance.
Note several of the places we need to revisit when we admit error.cause and error.errors.
Inline TODOs reminding us to revisit issues identified by zestival
> Retore edits from agoric-sdk #4304

- packages/lockdown/commit-debug.js
- packages/lockdown/pre.js
- packages/marshal/README.md
These remaining misnomers are in a layer below the package in question
and did not get caught in the initial migration.
> refactor: Clean up references to @endo/install-ses

- packages/base64/package.json
- packages/cjs-module-analyzer/package.json
- packages/cli/package.json
- packages/compartment-mapper/package.json
- packages/daemon/package.json
- packages/eslint-config/package.json
- packages/lp32/package.json
- packages/netstring/package.json
- packages/promise-kit/package.json
- packages/ses-ava/package.json
- packages/ses-types-test/package.json
- packages/ses/package.json
- packages/static-module-record/package.json
- packages/stream-node/package.json
- packages/stream-types-test/package.json
- packages/stream/package.json
- packages/syrup/package.json
- packages/where/package.json
- packages/zip/package.json
- yarn.lock
This syncs the current TypeScript version with Agoric SDK to reduce probability of divergent behavior under lint.
- chore: Sync TypeScript version with Agoric SDK
- chore: Update yarn.lock
> chore: Sync TypeScript with Agoric SDK

- packages/compartment-mapper/src/link.js
The has utility function in the compartment mapper did not need to be generic.  Because it was generic, at a vast distance down the dependency chain, TypeScript proposed bizarre combinations of types for each of the uses, probably sampling the first ambient type that emitted a valid function, then failed type check in compartment-mapper.
> fix(compartment-mapper): Needless genericity considered harmful

- packages/ses/index.d.ts
Evidently, in a recent change to appease eslint, SES stopped exporting a type for globalThis.assert et al.
> fix(ses): Globals have vars, not consts

- packages/ses/NEWS.md
- packages/ses/src/commons.js
- packages/ses/src/make-hardener.js
- packages/ses/test/test-is-typed-array.js
- packages/ses/test/test-make-hardener.js
Harden can now handle typed arrays.  Although typed arrays cannot be frozen because their integer properties cannot be made non-writable by any mechanism, these properties are analogous to the entries in a map, which can be hardened.  This change makes harden treat typed arrays as the moral equivalent of a map.  Hardening a typed array seals the object and makes all other properties non-writable and non-configurable.
Fixes #1029
> feat(ses): Harden typed arrays

- yarn.lock
The Agoric-patched agoric-labs/recast#Agoric-built and agoric-labs/ast-types#Agoric-built versions had too many files in them.  Updated to properly contain the same as the `yarn pack` versions, then republished.
This PR uses the new versions.
> build: repoint `yarn.lock` at slimmer package of recast for TS

- package.json
- packages/base64/package.json
- packages/cjs-module-analyzer/package.json
- packages/cli/package.json
- packages/compartment-mapper/package.json
- packages/daemon/package.json
- packages/eslint-config/package.json
- packages/eventual-send/src/handled-promise.js
- packages/lp32/package.json
- packages/marshal/src/dot-membrane.js
- packages/marshal/src/marshal-justin.js
- packages/marshal/src/marshal.js
- packages/marshal/src/passStyleOf.js
- packages/netstring/package.json
- packages/promise-kit/package.json
- packages/ses-ava/package.json
- packages/ses-types-test/package.json
- packages/ses/package.json
- packages/static-module-record/package.json
- packages/stream-node/package.json
- packages/stream-types-test/package.json
- packages/stream/package.json
- packages/syrup/package.json
- packages/where/package.json
- packages/zip/package.json
- scripts/repackage.sh
- yarn.lock
Update TS to 4.5 to align with upcoming `agoric-sdk` change (see https://github.com/Agoric/agoric-sdk/pull/4420).
Make some types explicit any to prevent inference. Sprinkle some jsdoc here and there.
> Update TypeScript to 4.5

- packages/captp/src/captp.js
- packages/captp/src/types.js
- packages/marshal/NEWS.md
- packages/marshal/exported.js
- packages/marshal/index.js
- packages/marshal/jsconfig.build.json
- packages/marshal/package.json
- packages/marshal/src/deeplyFulfilled.js
- packages/marshal/src/helpers/copyArray.js
- packages/marshal/src/helpers/copyRecord.js
- packages/marshal/src/helpers/error.js
- packages/marshal/src/helpers/internal-types.js
- packages/marshal/src/helpers/passStyle-helpers.js
- packages/marshal/src/helpers/remotable.js
- packages/marshal/src/helpers/tagged.js
- packages/marshal/src/make-far.js
- packages/marshal/src/marshal-justin.js
- packages/marshal/src/marshal-stringify.js
- packages/marshal/src/marshal.js
- packages/marshal/src/passStyleOf.js
- packages/marshal/src/pureCopy.js
- packages/marshal/src/typeGuards.js
- packages/marshal/src/types.js
- packages/marshal/test/test-marshal-far-obj.js
Experiment to remove dependency on ambient types.  The process:
1. Put `export {};` near the top of every JSDoc `types.js` file.  This switches it from an ambient file to a module with exported types.
2. Remove `exported.js` so that ambient type users break hard.
3. Add `export * from './src/types.js';` to `index.js` so that upstream consumers can import types from the package identifier.  Season with eslint-ignores to taste.
4. Remove any `import './types.js';`, `import './internal-types.js';` etc.
5. Add `/** @typedef {import('./types.js').MemberName} MemberName */` or for template types `/** @template T @typedef {import('./types.js').MemberName2<T>} MemberName2 */`. as needed to the top of `.js` sources.
6. Chase any other Typescript errors.
7. Add build step to generate declarations, …
> fix(marshal): remove ambient types, generate declarations from JSDoc

- packages/nat/src/index.js
This change is necessary to allow callers to use `Nat` on data whose type they are unsure of.
> fix(nat): declare `allegedNum` as `unknown`, then assert

- .github/workflows/ci.yml
- packages/cli/package.json
- packages/cli/src/endo.js
- packages/daemon/daemon.js
- packages/daemon/index.d.ts
- packages/daemon/index.js
- packages/daemon/jsconfig.json
- packages/daemon/src/client.js
- packages/daemon/src/connection.js
- packages/daemon/src/daemon.js
- packages/daemon/src/worker.js
- packages/daemon/test/test-endo.js
- packages/stream/index.js
- packages/stream/test/test-pump.js
- packages/where/index.d.ts
- packages/where/index.js
- packages/where/test/test-where-endo-cache.js
- packages/where/test/test-where-endo-state.js
- packages/where/types.d.ts
This change takes a number of steps toward spawning a worker which currently does nothing except support graceful termination. Commits are individually reviewable.
Refs #1036
The first change reverts eventual-messages for streams. #1028 because this unexpectedly causes data-lock for the Endo daemon. This might be because of a layering issue: the stream in question is carrying CapTP. It might be possible to recover the feature manually, but was probably unwise to lean on eventual-send anyway, on account of the layering.
The subsequent commits each make some surgical change necessary to explore outward to endo daemon workers.
In subsequent changes, this initial worker will grow the ability to run arbitrary programs under hardened JavaScript with limited access to user powers. But first, …
> feat(daemon): Add worker with lifecycle

- scripts/set-versions.sh
This change makes it possible to, for example from an Agoric dapp, use `~/endo/scripts/get-versions.sh ~/endo | ~/endo/scripts/set-versions.sh`, to update the versions of Endo dependencies to their most up-to-date versions in a local copy of Endo in the dapp's workspace, including dependencies at the top-level of Endo, or `~/endo/scripts/all-versions.sh ~/endo | ~/endo/scripts/set-versions.sh` (*all-versions*) to sync transitive dependencies.
> fix: Make scripts/set-versions suitable for external usage

- packages/ses/docs/lockdown.md
- packages/ses/error-codes/SES_NO_EVAL.md
- packages/ses/index.d.ts
- packages/ses/src/commons.js
- packages/ses/src/compartment-shim.js
- packages/ses/src/global-object.js
- packages/ses/src/lockdown-shim.js
- packages/ses/src/make-eval-function.js
- packages/ses/test/test-evalTaming-default.js
- packages/ses/test/test-evalTaming-noEval.js
- packages/ses/test/test-evalTaming-safeEval.js
- packages/ses/test/test-evalTaming-unsafe.js
- packages/ses/test/test-global-object.js
This PR adds a new option `evalTaming` which defaults to `"safeEval"` (current behavior).
I introduced a new behavior `"unsafeEval"` and `"noEval"`.
This option is for the environment that does not allow `eval` in the production mode but allows it in the development mode for webpack `eval-source-map`.
The current behavior will replace the `eval` constructor and cause the webpack bundle to fail to load.
I have documented this new option and warned any users do not use it unless they have the same situation as us.
> feat: add evalTaming option

- packages/compartment-mapper/NEWS.md
- packages/compartment-mapper/src/import-archive.js
- packages/compartment-mapper/src/import-hook.js
- packages/compartment-mapper/src/types.js
- packages/compartment-mapper/test/fixtures-cthuloops/README.md
- packages/compartment-mapper/test/fixtures-cthuloops/main.js
- packages/compartment-mapper/test/fixtures-cthuloops/package.json
- packages/compartment-mapper/test/scaffold.js
- packages/compartment-mapper/test/test-cthuloop.js
- packages/compartment-mapper/test/test-integrity.js
- packages/compartment-mapper/test/test-main.js
*BREAKING CHANGE:* Previously, `loadArchive` and `parseArchive`, when given a `computeSha512`, would accept just about any archive. Hash integrity checks for any used module occurred only after a request to import them. With this new version, all archives must use every file they contain and must pass hash integrity checks during the load or parse phase.  Consequently, if an archive requires any built-in modules ("exits"), these must be mentioned with the `modules` option to `loadArchive` or `parseArchive`, as an object whose keys are the names of the expected modules.
Refs: https://github.com/agoric/agoric-sdk/issues/3859
- I am posting this PR as an early draft for a direction check while I begin producing test cases that cover invalid bundles.
> feat(compartment-mapper)!: Pre-load for archive integrity checks

- packages/bundle-source/package.json
- packages/bundle-source/src/index.js
- packages/static-module-record/package.json
- packages/static-module-record/src/transform-analyze.js
- yarn.lock
While recast was good at trying to preserve existing formatting, it just wasn't cut out for line- and column-number preservation.
Rather than make more fragile hacks to it, I made a small change to `@babel/generator`:
```diff
diff --git a/packages/babel-generator/src/printer.ts b/packages/babel-generator/src/printer.ts
index bbdcc5b1ba..8383e6cf31 100644
--- a/packages/babel-generator/src/printer.ts
+++ b/packages/babel-generator/src/printer.ts
@@ -349,6 +349,15 @@ class Printer {
this._newline();
}
}
+
+    // catch up to this nodes column if we're behind
+    if (pos?.column != null) {
+      const count = pos.column - this._buf.getCurrentColumn();
+
+      if (count > 0) {
+        this._append(" ".repeat(count));
+      }
+    }
}
/**
```
Unfortunately, this change doesn't result in …
> Recast begone!

- yarn.lock
I've been trying to keep duplicate versions of babel away from `yarn.lock`. Manually deduplicated some entries that appeared after https://github.com/endojs/endo/pull/1096#issuecomment-1055808798
> chore: small yarn.lock dedup

- packages/cli/package.json
- packages/cli/src/endo.js
- packages/daemon/package.json
- packages/daemon/src/daemon.js
- packages/daemon/src/worker.js
- packages/daemon/test/test-endo.js
- packages/init/package.json
- packages/init/pre-bundle-source.js
- packages/ses-integration-test/scaffolding/rollup/test-rollup.config.js
- packages/ses/test262/make-importer.js.SKIP
- packages/static-module-record/DESIGN.md
- packages/static-module-record/package.json
- packages/static-module-record/src/static-module-record.js
- packages/static-module-record/src/transform-analyze.js
- yarn.lock
Remove our reliance on `@agoric/babel-standalone`, and instead compose `@babel/parser`, `@babel/traverse`, and `@agoric/babel-generator`.
> Pure Babel

- packages/eventual-send/jsconfig.test.json
- packages/eventual-send/package.json
- packages/eventual-send/src/E.js
- packages/eventual-send/src/index.d.ts
- packages/eventual-send/test/prepare-test-env-ava.js
- packages/eventual-send/test/test-types.js
- packages/far/src/index.js
- packages/marshal/src/make-far.js
First, a little change to propagate types from `@endo/eventual-send`'s `E` to the outside world.
Then, a more ambitious change to instate a proper `Remote<Primary, Local=DataOnly<Primary>>` type that enforces the rules of our distributed object system.  This helps prevent the `(await o).myMethod()` cheat that worked locally but failed when `o` was not the primary remotable.
> fix(eventual-send): stronger (compatible) typing of `E` and `Remote`

- packages/static-module-record/src/transform-analyze.js
- packages/static-module-record/test/test-static-module-record.js
Closes #1108.
Avoid assignment of proporties to Object with a prototype.
> fix(static-module-record): use `Object.create(null)` to prevent crashes

- packages/compartment-mapper/src/infer-exports.js
We solved this problem by adding `moduleMapHook` to the `Compartment` options and generating entries dynamically, based on the prefix of a known import prefix.
> fix(compartment-mapper): Remove stale note

- packages/compartment-mapper/NEWS.md
- packages/compartment-mapper/src/archive.js
- packages/compartment-mapper/src/node-modules.js
- packages/ses/package.json
- packages/ses/package.json.md
Refs https://github.com/endojs/endo/issues/1123
- fix(ses): Do not bundle modules for use as modules
- fix(endo): Ensure conditions include default, import, and endo
> fix: Support default conditions and avoid SES double bundle

- packages/ses/src/whitelist.js
Silences warnings on the latest XS.
> fix(ses): Ignore Array unscopable findLast{,Index}

- packages/ses/demos/challenge/README.md
- packages/ses/demos/challenge/index.html
- packages/ses/demos/challenge/main.js
- packages/ses/demos/challenge/style.css
- packages/ses/demos/index.html
This is mostly an aesthetic change that can be reviewed by the PR's Netlify deployment link below. Additionally, this renames the SES Challenge to Hardened JavaScript Escape Room, for your consideration.
Fixes #1132
> refactor(ses): Sharpen challenge demo

- packages/ses/test/error/test-tame-console-unfilteredError.js
- packages/ses/test/error/test-tame-console-unsafe-unfilteredError.js
- packages/ses/test/error/test-tame-console-unsafe.js
- packages/ses/test/error/test-tame-console.js
Some tests assumed that `errorTaming` had its default `'safe'` value by omitting it in their call to `lockdown`. However, I normally run with 
```sh
export LOCKDOWN_ERROR_TAMING=unsafe
```
which overrides that default. That's normally what I want, to see more diagnostics. But these test were testing the contents of the diagnostics with the `'safe'` setting. So I pass the `errorTaming: 'safe'` setting explicitly to their `lockdown`s.
> fix: some tests sensitive to errorTaming

- packages/base64/src/decode.js
- packages/base64/src/encode.js
- packages/zip/src/buffer-writer.js
This PR includes some changes I needed to do in order to debug trying to `ZipWriter.write(name, decodeBase64(str))`.
The solution is simple; just wrap the XS native decoder.
> XS `Base64.decode` returns an `ArrayBuffer`, not `Uint8Array`

- packages/compartment-mapper/test/fixtures-error-handling/node_modules/catch/README.md
- packages/compartment-mapper/test/fixtures-error-handling/node_modules/catch/getmissing.js
- packages/compartment-mapper/test/fixtures-error-handling/node_modules/catch/main.js
- packages/compartment-mapper/test/fixtures-error-handling/node_modules/catch/package.json
- packages/compartment-mapper/test/fixtures-error-handling/node_modules/what-the-falsy/README.md
- packages/compartment-mapper/test/fixtures-error-handling/node_modules/what-the-falsy/main.js
- packages/compartment-mapper/test/fixtures-error-handling/node_modules/what-the-falsy/package.json
- packages/compartment-mapper/test/fixtures-error-handling/node_modules/what-the-falsy/throws-falsy.js
- packages/compartment-mapper/test/test-error-handling.js
- packages/ses/src/module-instance.js
fixes #1116
I didn't observe negative consequences of calling activate() more than once, but that could be avoided.
ALso, it would be possible to hold on to the error and rethrow it instead of running execute each time, but I think that could get cached higher the dependency chain than needed.
> Handle user code catching errors from require

- packages/eventual-send/src/index.d.ts
- packages/eventual-send/src/index.test-d.ts
- packages/eventual-send/test/test-types.js
- packages/eventual-send/tsconfig.json
- packages/far/src/index.js
- packages/marshal/src/make-far.js
These improve the typing of `E` and `Trap` to be more accurate.
Also, introduce `FarRef<T>` as an "I can handle near, far objects and promises for them" type.
> More typing improvements to `@endo/eventual-send` and `@endo/captp`

- packages/ses/src/compartment-evaluate.js
- packages/ses/src/compartment-shim.js
- packages/ses/src/make-safe-evaluator.js
- packages/ses/src/scope-handler.js
- packages/ses/test/test-make-evaluate-factory.js
- packages/ses/test/test-make-evaluator.js
- packages/ses/test/test-scope-handler.js
- refactor(ses): Make evaluate factory validation less sensitive to white space
- refactor(ses): Rename localObject to globalLexicals
- fix(ses): Prevent hypothetical stack bumping for unsafe eval
Fixes #956
Fixes #840 (drive by fix)
> fix(ses): Prevent hypothetical stack bumping for unsafe eval

- packages/bundle-source/package.json
- packages/bundle-source/src/is-entrypoint.js
- packages/bundle-source/src/tool.js
cc @warner , @turadg  ref https://github.com/Agoric/agoric-sdk/issues/3609
demo:
```
$ rm -rf /tmp/d
$ bundle-source /tmp/d demo/dir1/index.js demo1 demo/circular/a.js circular
"demo1": cannot read bundle metadata: "[Error: ENOENT: no such file or directory, open '/tmp/d/bundle-demo1-meta.json']"
/tmp/d add: demo1 from demo/dir1/index.js
/tmp/d bundled 3 files in bundle-demo1.js at 2022-04-14T19:19:34.185Z
"circular": cannot read bundle metadata: "[Error: ENOENT: no such file or directory, open '/tmp/d/bundle-circular-meta.json']"
/tmp/d add: circular from demo/circular/a.js
/tmp/d bundled 2 files in bundle-circular.js at 2022-04-14T19:19:34.293Z
$ bundle-source /tmp/d demo/dir1/index.js demo1 demo/circular/a.js circular
/tmp/d bundle-demo1.js valid: 3 files bundled at …
```
> feat(bundle-source): CLI tool with caching

- packages/init/src/node-async_hooks.js
After #1115 landed in agoric-sdk, people stated experiencing errors like `TypeError#1: Cannot assign to read only property 'Symbol(destroyed)' of object '[object Promise]'`
The patch was overzealous and set the property as non-configurable and non-writable. This isn't a problem for the `async_id` and `trigger_async_id` symbols since node tests for their presence before assigning, however it seems node unconditionally set the destroyed symbol, and being an object, the description doesn't match (different value), and the later assignment throws.
I am not quite sure under which circumstances this situation arises, or I'd add a test for it.
> fix(init): workaround node promise destroyed bug

- packages/check-bundle/package.json
- packages/check-bundle/src/json.js
- packages/check-bundle/test/test-check-bundle.js
- packages/compartment-mapper/src/import-archive.js
This change improves an error diagnostic that has become common when we introduced a cache that sometimes vended out corrupt bundles.
> test(check-bundle): Cover invalid archive error with location diagnostic

- packages/ses/test/test-property-override.js
This is a sanity check that seems like a good one to carry forward into test 262 one day. The problem that motivated the sanity check was a hardened array instance. Hardening the prototype of all arrays doesn’t preclude using length assignment to truncate.
> test(ses): Verify assignability of array length over frozen prototype

- packages/ses/src/error/tame-error-constructor.js
- packages/ses/src/whitelist.js
- packages/ses/test/test-enable-property-overrides-default-unsafeError.js
- packages/ses/test/test-enable-property-overrides-default.js
- packages/ses/test/test-enable-property-overrides-min-unsafeError.js
- packages/ses/test/test-enable-property-overrides-min.js
Fixes #1165 
Implements https://github.com/tc39/proposal-error-stacks/ assuming the fix proposed at https://github.com/tc39/proposal-error-stacks/issues/46
> fix: all errors have stacks, even if empty

- packages/compartment-mapper/src/parse-cjs-shared-export-wrapper.js
- packages/compartment-mapper/test/fixtures-cjs-compat/node_modules/defineprop/c.js
- packages/compartment-mapper/test/fixtures-cjs-compat/node_modules/defineprop/example-babeltypes.js
- packages/compartment-mapper/test/fixtures-cjs-compat/node_modules/defineprop/main.js
… by not trying to create named exports too hard
Initially the idea was to use the same mechanic of promoting fields to named exports for the ones defined with a getter by calling the getter immediately. It ends up producing more harm than good, so I've decided to skip exposing getter-based exports as named exports from cjs. 
For now it seems like an overall improvement in ecosystem compatibility.
*Fedor's contraption* for lazy init now works as expected in cjs. Could even work as named exports if we're lucky, because once the getter is called it propagates the value. It'd need to be required before it's imported though. 
The ability to delegate a named export to a getter would require defining a getter on the exportsProxy or opening more of its internals to parse-cjs. 
It changes our …
> fix(compartment-mapper) Increase defineProperty no exports compatibility

- packages/ses/docs/lockdown.md
The early entries in lockdown.md followed a consistent convention when showing the different possible calls to `lockdown` within each section. More recent entries did not, probably because it was not clear that there was a convention to be followed. This PR is stacked on #1178 and repairs that convention throughout lockdown.md as of #1178 .
Also updates domainTaming to show that it now defaults to `'safe'`.
@michaelfig if you'd like to just fold this into #1178, please do. I would prefer that. But if you'd like me to hold this as a follow-on PR, that would be ok.
@kriskowal I included you because some of the repairs are, I think, to text you wrote so you should be aware of this.
> fix: or vs vs convention

- packages/marshal/src/marshal-justin.js
- packages/marshal/src/marshal.js
- packages/marshal/src/types.js
- packages/marshal/test/test-marshal-justin.js
- packages/marshal/test/test-marshal.js
We first had a special marshal encoding special case for `Symbol.asyncIterator`. Over 4 months ago we introduced general symbol handling. But we kept sending the special case in case there were non-updated receivers, and kept understanding the special case on reception in case there were non-updated senders.
These four months is enough to give us confidence that there are no longer only receivers that do not understand the new symbol encoding. So this PR retires the code for sending the special case. Once we're confident that there are no senders older than this PR we'll be able to update the receivers too.
> fix: retire deprecated "@@asyncIterator" sending only

- packages/marshal/index.js
- packages/marshal/src/marshal-justin.js
- packages/marshal/test/test-marshal-justin.js
Fixes #1185 
As of https://github.com/Agoric/agoric-sdk/pull/5401 we'll use `decodeToJustin`, so export it as we always expected to.
Take @dtribble 's suggestion to rename `getSlotVal` to simply `slot`.
> fix: decodeToJustin accepts slot backrefs

- packages/stream/index.js
- packages/stream/package.json
This refactor is merely deduplication of makePromiseKit in the stream library.
Since writing stream, we moved promise kit to Endo, simplified, and committed to hardened-only streams.
> refactor(stream): Stand on promise-kit dependency

- packages/static-module-record/package.json
- packages/static-module-record/src/babelPlugin.js
- packages/static-module-record/src/transform-analyze.js
- packages/static-module-record/src/transformSource.js
- packages/static-module-record/test/benchmark-babel-plugin.js
- packages/static-module-record/test/fixtures/exportheavy.js
- packages/static-module-record/test/fixtures/large.js
- packages/static-module-record/test/fixtures/small.js
- packages/static-module-record/test/test-static-module-record.js
- yarn.lock
Note this PR has been opened against naugtur-import-meta-url branch. I wanted to discuss this commit separately
Working on import.meta I stumbled upon a case where if import.meta is used in an export statement it's not being reached by the visitor. 
This is one of the possible implementations.
Other ideas include:
- calling path.traverse inside rewriteDeclaration, which makes the whole thing take 2x the time
- replacing import.meta in the first ('Analyze') pass, which is controversial.
I think this fix may also fix other issues we didn't discover yet.
_I'm aware this has lint issues and a console.log leftover. I'm setting up the PR to make discussion easier_
> babelPlugin fix proposal and benchmarking setup

- packages/eventual-send/src/handled-promise.js
We need to be more defensive in the `HandledPromise` innards or else we get the following if `NaN` is shortened:
```
TypeError#18: Invalid value used as weak map key
at WeakMap.set (<anonymous>)
at shorten (file:///Users/michael/agoric/agoric-sdk/node_modules/@endo/eventual-send/src/handled-promise.js:114:35)
at handledResolve (file:///Users/michael/agoric/agoric-sdk/node_modules/@endo/eventual-send/src/handled-promise.js:232:17)
at resolveHandled (file:///Users/michael/agoric/agoric-sdk/node_modules/@endo/eventual-send/src/handled-promise.js:380:9)
at win (file:///Users/michael/agoric/agoric-sdk/node_modules/@endo/eventual-send/src/handled-promise.js:510:11)
at file:///Users/michael/agoric/agoric-sdk/node_modules/@endo/eventual-send/src/handled-promise.js:528:20
at …
```
> fix(eventual-send): use `!Object.is(a, b)` instead of `a !== b` for NaNs

- packages/ses/src/error/console.js
- packages/ses/src/error/internal-types.js
- packages/ses/test/error/test-assert-log.js
- packages/ses/test/test-console-error-trap.js
- packages/ses/test/test-console-rejection-trap.js
This fixes a longstanding problem where if you did a `console[level](...args_with_some_error)`, then the error output would not necessarily go to `level`.  Now it does.
> fix(console): direct error output to the current severity

- packages/base64/NEWS.md
- packages/base64/atob.js
- packages/base64/btoa.js
- packages/base64/index.js
- packages/base64/package.json
- packages/base64/shim.js
- packages/base64/test/capture-atob-btoa.js
- packages/base64/test/test-main.js
- packages/import-bundle/src/index.js
- packages/init/package.json
- packages/init/pre.js
- packages/init/src/pre-node.js
- yarn.lock
These are useful and standard Web/Node.js APIs for Base64 support.
At least `protobufjs` relies on having them in the global scope (Web-compatible) when `Buffer` is unavailable.
> Implement and shim `atob` and `btoa`

- packages/ses/src/commons.js
- packages/ses/src/error/console.js
- packages/ses/src/error/internal-types.js
This fix is required as my existing attempt at severity propagation caused exceptions in actual use.
I improved the commons typing around WeakMaps a little bit to help find this problem.
> fix(console): close over severity for error note callbacks

- packages/check-bundle/test/test-check-bundle.js
- packages/init/test/test-async_hooks.js
- packages/lp32/test/test-lp32.js
- packages/netstring/test/test-netstring.js
- packages/stream-node/test/test-stream-node.js
- packages/stream/test/test-map.js
- packages/stream/test/test-prime.js
- packages/stream/test/test-pump.js
- packages/stream/test/test-stream.js
I normally run with 
```sh
export LOCKDOWN_ERROR_TAMING=unsafe
```
This caused a failure in a test case comparing error messages, that were made more explanatory with this setting. The problem is that our tests were run with a neutral `lockdown` call that was letting this setting be set by the environment variable, but the test itself happened to depend on this option being `'safe'`. I think our best practice should be that `test-*.js` ava test files[1] should use the `@endo/init/debug.js` settings rather than the `@endo/init` settings. Then the error messages during testing will be more informative without endangering info leakage in production.
[1] aside from those whose purpose is to test the lockdown options, or whose purpose is to test that sensitive info in error messages get …
> fix: tests use debug settings

- packages/compartment-mapper/src/bundle.js
- packages/ses/README.md
- packages/ses/src/compartment-shim.js
- packages/ses/src/module-instance.js
- packages/ses/src/module-load.js
- packages/ses/test/node.js
- packages/ses/test/test-import.js
- packages/static-module-record/DESIGN.md
- packages/static-module-record/package.json
- packages/static-module-record/src/babelPlugin.js
- packages/static-module-record/src/hidden.js
- packages/static-module-record/src/static-module-record.js
- packages/static-module-record/src/transform-analyze.js
- packages/static-module-record/src/transformSource.js
- packages/static-module-record/test/benchmark-babel-plugin.js
- packages/static-module-record/test/fixtures/exportheavy.js
- packages/static-module-record/test/fixtures/large.js
- packages/static-module-record/test/fixtures/small.js
- packages/static-module-record/test/test-static-module-record.js
- yarn.lock
Implemented import.meta according to #291
The actual implementation of exposing import.meta.url to modules loaded by compartment-mapper is going to be a separate PR.
> feat(static-module-record): add support for import.meta

- packages/compartment-mapper/src/compartment-map.js
- packages/compartment-mapper/src/parse-cjs-shared-export-wrapper.js
- packages/marshal/src/typeGuards.js
- packages/ses/src/transforms.js
For some reason, when a newline is placed between a function jsdoc-type declaration and the function itself, ts type checking makes fewer bad rejections while otherwise seeming to stay as accurate. Discovered by accident. I have no idea why.
Also removing extraneous spaces within the outer curlies of jsdoc type decls, as our style is generally to omit them. By omitting them consistently, it is easier to find things with trivial greps.
See https://github.com/Agoric/agoric-sdk/pull/5597
> fix: trivial changes to make lint happy

- packages/ses/src/whitelist-intrinsics.js
- packages/ses/test/test-tolerate-empty-prototype.js
See https://github.com/zloirock/core-js/issues/1092
If a primordial method is whitelisted as `fn`, then it is not supposed to have `prototype` property. However, as explained by https://github.com/zloirock/core-js/issues/1092 , there is some desire to run `core-js` as a vetted shim, i.e., a shim run before `lockdown` that does not break any of the invariants that SES depends on. However, the core-js shim also targets ES5, and there's no good option in ES5 for making a replacement primordial function that does not have an undeletable `prototype` property.
With this PR, our whitelisting, on encountering such a function, instead sets its `prototype` to `undefined` and then checks that it has done so. If so, then it issues a warning but allows the whitelisting to continue.
> fix: tolerate empty func.prototype

- packages/daemon/src/daemon.js
- packages/init/NEWS.md
- packages/init/package.json
- packages/init/pre.js
- packages/promise-kit/NEWS.md
- packages/promise-kit/index.js
- packages/promise-kit/package.json
- packages/promise-kit/shim.js
- packages/promise-kit/src/is-promise.js
- packages/promise-kit/src/memo-race.js
- packages/promise-kit/src/promise-executor-kit.js
- packages/promise-kit/src/types.js
- packages/promise-kit/test/test-promise-kit.js
The investigation into https://github.com/Agoric/agoric-sdk/issues/5507 lead us into discovering a leak caused by promises, in particular when using [`Promise.race` with a long pending promise](https://github.com/nodejs/node/issues/17469). The root cause really seem that the promise resolve functions hold onto the promise strongly (instead of just an internal record representing the reactions registered on the promise), and through that, the result of said promise. `Promise.race` is implemented as adding the result's promise's resolver functions to each of the contenders reactions, causing the long pending promise to keep the raced result alive.
This PR re-implements `Promise.race` based on the solution in https://github.com/nodejs/node/issues/17469#issuecomment-685216777. It also updates …
> fix: workaround leak through promise resolvers

- packages/ses/src/error/tame-v8-error-constructor.js
- packages/stream-node/writer.js
While investigating https://github.com/Agoric/agoric-sdk/issues/5447, I found that endo was possibly unnecessarily holding onto memory in a couple places. This PR fixes them:
- SES's v8 Error taming no longer holds onto the raw CallSite stack for error objects after it has created a string for them. It does so by keeping a second WeakMap with the generates stack string, and nulls out the content of the first WeakMap. That way the stack is still processed lazily.
- stream-node possibly held onto the finalResolution promise and other things in context even after the stream closed.
> fix unnecessary memory retention paths

- packages/marshal/src/typeGuards.js
At https://github.com/endojs/endo/commit/f08cad99aa715aa36f78dfd67b9f581cdd22bb3c#diff-d0d534331f6e24715174998494ab6eb7a9349c7e50aba59661267824001fb871 I added a function `assertPure` to marshal which is obviously wrong and dangerous. It is also exported from marshal. Fortunately no one uses it, so this PR deletes it.
There is a use of `assertPure` in agoric-sdk, which is wrong because `assertPure` is wrong. But it is using its own copy so removing it from endo has no effect on it. There do not seem to be any other uses.
Reviewers, deleting this is technically a non-compat change. Please let me know if you think we need to do the deprecation dance in order to get rid of it. If we do, we should also fix the deprecated one since it would still be exported, and it is still dangerously wrong. …
> fix(marshal)!: assertPure wrong but unused

- packages/eventual-send/NEWS.md
- packages/eventual-send/src/E.js
- packages/eventual-send/test/test-e.js
Closes #1253 
I decided to reject with an error instead of using a plain `assert`ion which would have thrown synchronously for an expected "async function". Cannot use a real `async function` of course since that would absorb the `HandledPromise` into a platform `Promise`.
@kriskowal please let me know if I got the dance of breaking change documentation right.
One this is approved, I will incorporate the changed in a patch on `agoric-sdk` along with the fixes from https://github.com/Agoric/agoric-sdk/commit/ab3b5900fd0845b9ed8081f61cadf81704891ba2
> fix(eventual-send)!: Disallow using E proxy methods as functions

- packages/marshal/src/helpers/remotable.js
- packages/marshal/test/test-passStyleOf.js
In order to support https://github.com/Agoric/agoric-sdk/pull/5970 , we need to allow at least one level of remotable inheritance. Currently supported in agoric-sdk as a patch. TODO after this is merged and agoric-sdk updated to depend on it, remove the patch.
> fix: prepare for far classes

- packages/marshal/src/helpers/safe-promise.js
- packages/marshal/test/test-passStyleOf.js
Refs https://github.com/endojs/endo/pull/1250#pullrequestreview-1082870845
The checks introduced in #1250 are not compatible with the async_hooks repair (https://github.com/endojs/endo/pull/1115). This PR fixes that in the narrowest way by allowing these symbols only if the repair is enabled and their value has the expected shape.
> Fix safe promise checks

- packages/eventual-send/src/track-turns.js
- packages/eventual-send/test/prepare-test-env-ava.js
This change includes work from myself and @warner.
1. Reduces the closure retention of functions wrapped for tracking event-loop turns.
2. Supports a DEBUG=track-turns flag that enables verbose logging, previously only available by editing track-turns.js
3. Supports a TRACK_TURNS=enabled flag that enables the feature. The intention is to reverse the flag’s polarity when we are confident that the feature can be used in production without retaining memory indefinitely.
Fixes #1245
> feat(eventual-send): De-risk track-turns

- packages/marshal/src/helpers/safe-promise.js
Our attempt to safely tolerate Node async_hooks was safe, but missed a case we could handle safely and which is provoked at least by the vscode debugger.
Node's async_hooks currently contains the following code, which we can also safely tolerate
```js
function destroyTracking(promise, parent) {
trackPromise(promise, parent);
const asyncId = promise[async_id_symbol];
const destroyed = { destroyed: false };
promise[destroyedSymbol] = destroyed;
registerDestroyHook(promise, asyncId, destroyed);
}
```
However, before this PR we did not know to expect this. I just encountered this failure when trying to debug some of our code in the vscode debugger. The additional record that Node adds here is one we can tolerate safely. This PR's expectations includes this additional record, so that we can …
> fix: tolerate more from async_hooks

- packages/daemon/src/connection.js
- packages/netstring/reader.js
- packages/netstring/test/test-netstring.js
- packages/netstring/writer.js
- packages/stream-node/test/test-stream-node.js
- packages/stream-node/writer.js
Rewrite the reader and writer of the netstring stream transform to avoid buffer copies and allocations as much as possible.
- The reader delays allocation of a buffer until the length prefix is parsed.
- The reader re-uses the input buffer if the whole data is a subset of the incoming chunk
- possible point of improvement is to handle the trailing separator (comma) in a separate chunk, as may happen went sent chunked in the first place
- The writer can output in chunked mode, where the prefix, data and separator are sent to the output as separate writes/next calls.
- The writer can handle an array of buffers as input for producers which would otherwise concatenate their data.
- The writer no longer re-uses an internal buffer for its output as a consumer that doesn't fully process the …
> Avoid buffer copies in netstring

- packages/bundle-source/NEWS.md
- packages/bundle-source/package.json
- packages/bundle-source/src/tool.js
- Adds a `--cache-json` mode that:
- Generates `.json` bundle files in JSON format.
- Generates `-json-meta.json` meta files in JSON format.
- Adds a `--cache-js` mode that should replace `--to`:
- Generates `.js` bundle files in JSON format.
Adds a UNIX newline absent when using `--to`.
- Generates `-json-meta.json` meta files in JSON format instead of
`-meta.js`.
> feat(bundle-source): Add JSON cache mode

- packages/captp/src/atomics.js
- packages/captp/src/captp.js
- packages/import-bundle/test/test-compartment-wrapper.js
- packages/marshal/src/encodeToCapData.js
- packages/marshal/src/helpers/passStyle-helpers.js
- packages/marshal/src/helpers/remotable.js
- packages/marshal/src/helpers/safe-promise.js
- packages/marshal/src/helpers/symbol.js
- packages/marshal/src/helpers/tagged.js
- packages/marshal/src/make-far.js
- packages/marshal/src/marshal-justin.js
- packages/marshal/src/marshal.js
- packages/marshal/src/passStyleOf.js
- packages/ses/src/environment-options.js
- packages/stream-node/reader.js
- packages/stream-node/writer.js
Like https://github.com/Agoric/agoric-sdk/pull/6174
Replace some occurrences of
```js
assert(..condExpr.., X`..detailsString..`);
```
with
```js
..condExpr.. || assert.fail(X`..detailsString..`);
```
I only made the changes that I was easily able to do via regexp search and replace in vscode
```
^\s*assert\(\n\s*(.*?),\n\s*X`(.*?)`,\n\s*\);
($1) || assert.fail(X`$2`);
```
and similar, followed by a global `yarn lint-fix` and then repair until everything tested green again. No doubt there are more cases that I missed. But from @dtribble 's measurements, these are already enough to show significant perf improvements.
> fix: alt syntax for positive but faster assertions

- packages/ses/NEWS.md
- packages/ses/src/commons.js
- packages/ses/src/compartment-shim.js
- packages/ses/src/error/console.js
- packages/ses/src/error/stringify-utils.js
- packages/ses/src/error/unhandled-rejection.js
From micro benchmarks, it looks like the bind form is 2x on v8 JIT, 1.5x on v8 jitless, and 1.3x on xsnap.
While looking at this I found a bug in the type definition, which when fixing, uncovered a couple real bugs (including one in the unhandled rejection logic).
> feat(ses): uncurryThis uses bind

- packages/marshal/package.json
- packages/marshal/test/prepare-test-env-ava.js
Addresses the immediate problem explained at https://github.com/endojs/endo/issues/1298
Does not fix 1098 as it suggests a deeper reform.
> fix: import endo/init, not lockdown

- packages/bundle-source/src/index.js
- packages/bundle-source/test/sanity.js
Remove pathname sensitivity from the `getExport` and `nestedEvaluate` bundle formats by trimming the longest common prefix from emitted output names. 
Also, make the `nestedEvaluate` format backwards compatible with `getExport` when evaluating code in the start compartment.
> feat(bundle-source): normalized `getExport` and `nestedEvaluate` pathnames

- packages/marshal/src/encodeToCapData.js
- packages/marshal/src/encodeToSmallcaps.js
- packages/marshal/test/test-marshal-capdata.js
- packages/marshal/test/test-marshal-smallcaps.js
fixes #1303 
Includes new test cases that I did see fail before the code was fixed.
> fix: unserialize makes copyRecords without problematic assign semantics

- .github/workflows/ci.yml
- packages/ses/package.json
Per #1306, we have an invalid `Object.fromEntries` shim that is only needed before Node.js 12 and analogous browsers. This change raises the _tested_ lockdown compatibility floor up to Node.js 12.
- fix(ses): Fix incompatible spelling
- chore(ses): Advance lowest supported Node.js compatibility test from 10 to 12
> chore(ses): Advance Node.js compatibility test from version 10 to 12

- packages/ses/src/commons.js
commons.js contains its own ponyFill (aka shim, polyfill) of `Object.fromEntries` because it was relevant at the time. It no longer is. Fortunately it was dead code anyway because it was only exported (as `fromEntries`) when on a platform on which it is absent. Thus deleting it causes no transition cost. We can avoid the deprecation dance. By this criteria of course, fixing this is also low priority.
The reason to bother getting rid of it is that it uses assignment semantics to initialize the object it creates and returns. The resulting problems explained at https://github.com/endojs/endo/issues/1303 this has some terrible problems do apply to this code as well.
> fix: delete broken objectFromEntries

- packages/marshal/src/helpers/copyArray.js
- packages/marshal/src/helpers/copyRecord.js
- packages/marshal/src/helpers/error.js
- packages/marshal/src/helpers/passStyle-helpers.js
- packages/marshal/src/helpers/remotable.js
- packages/marshal/src/helpers/safe-promise.js
- packages/marshal/src/helpers/tagged.js
Ref dc24f2f2c3cac7ce239a64c503493c41a2334315
<details><summary>ad hoc analysis</summary>
```sh
$ node --input-type=module -e '
import Benchmark from "benchmark";
import "../init/index.js";
import { passStyleOf } from "./src/passStyleOf.js";
import { makeTagged } from "./src/makeTagged.js";
const inputs = [
undefined,
"foo",
true,
33,
33n,
Symbol.for("foo"),
Symbol.iterator,
null,
Promise.resolve(null),
[3, 4],
{ foo: 3 },
{ then: "non-function then ok" },
makeTagged("unknown", undefined),
Error("ok"),
].map(v => harden(v));
const badInputs = [
Symbol("unique"),
{},
harden(Object.setPrototypeOf(Promise.resolve(), { __proto__: Promise.prototype })),
harden(Object.assign(Promise.resolve(), { extra: "unexpected own property" })),
harden(Object.defineProperties(Promise.resolve(), { then: { …
```
> perf(marshal): Extend new assert style to passStyleOf `check` calls

- packages/marshal/src/helpers/remotable.js
- packages/marshal/src/helpers/tagged.js
- packages/marshal/test/test-passStyleOf.js
> fix(marshal): Detect unexpected nonenumerable properties on tagged records and remotables

- packages/marshal/src/encodeToCapData.js
- packages/marshal/test/test-marshal-capdata.js
- packages/marshal/test/test-marshal-stringify.js
Should not merge ahead of fixing #1312 unless confirmed safe by @FUDCo.
* Add assertions mirroring Smallcaps
* Consistently order special cases: remotable, promise, error
* Consistently quote "@qclass" in error messages
> fix(marshal): Increase consistency for encoding/decoding CapData

- packages/marshal/src/helpers/copyArray.js
- packages/marshal/src/helpers/copyRecord.js
- packages/marshal/src/helpers/passStyle-helpers.js
- packages/marshal/src/helpers/tagged.js
The `nameType` argument is mostly noise and can only fail at one call site, so this PR moves the relevant check to it.
> refactor(marshal): Simplify checkNormalProperty

- packages/marshal/src/encodeToCapData.js
- packages/marshal/src/encodeToSmallcaps.js
- packages/marshal/src/helpers/copyArray.js
- packages/marshal/src/helpers/copyRecord.js
- packages/marshal/src/helpers/error.js
- packages/marshal/src/helpers/internal-types.js
- packages/marshal/src/helpers/passStyle-helpers.js
- packages/marshal/src/helpers/remotable.js
- packages/marshal/src/passStyleOf.js
Ref 11d9f976944b4faaea06037252cfd54e3dd91c37
A modest but significant speedup, especially for big invalid input:
<details><summary>ad hoc analysis</summary>
```sh
$ node --input-type=module -e '
import Benchmark from "benchmark";
import "../init/index.js";
import { makeTagged } from "./src/makeTagged.js";
import { makeMarshal } from "./src/marshal.js";
const { serialize } = makeMarshal(x => x, x => x, { errorTagging: "off", serializeBodyFormat: "smallcaps" });
const rProto = Object.defineProperties({}, { [Symbol.for("passStyle")]: { value: "remotable" }, [Symbol.toStringTag]: { value: "Remotable" } });
const inputs = [
undefined,
"foo",
true,
33,
33n,
Symbol.for("foo"),
Symbol.iterator,
null,
Promise.resolve(null),
[3, 4],
{ foo: 3 },
{ then: "non-function then ok" }, …
```
> perf(marshal): Skip unnecessary assert.details calls

- packages/marshal/src/encodeToSmallcaps.js
> fix: parse positive bigints correctly despite XS parsing them wrong

- packages/marshal/src/encodeToCapData.js
- packages/marshal/test/test-marshal-capdata.js
capdata is being deprecated. It exists only to avoid breaking old clients that have not yet updated to smallcaps. However, I accidentally introduced an error check that I did not realize would be a breaking change. This removes that extra check, enabling old code to continue working the old way until it upgrades to smallcaps.
> fix: restore capdata leniency

- packages/marshal/test/test-marshal-capdata.js
- packages/marshal/test/test-marshal-smallcaps.js
Eliminate magic strings and an unnecessary helper function.
> test(marshal): Clean up encoding tests

- packages/marshal/package.json
- packages/marshal/src/encodePassable.js
- packages/marshal/src/rankOrder.js
- packages/marshal/src/types.js
- packages/marshal/test/test-encodePassable.js
- packages/marshal/test/test-rankOrder.js
- yarn.lock
For our passable data types, mostly, we have a clean abstraction layering between the "marshal" layer (here in the endo repository) and the "store" layer (currently in the agoric-sdk repository). However, two modules (rankOrder and encodePassable) currently at the store layer really belong at the marshal layer.
The `encodePassable` API and marshal's `encodeToCapData` and `encodeToSmallcaps` APIs have converged to the degree that they should. They can be understood together. Before smallcaps, I originally wanted to do this in the hope that `encodePassable` would become an alternate to capData for general use, but @warner 's criticisms below are likely fatal. The remaining purpose of `encodePassable` is specialized uses for which a sort-order-preserving string encoding is useful. …
> fix: Start migrating encodePassable and rankOrder from agoric-sdk to endo

- packages/captp/src/atomics.js
- packages/captp/src/captp.js
- packages/captp/test/traplib.js
- packages/captp/test/worker.js
- packages/eventual-send/src/track-turns.js
- packages/import-bundle/src/index.js
- packages/import-bundle/test/test-compartment-wrapper.js
- packages/marshal/src/dot-membrane.js
- packages/marshal/src/encodeToCapData.js
- packages/marshal/src/encodeToSmallcaps.js
- packages/marshal/src/helpers/remotable.js
- packages/marshal/src/helpers/symbol.js
- packages/marshal/src/helpers/tagged.js
- packages/marshal/src/make-far.js
- packages/marshal/src/marshal-justin.js
- packages/marshal/src/marshal-stringify.js
- packages/marshal/src/marshal.js
- packages/marshal/src/passStyleOf.js
- packages/ses/index.d.ts
- packages/ses/src/environment-options.js
- packages/ses/src/error/assert.js
- packages/ses/src/error/types.js
- packages/static-module-record/test/fixtures/exportheavy.js
- packages/stream-node/reader.js
- packages/stream-node/writer.js
See https://github.com/Agoric/agoric-sdk/pull/6482
Prior to this PR, our new assertion style let to many statements of the form
```js
condition || assert.fail(X`...`);
```
with this PR, we can now write
```js
condition || Fail`...`;
```
which is more compact and more readable.
> fix: fail template

- packages/captp/src/atomics.js
- packages/captp/src/captp.js
- packages/check-bundle/lite.js
- packages/check-bundle/test/test-check-bundle.js
- packages/compartment-mapper/src/compartment-map.js
- packages/compartment-mapper/src/import-archive.js
- packages/eventual-send/src/handled-promise.js
- packages/lp32/reader.js
- packages/lp32/writer.js
- packages/marshal/src/encodeToCapData.js
- packages/marshal/src/helpers/symbol.js
- packages/marshal/src/make-far.js
- packages/marshal/src/marshal-justin.js
- packages/marshal/src/passStyleOf.js
- packages/marshal/src/rankOrder.js
- packages/marshal/src/typeGuards.js
- packages/ses/index.test-d.ts
- packages/ses/src/environment-options.js
- packages/ses/src/eval-scope.js
- packages/ses/src/lockdown-shim.js
- packages/ses/src/make-function-constructor.js
- packages/ses/src/make-safe-evaluator.js
- packages/ses/src/module-link.js
- packages/ses/src/module-load.js
- packages/ses/src/strict-scope-terminator.js
- packages/ses/src/tame-locale-methods.js
- packages/stream-node/reader.js
Now that https://github.com/endojs/endo/pull/1334 has been merged, this PR converts remaining stragglers in endo from the old `assert(` style to the new `||` style. Convert to `|| Fail...` when possible; otherwise still to `|| assert.fail(X...)`.
> fix: assert touchups

- packages/static-module-record/src/transform-analyze.js
before:
```
TypeError#1: Cannot read properties of undefined (reading 'forEach')
```
after:
```
SyntaxError#1: Error transforming source in "file:///home/xyz/Development/metamask-extension4/node_modules/immer/dist/immer.esm.js": Cannot read properties of undefined (reading 'forEach')
```
> Static module record: error with module url on transform fail

- packages/compartment-mapper/NEWS.md
- packages/compartment-mapper/src/bundle.js
- packages/compartment-mapper/src/import-archive.js
- packages/compartment-mapper/test/fixtures-0/node_modules/bundle-dep/index.js
- packages/compartment-mapper/test/fixtures-0/node_modules/bundle-dep/package.json
- packages/compartment-mapper/test/fixtures-0/node_modules/bundle/main.js
- packages/compartment-mapper/test/fixtures-0/node_modules/bundle/package.json
- packages/compartment-mapper/test/test-bundle.js
- packages/compartment-mapper/test/test-main.js
- feat(compartment-mapper): Bundles evaluate to entrypoint namespace
- test(compartment-mapper): Verify that importArchive can be bundled by makeBundle
- test(compartment-mapper): Verify bundles can transit package boundaries
> feat(compartment-mapper): Bundle the unarchiver

- packages/compartment-mapper/src/node-modules.js
`translateGraph` accidentally set packages' own `packageLocation` as the `entryPackageLocation`
further naming improvements could happen here
> fix(compartment-mapper): fix reflexive packageLocation in node-modules/translateGraph

- packages/compartment-mapper/src/import-hook.js
- packages/compartment-mapper/test/fixtures-resolve/node_modules/path-with-dot/dir.with.dot/index.js
- packages/compartment-mapper/test/fixtures-resolve/node_modules/path-with-dot/main.js
- packages/compartment-mapper/test/fixtures-resolve/node_modules/path-with-dot/module.with.dot.js
- packages/compartment-mapper/test/fixtures-resolve/node_modules/path-with-dot/package.json
- packages/compartment-mapper/test/test-main.js
specifier `./util.thing` may refer to `./util.thing.js`
> fix(compartment-mapper): allow specifier to include period and omit extension

- packages/ses/src/error/types.js
https://github.com/Agoric/agoric-sdk/blob/master/packages/assert/src/types.js says
```js
// Based on
// https://github.com/Agoric/SES-shim/blob/master/packages/ses/src/error/types.js
// Coordinate edits until we refactor to avoid this duplication
```
This PR borrows back some minor improvements from that other types.js , so that diffs will again show only real differences.
See https://github.com/Agoric/agoric-sdk/pull/6613
> refactor: track comment changes from agoric-sdk

- packages/ses/index.d.ts
- packages/ses/src/module-load.js
- packages/ses/test/node.js
- packages/ses/test/test-import-gauntlet.js
- packages/ses/test/test-import.js
allow `importHook` to return an alias record that `ses/src/module-load.js` can attempt to import
this allows `importHook` to resolve to something that may be provided by a different part of the import phase, like the `moduleMapHook`
> feat(ses): support RedirectStaticModuleInterface without specifying a record

- packages/ses/src/module-load.js
This removes a superfluous and possibly dangerous await in the module loader. Delimiting the event could cause a race to write to the module memo.
Fixes #1394
> fix(ses): Remove superfluous tick in module loader

- packages/ses/README.md
Fixes a broken link to the YouTube video of Hardened JavaScript, as reported by @smotaal.
> fix(ses): Link to primer on Hardened JavaScript

- packages/compartment-mapper/src/bundle.js
This converges the style of generated bundles on our known best practices, ensuring that emulated module namespace objects would be frozen and that hardening the internal cells would be a no-op after lockdown.
> fix(compartment-mapper): Harden bundles

- packages/marshal/src/encodePassable.js
- packages/marshal/src/encodeToCapData.js
- packages/marshal/src/encodeToSmallcaps.js
- packages/marshal/src/helpers/copyRecord.js
- packages/marshal/src/helpers/error.js
- packages/marshal/src/helpers/remotable.js
* Fix typos
* Work around [microsoft/TypeScript#50286](https://github.com/microsoft/TypeScript/issues/50286) without `@ts-ignore`
* Increase similarity between encodeTo{CapData,Smallcaps}
* DRY out encodeToSmallcaps
* Use more standard patterns in helpers
* Move detailed ErrorHelper checks from canBeValid to assertValid
* Update ErrorHelper to use `assert.Fail`
> refactor(marshal): Increase internal consistency

- packages/eventual-send/src/handled-promise.js
- packages/eventual-send/test/test-thenable.js
If a genuine promise has an own `constructor` accessor property, the getter can mount a reentrancy attack on `Promise.resolve'. Call this the "constructor" attack. This is similar to the "then" attack of https://github.com/Agoric/agoric-sdk/issues/9 but more obscure.
Currently `HandledPromise.resolve` and its alias `E.resolve` protect against the "then" attack but not the "constructor" attack. This PR fixes `HandledPromise.resolve` and `E.resolve` to provide partial reentrancy defense against the "constructor" attack. The "constructor" getter can still run synchronously during the call. But the mere presence of the `constructor` own property will cause `HandledPromise.resolve` and `E.resolve` to coerce the malicious promise into a fresh benign one that will not cause a reentrancy attack.
> fix(eventual-send): E.resolve safer against constructor attack

- packages/import-bundle/src/index.js
In order to obviate a patch in Agoric SDK, this change marks `importBundle` as explicitly not yet ready to be mechanically verified by TypeScript.
> chore(import-bundle): Not yet TypeScriptable

- packages/compartment-mapper/src/bundle.js
It seems I neglected to thread a flag. This allows `devDependencies` to be incorporated into a bundle.
> fix(compartment-mapper): Thread dev option thru bundler

- packages/compartment-mapper/src/bundle.js
commonjs loader will sometimes set `deferredError` on the module record. the bundler should throw when it encounters this instead of failing due to other properties being missing
> feat(compartment-mapper): bundle throws on encountering deferredError

- packages/compartment-mapper/src/link.js
- packages/compartment-mapper/test/fixtures-0/node_modules/language-unknown/README.md
- packages/compartment-mapper/test/fixtures-0/node_modules/language-unknown/main.xyz
- packages/compartment-mapper/test/fixtures-0/node_modules/language-unknown/package.json
- packages/compartment-mapper/test/test-transform.js
this allowed me to add transforms for typescript files, that transform them into cjs modules.
The extension is used when the language is unknown. It still enforces that there is a parser for the language as a result of the transformations.
```js
const moduleTransforms = {
// ...
'extension:ts': async (bytes, specifier, location, packageLocation) => {
let parserLanguage = 'cjs'
const moduleRecord = {
file: location.toString(),
source: bytes.toString(),
}
await runMetaMaskTransforms(moduleRecord)
const transformedSource = Buffer.from(moduleRecord.source, 'utf8')
return { bytes: transformedSource, parser: parserLanguage }
},
}
```
> fix(compartment-mapper): allow transforms to run on unknown languages

- packages/compartment-mapper/src/archive.js
- packages/compartment-mapper/src/bundle.js
- packages/compartment-mapper/src/import-hook.js
- packages/compartment-mapper/src/import.js
- packages/compartment-mapper/src/types.js
- packages/compartment-mapper/test/fixtures-0/node_modules/candidates-custom/index.js
- packages/compartment-mapper/test/fixtures-0/node_modules/candidates-custom/package.json
- packages/compartment-mapper/test/fixtures-0/node_modules/candidates-custom/util.abc.js
- packages/compartment-mapper/test/scaffold.js
- packages/compartment-mapper/test/test-main.js
- packages/compartment-mapper/test/test-transform.js
allows the specification of alternate suffixes when determining candidates
related to supporting features like typescript where files may import other typescript modules with the extension omitted or browserify's `opts.extensions` https://github.com/browserify/browserify#browserifyfiles--opts
> feat(compartment-mapper): allow alternate candidateSuffixes

- packages/compartment-mapper/src/archive.js
- packages/compartment-mapper/src/bundle.js
- packages/compartment-mapper/src/import.js
- packages/compartment-mapper/src/node-modules.js
- packages/compartment-mapper/src/types.js
- packages/compartment-mapper/test/fixtures-common-deps/node_modules/app/index.js
- packages/compartment-mapper/test/fixtures-common-deps/node_modules/app/package.json
- packages/compartment-mapper/test/fixtures-common-deps/node_modules/common-dep-required/index.js
- packages/compartment-mapper/test/fixtures-common-deps/node_modules/common-dep-required/package.json
- packages/compartment-mapper/test/fixtures-common-deps/node_modules/common-dep-target/index.js
- packages/compartment-mapper/test/fixtures-common-deps/node_modules/common-dep-target/package.json
- packages/compartment-mapper/test/scaffold.js
- packages/compartment-mapper/test/test-main.js
provides a means of exposing additional dependencies to every package
this is common when a transpiler adds additional dependencies (eg `@babel/runtime`) or when relying on polyfills of node builtins (eg browserify's replacement of `buffer`, etc)
this is somewhat related to `exitModules`, but they can otherwise be treated as normal packages that can be loaded from the file system
see related:
- browserify: `{ builtins: { [name]: location } }`
see `opts.builtins` https://github.com/browserify/browserify#browserifyfiles--opts
- webpack: `{ resolve: { fallback: { [name]: location } } }`
see https://webpack.js.org/configuration/resolve/#resolvefallback
> feat(compartment-mapper): common dependencies

- packages/captp/src/captp.js
Wherein we observe that resolving a remote promise with a non-remotable causes an exception and for the receiver to hang indefinitely. This neat trick promotes the serialization error and stuffs it in the return path so the originator can observe the error.
> fix(captp): Serialize serialization errors

- packages/captp/src/captp.js
See https://github.com/Agoric/agoric-sdk/pull/6684
`val.then(` can be vulnerable to reentrancy by a "bad" `then` method, either because `val` is not a promise, or because it is a promise with an own `then` method overriding the `Promise.prototype.then` method.
`E.when` provides several advantages
* it provides some protection against such reentrancy. (This protection is not perfect because of the `constructor` attack. With possible future changes to the language or platform, we may be able to address this, in which case we will upgrade `E.when` to provide this extra protection.)
* It works even when `val` is properly described by the type `ERef<T>` rather than just `Promise<T>`. Thus, it is more equivalent to `Promise.resolve(val).then(`, but less verbose.
* If we introduce non-thenable …
> fix: change unsafe then to E.when

- packages/cli/src/endo.js
- packages/daemon/index.js
- packages/where/README.md
- packages/where/index.d.ts
- packages/where/index.js
- packages/where/test/test-where-endo-cache.js
- packages/where/test/test-where-endo-ephemeral-state.js
- packages/where/test/test-where-endo-sock.js
- packages/where/test/test-where-endo-state.js
- packages/where/types.d.ts
1. There’s a typo for `XDG_CACHE_DIR` that should be `XDG_CACHE_HOME`
2. `XDG` prefixes should be respected everywhere, including Darwin and Windows, except (probably) for the named pipe on Windows.
3. State and Cache should be clearly delineated, except on Windows where there does not appear to be an (obvious) separation within its native conventions.
Based on feedback out of band, I intend to use whereEndoState to locate anything intended to persist between daemon restarts, including logs. I no longer have anything in mind for whereEndoCache. whereEndoSock is using the runtime directory for PID files and Unix Domain Sockets.
> fix(where): Fix XDG conventions

- packages/ses/src/enablements.js
The Immer library currently provokes the override mistake. https://github.com/immerjs/immer/pull/914 is a PR that would fix it, but this PR has currently been rejected, seemingly committing the Immer library to not fixing is problem. (Appeal at https://github.com/immerjs/immer/pull/914#issuecomment-1374677902 )
For compatibility with Immer before https://github.com/immerjs/immer/pull/914 is accepted,  this PR extends the severeEnablements to enable all the properties of `Map.prototype` and `Set.prototype` to be overridden by assignment.
@Jack-Works , for some reason I cannot add you as a reviewer to this PR. But please consider yourself one. I would appreciate your comments. Thanks.
> fix: extend severeEnablements with immer workaround

- packages/marshal/package.json
- packages/marshal/src/encodePassable.js
- packages/marshal/src/encodeToCapData.js
- packages/marshal/src/encodeToSmallcaps.js
- packages/marshal/src/rankOrder.js
- packages/marshal/test/test-encodePassable.js
- packages/marshal/test/test-rankOrder.js
- packages/marshal/tools/arb-passable.js
Follows https://github.com/Agoric/agoric-sdk/pull/6296 , to move those enhancements to test-rankOrder to endo as well.
> fix: tools arb passable

- packages/marshal/index.js
Now that @endo/marshal has what it should (due to https://github.com/endojs/endo/pull/1439 and https://github.com/endojs/endo/pull/1291 ), when this version of endo is released and agoric-sdk is upgraded to depend on it, we have a potential problem: deep imports by code in agoric-sdk into the midst of internal modules in endo. In particular, the compat requirements #1439 was written to meet was to continue to support code that imports what @endo/marshal explicitly exports. But #1439 was not written to support code that deeply imports from the internals of marshal.
The best answer to that is for agoric-sdk to stop deeply importing from marshal, which is what https://github.com/Agoric/agoric-sdk/pull/6792 will accomplish. But https://github.com/Agoric/agoric-sdk/pull/6792 cannot work until …
> fix: marshal export what others import

- packages/marshal/test/test-marshal-stringify.js
- packages/ses/test/test-tame-function-unit.js
Addresses: #1414
The ECMAScript spec explicitly states the types of error to be expected in the cases of [`JSON.parse`](https://tc39.es/ecma262/#sec-json.parse) and [`eval`](https://tc39.es/ecma262/#sec-performeval) leaving the message itself at the discretion of implementers.
As such, this PR removes assertions for the `message` string from across this repository, some of which fail today in newer Node.js versions tracking with https://github.com/v8/v8/commit/718f743750135b3a3e643655a0406a90bf4bf010.
Co-Authored-By: @michaelfig
> test: expect `SyntaxError` instance only instead of "Unexpected token…" message

- packages/marshal/src/deeplyFulfilled.js
I already manually checked all uses in the endo and agoric-sdk repository. It looks like this change will be harmless. The advantage (discussed in private chat) is that it normalized the outcome of `deeplyFulfilled` to always be a promise, even if
* the argument was already deeply fulfilled, i.e., a Passable without promises
* an error needs to be reported, even if the error is immediate, e.g., the argument is not Passable
This normalization of the outcome, especially for the error case, should reduce the case analysis burden on callers.
> fix: make deeplyFulfilled an async function

- packages/exo/docs/exo-taxonomy.md
The change I made to the agoric-sdk copy of this package also has a doc fix in response to https://github.com/Agoric/agoric-sdk/pull/6838#discussion_r1085515755 that I foolishly omitted from https://github.com/endojs/endo/pull/1459 . This PR repairs that, bringing the copies back into alignment.
> docs: missed documentation suggestion

- packages/ses/NEWS.md
- packages/ses/README.md
- packages/ses/src/module-instance.js
- packages/ses/test/test-import-gauntlet.js
the "precompiled functor" is a function potentially present on the `staticModuleRecord`. If present, it is used as a replacement for string evaluation of the module code, useful in environments where eval is not available. Confinement of the functor is the responsibility of the creator of the precompiled functor and `staticModuleRecord`.
`ThirdPartyModuleInstances` can already do this by implementing a custom `execute` fn https://github.com/endojs/endo/blob/7de3ef8e9d5bcecc09545f5782eeb647a742ba51/packages/ses/src/module-instance.js#L99-L103
This is intended to be used by the `compartment-mapper`'s secureBundler "no eval" output format
> feat(ses): allow module-instance to use a precompiledFunctor

- packages/exo/docs/exo-taxonomy.md
At https://github.com/endojs/endo/pull/1469#discussion_r1089011161 @turadg explains advantages of docs urls using `master` rather than `HEAD`. Although he says "not worth another commit", the advantages seem compelling enough to be worth one.
Recommend reviewing with "Hide whitespace"
> docs(exo): urls - rename HEAD to master

- packages/far/README.md
- packages/ses/README.md
- packages/ses/docs/lockdown.md
Update agoric.com doc links to remove 404s. Addresses #1475
Did a quick search on repo for `agoric.com/` and updated all doc links to things that don't 404
Manually clicked all the links I added. No code changes to no real tests.
> Update docs links into agoric.com to avoid 404s

- packages/static-module-record/src/transformSource.js
- packages/static-module-record/test/fixtures/small.js
There is no `default` export on `@babel/types`. Not sure how this worked in the first place for Node.js but it makes `esm` happy for the few places that still use RESM.
See https://github.com/babel/babel/pull/14674 and https://github.com/babel/babel/pull/13414
> fix(static-module-record): ESM compatibility

- packages/stream-node/writer.js
In https://github.com/Agoric/agoric-sdk/pull/6881, on Node 14, I experienced a hard failure when trying to write into the stream to the xsnap-worker child (a node stream implemented internally as a socket/pipe). The process exited with an error triggered by [`writeAfterFIN`](https://github.com/nodejs/node/blob/92caea621d0fea47ef5af0b3dda427ac2fe2df3f/lib/net.js#L458-L476).
Apparently an error on such a stream where no error handler is present results in a global unhandler error, on which the ses shim forcibly calls `process.exit`.
While installing a no-op error handler after cleanup solved that problem, I observed that really the write call should be error-ing itself as that is what would normally happen if the write callback was wired (which it wasn't, and now is). But really there is no …
> fix(stream-node): Handle write attempt after close

- packages/patterns/README.md
- packages/patterns/src/types.js
* Fix typos
* Tweak phrasing
* Add a clarifying example
> docs(pattern): Clean up the README and type documentation

- packages/cli/src/endo.js
Either these never worked or something changed in an upgrade of Commander (the command line flag parser we use) between when these commands last worked and present day.
> fix(cli): Fix hash, map, and hash-archive commands

- packages/compartment-mapper/demo/policy/index.mjs
- packages/compartment-mapper/src/policy.js
- packages/compartment-mapper/test/test-policy.js
This change introduces an option to specify a more permissive policy so that building a more human-friendly policy format is not blocked but the impossibility of listing all possible values in the policy.
I choose the word `"any"` for the magic value because it already has a reputation because of what it means in Typescript and thus makes it more likely that a developer specifying it will get triggered to think twice.
> feat(compartment-mapper): wildcard policy specified as "any"

- packages/pass-style/src/types.js
- packages/patterns/src/patterns/patternMatchers.js
- packages/patterns/src/types.js
* Update JSDoc descriptions for pattern-related types.
* Consistently capitalize types Key, Passable, and Pattern.
* Constrain template base types for CopyArray, CopyRecord, CopySet, CopyBag, CopyMap, and Matcher.
* Approximate `[PASS_STYLE]: 'tagged'` in the CopyTagged typedef.
* Update typo in an error message.
cc @Tyrosine22
> refactor: Tighten pattern-related type constraints

- packages/captp/src/captp.js
- packages/captp/src/finalize.js
- packages/captp/src/loopback.js
- packages/captp/test/engine-gc.js
- packages/captp/test/gc-and-finalize.js
- packages/captp/test/test-disco.js
- packages/captp/test/test-export-hook.js
- packages/captp/test/test-gc.js
- packages/captp/test/test-loopback.js
- packages/eventual-send/src/handled-promise.js
- packages/eventual-send/src/index.d.ts
Added some new features:
- implement WeakRef/FinalizationRegistry-based garbage collection (refactoring for this tightened up the implementation considerably)
- allow optional `nearOptions` and `farOptions` for `makeLoopback`
- expose `isOnlyLocal(specimen)` to see if a passable specimen contains any nonlocal promises/presences
- add `importHook(val, slot)` and `exportHook(val, slot)` to allow interception of vals that are being imported/exported.  This allows warning about (or preventing) in-transit object references that may be severed if the client exits
> `@endo/captp` client robustness features

- packages/ses/src/error/assert.js
- packages/ses/test/error/test-assert-log.js
Pick the lowest hanging performance fruit.
In general we try to avoid the 
```js
assert(cond, X`...`);
```
style, and use instead
```js
cond || Fail`...`;
```
However, sometimes we are confident enough that the failure can never happen that we do not bother with the details (the 
```js
Something`...`
```
part). This happens often when we're just doing the assertion to inform the type checker of something we believe to be true. For these cases, we often write
```js
assert(cond);
```
Yes, the success case is slower than the `|| Fail` pattern by a function call. But the success case should not be more slower than that. It was, due to a completely unnecessary function call within the default argument for `assert`'s optional second parameter. 
Also fixed: The optional third parameter also …
> fix: speed up assert default details case

- packages/eventual-send/src/E.js
- packages/eventual-send/src/local.js
- packages/marshal/src/encodeToCapData.js
- packages/marshal/src/marshal-justin.js
- packages/pass-style/src/makeTagged.js
- packages/ses/src/environment-options.js
Convert more code to new assert style.
Newly motivated by perf cost of old style, but these changes not measured.
See https://github.com/Agoric/agoric-sdk/pull/7100
> refactor: faster assert style

- packages/ses/src/whitelist.js
Fix: https://github.com/endojs/endo/issues/660
Fix: https://github.com/LavaMoat/docs/issues/16
cc @naugtur
_nb: will stick to 1 commit in future_
---
Before
After
---
looks like checks `CI / test-async-hooks` failing on GHA setup-node matrix after adding docs (code comments) :suspect:
so hopefully we only need to re-trigger the checks (i don't have permish from my fork)
```console
Run actions/setup-node@v1
with:
node-version: 16.1
always-auth: false
Premature close
Waiting 14 seconds before trying again
Premature close
Waiting 1[2](https://github.com/endojs/endo/actions/runs/4425617947/jobs/7760903288#step:3:2) seconds before trying again
Error: Premature close
```
edit: rebase + force-push worked ✅
> Add `length` (number) prop to whitelist AsyncGenerator and AsyncFunctionPrototype

- packages/exo/src/exo-tools.js
Running tsc in some other packages causes this unrelated line in packages/exo to start complaining. Removing the ts-expect-error caused it to fail tsc when run in packages/exo. Thanks to @michaelfig for a fix that appeased both cases.
Copied from https://github.com/Agoric/agoric-sdk/pull/7177
> fix(exo): fix exo-tools TSC problem

- packages/captp/test/gc-and-finalize.js
- packages/captp/test/test-finalizing-map.js
- packages/captp/test/test-gc.js
Track down divergent Node.js GC behaviour on Windows.
> test(captp): split gc tests into separate files

- packages/captp/test/test-gc.js
- packages/eventual-send/src/track-turns.js
- packages/ses/src/error/assert.js
- packages/ses/src/error/note-log-args.js
The deep stacks continue to use the `assert.note` mechanism to associate an error with previous stack-capturing errors. The unbounded leak that caused us to turn deep stacks off was really the unbounded memory of error-note-graphs.
Prior to this PR, the line disabling deep stacks by default was commented
```js
// ... We intend to change the default after verifying that having
// the feature enabled in production does not cause memory to leak.
```
This PR makes the error-note storage into a finite budget LRU cache, defaulting to a budget of `1000`. With the memory leak fixed, `track-turns.js` is changed to enable deep stacks by default. Measurements will still be needed to see what the cost is, and what is a reasonable budget.
> feat(ses): finite deep stacks, on by default

- packages/ses/package.json
- packages/ses/scripts/bundle.js
- yarn.lock
closes: #1514
https://github.com/terser/terser/blob/master/CHANGELOG.md#v500-beta0 shows these breaking changes,
- BREAKING: minify() is now async and rejects a promise instead of returning an error.
- BREAKING: Internal AST is no longer exposed, so that it can be improved without releasing breaking changes.
- BREAKING: Lowest supported node version is 10
- BREAKING: There are no more warnings being emitted
Anything more than CI?
> chore(deps): bump Terser 4.8 to 5.16

- packages/ses/src/strict-scope-terminator.js
Investigating https://github.com/endojs/endo/issues/1510 , I see that the code already had a proxy trap to deal with this case, and the trace I observed was correctly generated by a `console.warn` in that code. The issue adds a more specific observation of this anomaly. With this PR, that issue can be closed but remain linked as an explanation.
Closed #1510
> doc: add issue link for bogus proxy trap observation

- packages/captp/test/test-export-hook.js
- packages/check-bundle/test/test-check-bundle.js
- packages/far/test/test-marshal-far-function.js
- packages/init/test/test-async_hooks.js
- packages/marshal/test/test-marshal-capdata.js
- packages/marshal/test/test-marshal-far-function.js
- packages/marshal/test/test-marshal-smallcaps.js
- packages/marshal/test/test-marshal-stringify.js
- packages/pass-style/src/make-far.js
- packages/pass-style/test/test-passStyleOf.js
- packages/ses/docs/lockdown.md
- packages/ses/src/commons.js
- packages/ses/src/lockdown-shim.js
- packages/ses/src/tame-harden.js
- packages/ses/src/whitelist.js
- packages/ses/test/test-compartment.js
- packages/ses/test/test-enable-default-overrides-default.js
- packages/ses/test/test-enable-property-overrides-default-unsafeError.js
- packages/ses/test/test-enable-property-overrides-default.js
- packages/ses/test/test-enable-property-overrides-min-unsafeError.js
- packages/ses/test/test-enable-property-overrides-min.js
- packages/ses/test/test-enable-property-overrides-severe-debug.js
- packages/ses/test/test-enable-property-overrides-severe.js
- packages/ses/test/test-global-object.js
- packages/ses/test/test-harden.js
- packages/ses/test/test-ses.js
- packages/ses/test/test-tame-harden.js
- packages/ses/test/test-tolerate-empty-prototype.js
- packages/ses/types.d.ts
Adds an option to make `harden` a do-nothing identity function, specifically for speed of the SwingSet kernel, though it could be used for other highly vetted, style restricted, security-critical, and speed-critical code. This would be safe to turn on in the SwingSet kernel or other such specialized code once we're confident that they are free of the kinds of bugs that a working `harden` would have protected them from.
Adds a `__hardenTaming__` option to `lockdown`, with values `'safe'` (the default) in which `harden` still works, and `'unsafe'`, in which `harden` is a do-nothing identity function.
There are various tests for whether something is frozen, sealed, non-extensible, non-configurable, non-writable, that could all be broken by this fake `harden`. However, in all cases in our …
> feat(ses): option to fake harden unsafely

- packages/exo/src/exo-makers.js
- packages/exo/src/exo-tools.js
Sync with https://github.com/Agoric/agoric-sdk/pull/7304 
To cope with the https://github.com/Agoric/agoric-sdk/pull/7138 API change, so that the next published endo can be compat with the agoric-sdk upgraded to depend on it.
> fix: sync with exo API change

- packages/pass-style/index.js
Needed in [agoric-sdk callback.js](https://github.com/Agoric/agoric-sdk/blob/master/packages/internal/src/callback.js) as of https://github.com/Agoric/agoric-sdk/pull/7341
> chore(pass-style): Export isPassableSymbol

- packages/ses/src/error/note-log-args.js
- packages/ses/test/error/test-lru-cache-map.js
- packages/ses/test/error/test-note-log-args.js
While @michaelfig and I were trying to track down a different bug, we noticed that the LRU budget on error notes, while correctly limiting the number of logged errors according to budget, failed to limit the number of logged args per error.
The latter is just kept as an ordered array. For the errors, there's a chronology of use after the initial entry was created, so an LRU was needed. For the logged args per error, they are only entered, and then not used until all of them are taken at once. Thus, dropping the front of the array if over budget is an adequate LRU.
This PR adds and enforces this separate budget of logged args per error.
> fix(ses): limit logged args per error

- packages/captp/test/test-gc.js
- packages/ses/src/error/note-log-args.js
- packages/ses/test/error/test-note-log-args.js
Refs #1513 
I tracked down the object leak to [where cause stacks are being attached to a given eventual-send](https://github.com/endojs/endo/blob/aae0e57f7a6bdcc898396c65ec22616a33672d32/packages/eventual-send/src/track-turns.js#L116). This pointed to a strongly-held chain of errors and their details arguments.
This weakifying of the LRUCacheMap uses an outer WeakMap instead of the strong map, and then a *unique* WeakMap instance **per non-condemned entry in the cache**.  That is, given N entries in the cache, 1+N WeakMaps in total (!).  This is because WeakMaps don't support composite keys, and we are avoiding using WeakRefs in the Endo implementation.
The benefit is that we no longer have a leak.  Now the CapTP GC drop counts are the same as before #1513 (3 drop messages instead of 2 …
> Weak LRU Cache Map

- packages/patterns/src/keys/checkKey.js
- packages/patterns/src/types.js
Enables us to say, for example, `CopyBag` rather than `CopyBag<Key>`, which in turn lets agoric-sdk delete unnecessary names like `CopyBagValue`.
Coordinated with change to agoric-sdk at https://github.com/Agoric/agoric-sdk/pull/7363
Will help https://github.com/Agoric/agoric-sdk/pull/7352
> fix(pattern): copy collection param type defaults

- packages/marshal/src/encodeToSmallcaps.js
closes: https://github.com/endojs/endo/issues/1548
This reverts commit ab31d51fc2df0355b45da8bbeff892c45d81c98a from https://github.com/endojs/endo/issues/1309
> revert bigint parsing workaround

- packages/captp/src/captp.js
- packages/captp/src/finalize.js
- packages/captp/test/test-finalizing-map.js
- packages/captp/test/test-gc.js
- Uses in-transit `exportID` reference counts to prevent races when dropping references
- Split the `slotToVal` map into `slotToImported`(strong)  and `slotToExported` (weak values with finalizers)
- Remove `async` methods wherever possible to better distinguish and propagate CapTP errors vs. userspace errors
> feat(captp): consistent garbage collection

- packages/init/package.json
- packages/init/test/test-init.js
- packages/init/test/test-unsafe-fast.js
- packages/init/unsafe-fast.js
As discussed with @erights in a private meeting:
Create `@endo/init/unsafe-fast.js` to use a performant, but less-than-safe SES lockdown, currently
`lockdown({ __hardenTaming__: 'unsafe' })`
> feat(init): add `@endo/init/unsafe-fast.js`

- packages/eventual-send/src/handled-promise.js
- packages/eventual-send/src/track-turns.js
As discussed at Agoric.
Also, fix a layering mistake in which hardened results required `TRACK_TURNS=enabled`.
> Default `TRACK_TURNS=disabled`

- packages/exo/src/exo-makers.js
- packages/exo/test/prepare-test-env-ava-label-instances.js
- packages/exo/test/test-heap-classes.js
- packages/exo/test/test-label-instances.js
- packages/far/test/test-marshal-far-obj.js
- packages/marshal/test/test-marshal-far-obj.js
- packages/marshal/test/test-marshal-smallcaps.js
- packages/pass-style/src/make-far.js
- packages/pass-style/src/remotable.js
- packages/pass-style/test/test-passStyleOf.js
Replaces https://github.com/Agoric/agoric-sdk/pull/6218 on the endo side. Similar LABEL_INSTANCE logic will then be needed on the agoric-sdk side using `baseRef` and `facetNames` as https://github.com/Agoric/agoric-sdk/pull/6218 does.
Stay in sync with https://github.com/Agoric/agoric-sdk/pull/7409
> feat(pass-style,exo): label remotable instances

- packages/ses/src/make-hardener.js
- packages/ses/src/tame-harden.js
- packages/ses/test/harden-mockery.js
- packages/ses/test/lockdown-harden-unsafe.js
- packages/ses/test/test-native-harden.js
Allows the start compartment to provide `globalThis.harden` to override the `harden` used by the SES shim.
This enables some hosts (like Moddable's XS) to provide their own (likely more performant) `harden` implementations.
> feat(ses): use the start compartment's `globalThis.harden` if available

- packages/exo/src/exo-makers.js
The [Agoric SDK](https://github.com/Agoric/agoric-sdk/blob/381b9d1197ffc18cfd2d5b63534e2aa71dafc9f1/docs/env.md#debug) describes `$DEBUG` as a comma-separated list of colon-separated namespaces.  The convention is derived from the Node.js `$NODE_DEBUG` environment variable, and is [part of JS development lore](https://dev.to/aderchox/what-is-the-debug-environment-variable-in-nodejs-and-how-to-use-it-3fal).
This PR adjusts `@endo/exo` to conform, so that `DEBUG=...,label-instances,...` is recognized by comma-splitting.
> fix(exo): parse `$DEBUG` as comma-separated

- packages/patterns/src/patterns/patternMatchers.js
If we accept this PR, we also need to make it clear, *somewhere findable*, that secrets should not be placed into patterns (other than keys-as-patterns), since they will not be redacted in error messages. But where?
> fix(patterns): mismatch errors should not redact the pattern

- packages/marshal/test/test-marshal-testing.js
Demonstrates how to use ava `t.deepEqual` on remotables (and therefore on structures containing remotables).
> test(marshal): ava deepEqual on remotables works for testing

- packages/ses/src/whitelist.js
Purposely making this change by itself, separate from addressing
https://github.com/endojs/endo/issues/1577 
Either one would solve the immediate problem, but both must happen. This PR is needed for SES programmer to use https://github.com/tc39/proposal-async-explicit-resource-management as intended.
(See also https://github.com/tc39/proposal-explicit-resource-management/pull/154 )
> feat(ses): allow new dispose symbols

- packages/compartment-mapper/src/link.js
provides more contextual information, like what module failed
> CompartmentMapper: throw contextual error when moduleTransform fails

- packages/ses/src/commons.js
- packages/ses/src/lockdown-shim.js
- packages/ses/src/tame-symbol-constructor.js
- packages/ses/src/whitelist-intrinsics.js
- packages/ses/src/whitelist.js
- packages/ses/test/test-get-global-intrinsics.js
- packages/ses/test/test-tame-symbol-constructor.js
- packages/ses/test/test-whitelist-intrinsics.js
Fixes #1577 
If the ses shim initializes on a platform in which Symbol contains non-configurable properties absent from the whitelist, `lockdown` will effectively succeed at deleting them anyway.
This is a concern because later versions of the language, as well as bespoke variations, may add symbols whose meaning is currently unknown. The symbols themselves would be safe, be we should know what behavior they unlock before making them generally available.
> feat(ses): tame Symbol so whitelist works

- packages/env-options/LICENSE
- packages/env-options/README.md
- packages/env-options/SECURITY.md
- packages/env-options/index.js
- packages/env-options/jsconfig.build.json
- packages/env-options/jsconfig.json
- packages/env-options/package.json
- packages/env-options/src/env-options.js
- packages/env-options/test/prepare-test-env-ava.js
- packages/env-options/test/test-env-options.js
- packages/eventual-send/package.json
- packages/eventual-send/src/track-turns.js
- packages/eventual-send/test/prepare-test-env-ava.js
- packages/exo/src/exo-makers.js
- packages/exo/test/prepare-test-env-ava-label-instances.js
- yarn.lock
Lets us do the many `// TODO Use environment-options.js`, rather than hand rolling `process.env[name]` handling each time.
> feat(env-options): env-options as separate importable package

- packages/env-options/package.json
- yarn.lock
As https://github.com/endojs/endo/pull/1585 was in review, the versions to depend on were updated, so the versions in its own package.json were stale.
> fix(env-options): fix stale dependency versions

- packages/patterns/src/patterns/patternMatchers.js
- packages/ses/src/error/assert.js
- packages/ses/src/error/types.js
- packages/ses/test/error/test-assert-log.js
- packages/ses/types.d.ts
When working on #1600 and #1605, I noticed patterns like
```js
// quoting without quotes
const details = X([`${realKind} `, ` - Must be a ${kind}`], specimen);
```
Rather than manually manipulating the input of a function intended for use in tagged templates (and mixing up the order in which parts appear), it seems more clear to have a function that is like `quote` but does not add quotes (replacing the above with ```const details = X`${r(realKind)} ${specimen} - Must be a ${r(kind)}`;```). Also tagging @FUDCo, who IIRC has asked for this in the past.
> feat(ses): Add assert.raw for embedding unquoted strings in details

- packages/env-options/README.md
- packages/ses/src/lockdown-shim.js
Remove the `console.warn` logic for reporting which `LOCKDOWN_...` options were used. The extra noise does not seem to serve any purpose.
> fix(ses)! make `LOCKDOWN_...` options less noisy

- packages/ses/README.md
> docs(ses): Provide guidance/coordination for SES incompatibility tracking

- .github/workflows/ci.yml
- .github/workflows/depcheck.yml
- package.json
- packages/promise-kit/package.json
- yarn.lock
closes: https://github.com/endojs/endo/issues/1540
Node 14 is EOL and Node 18 is now the Active LTS. 
This updates engines, types deps, and CI accordingly.
> update Node versions

- packages/patterns/src/types.js
- packages/patterns/test/test-patterns.js
Fixes #1597
Also improves pattern matcher test coverage in general.
> docs(patterns): Limit M.nat() to bigints

- packages/patterns/src/patterns/patternMatchers.js
- packages/patterns/test/test-patterns.js
Fixes #1601
stacked on #1600: https://github.com/endojs/endo/compare/gibson-1597-nat-matcher-requires-bigint...gibson-1601-null-undefined-pattern
> fix(patterns): Implement M.null() and M.undefined() as Key Patterns

- .github/workflows/depcheck.yml
- .gitignore
- scripts/check-dependency-cycles.sh
- scripts/graph.sh
Adapts `scripts/graph.sh` to detect cycles and adds a job to CI to fail if there are any.
This only detects cycles among `dependencies` declarations and ignores `devDependencies`. Lerna's check includes the latter:
```
lerna WARN ECYCLE @endo/compartment-mapper -> ses -> @endo/env-options -> @endo/init -> @endo/compartment-mapper
lerna WARN ECYCLE @endo/eventual-send -> (nested cycle: @endo/compartment-mapper -> ses -> @endo/env-options -> @endo/init -> @endo/compartment-mapper) -> @endo/eventual-send
lerna WARN ECYCLE @endo/lockdown -> (nested cycle: @endo/eventual-send -> (nested cycle: @endo/compartment-mapper -> ses -> @endo/env-options -> @endo/init -> @endo/compartment-mapper) -> @endo/eventual-send) -> @endo/lockdown
lerna WARN ECYCLE @endo/promise-kit -> (nested cycle: …
```
> prevent dependency cycles

- packages/exo/src/exo-makers.js
- packages/exo/src/exo-tools.js
- packages/exo/test/test-heap-classes.js
- packages/patterns/jsconfig.json
- packages/patterns/src/patterns/patternMatchers.js
- packages/patterns/src/types.js
- packages/patterns/test/test-pattern-limits.js
- packages/patterns/test/test-patterns.js
Replaces https://github.com/Agoric/agoric-sdk/pull/7375/ now that it's in Endo.
Parameterizes the `InterfaceGuard` type.
The immediate benefit is getting static errors for mismatch between interface guards and behavior methods.
> parameterize InterfaceGuard

- packages/ses/src/permits.js
At https://github.com/zloirock/core-js#ecmascript-symbol we see that core-js adds the non-standard `Symbol.useSimple` and `Symbol.useSetter`. Before this PR, our whitelisting mechanism, having never heard of these, safely removes them during `lockdown`. But because they're unexpected, ses also emits a console diagnostic.
This PR enhances our whitelist so that these two properties are silently removed.
> refactor(ses): tolerate core-js better

- packages/exo/src/exo-makers.js
- packages/exo/src/exo-tools.js
Fixes https://github.com/endojs/endo/issues/1641
OMG I was mutating a passed in argument that originated from a normal program outside the package. Thus, I was inadvertently mutating that program's state that was not supposed to be mutated. When they then reused that argument in another call, they were passing in the mutated one.
> fix(exo): do NOT mutate behaviorMethods argument

- packages/ses/src/permits.js
When doing https://github.com/endojs/endo/pull/1618
I had misread @gibson042 's proposal as adding a `toRawJSON` rather than `isRawJSON`.
I had missed that ArrayBuffer `detached` is an accessor.
I also added citations for the #1618 additions. While doing so, I remain confused about where `group` and `groupToMap` came from. I also noticed `groupBy` missing.
> fix(ses): permits for new proposal problems

- packages/ses/src/lockdown-shim.js
- packages/ses/src/permits-intrinsics.js
- packages/ses/src/permits.js
- packages/ses/test/test-evalTaming-default.js
Fixes #1228 
Fixes https://github.com/endojs/endo/issues/835
The replacement `Function.prototype.toString`, which uses the synthetic native function marking, should itself have been marked as a native function, so that it would recognize itself as such. First, I saw I needed to install it early. But it still wasn't being marked, which was quite puzzling. Turns out there was a bug in the marking logic in the whitelist-intrinsics code, where functions could both skip being marked, or could be pointlessly marked redundantly.
@Jack-Works , please consider yourself a reviewer of this PR. I look forward to your comments. And thanks for the original report! If I hadn't investigated I would not have found this deeper bug.
Turns out that this deeper bug was already reported by @kriskowal at #835
> fix(ses): missing native function markings

- packages/eventual-send/src/E.js
- packages/eventual-send/src/types.d.ts
A few little tweaks needed to satisfy type uses in the Agoric SDK.
> fix(eventual-send): propagate `ERef<EOnly<R>>` to `EOnly` returns

- packages/ses/package.json
- packages/ses/src/get-anonymous-intrinsics.js
- packages/ses/src/permits-intrinsics.js
- packages/ses/src/permits.js
- packages/ses/test/test-anticipate-async-iterator-helpers-shimmed.js
- packages/ses/test/test-anticipate-iterator-helpers-shimmed.js
- yarn.lock
Fixes #1289 
Anticipate both [Iterator Helpers](https://github.com/tc39/proposal-iterator-helpers) and [Async Iterator Helpers](https://github.com/tc39/proposal-async-iterator-helpers).
Note that Iterator Helpers are already as stage 3, so we can expect engines to start shipping these at any time.
Reviewers, please check it against the text of the proposals.
> feat(ses): anticipate iterator helpers

- packages/ses/src/get-anonymous-intrinsics.js
- packages/ses/src/permits.js
- packages/ses/test/core-js-configuration.js
- packages/ses/test/enforce-cjs-strict.js
- packages/ses/test/test-anticipate-async-iterator-helpers-shimmed.js
- packages/ses/test/test-anticipate-iterator-helpers-shimmed.js
#1655 introduced support for iterator helpers, but due to a limitation in the core-js shim usage, the async iterator helper test was disabled, and the PR missed a couple errors in the implementation of permits for the async iterator helpers.
This PR fixes these errors, and addresses the testing limitations so that the iterator helpers tests (both sync and async) can behave more like normal tests.
Closes #1669 
Closes #1289
> fix(ses): fixup async iterator helpers

- packages/eventual-send/src/E.js
This is needed for compatibility with Typescript pre-5.x (Agoric/agoric-sdk is still on v4.7.4).
The symptom of the error is a tsc failure like:
```
The types returned by 'getPromise(...)' are incompatible between these types.
Type 'ERef<ERef<PriceQuote>>' is not assignable to type 'ERef<PriceQuote>'.
Type 'PromiseLike<ERef<PriceQuote>>' is not assignable to type 'ERef<PriceQuote>'.
Type 'PromiseLike<ERef<PriceQuote>>' is not assignable to type 'PromiseLike<PriceQuote>'.
Type 'ERef<PriceQuote>' is not assignable to type 'PriceQuote'.
Type 'PromiseLike<PriceQuote>' is missing the following properties from type 'PriceQuote': quoteAmount, quotePayment
```
note the nested `ERef<ERef<` on the second line.  After Typescript 5.x, the nested PromiseLikes seem to be automatically merged, resulting …
> fix(eventual-send): unwrap PromiseLikes before EOnly surrounds them with ERef

- .github/workflows/ci.yml
- packages/init/src/node-async-local-storage-patch.js
- packages/init/src/node-async_hooks-patch.js
- packages/init/test/test-async_hooks.js
Fixes #1657 
Monkey patch the `AsyncLocalStorage` implementation to rewrite the handling of stores, replacing the use of symbol expando properties on promises with a WeakMap per instance.
`@endo/pass-style` and more specifically the `safePromise` check asserts that no extra own keys exist on promise instances. Furthermore hardening a promise would also harden any store object added as expando to promise instances.
> Make `AsyncLocalStorage` compatible with `@endo/pass-style`

- packages/compartment-mapper/src/archive.js
- packages/compartment-mapper/src/bundle.js
- packages/compartment-mapper/src/import-hook.js
- packages/compartment-mapper/src/import.js
- packages/compartment-mapper/src/link.js
- packages/compartment-mapper/test/fixtures-strictly-inconsistent-directories/left/index.cjs
- packages/compartment-mapper/test/fixtures-strictly-inconsistent-directories/main.js
- packages/compartment-mapper/test/fixtures-strictly-inconsistent-directories/package.json
- packages/compartment-mapper/test/fixtures-strictly-inconsistent-directories/right/child/index.mjs
- packages/compartment-mapper/test/fixtures-strictly-inconsistent-directories/right/inconsistent.js
- packages/compartment-mapper/test/fixtures-strictly-inconsistent-packages/main.js
- packages/compartment-mapper/test/fixtures-strictly-inconsistent-packages/node_modules/left/main.js
- packages/compartment-mapper/test/fixtures-strictly-inconsistent-packages/node_modules/left/package.json
- packages/compartment-mapper/test/fixtures-strictly-inconsistent-packages/node_modules/right/inconsistent.js
- packages/compartment-mapper/test/fixtures-strictly-inconsistent-packages/node_modules/right/main.js
- packages/compartment-mapper/test/fixtures-strictly-inconsistent-packages/node_modules/right/package.json
- packages/compartment-mapper/test/fixtures-strictly-inconsistent-packages/package.json
- packages/compartment-mapper/test/test-missing-entry.js
- packages/compartment-mapper/test/test-strictly-inconsistent.js
This change includes related fixes in the compartment mapper and a drive-by refactor.
In order to allow CommonJS to conditionally import a dependency, it must be possible for that dependency to be absent. To that end, the Compartment Mapper tracks which modules are strictly required (because they’re retained by an ESM, as opposed to CJS).
Fixes https://github.com/endojs/endo/issues/1206: `bundleSource` generates invalid bundles if the entry module does not exist, where it should simply fail to generate a bundle. The fix is to include the entry module in the set of strictly required modules.
This also fixes overlapping bugs I missed in review:
Each compartment must have a separate set of strictly required module specifiers. This change includes a test that illustrates that a compartment …
> fix(compartment-mapper): Missing entries and conflated namespace

- packages/pass-style/src/passStyleOf.js
See https://github.com/Agoric/agoric-sdk/pull/8051
If there is already a `VataData` global containing a function named `passStyleOf`, then presumably it was endowed for us by liveslots, so we should use and export that one instead.
> refactor: get passStyleOf from VataData if there

- packages/compartment-mapper/README.md
This is one of those useless "improved documentation" PRs.  Sorry.
> docs(compartment-mapper): remove duplicate link ref to lavamoat

- packages/marshal/README.md
Fixes #1683
Fixes #1680
* Reference toCapData/fromCapData
* Emphasize smallcaps over the original encoding
* Tweak phrasing
* Fix inaccurate claims
> docs(marshal): Update README

- packages/ses/src/permits.js
Both `RegExp.prototype.hasIndices` and `RegExp.prototype.unicodeSets` are standard at least as of EcmaScript 2024, as seen at https://tc39.es/ecma262/multipage/text-processing.html#sec-properties-of-the-regexp-prototype-object
I noticed the missing `RegExp.prototype.unicodeSets` because of the ses initialization warning only starting on Node 20. While investigating, I saw that `permits.js` had classified `RegExp.prototype.hasIndices` as an expected anomaly to be silently removed, but that it is now standard.
> fix(ses): add more missing permits
